# -*- coding: utf-8 -*-
"""
Schwedische Top-500-Wortliste fuer die Sprachlern-App.
Wird schrittweise erweitert - IMMER diese eine Datei verwenden/neu herunterladen.
Aktueller Stand: Funktionswoerter (Pronomen, Zahlen, Fragewoerter, Praepositionen,
Konjunktionen, Adverbien). Als naechstes folgen Verben, dann Nomen, dann Adjektive.
"""

WORDS = [
    # --- Personalpronomen ---
    {"swedish": "jag", "german": "ich", "category": "Pronomen"},
    {"swedish": "du", "german": "du", "category": "Pronomen"},
    {"swedish": "han", "german": "er", "category": "Pronomen"},
    {"swedish": "hon", "german": "sie (Sg.)", "category": "Pronomen"},
    {"swedish": "den", "german": "er/sie/es (Utrum)", "category": "Pronomen", "grammar_note": "für en-Wörter (Utrum)"},
    {"swedish": "det", "german": "er/sie/es (Neutrum)", "category": "Pronomen", "grammar_note": "für ett-Wörter (Neutrum)"},
    {"swedish": "vi", "german": "wir", "category": "Pronomen"},
    {"swedish": "ni", "german": "ihr", "category": "Pronomen"},
    {"swedish": "de", "german": "sie (Pl.)", "category": "Pronomen", "grammar_note": "gesprochen oft 'dom'"},
    {"swedish": "man", "german": "man", "category": "Pronomen"},
    {"swedish": "mig", "german": "mich, mir", "category": "Pronomen"},
    {"swedish": "dig", "german": "dich, dir", "category": "Pronomen"},
    {"swedish": "honom", "german": "ihn, ihm", "category": "Pronomen"},
    {"swedish": "henne", "german": "sie, ihr (Akk./Dat.)", "category": "Pronomen"},
    {"swedish": "oss", "german": "uns", "category": "Pronomen"},
    {"swedish": "er", "german": "euch", "category": "Pronomen"},
    {"swedish": "dem", "german": "sie, ihnen (Pl.)", "category": "Pronomen", "grammar_note": "gesprochen oft 'dom'"},
    {"swedish": "min", "german": "mein (Utrum)", "category": "Pronomen"},
    {"swedish": "mitt", "german": "mein (Neutrum)", "category": "Pronomen"},
    {"swedish": "mina", "german": "meine (Pl.)", "category": "Pronomen"},
    {"swedish": "din", "german": "dein (Utrum)", "category": "Pronomen"},
    {"swedish": "ditt", "german": "dein (Neutrum)", "category": "Pronomen"},
    {"swedish": "dina", "german": "deine (Pl.)", "category": "Pronomen"},
    {"swedish": "sin", "german": "sein/ihr eigenes (Utrum, reflexiv)", "category": "Pronomen"},
    {"swedish": "sitt", "german": "sein/ihr eigenes (Neutrum, reflexiv)", "category": "Pronomen"},
    {"swedish": "vår", "german": "unser (Utrum)", "category": "Pronomen"},
    {"swedish": "vårt", "german": "unser (Neutrum)", "category": "Pronomen"},
    {"swedish": "våra", "german": "unsere (Pl.)", "category": "Pronomen"},
    {"swedish": "denna", "german": "dieser/diese (Utrum)", "category": "Pronomen"},
    {"swedish": "detta", "german": "dieses (Neutrum)", "category": "Pronomen"},
    {"swedish": "dessa", "german": "diese (Pl.)", "category": "Pronomen"},
    {"swedish": "något", "german": "etwas", "category": "Pronomen"},
    {"swedish": "allt", "german": "alles", "category": "Pronomen"},
    {"swedish": "alla", "german": "alle", "category": "Pronomen"},
    {"swedish": "ingen", "german": "keiner/keine (Utrum)", "category": "Pronomen"},
    {"swedish": "inget", "german": "keines (Neutrum)", "category": "Pronomen"},

    # --- Zahlwörter ---
    {"swedish": "noll", "german": "null", "category": "Zahlwort"},
    {"swedish": "en/ett", "german": "eins", "category": "Zahlwort", "grammar_note": "en für Utrum-Wörter, ett für Neutrum-Wörter"},
    {"swedish": "två", "german": "zwei", "category": "Zahlwort"},
    {"swedish": "tre", "german": "drei", "category": "Zahlwort"},
    {"swedish": "fyra", "german": "vier", "category": "Zahlwort"},
    {"swedish": "fem", "german": "fünf", "category": "Zahlwort"},
    {"swedish": "sex", "german": "sechs", "category": "Zahlwort"},
    {"swedish": "sju", "german": "sieben", "category": "Zahlwort"},
    {"swedish": "åtta", "german": "acht", "category": "Zahlwort"},
    {"swedish": "nio", "german": "neun", "category": "Zahlwort"},
    {"swedish": "tio", "german": "zehn", "category": "Zahlwort"},
    {"swedish": "elva", "german": "elf", "category": "Zahlwort"},
    {"swedish": "tolv", "german": "zwölf", "category": "Zahlwort"},
    {"swedish": "tretton", "german": "dreizehn", "category": "Zahlwort"},
    {"swedish": "fjorton", "german": "vierzehn", "category": "Zahlwort"},
    {"swedish": "femton", "german": "fünfzehn", "category": "Zahlwort"},
    {"swedish": "sexton", "german": "sechzehn", "category": "Zahlwort"},
    {"swedish": "sjutton", "german": "siebzehn", "category": "Zahlwort"},
    {"swedish": "arton", "german": "achtzehn", "category": "Zahlwort"},
    {"swedish": "nitton", "german": "neunzehn", "category": "Zahlwort"},
    {"swedish": "tjugo", "german": "zwanzig", "category": "Zahlwort"},
    {"swedish": "trettio", "german": "dreißig", "category": "Zahlwort"},
    {"swedish": "fyrtio", "german": "vierzig", "category": "Zahlwort"},
    {"swedish": "femtio", "german": "fünfzig", "category": "Zahlwort"},
    {"swedish": "sextio", "german": "sechzig", "category": "Zahlwort"},
    {"swedish": "sjuttio", "german": "siebzig", "category": "Zahlwort"},
    {"swedish": "åttio", "german": "achtzig", "category": "Zahlwort"},
    {"swedish": "nittio", "german": "neunzig", "category": "Zahlwort"},
    {"swedish": "hundra", "german": "hundert", "category": "Zahlwort"},
    {"swedish": "tusen", "german": "tausend", "category": "Zahlwort"},
    {"swedish": "första", "german": "erste(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},
    {"swedish": "andra", "german": "zweite(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},
    {"swedish": "tredje", "german": "dritte(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},

    # --- Fragewörter ---
    {"swedish": "vad", "german": "was", "category": "Fragewort"},
    {"swedish": "vem", "german": "wer", "category": "Fragewort"},
    {"swedish": "vilken", "german": "welcher/welche (Utrum)", "category": "Fragewort"},
    {"swedish": "vilket", "german": "welches (Neutrum)", "category": "Fragewort"},
    {"swedish": "vilka", "german": "welche (Pl.)", "category": "Fragewort"},
    {"swedish": "var", "german": "wo", "category": "Fragewort"},
    {"swedish": "vart", "german": "wohin", "category": "Fragewort"},
    {"swedish": "när", "german": "wann", "category": "Fragewort"},
    {"swedish": "hur", "german": "wie", "category": "Fragewort"},
    {"swedish": "varför", "german": "warum", "category": "Fragewort"},
    {"swedish": "hur mycket", "german": "wie viel", "category": "Fragewort"},
    {"swedish": "hur många", "german": "wie viele", "category": "Fragewort"},

    # --- Präpositionen ---
    {"swedish": "i", "german": "in", "category": "Präposition"},
    {"swedish": "på", "german": "auf, an", "category": "Präposition"},
    {"swedish": "av", "german": "von", "category": "Präposition"},
    {"swedish": "till", "german": "zu, nach", "category": "Präposition"},
    {"swedish": "från", "german": "von, aus", "category": "Präposition"},
    {"swedish": "med", "german": "mit", "category": "Präposition"},
    {"swedish": "om", "german": "über, um, falls", "category": "Präposition"},
    {"swedish": "för", "german": "für", "category": "Präposition"},
    {"swedish": "utan", "german": "ohne", "category": "Präposition"},
    {"swedish": "under", "german": "unter, während", "category": "Präposition"},
    {"swedish": "över", "german": "über", "category": "Präposition"},
    {"swedish": "mellan", "german": "zwischen", "category": "Präposition"},
    {"swedish": "genom", "german": "durch", "category": "Präposition"},
    {"swedish": "efter", "german": "nach", "category": "Präposition"},
    {"swedish": "innan", "german": "vor (zeitlich)", "category": "Präposition"},
    {"swedish": "mot", "german": "gegen", "category": "Präposition"},
    {"swedish": "hos", "german": "bei", "category": "Präposition"},
    {"swedish": "vid", "german": "bei, an", "category": "Präposition"},
    {"swedish": "bakom", "german": "hinter", "category": "Präposition"},
    {"swedish": "framför", "german": "vor (räumlich)", "category": "Präposition"},
    {"swedish": "bredvid", "german": "neben", "category": "Präposition"},
    {"swedish": "runt", "german": "um, herum", "category": "Präposition"},

    # --- Konjunktionen ---
    {"swedish": "och", "german": "und", "category": "Konjunktion"},
    {"swedish": "men", "german": "aber", "category": "Konjunktion"},
    {"swedish": "eller", "german": "oder", "category": "Konjunktion"},
    {"swedish": "så", "german": "also, so", "category": "Konjunktion"},
    {"swedish": "att", "german": "dass", "category": "Konjunktion"},
    {"swedish": "om", "german": "wenn, falls", "category": "Konjunktion"},
    {"swedish": "när", "german": "wenn, als (zeitlich)", "category": "Konjunktion"},
    {"swedish": "eftersom", "german": "weil, da", "category": "Konjunktion"},
    {"swedish": "fastän", "german": "obwohl", "category": "Konjunktion"},
    {"swedish": "medan", "german": "während", "category": "Konjunktion"},
    {"swedish": "innan", "german": "bevor", "category": "Konjunktion"},
    {"swedish": "tills", "german": "bis", "category": "Konjunktion"},
    {"swedish": "för att", "german": "damit, um zu", "category": "Konjunktion"},

    # --- Häufige Adverbien ---
    {"swedish": "inte", "german": "nicht", "category": "Adverb"},
    {"swedish": "mycket", "german": "sehr, viel", "category": "Adverb"},
    {"swedish": "lite", "german": "wenig, ein bisschen", "category": "Adverb"},
    {"swedish": "alltid", "german": "immer", "category": "Adverb"},
    {"swedish": "aldrig", "german": "nie", "category": "Adverb"},
    {"swedish": "ofta", "german": "oft", "category": "Adverb"},
    {"swedish": "ibland", "german": "manchmal", "category": "Adverb"},
    {"swedish": "redan", "german": "schon", "category": "Adverb"},
    {"swedish": "snart", "german": "bald", "category": "Adverb"},
    {"swedish": "nu", "german": "jetzt", "category": "Adverb"},
    {"swedish": "då", "german": "dann, damals", "category": "Adverb"},
    {"swedish": "här", "german": "hier", "category": "Adverb"},
    {"swedish": "där", "german": "dort", "category": "Adverb"},
    {"swedish": "också", "german": "auch", "category": "Adverb"},
    {"swedish": "bara", "german": "nur", "category": "Adverb"},
    {"swedish": "kanske", "german": "vielleicht", "category": "Adverb"},
    {"swedish": "ganska", "german": "ziemlich", "category": "Adverb"},
    {"swedish": "väldigt", "german": "sehr", "category": "Adverb"},
    {"swedish": "idag", "german": "heute", "category": "Adverb"},
    {"swedish": "igår", "german": "gestern", "category": "Adverb"},
    {"swedish": "imorgon", "german": "morgen", "category": "Adverb"},
    {"swedish": "sedan", "german": "seitdem, danach", "category": "Adverb"},
    {"swedish": "fortfarande", "german": "immer noch", "category": "Adverb"},
    {"swedish": "genast", "german": "sofort", "category": "Adverb"},
    {"swedish": "tillsammans", "german": "zusammen", "category": "Adverb"},

    # --- Verben (Praesens/Preteritum/Supinum; Perfekt-Hilfsverb ist im Schwedischen
    #     praktisch immer "ha" -> har/hade + Supinum, deshalb keine eigene Spalte noetig.
    #     Futur wird mit "ska" + Infinitiv gebildet, ebenfalls ohne Zusatzdaten. ---
    {"swedish": "vara", "german": "sein", "category": "Verb", "forms": {"present": "är", "preteritum": "var", "supinum": "varit"}},
    {"swedish": "ha", "german": "haben", "category": "Verb", "forms": {"present": "har", "preteritum": "hade", "supinum": "haft"}},
    {"swedish": "göra", "german": "machen, tun", "category": "Verb", "forms": {"present": "gör", "preteritum": "gjorde", "supinum": "gjort"}},
    {"swedish": "säga", "german": "sagen", "category": "Verb", "forms": {"present": "säger", "preteritum": "sa", "supinum": "sagt"}},
    {"swedish": "kunna", "german": "können", "category": "Verb", "forms": {"present": "kan", "preteritum": "kunde", "supinum": "kunnat"}, "grammar_note": "Modalverb"},
    {"swedish": "vilja", "german": "wollen", "category": "Verb", "forms": {"present": "vill", "preteritum": "ville", "supinum": "velat"}, "grammar_note": "Modalverb"},
    {"swedish": "ska", "german": "werden, sollen", "category": "Verb", "forms": {"present": "ska", "preteritum": "skulle", "supinum": "skolat"}, "grammar_note": "Modalverb, bildet den Futur: ska + Infinitiv"},
    {"swedish": "måste", "german": "müssen", "category": "Verb", "forms": {"present": "måste", "preteritum": "var tvungen att", "supinum": "varit tvungen att"}, "grammar_note": "Modalverb ohne eigene Praesensform (immer 'måste')"},
    {"swedish": "komma", "german": "kommen", "category": "Verb", "forms": {"present": "kommer", "preteritum": "kom", "supinum": "kommit"}},
    {"swedish": "gå", "german": "gehen", "category": "Verb", "forms": {"present": "går", "preteritum": "gick", "supinum": "gått"}},
    {"swedish": "se", "german": "sehen", "category": "Verb", "forms": {"present": "ser", "preteritum": "såg", "supinum": "sett"}},
    {"swedish": "veta", "german": "wissen", "category": "Verb", "forms": {"present": "vet", "preteritum": "visste", "supinum": "vetat"}},
    {"swedish": "ta", "german": "nehmen", "category": "Verb", "forms": {"present": "tar", "preteritum": "tog", "supinum": "tagit"}},
    {"swedish": "få", "german": "bekommen, dürfen", "category": "Verb", "forms": {"present": "får", "preteritum": "fick", "supinum": "fått"}},
    {"swedish": "tro", "german": "glauben", "category": "Verb", "forms": {"present": "tror", "preteritum": "trodde", "supinum": "trott"}},
    {"swedish": "tycka", "german": "finden, meinen", "category": "Verb", "forms": {"present": "tycker", "preteritum": "tyckte", "supinum": "tyckt"}},
    {"swedish": "behöva", "german": "brauchen", "category": "Verb", "forms": {"present": "behöver", "preteritum": "behövde", "supinum": "behövt"}},
    {"swedish": "fråga", "german": "fragen", "category": "Verb", "forms": {"present": "frågar", "preteritum": "frågade", "supinum": "frågat"}},
    {"swedish": "tänka", "german": "denken", "category": "Verb", "forms": {"present": "tänker", "preteritum": "tänkte", "supinum": "tänkt"}},
    {"swedish": "arbeta", "german": "arbeiten", "category": "Verb", "forms": {"present": "arbetar", "preteritum": "arbetade", "supinum": "arbetat"}},
    {"swedish": "spela", "german": "spielen", "category": "Verb", "forms": {"present": "spelar", "preteritum": "spelade", "supinum": "spelat"}},
    {"swedish": "tala", "german": "sprechen", "category": "Verb", "forms": {"present": "talar", "preteritum": "talade", "supinum": "talat"}},
    {"swedish": "prata", "german": "reden, sprechen", "category": "Verb", "forms": {"present": "pratar", "preteritum": "pratade", "supinum": "pratat"}},
    {"swedish": "skriva", "german": "schreiben", "category": "Verb", "forms": {"present": "skriver", "preteritum": "skrev", "supinum": "skrivit"}},
    {"swedish": "läsa", "german": "lesen", "category": "Verb", "forms": {"present": "läser", "preteritum": "läste", "supinum": "läst"}},
    {"swedish": "äta", "german": "essen", "category": "Verb", "forms": {"present": "äter", "preteritum": "åt", "supinum": "ätit"}},
    {"swedish": "dricka", "german": "trinken", "category": "Verb", "forms": {"present": "dricker", "preteritum": "drack", "supinum": "druckit"}},
    {"swedish": "sova", "german": "schlafen", "category": "Verb", "forms": {"present": "sover", "preteritum": "sov", "supinum": "sovit"}},
    {"swedish": "bo", "german": "wohnen", "category": "Verb", "forms": {"present": "bor", "preteritum": "bodde", "supinum": "bott"}},
    {"swedish": "leva", "german": "leben", "category": "Verb", "forms": {"present": "lever", "preteritum": "levde", "supinum": "levt"}},
    {"swedish": "dö", "german": "sterben", "category": "Verb", "forms": {"present": "dör", "preteritum": "dog", "supinum": "dött"}},
    {"swedish": "köpa", "german": "kaufen", "category": "Verb", "forms": {"present": "köper", "preteritum": "köpte", "supinum": "köpt"}},
    {"swedish": "sälja", "german": "verkaufen", "category": "Verb", "forms": {"present": "säljer", "preteritum": "sålde", "supinum": "sålt"}},
    {"swedish": "ge", "german": "geben", "category": "Verb", "forms": {"present": "ger", "preteritum": "gav", "supinum": "gett"}},
    {"swedish": "hjälpa", "german": "helfen", "category": "Verb", "forms": {"present": "hjälper", "preteritum": "hjälpte", "supinum": "hjälpt"}},
    {"swedish": "förstå", "german": "verstehen", "category": "Verb", "forms": {"present": "förstår", "preteritum": "förstod", "supinum": "förstått"}},
    {"swedish": "lära", "german": "lehren, lernen", "category": "Verb", "forms": {"present": "lär", "preteritum": "lärde", "supinum": "lärt"}},
    {"swedish": "börja", "german": "beginnen", "category": "Verb", "forms": {"present": "börjar", "preteritum": "började", "supinum": "börjat"}},
    {"swedish": "sluta", "german": "aufhören", "category": "Verb", "forms": {"present": "slutar", "preteritum": "slutade", "supinum": "slutat"}},
    {"swedish": "fortsätta", "german": "fortsetzen", "category": "Verb", "forms": {"present": "fortsätter", "preteritum": "fortsatte", "supinum": "fortsatt"}},
    {"swedish": "stanna", "german": "bleiben, anhalten", "category": "Verb", "forms": {"present": "stannar", "preteritum": "stannade", "supinum": "stannat"}},
    {"swedish": "hitta", "german": "finden", "category": "Verb", "forms": {"present": "hittar", "preteritum": "hittade", "supinum": "hittat"}},
    {"swedish": "leta", "german": "suchen", "category": "Verb", "forms": {"present": "letar", "preteritum": "letade", "supinum": "letat"}},
    {"swedish": "titta", "german": "schauen", "category": "Verb", "forms": {"present": "tittar", "preteritum": "tittade", "supinum": "tittat"}},
    {"swedish": "lyssna", "german": "zuhören", "category": "Verb", "forms": {"present": "lyssnar", "preteritum": "lyssnade", "supinum": "lyssnat"}},
    {"swedish": "höra", "german": "hören", "category": "Verb", "forms": {"present": "hör", "preteritum": "hörde", "supinum": "hört"}},
    {"swedish": "känna", "german": "fühlen, kennen", "category": "Verb", "forms": {"present": "känner", "preteritum": "kände", "supinum": "känt"}},
    {"swedish": "bli", "german": "werden", "category": "Verb", "forms": {"present": "blir", "preteritum": "blev", "supinum": "blivit"}},
    {"swedish": "sitta", "german": "sitzen", "category": "Verb", "forms": {"present": "sitter", "preteritum": "satt", "supinum": "suttit"}},
    {"swedish": "stå", "german": "stehen", "category": "Verb", "forms": {"present": "står", "preteritum": "stod", "supinum": "stått"}},
    {"swedish": "ligga", "german": "liegen", "category": "Verb", "forms": {"present": "ligger", "preteritum": "låg", "supinum": "legat"}},
    {"swedish": "springa", "german": "laufen, rennen", "category": "Verb", "forms": {"present": "springer", "preteritum": "sprang", "supinum": "sprungit"}},
    {"swedish": "köra", "german": "fahren (Fahrzeug)", "category": "Verb", "forms": {"present": "kör", "preteritum": "körde", "supinum": "kört"}},
    {"swedish": "resa", "german": "reisen", "category": "Verb", "forms": {"present": "reser", "preteritum": "reste", "supinum": "rest"}},
    {"swedish": "flyga", "german": "fliegen", "category": "Verb", "forms": {"present": "flyger", "preteritum": "flög", "supinum": "flugit"}},
    {"swedish": "simma", "german": "schwimmen", "category": "Verb", "forms": {"present": "simmar", "preteritum": "simmade", "supinum": "simmat"}},
    {"swedish": "laga", "german": "reparieren, kochen", "category": "Verb", "forms": {"present": "lagar", "preteritum": "lagade", "supinum": "lagat"}},
    {"swedish": "öppna", "german": "öffnen", "category": "Verb", "forms": {"present": "öppnar", "preteritum": "öppnade", "supinum": "öppnat"}},
    {"swedish": "stänga", "german": "schließen", "category": "Verb", "forms": {"present": "stänger", "preteritum": "stängde", "supinum": "stängt"}},
    {"swedish": "lämna", "german": "verlassen, lassen", "category": "Verb", "forms": {"present": "lämnar", "preteritum": "lämnade", "supinum": "lämnat"}},
    {"swedish": "träffa", "german": "treffen", "category": "Verb", "forms": {"present": "träffar", "preteritum": "träffade", "supinum": "träffat"}},
    {"swedish": "ringa", "german": "anrufen, klingeln", "category": "Verb", "forms": {"present": "ringer", "preteritum": "ringde", "supinum": "ringt"}},
    {"swedish": "skicka", "german": "schicken", "category": "Verb", "forms": {"present": "skickar", "preteritum": "skickade", "supinum": "skickat"}},
    {"swedish": "betala", "german": "bezahlen", "category": "Verb", "forms": {"present": "betalar", "preteritum": "betalade", "supinum": "betalat"}},
    {"swedish": "glömma", "german": "vergessen", "category": "Verb", "forms": {"present": "glömmer", "preteritum": "glömde", "supinum": "glömt"}},
    {"swedish": "förlora", "german": "verlieren", "category": "Verb", "forms": {"present": "förlorar", "preteritum": "förlorade", "supinum": "förlorat"}},
    {"swedish": "vinna", "german": "gewinnen", "category": "Verb", "forms": {"present": "vinner", "preteritum": "vann", "supinum": "vunnit"}},
    {"swedish": "skratta", "german": "lachen", "category": "Verb", "forms": {"present": "skrattar", "preteritum": "skrattade", "supinum": "skrattat"}},
    {"swedish": "gråta", "german": "weinen", "category": "Verb", "forms": {"present": "gråter", "preteritum": "grät", "supinum": "gråtit"}},
    {"swedish": "le", "german": "lächeln", "category": "Verb", "forms": {"present": "ler", "preteritum": "log", "supinum": "lett"}},
    {"swedish": "vakna", "german": "aufwachen", "category": "Verb", "forms": {"present": "vaknar", "preteritum": "vaknade", "supinum": "vaknat"}},
    {"swedish": "duscha", "german": "duschen", "category": "Verb", "forms": {"present": "duschar", "preteritum": "duschade", "supinum": "duschat"}},
    {"swedish": "tvätta", "german": "waschen", "category": "Verb", "forms": {"present": "tvättar", "preteritum": "tvättade", "supinum": "tvättat"}},
    {"swedish": "städa", "german": "putzen", "category": "Verb", "forms": {"present": "städar", "preteritum": "städade", "supinum": "städat"}},
    {"swedish": "önska", "german": "wünschen", "category": "Verb", "forms": {"present": "önskar", "preteritum": "önskade", "supinum": "önskat"}},
    {"swedish": "hoppas", "german": "hoffen", "category": "Verb", "forms": {"present": "hoppas", "preteritum": "hoppades", "supinum": "hoppats"}, "grammar_note": "Deponens-Verb (endet immer auf -s)"},
    {"swedish": "bestämma", "german": "bestimmen, entscheiden", "category": "Verb", "forms": {"present": "bestämmer", "preteritum": "bestämde", "supinum": "bestämt"}},
    {"swedish": "välja", "german": "wählen", "category": "Verb", "forms": {"present": "väljer", "preteritum": "valde", "supinum": "valt"}},
    {"swedish": "förklara", "german": "erklären", "category": "Verb", "forms": {"present": "förklarar", "preteritum": "förklarade", "supinum": "förklarat"}},
    {"swedish": "visa", "german": "zeigen", "category": "Verb", "forms": {"present": "visar", "preteritum": "visade", "supinum": "visat"}},
    {"swedish": "byta", "german": "wechseln, tauschen", "category": "Verb", "forms": {"present": "byter", "preteritum": "bytte", "supinum": "bytt"}},
    {"swedish": "använda", "german": "benutzen", "category": "Verb", "forms": {"present": "använder", "preteritum": "använde", "supinum": "använt"}},
    {"swedish": "skapa", "german": "erschaffen", "category": "Verb", "forms": {"present": "skapar", "preteritum": "skapade", "supinum": "skapat"}},
    {"swedish": "bygga", "german": "bauen", "category": "Verb", "forms": {"present": "bygger", "preteritum": "byggde", "supinum": "byggt"}},
    {"swedish": "växa", "german": "wachsen", "category": "Verb", "forms": {"present": "växer", "preteritum": "växte", "supinum": "vuxit"}},
    {"swedish": "förändra", "german": "verändern", "category": "Verb", "forms": {"present": "förändrar", "preteritum": "förändrade", "supinum": "förändrat"}},
    {"swedish": "sätta", "german": "setzen, stellen", "category": "Verb", "forms": {"present": "sätter", "preteritum": "satte", "supinum": "satt"}},
    {"swedish": "flytta", "german": "umziehen", "category": "Verb", "forms": {"present": "flyttar", "preteritum": "flyttade", "supinum": "flyttat"}},

    # --- Verben: ergänzt beim Nomen/Adjektiv-Ausbau (fehlten in den urspruenglichen 88) ---
    {"swedish": "älska", "german": "lieben", "category": "Verb", "forms": {"present": "älskar", "preteritum": "älskade", "supinum": "älskat"}},
    {"swedish": "gilla", "german": "mögen, gernhaben", "category": "Verb", "forms": {"present": "gillar", "preteritum": "gillade", "supinum": "gillat"}},
    {"swedish": "heta", "german": "heißen", "category": "Verb", "forms": {"present": "heter", "preteritum": "hette", "supinum": "hetat"}, "grammar_note": "unregelmäßig"},
    {"swedish": "vänta", "german": "warten", "category": "Verb", "forms": {"present": "väntar", "preteritum": "väntade", "supinum": "väntat"}},
    {"swedish": "sakna", "german": "vermissen", "category": "Verb", "forms": {"present": "saknar", "preteritum": "saknade", "supinum": "saknat"}},
    {"swedish": "dansa", "german": "tanzen", "category": "Verb", "forms": {"present": "dansar", "preteritum": "dansade", "supinum": "dansat"}},
    {"swedish": "festa", "german": "feiern", "category": "Verb", "forms": {"present": "festar", "preteritum": "festade", "supinum": "festat"}},
    {"swedish": "kyssa", "german": "küssen", "category": "Verb", "forms": {"present": "kysser", "preteritum": "kysste", "supinum": "kysst"}},

    # --- Nomen: Familie ---
    {"swedish": "mamma", "german": "Mutter", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mamma", "def_sg": "mamman", "indef_pl": "mammor", "def_pl": "mammorna"}},
    {"swedish": "pappa", "german": "Vater", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "pappa", "def_sg": "pappan", "indef_pl": "pappor", "def_pl": "papporna"}},
    {"swedish": "mor", "german": "Mutter (formell)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mor", "def_sg": "modern", "indef_pl": "mödrar", "def_pl": "mödrarna"}, "grammar_note": "unregelmäßige Deklination"},
    {"swedish": "far", "german": "Vater (formell)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "far", "def_sg": "fadern", "indef_pl": "fäder", "def_pl": "fäderna"}, "grammar_note": "unregelmäßige Deklination"},
    {"swedish": "barn", "german": "Kind", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "barn", "def_sg": "barnet", "indef_pl": "barn", "def_pl": "barnen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "son", "german": "Sohn", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "son", "def_sg": "sonen", "indef_pl": "söner", "def_pl": "sönerna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "dotter", "german": "Tochter", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "dotter", "def_sg": "dottern", "indef_pl": "döttrar", "def_pl": "döttrarna"}, "grammar_note": "unregelmäßige Deklination"},
    {"swedish": "bror", "german": "Bruder", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "bror", "def_sg": "brodern", "indef_pl": "bröder", "def_pl": "bröderna"}, "grammar_note": "unregelmäßige Deklination"},
    {"swedish": "syster", "german": "Schwester", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "syster", "def_sg": "systern", "indef_pl": "systrar", "def_pl": "systrarna"}, "grammar_note": "Stammvokal-e fällt vor -ar weg"},
    {"swedish": "familj", "german": "Familie", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "familj", "def_sg": "familjen", "indef_pl": "familjer", "def_pl": "familjerna"}},
    {"swedish": "man", "german": "Mann, Ehemann", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "man", "def_sg": "mannen", "indef_pl": "män", "def_pl": "männen"}, "grammar_note": "unregelmäßiger Plural mit Umlaut + Konsonantenverdoppelung; Homonym zum Pronomen 'man' (= generisches 'man')"},
    {"swedish": "fru", "german": "Frau, Ehefrau", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "fru", "def_sg": "frun", "indef_pl": "fruar", "def_pl": "fruarna"}},
    {"swedish": "barnbarn", "german": "Enkelkind", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "barnbarn", "def_sg": "barnbarnet", "indef_pl": "barnbarn", "def_pl": "barnbarnen"}, "grammar_note": "unveränderlicher Plural"},

    # --- Nomen: Zuhause ---
    {"swedish": "hus", "german": "Haus", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "hus", "def_sg": "huset", "indef_pl": "hus", "def_pl": "husen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "lägenhet", "german": "Wohnung", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lägenhet", "def_sg": "lägenheten", "indef_pl": "lägenheter", "def_pl": "lägenheterna"}},
    {"swedish": "rum", "german": "Zimmer", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "rum", "def_sg": "rummet", "indef_pl": "rum", "def_pl": "rummen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "kök", "german": "Küche", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "kök", "def_sg": "köket", "indef_pl": "kök", "def_pl": "köken"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "badrum", "german": "Badezimmer", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "badrum", "def_sg": "badrummet", "indef_pl": "badrum", "def_pl": "badrummen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "sovrum", "german": "Schlafzimmer", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "sovrum", "def_sg": "sovrummet", "indef_pl": "sovrum", "def_pl": "sovrummen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "vardagsrum", "german": "Wohnzimmer", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "vardagsrum", "def_sg": "vardagsrummet", "indef_pl": "vardagsrum", "def_pl": "vardagsrummen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "dörr", "german": "Tür", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "dörr", "def_sg": "dörren", "indef_pl": "dörrar", "def_pl": "dörrarna"}},
    {"swedish": "fönster", "german": "Fenster", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "fönster", "def_sg": "fönstret", "indef_pl": "fönster", "def_pl": "fönstren"}, "grammar_note": "ett-Wort trotz -er-Endung, unveränderlicher Plural"},
    {"swedish": "bord", "german": "Tisch", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "bord", "def_sg": "bordet", "indef_pl": "bord", "def_pl": "borden"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "stol", "german": "Stuhl", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "stol", "def_sg": "stolen", "indef_pl": "stolar", "def_pl": "stolarna"}},
    {"swedish": "säng", "german": "Bett", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "säng", "def_sg": "sängen", "indef_pl": "sängar", "def_pl": "sängarna"}},
    {"swedish": "soffa", "german": "Sofa", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "soffa", "def_sg": "soffan", "indef_pl": "soffor", "def_pl": "sofforna"}},
    {"swedish": "nyckel", "german": "Schlüssel", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "nyckel", "def_sg": "nyckeln", "indef_pl": "nycklar", "def_pl": "nycklarna"}, "grammar_note": "Stammvokal-e fällt vor -ar weg"},
    {"swedish": "golv", "german": "Boden", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "golv", "def_sg": "golvet", "indef_pl": "golv", "def_pl": "golven"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "tak", "german": "Dach, Decke", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "tak", "def_sg": "taket", "indef_pl": "tak", "def_pl": "taken"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "vägg", "german": "Wand", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "vägg", "def_sg": "väggen", "indef_pl": "väggar", "def_pl": "väggarna"}},
    {"swedish": "trädgård", "german": "Garten", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "trädgård", "def_sg": "trädgården", "indef_pl": "trädgårdar", "def_pl": "trädgårdarna"}},
    {"swedish": "lampa", "german": "Lampe", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lampa", "def_sg": "lampan", "indef_pl": "lampor", "def_pl": "lamporna"}},

    # --- Nomen: Zeit ---
    {"swedish": "dag", "german": "Tag", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "dag", "def_sg": "dagen", "indef_pl": "dagar", "def_pl": "dagarna"}},
    {"swedish": "vecka", "german": "Woche", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "vecka", "def_sg": "veckan", "indef_pl": "veckor", "def_pl": "veckorna"}},
    {"swedish": "morgon", "german": "Morgen", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "morgon", "def_sg": "morgonen", "indef_pl": "morgnar", "def_pl": "morgnarna"}, "grammar_note": "Stammvokal-o fällt vor -nar weg"},
    {"swedish": "kväll", "german": "Abend", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kväll", "def_sg": "kvällen", "indef_pl": "kvällar", "def_pl": "kvällarna"}},
    {"swedish": "natt", "german": "Nacht", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "natt", "def_sg": "natten", "indef_pl": "nätter", "def_pl": "nätterna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "timme", "german": "Stunde", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "timme", "def_sg": "timmen", "indef_pl": "timmar", "def_pl": "timmarna"}},
    {"swedish": "minut", "german": "Minute", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "minut", "def_sg": "minuten", "indef_pl": "minuter", "def_pl": "minuterna"}},
    {"swedish": "sekund", "german": "Sekunde", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sekund", "def_sg": "sekunden", "indef_pl": "sekunder", "def_pl": "sekunderna"}},
    {"swedish": "vatten", "german": "Wasser", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "vatten", "def_sg": "vattnet", "indef_pl": "vatten", "def_pl": "vattnen"}, "grammar_note": "Stammvokal-e fällt vor Endung weg"},

    # --- Nomen: Alltagsgegenstände ---
    {"swedish": "telefon", "german": "Telefon", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "telefon", "def_sg": "telefonen", "indef_pl": "telefoner", "def_pl": "telefonerna"}},
    {"swedish": "dator", "german": "Computer", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "dator", "def_sg": "datorn", "indef_pl": "datorer", "def_pl": "datorerna"}},
    {"swedish": "bok", "german": "Buch", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "bok", "def_sg": "boken", "indef_pl": "böcker", "def_pl": "böckerna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "penna", "german": "Stift", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "penna", "def_sg": "pennan", "indef_pl": "pennor", "def_pl": "pennorna"}},
    {"swedish": "papper", "german": "Papier", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "papper", "def_sg": "pappret", "indef_pl": "papper", "def_pl": "papperen"}, "grammar_note": "Stammvokal-e fällt in bestimmter Form weg"},
    {"swedish": "väska", "german": "Tasche", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "väska", "def_sg": "väskan", "indef_pl": "väskor", "def_pl": "väskorna"}},

    # --- Nomen: Essen ---
    {"swedish": "mat", "german": "Essen (allgemein)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mat", "def_sg": "maten", "indef_pl": "mat", "def_pl": "maten"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "frukost", "german": "Frühstück", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "frukost", "def_sg": "frukosten", "indef_pl": "frukostar", "def_pl": "frukostarna"}},
    {"swedish": "lunch", "german": "Mittagessen", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lunch", "def_sg": "lunchen", "indef_pl": "lunchar", "def_pl": "luncharna"}},
    {"swedish": "middag", "german": "Abendessen", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "middag", "def_sg": "middagen", "indef_pl": "middagar", "def_pl": "middagarna"}},
    {"swedish": "bröd", "german": "Brot", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "bröd", "def_sg": "brödet", "indef_pl": "bröd", "def_pl": "bröden"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "smör", "german": "Butter", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "smör", "def_sg": "smöret", "indef_pl": "smör", "def_pl": "smöret"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "ost", "german": "Käse", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "ost", "def_sg": "osten", "indef_pl": "ostar", "def_pl": "ostarna"}},
    {"swedish": "mjölk", "german": "Milch", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mjölk", "def_sg": "mjölken", "indef_pl": "mjölk", "def_pl": "mjölken"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "ägg", "german": "Ei", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "ägg", "def_sg": "ägget", "indef_pl": "ägg", "def_pl": "äggen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "kött", "german": "Fleisch", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "kött", "def_sg": "köttet", "indef_pl": "kött", "def_pl": "köttet"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "fisk", "german": "Fisch", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "fisk", "def_sg": "fisken", "indef_pl": "fiskar", "def_pl": "fiskarna"}},
    {"swedish": "grönsak", "german": "Gemüse (einzelnes)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "grönsak", "def_sg": "grönsaken", "indef_pl": "grönsaker", "def_pl": "grönsakerna"}},
    {"swedish": "frukt", "german": "Obst, Frucht", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "frukt", "def_sg": "frukten", "indef_pl": "frukter", "def_pl": "frukterna"}},
    {"swedish": "äpple", "german": "Apfel", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "äpple", "def_sg": "äpplet", "indef_pl": "äpplen", "def_pl": "äpplena"}},
    {"swedish": "banan", "german": "Banane", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "banan", "def_sg": "bananen", "indef_pl": "bananer", "def_pl": "bananerna"}},
    {"swedish": "potatis", "german": "Kartoffel", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "potatis", "def_sg": "potatisen", "indef_pl": "potatisar", "def_pl": "potatisarna"}},
    {"swedish": "socker", "german": "Zucker", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "socker", "def_sg": "sockret", "indef_pl": "socker", "def_pl": "sockret"}, "grammar_note": "Massennomen, Stammvokal-e fällt in bestimmter Form weg"},
    {"swedish": "salt", "german": "Salz", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "salt", "def_sg": "saltet", "indef_pl": "salt", "def_pl": "saltet"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "kaffe", "german": "Kaffee", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "kaffe", "def_sg": "kaffet", "indef_pl": "kaffe", "def_pl": "kaffet"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "te", "german": "Tee", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "te", "def_sg": "tet", "indef_pl": "te", "def_pl": "tet"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "vin", "german": "Wein", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "vin", "def_sg": "vinet", "indef_pl": "viner", "def_pl": "vinerna"}},
    {"swedish": "öl", "german": "Bier", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "öl", "def_sg": "ölet", "indef_pl": "öl", "def_pl": "ölen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "sallad", "german": "Salat", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sallad", "def_sg": "salladen", "indef_pl": "sallader", "def_pl": "salladerna"}},
    {"swedish": "soppa", "german": "Suppe", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "soppa", "def_sg": "soppan", "indef_pl": "soppor", "def_pl": "sopporna"}},
    {"swedish": "kaka", "german": "Kuchen, Keks", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kaka", "def_sg": "kakan", "indef_pl": "kakor", "def_pl": "kakorna"}},
    {"swedish": "glass", "german": "Eis (Süßspeise)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "glass", "def_sg": "glassen", "indef_pl": "glassar", "def_pl": "glassarna"}},
    {"swedish": "tallrik", "german": "Teller", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "tallrik", "def_sg": "tallriken", "indef_pl": "tallrikar", "def_pl": "tallrikarna"}},
    {"swedish": "glas", "german": "Glas (Trinkgefäß)", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "glas", "def_sg": "glaset", "indef_pl": "glas", "def_pl": "glasen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "kniv", "german": "Messer", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kniv", "def_sg": "kniven", "indef_pl": "knivar", "def_pl": "knivarna"}},
    {"swedish": "gaffel", "german": "Gabel", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "gaffel", "def_sg": "gaffeln", "indef_pl": "gafflar", "def_pl": "gafflarna"}, "grammar_note": "Stammvokal-e fällt vor -ar weg"},
    {"swedish": "sked", "german": "Löffel", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sked", "def_sg": "skeden", "indef_pl": "skedar", "def_pl": "skedarna"}},
    {"swedish": "restaurang", "german": "Restaurant", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "restaurang", "def_sg": "restaurangen", "indef_pl": "restauranger", "def_pl": "restaurangerna"}},

    # --- Nomen: Körper ---
    {"swedish": "kropp", "german": "Körper", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kropp", "def_sg": "kroppen", "indef_pl": "kroppar", "def_pl": "kropparna"}},
    {"swedish": "huvud", "german": "Kopf", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "huvud", "def_sg": "huvudet", "indef_pl": "huvuden", "def_pl": "huvudena"}, "grammar_note": "unregelmäßige Deklination"},
    {"swedish": "hår", "german": "Haar", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "hår", "def_sg": "håret", "indef_pl": "hår", "def_pl": "håren"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "öga", "german": "Auge", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "öga", "def_sg": "ögat", "indef_pl": "ögon", "def_pl": "ögonen"}, "grammar_note": "stark unregelmäßig, ett-Wort trotz -a-Endung"},
    {"swedish": "öra", "german": "Ohr", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "öra", "def_sg": "örat", "indef_pl": "öron", "def_pl": "öronen"}, "grammar_note": "stark unregelmäßig, ett-Wort trotz -a-Endung"},
    {"swedish": "näsa", "german": "Nase", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "näsa", "def_sg": "näsan", "indef_pl": "näsor", "def_pl": "näsorna"}},
    {"swedish": "mun", "german": "Mund", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mun", "def_sg": "munnen", "indef_pl": "munnar", "def_pl": "munnarna"}, "grammar_note": "Konsonantenverdoppelung"},
    {"swedish": "tand", "german": "Zahn", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "tand", "def_sg": "tanden", "indef_pl": "tänder", "def_pl": "tänderna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "hals", "german": "Hals", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "hals", "def_sg": "halsen", "indef_pl": "halsar", "def_pl": "halsarna"}},
    {"swedish": "arm", "german": "Arm", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "arm", "def_sg": "armen", "indef_pl": "armar", "def_pl": "armarna"}},
    {"swedish": "hand", "german": "Hand", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "hand", "def_sg": "handen", "indef_pl": "händer", "def_pl": "händerna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "finger", "german": "Finger", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "finger", "def_sg": "fingret", "indef_pl": "fingrar", "def_pl": "fingrarna"}, "grammar_note": "Stammvokal-e fällt weg"},
    {"swedish": "ben", "german": "Bein, Knochen", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "ben", "def_sg": "benet", "indef_pl": "ben", "def_pl": "benen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "fot", "german": "Fuß", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "fot", "def_sg": "foten", "indef_pl": "fötter", "def_pl": "fötterna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "mage", "german": "Bauch", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mage", "def_sg": "magen", "indef_pl": "magar", "def_pl": "magarna"}},
    {"swedish": "rygg", "german": "Rücken", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "rygg", "def_sg": "ryggen", "indef_pl": "ryggar", "def_pl": "ryggarna"}},
    {"swedish": "hjärta", "german": "Herz", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "hjärta", "def_sg": "hjärtat", "indef_pl": "hjärtan", "def_pl": "hjärtana"}, "grammar_note": "ett-Wort trotz -a-Endung (wie öga, öra)"},
    {"swedish": "hud", "german": "Haut", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "hud", "def_sg": "huden", "indef_pl": "hudar", "def_pl": "hudarna"}, "grammar_note": "meist nur im Singular verwendet"},
    {"swedish": "axel", "german": "Schulter", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "axel", "def_sg": "axeln", "indef_pl": "axlar", "def_pl": "axlarna"}, "grammar_note": "Stammvokal-e fällt vor -ar weg"},
    {"swedish": "knä", "german": "Knie", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "knä", "def_sg": "knät", "indef_pl": "knän", "def_pl": "knäna"}},

    # --- Nomen: Arbeit ---
    {"swedish": "arbete", "german": "Arbeit", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "arbete", "def_sg": "arbetet", "indef_pl": "arbeten", "def_pl": "arbetena"}},
    {"swedish": "jobb", "german": "Job, Arbeitsstelle", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "jobb", "def_sg": "jobbet", "indef_pl": "jobb", "def_pl": "jobben"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "företag", "german": "Firma", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "företag", "def_sg": "företaget", "indef_pl": "företag", "def_pl": "företagen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "kontor", "german": "Büro", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "kontor", "def_sg": "kontoret", "indef_pl": "kontor", "def_pl": "kontoren"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "chef", "german": "Chef", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "chef", "def_sg": "chefen", "indef_pl": "chefer", "def_pl": "cheferna"}},
    {"swedish": "kollega", "german": "Kollege", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kollega", "def_sg": "kollegan", "indef_pl": "kollegor", "def_pl": "kollegorna"}},
    {"swedish": "lön", "german": "Gehalt", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lön", "def_sg": "lönen", "indef_pl": "löner", "def_pl": "lönerna"}},
    {"swedish": "möte", "german": "Meeting, Treffen", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "möte", "def_sg": "mötet", "indef_pl": "möten", "def_pl": "mötena"}},
    {"swedish": "projekt", "german": "Projekt", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "projekt", "def_sg": "projektet", "indef_pl": "projekt", "def_pl": "projekten"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "uppgift", "german": "Aufgabe", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "uppgift", "def_sg": "uppgiften", "indef_pl": "uppgifter", "def_pl": "uppgifterna"}},
    {"swedish": "anställning", "german": "Anstellung", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "anställning", "def_sg": "anställningen", "indef_pl": "anställningar", "def_pl": "anställningarna"}},
    {"swedish": "intervju", "german": "Vorstellungsgespräch", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "intervju", "def_sg": "intervjun", "indef_pl": "intervjuer", "def_pl": "intervjuerna"}},
    {"swedish": "yrke", "german": "Beruf", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "yrke", "def_sg": "yrket", "indef_pl": "yrken", "def_pl": "yrkena"}},
    {"swedish": "lärare", "german": "Lehrer", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lärare", "def_sg": "läraren", "indef_pl": "lärare", "def_pl": "lärarna"}, "grammar_note": "unveränderlicher indef. Plural (-are-Klasse)"},

    # --- Nomen: Stadt ---
    {"swedish": "stad", "german": "Stadt", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "stad", "def_sg": "staden", "indef_pl": "städer", "def_pl": "städerna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "gata", "german": "Straße", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "gata", "def_sg": "gatan", "indef_pl": "gator", "def_pl": "gatorna"}},
    {"swedish": "affär", "german": "Geschäft, Laden", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "affär", "def_sg": "affären", "indef_pl": "affärer", "def_pl": "affärerna"}},
    {"swedish": "butik", "german": "Laden, Geschäft", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "butik", "def_sg": "butiken", "indef_pl": "butiker", "def_pl": "butikerna"}},
    {"swedish": "torg", "german": "Marktplatz", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "torg", "def_sg": "torget", "indef_pl": "torg", "def_pl": "torgen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "park", "german": "Park", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "park", "def_sg": "parken", "indef_pl": "parker", "def_pl": "parkerna"}},
    {"swedish": "bro", "german": "Brücke", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "bro", "def_sg": "bron", "indef_pl": "broar", "def_pl": "broarna"}},
    {"swedish": "skola", "german": "Schule", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "skola", "def_sg": "skolan", "indef_pl": "skolor", "def_pl": "skolorna"}},
    {"swedish": "sjukhus", "german": "Krankenhaus", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "sjukhus", "def_sg": "sjukhuset", "indef_pl": "sjukhus", "def_pl": "sjukhusen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "station", "german": "Bahnhof, Station", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "station", "def_sg": "stationen", "indef_pl": "stationer", "def_pl": "stationerna"}},
    {"swedish": "flygplats", "german": "Flughafen", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "flygplats", "def_sg": "flygplatsen", "indef_pl": "flygplatser", "def_pl": "flygplatserna"}},
    {"swedish": "hotell", "german": "Hotel", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "hotell", "def_sg": "hotellet", "indef_pl": "hotell", "def_pl": "hotellen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "bank", "german": "Bank (Institut)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "bank", "def_sg": "banken", "indef_pl": "banker", "def_pl": "bankerna"}},
    {"swedish": "kyrka", "german": "Kirche", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kyrka", "def_sg": "kyrkan", "indef_pl": "kyrkor", "def_pl": "kyrkorna"}},
    {"swedish": "bibliotek", "german": "Bibliothek", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "bibliotek", "def_sg": "biblioteket", "indef_pl": "bibliotek", "def_pl": "biblioteken"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "museum", "german": "Museum", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "museum", "def_sg": "museet", "indef_pl": "museer", "def_pl": "museerna"}, "grammar_note": "unregelmäßig (Lehnwort)"},
    {"swedish": "polis", "german": "Polizei, Polizist", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "polis", "def_sg": "polisen", "indef_pl": "poliser", "def_pl": "poliserna"}},
    {"swedish": "buss", "german": "Bus", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "buss", "def_sg": "bussen", "indef_pl": "bussar", "def_pl": "bussarna"}},
    {"swedish": "tåg", "german": "Zug", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "tåg", "def_sg": "tåget", "indef_pl": "tåg", "def_pl": "tågen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "bil", "german": "Auto", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "bil", "def_sg": "bilen", "indef_pl": "bilar", "def_pl": "bilarna"}},
    {"swedish": "väg", "german": "Weg, Straße", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "väg", "def_sg": "vägen", "indef_pl": "vägar", "def_pl": "vägarna"}},

    # --- Adjektive: Größe ---
    {"swedish": "stor", "german": "groß", "category": "Adjektiv", "forms": {"en_form": "stor", "ett_form": "stort", "plural_bestimmt": "stora"}},
    {"swedish": "liten", "german": "klein", "category": "Adjektiv", "forms": {"en_form": "liten", "ett_form": "litet", "plural_bestimmt": "små"}, "grammar_note": "stark unregelmäßig, Pluralform ist ein anderes Wort"},
    {"swedish": "lång", "german": "lang", "category": "Adjektiv", "forms": {"en_form": "lång", "ett_form": "långt", "plural_bestimmt": "långa"}},
    {"swedish": "kort", "german": "kurz", "category": "Adjektiv", "forms": {"en_form": "kort", "ett_form": "kort", "plural_bestimmt": "korta"}, "grammar_note": "ett-Form unverändert, endet schon auf -t"},
    {"swedish": "hög", "german": "hoch", "category": "Adjektiv", "forms": {"en_form": "hög", "ett_form": "högt", "plural_bestimmt": "höga"}},
    {"swedish": "låg", "german": "niedrig", "category": "Adjektiv", "forms": {"en_form": "låg", "ett_form": "lågt", "plural_bestimmt": "låga"}},
    {"swedish": "bred", "german": "breit", "category": "Adjektiv", "forms": {"en_form": "bred", "ett_form": "brett", "plural_bestimmt": "breda"}},
    {"swedish": "smal", "german": "schmal", "category": "Adjektiv", "forms": {"en_form": "smal", "ett_form": "smalt", "plural_bestimmt": "smala"}},
    {"swedish": "djup", "german": "tief", "category": "Adjektiv", "forms": {"en_form": "djup", "ett_form": "djupt", "plural_bestimmt": "djupa"}},
    {"swedish": "tung", "german": "schwer (Gewicht)", "category": "Adjektiv", "forms": {"en_form": "tung", "ett_form": "tungt", "plural_bestimmt": "tunga"}},
    {"swedish": "lätt", "german": "leicht (Gewicht), einfach", "category": "Adjektiv", "forms": {"en_form": "lätt", "ett_form": "lätt", "plural_bestimmt": "lätta"}, "grammar_note": "ett-Form unverändert, endet schon auf -t"},
    {"swedish": "tjock", "german": "dick", "category": "Adjektiv", "forms": {"en_form": "tjock", "ett_form": "tjockt", "plural_bestimmt": "tjocka"}},
    {"swedish": "tunn", "german": "dünn", "category": "Adjektiv", "forms": {"en_form": "tunn", "ett_form": "tunt", "plural_bestimmt": "tunna"}, "grammar_note": "Konsonantenvereinfachung vor -t (tunn -> tunt)"},

    # --- Adjektive: Farbe ---
    {"swedish": "röd", "german": "rot", "category": "Adjektiv", "forms": {"en_form": "röd", "ett_form": "rött", "plural_bestimmt": "röda"}, "grammar_note": "d+t verschmilzt zu tt"},
    {"swedish": "blå", "german": "blau", "category": "Adjektiv", "forms": {"en_form": "blå", "ett_form": "blått", "plural_bestimmt": "blåa"}},
    {"swedish": "gul", "german": "gelb", "category": "Adjektiv", "forms": {"en_form": "gul", "ett_form": "gult", "plural_bestimmt": "gula"}},
    {"swedish": "grön", "german": "grün", "category": "Adjektiv", "forms": {"en_form": "grön", "ett_form": "grönt", "plural_bestimmt": "gröna"}},
    {"swedish": "svart", "german": "schwarz", "category": "Adjektiv", "forms": {"en_form": "svart", "ett_form": "svart", "plural_bestimmt": "svarta"}, "grammar_note": "ett-Form unverändert, endet schon auf -t"},
    {"swedish": "vit", "german": "weiß", "category": "Adjektiv", "forms": {"en_form": "vit", "ett_form": "vitt", "plural_bestimmt": "vita"}},
    {"swedish": "brun", "german": "braun", "category": "Adjektiv", "forms": {"en_form": "brun", "ett_form": "brunt", "plural_bestimmt": "bruna"}},
    {"swedish": "grå", "german": "grau", "category": "Adjektiv", "forms": {"en_form": "grå", "ett_form": "grått", "plural_bestimmt": "gråa"}},
    {"swedish": "rosa", "german": "rosa", "category": "Adjektiv", "forms": {"en_form": "rosa", "ett_form": "rosa", "plural_bestimmt": "rosa"}, "grammar_note": "unveränderlich (Lehnwort-Farbe)"},
    {"swedish": "orange", "german": "orange", "category": "Adjektiv", "forms": {"en_form": "orange", "ett_form": "orange", "plural_bestimmt": "orange"}, "grammar_note": "unveränderlich (Lehnwort-Farbe)"},
    {"swedish": "lila", "german": "lila", "category": "Adjektiv", "forms": {"en_form": "lila", "ett_form": "lila", "plural_bestimmt": "lila"}, "grammar_note": "unveränderlich (Lehnwort-Farbe)"},

    # --- Adjektive: Gefühl ---
    {"swedish": "glad", "german": "froh, glücklich", "category": "Adjektiv", "forms": {"en_form": "glad", "ett_form": "glatt", "plural_bestimmt": "glada"}, "grammar_note": "d+t verschmilzt zu tt"},
    {"swedish": "ledsen", "german": "traurig", "category": "Adjektiv", "forms": {"en_form": "ledsen", "ett_form": "ledset", "plural_bestimmt": "ledsna"}, "grammar_note": "Stammvokal-e fällt vor -na weg"},
    {"swedish": "arg", "german": "wütend", "category": "Adjektiv", "forms": {"en_form": "arg", "ett_form": "argt", "plural_bestimmt": "arga"}},
    {"swedish": "trött", "german": "müde", "category": "Adjektiv", "forms": {"en_form": "trött", "ett_form": "trött", "plural_bestimmt": "trötta"}, "grammar_note": "ett-Form unverändert, endet schon auf -tt"},
    {"swedish": "rädd", "german": "ängstlich, verängstigt", "category": "Adjektiv", "forms": {"en_form": "rädd", "ett_form": "rädd", "plural_bestimmt": "rädda"}, "grammar_note": "ett-Form unverändert, endet schon auf -dd"},
    {"swedish": "nöjd", "german": "zufrieden", "category": "Adjektiv", "forms": {"en_form": "nöjd", "ett_form": "nöjt", "plural_bestimmt": "nöjda"}, "grammar_note": "d fällt vor -t weg"},
    {"swedish": "förvånad", "german": "überrascht", "category": "Adjektiv", "forms": {"en_form": "förvånad", "ett_form": "förvånat", "plural_bestimmt": "förvånade"}},
    {"swedish": "trevlig", "german": "nett, angenehm", "category": "Adjektiv", "forms": {"en_form": "trevlig", "ett_form": "trevligt", "plural_bestimmt": "trevliga"}},
    {"swedish": "rolig", "german": "lustig, spaßig", "category": "Adjektiv", "forms": {"en_form": "rolig", "ett_form": "roligt", "plural_bestimmt": "roliga"}},
    {"swedish": "tråkig", "german": "langweilig", "category": "Adjektiv", "forms": {"en_form": "tråkig", "ett_form": "tråkigt", "plural_bestimmt": "tråkiga"}},
    {"swedish": "spännande", "german": "spannend", "category": "Adjektiv", "forms": {"en_form": "spännande", "ett_form": "spännande", "plural_bestimmt": "spännande"}, "grammar_note": "Partizip-Adjektiv, komplett unveränderlich"},
    {"swedish": "intressant", "german": "interessant", "category": "Adjektiv", "forms": {"en_form": "intressant", "ett_form": "intressant", "plural_bestimmt": "intressanta"}, "grammar_note": "ett-Form unverändert (-ant-Endung)"},
    {"swedish": "lugn", "german": "ruhig", "category": "Adjektiv", "forms": {"en_form": "lugn", "ett_form": "lugnt", "plural_bestimmt": "lugna"}},
    {"swedish": "nervös", "german": "nervös", "category": "Adjektiv", "forms": {"en_form": "nervös", "ett_form": "nervöst", "plural_bestimmt": "nervösa"}},
    {"swedish": "stressad", "german": "gestresst", "category": "Adjektiv", "forms": {"en_form": "stressad", "ett_form": "stressat", "plural_bestimmt": "stressade"}},
    {"swedish": "förälskad", "german": "verliebt", "category": "Adjektiv", "forms": {"en_form": "förälskad", "ett_form": "förälskat", "plural_bestimmt": "förälskade"}},
    {"swedish": "ensam", "german": "einsam", "category": "Adjektiv", "forms": {"en_form": "ensam", "ett_form": "ensamt", "plural_bestimmt": "ensamma"}, "grammar_note": "Konsonantenverdoppelung vor -a"},
    {"swedish": "lycklig", "german": "glücklich", "category": "Adjektiv", "forms": {"en_form": "lycklig", "ett_form": "lyckligt", "plural_bestimmt": "lyckliga"}},

    # --- Adjektive: Eigenschaften ---
    {"swedish": "bra", "german": "gut", "category": "Adjektiv", "forms": {"en_form": "bra", "ett_form": "bra", "plural_bestimmt": "bra"}, "grammar_note": "unveränderlich"},
    {"swedish": "dålig", "german": "schlecht", "category": "Adjektiv", "forms": {"en_form": "dålig", "ett_form": "dåligt", "plural_bestimmt": "dåliga"}},
    {"swedish": "ny", "german": "neu", "category": "Adjektiv", "forms": {"en_form": "ny", "ett_form": "nytt", "plural_bestimmt": "nya"}, "grammar_note": "t verdoppelt sich nach Vokal"},
    {"swedish": "gammal", "german": "alt", "category": "Adjektiv", "forms": {"en_form": "gammal", "ett_form": "gammalt", "plural_bestimmt": "gamla"}, "grammar_note": "Stammvokal fällt vor -a weg"},
    {"swedish": "snabb", "german": "schnell", "category": "Adjektiv", "forms": {"en_form": "snabb", "ett_form": "snabbt", "plural_bestimmt": "snabba"}},
    {"swedish": "långsam", "german": "langsam", "category": "Adjektiv", "forms": {"en_form": "långsam", "ett_form": "långsamt", "plural_bestimmt": "långsamma"}, "grammar_note": "Konsonantenverdoppelung vor -a"},
    {"swedish": "stark", "german": "stark", "category": "Adjektiv", "forms": {"en_form": "stark", "ett_form": "starkt", "plural_bestimmt": "starka"}},
    {"swedish": "svag", "german": "schwach", "category": "Adjektiv", "forms": {"en_form": "svag", "ett_form": "svagt", "plural_bestimmt": "svaga"}},
    {"swedish": "vacker", "german": "schön", "category": "Adjektiv", "forms": {"en_form": "vacker", "ett_form": "vackert", "plural_bestimmt": "vackra"}, "grammar_note": "Stammvokal-e fällt vor -ra weg"},
    {"swedish": "ful", "german": "hässlich", "category": "Adjektiv", "forms": {"en_form": "ful", "ett_form": "fult", "plural_bestimmt": "fula"}},
    {"swedish": "snäll", "german": "nett, lieb", "category": "Adjektiv", "forms": {"en_form": "snäll", "ett_form": "snällt", "plural_bestimmt": "snälla"}},
    {"swedish": "dum", "german": "dumm", "category": "Adjektiv", "forms": {"en_form": "dum", "ett_form": "dumt", "plural_bestimmt": "dumma"}, "grammar_note": "Konsonantenverdoppelung vor -a"},
    {"swedish": "smart", "german": "klug", "category": "Adjektiv", "forms": {"en_form": "smart", "ett_form": "smart", "plural_bestimmt": "smarta"}, "grammar_note": "ett-Form unverändert, endet schon auf -t"},
    {"swedish": "dyr", "german": "teuer", "category": "Adjektiv", "forms": {"en_form": "dyr", "ett_form": "dyrt", "plural_bestimmt": "dyra"}},
    {"swedish": "billig", "german": "billig, günstig", "category": "Adjektiv", "forms": {"en_form": "billig", "ett_form": "billigt", "plural_bestimmt": "billiga"}},
    {"swedish": "viktig", "german": "wichtig", "category": "Adjektiv", "forms": {"en_form": "viktig", "ett_form": "viktigt", "plural_bestimmt": "viktiga"}},
    {"swedish": "svår", "german": "schwierig", "category": "Adjektiv", "forms": {"en_form": "svår", "ett_form": "svårt", "plural_bestimmt": "svåra"}},
    {"swedish": "enkel", "german": "einfach", "category": "Adjektiv", "forms": {"en_form": "enkel", "ett_form": "enkelt", "plural_bestimmt": "enkla"}, "grammar_note": "Stammvokal-e fällt vor -la weg"},
    {"swedish": "konstig", "german": "komisch, seltsam", "category": "Adjektiv", "forms": {"en_form": "konstig", "ett_form": "konstigt", "plural_bestimmt": "konstiga"}},
    {"swedish": "vanlig", "german": "gewöhnlich, üblich", "category": "Adjektiv", "forms": {"en_form": "vanlig", "ett_form": "vanligt", "plural_bestimmt": "vanliga"}},
    {"swedish": "speciell", "german": "besonders, speziell", "category": "Adjektiv", "forms": {"en_form": "speciell", "ett_form": "speciellt", "plural_bestimmt": "speciella"}},
    {"swedish": "säker", "german": "sicher", "category": "Adjektiv", "forms": {"en_form": "säker", "ett_form": "säkert", "plural_bestimmt": "säkra"}, "grammar_note": "Stammvokal-e fällt vor -ra weg"},
    {"swedish": "farlig", "german": "gefährlich", "category": "Adjektiv", "forms": {"en_form": "farlig", "ett_form": "farligt", "plural_bestimmt": "farliga"}},
    {"swedish": "ren", "german": "sauber", "category": "Adjektiv", "forms": {"en_form": "ren", "ett_form": "rent", "plural_bestimmt": "rena"}},
    {"swedish": "smutsig", "german": "schmutzig", "category": "Adjektiv", "forms": {"en_form": "smutsig", "ett_form": "smutsigt", "plural_bestimmt": "smutsiga"}},
    {"swedish": "torr", "german": "trocken", "category": "Adjektiv", "forms": {"en_form": "torr", "ett_form": "torrt", "plural_bestimmt": "torra"}},
    {"swedish": "våt", "german": "nass", "category": "Adjektiv", "forms": {"en_form": "våt", "ett_form": "vått", "plural_bestimmt": "våta"}},
    {"swedish": "varm", "german": "warm", "category": "Adjektiv", "forms": {"en_form": "varm", "ett_form": "varmt", "plural_bestimmt": "varma"}},
    {"swedish": "kall", "german": "kalt", "category": "Adjektiv", "forms": {"en_form": "kall", "ett_form": "kallt", "plural_bestimmt": "kalla"}},
    {"swedish": "söt", "german": "süß, niedlich", "category": "Adjektiv", "forms": {"en_form": "söt", "ett_form": "sött", "plural_bestimmt": "söta"}},
    {"swedish": "sur", "german": "sauer", "category": "Adjektiv", "forms": {"en_form": "sur", "ett_form": "surt", "plural_bestimmt": "sura"}},
    {"swedish": "salt", "german": "salzig", "category": "Adjektiv", "forms": {"en_form": "salt", "ett_form": "salt", "plural_bestimmt": "salta"}, "grammar_note": "ett-Form unverändert, endet schon auf -t; Homonym zum Nomen 'salt' (Salz)"},
    {"swedish": "öppen", "german": "offen", "category": "Adjektiv", "forms": {"en_form": "öppen", "ett_form": "öppet", "plural_bestimmt": "öppna"}, "grammar_note": "unregelmäßig (-en-Adjektiv-Klasse)"},
    {"swedish": "stängd", "german": "geschlossen", "category": "Adjektiv", "forms": {"en_form": "stängd", "ett_form": "stängt", "plural_bestimmt": "stängda"}, "grammar_note": "d fällt vor -t weg"},
    {"swedish": "färdig", "german": "fertig", "category": "Adjektiv", "forms": {"en_form": "färdig", "ett_form": "färdigt", "plural_bestimmt": "färdiga"}},
    {"swedish": "klar", "german": "fertig, klar", "category": "Adjektiv", "forms": {"en_form": "klar", "ett_form": "klart", "plural_bestimmt": "klara"}},
    {"swedish": "rätt", "german": "richtig, korrekt", "category": "Adjektiv", "forms": {"en_form": "rätt", "ett_form": "rätt", "plural_bestimmt": "rätta"}, "grammar_note": "ett-Form unverändert, endet schon auf -tt"},
    {"swedish": "fel", "german": "falsch", "category": "Adjektiv", "forms": {"en_form": "fel", "ett_form": "fel", "plural_bestimmt": "fel"}, "grammar_note": "unveränderlich"},

    # --- Nomen: Kleidung (Auffuellung auf ca. 500 Woerter) ---
    {"swedish": "kläder", "german": "Kleidung", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kläder", "def_sg": "kläderna", "indef_pl": "kläder", "def_pl": "kläderna"}, "grammar_note": "Pluraletantum, hat keine eigentliche Singularform"},
    {"swedish": "skjorta", "german": "Hemd", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "skjorta", "def_sg": "skjortan", "indef_pl": "skjortor", "def_pl": "skjortorna"}},
    {"swedish": "byxor", "german": "Hose", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "byxor", "def_sg": "byxorna", "indef_pl": "byxor", "def_pl": "byxorna"}, "grammar_note": "Pluraletantum, hat keine eigentliche Singularform"},
    {"swedish": "tröja", "german": "Pullover, Shirt", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "tröja", "def_sg": "tröjan", "indef_pl": "tröjor", "def_pl": "tröjorna"}},
    {"swedish": "jacka", "german": "Jacke", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "jacka", "def_sg": "jackan", "indef_pl": "jackor", "def_pl": "jackorna"}},
    {"swedish": "klänning", "german": "Kleid", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "klänning", "def_sg": "klänningen", "indef_pl": "klänningar", "def_pl": "klänningarna"}},
    {"swedish": "kjol", "german": "Rock", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kjol", "def_sg": "kjolen", "indef_pl": "kjolar", "def_pl": "kjolarna"}},
    {"swedish": "sko", "german": "Schuh", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sko", "def_sg": "skon", "indef_pl": "skor", "def_pl": "skorna"}},
    {"swedish": "strumpa", "german": "Socke", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "strumpa", "def_sg": "strumpan", "indef_pl": "strumpor", "def_pl": "strumporna"}},
    {"swedish": "hatt", "german": "Hut", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "hatt", "def_sg": "hatten", "indef_pl": "hattar", "def_pl": "hattarna"}},
    {"swedish": "mössa", "german": "Mütze", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "mössa", "def_sg": "mössan", "indef_pl": "mössor", "def_pl": "mössorna"}},
    {"swedish": "handske", "german": "Handschuh", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "handske", "def_sg": "handsken", "indef_pl": "handskar", "def_pl": "handskarna"}},

    # --- Nomen: Wetter ---
    {"swedish": "väder", "german": "Wetter", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "väder", "def_sg": "vädret", "indef_pl": "väder", "def_pl": "vädren"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "sol", "german": "Sonne", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sol", "def_sg": "solen", "indef_pl": "solar", "def_pl": "solarna"}, "grammar_note": "Plural in der Praxis selten verwendet"},
    {"swedish": "regn", "german": "Regen", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "regn", "def_sg": "regnet", "indef_pl": "regn", "def_pl": "regnen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "snö", "german": "Schnee", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "snö", "def_sg": "snön", "indef_pl": "snö", "def_pl": "snön"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "vind", "german": "Wind", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "vind", "def_sg": "vinden", "indef_pl": "vindar", "def_pl": "vindarna"}},
    {"swedish": "moln", "german": "Wolke", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "moln", "def_sg": "molnet", "indef_pl": "moln", "def_pl": "molnen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "himmel", "german": "Himmel", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "himmel", "def_sg": "himlen", "indef_pl": "himlar", "def_pl": "himlarna"}, "grammar_note": "Stammvokal-e fällt vor -en/-ar weg"},
    {"swedish": "is", "german": "Eis (gefroren)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "is", "def_sg": "isen", "indef_pl": "is", "def_pl": "isen"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
    {"swedish": "storm", "german": "Sturm", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "storm", "def_sg": "stormen", "indef_pl": "stormar", "def_pl": "stormarna"}},
    {"swedish": "åska", "german": "Gewitter, Donner", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "åska", "def_sg": "åskan", "indef_pl": "åska", "def_pl": "åskan"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},

    # --- Nomen: Reisen ---
    {"swedish": "resa", "german": "Reise", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "resa", "def_sg": "resan", "indef_pl": "resor", "def_pl": "resorna"}, "grammar_note": "Homonym zum Verb 'resa' (reisen)"},
    {"swedish": "biljett", "german": "Ticket", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "biljett", "def_sg": "biljetten", "indef_pl": "biljetter", "def_pl": "biljetterna"}},
    {"swedish": "pass", "german": "Reisepass", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "pass", "def_sg": "passet", "indef_pl": "pass", "def_pl": "passen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "resväska", "german": "Koffer", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "resväska", "def_sg": "resväskan", "indef_pl": "resväskor", "def_pl": "resväskorna"}},
    {"swedish": "karta", "german": "Landkarte", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "karta", "def_sg": "kartan", "indef_pl": "kartor", "def_pl": "kartorna"}},
    {"swedish": "gräns", "german": "Grenze", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "gräns", "def_sg": "gränsen", "indef_pl": "gränser", "def_pl": "gränserna"}},
    {"swedish": "flygplan", "german": "Flugzeug", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "flygplan", "def_sg": "flygplanet", "indef_pl": "flygplan", "def_pl": "flygplanen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "hamn", "german": "Hafen", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "hamn", "def_sg": "hamnen", "indef_pl": "hamnar", "def_pl": "hamnarna"}},
    {"swedish": "semester", "german": "Urlaub", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "semester", "def_sg": "semestern", "indef_pl": "semestrar", "def_pl": "semestrarna"}, "grammar_note": "Stammvokal-e fällt vor -ar weg"},
    {"swedish": "turist", "german": "Tourist", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "turist", "def_sg": "turisten", "indef_pl": "turister", "def_pl": "turisterna"}},

    # --- Nomen: Universität, Studium ---
    {"swedish": "student", "german": "Student", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "student", "def_sg": "studenten", "indef_pl": "studenter", "def_pl": "studenterna"}},
    {"swedish": "kurs", "german": "Kurs", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "kurs", "def_sg": "kursen", "indef_pl": "kurser", "def_pl": "kurserna"}},
    {"swedish": "lektion", "german": "Unterrichtsstunde", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "lektion", "def_sg": "lektionen", "indef_pl": "lektioner", "def_pl": "lektionerna"}},
    {"swedish": "prov", "german": "Prüfung, Test", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "prov", "def_sg": "provet", "indef_pl": "prov", "def_pl": "proven"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "betyg", "german": "Note (Zeugnis)", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "betyg", "def_sg": "betyget", "indef_pl": "betyg", "def_pl": "betygen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "universitet", "german": "Universität", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "universitet", "def_sg": "universitetet", "indef_pl": "universitet", "def_pl": "universiteten"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "klass", "german": "Klasse", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "klass", "def_sg": "klassen", "indef_pl": "klasser", "def_pl": "klasserna"}},
    {"swedish": "fråga", "german": "Frage", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "fråga", "def_sg": "frågan", "indef_pl": "frågor", "def_pl": "frågorna"}, "grammar_note": "Homonym zum Verb 'fråga' (fragen)"},
    {"swedish": "svar", "german": "Antwort", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "svar", "def_sg": "svaret", "indef_pl": "svar", "def_pl": "svaren"}, "grammar_note": "unveränderlicher Plural"},

    # --- Nomen: Natur ---
    {"swedish": "träd", "german": "Baum", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "träd", "def_sg": "trädet", "indef_pl": "träd", "def_pl": "träden"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "blomma", "german": "Blume", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "blomma", "def_sg": "blomman", "indef_pl": "blommor", "def_pl": "blommorna"}},
    {"swedish": "skog", "german": "Wald", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "skog", "def_sg": "skogen", "indef_pl": "skogar", "def_pl": "skogarna"}},
    {"swedish": "berg", "german": "Berg", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "berg", "def_sg": "berget", "indef_pl": "berg", "def_pl": "bergen"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "sjö", "german": "See (Gewässer)", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "sjö", "def_sg": "sjön", "indef_pl": "sjöar", "def_pl": "sjöarna"}},
    {"swedish": "hav", "german": "Meer", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "hav", "def_sg": "havet", "indef_pl": "hav", "def_pl": "haven"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "strand", "german": "Strand", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "strand", "def_sg": "stranden", "indef_pl": "stränder", "def_pl": "stränderna"}, "grammar_note": "unregelmäßiger Plural mit Umlaut"},
    {"swedish": "djur", "german": "Tier", "category": "Nomen", "genus": "ett", "forms": {"indef_sg": "djur", "def_sg": "djuret", "indef_pl": "djur", "def_pl": "djuren"}, "grammar_note": "unveränderlicher Plural"},
    {"swedish": "natur", "german": "Natur", "category": "Nomen", "genus": "en", "forms": {"indef_sg": "natur", "def_sg": "naturen", "indef_pl": "natur", "def_pl": "naturen"}, "grammar_note": "Massennomen, wird meist nur im Singular verwendet"},
]