# -*- coding: utf-8 -*-
"""Die 500 meistgenutzten spanischen Woerter (2026-08-30, Simons Auftrag).

Schwedisch (schwedisch_vocab, 501) und Franzoesisch (franz_vocab, 515)
hatten diese Liste laengst - Spanisch fehlte trotz vollstaendig
uebersetztem Phrasebook komplett. Ohne sie lief die Woerter-Wiederholung
(Zuordnungsspiel, Personen-Zuordnung) fuer Spanisch ins Leere.

**Struktur wie schwedisch_vocab**, nicht wie franz_vocab: mit eigenem
`Fragewort`-Topf statt Fragewoerter unter Pronomen/Adverb zu verstecken -
das war beim Franzoesisch-Bestand im Nachhinein unklar zuzuordnen.

**Von Claude direkt zusammengestellt** aus etabliertem, oeffentlich gut
dokumentiertem Spanisch-Frequenzwortschatz (RAE-Corpus-nahe Standardlisten,
wie sie in A1/A2-Lehrwerken durchgehend auftauchen) - **nicht von
Muttersprachlern geprueft**, Spot-Check vor der Vertonung sinnvoll (gleicher
Vorbehalt wie bei Schwedisch/Chinesisch in dieser App ueblich).

**Auswahlkriterium wie bei den anderen Sprachen:** kein Fokus auf
Themenwortschatz (der steckt in den Kaufkategorien), sondern die
Woerter, die in JEDEM Alltagssatz vorkommen - Funktionswoerter vollstaendig,
dazu die haeufigsten Verben/Nomen/Adjektive/Adverbien.

Format je Eintrag: (spanisch, deutsch, Kategorie, Genus)
  Genus nur bei Nomen gesetzt: 'm' oder 'f', sonst None.
  Mehrdeutige deutsche Uebersetzungen stehen komma-getrennt im Deutsch-Feld
  (gleiche Konvention wie franz_vocab, z.B. "Mann, Mensch").

Nutzung: python import_spanisch_vocab.py [--echt]
"""

WOERTER = [
    # ---------------------------------------------------------------- Artikel (6)
    ("el / la / los / las", "der, die, das (bestimmter Artikel)", "Artikel", None),
    ("un / una", "ein, eine", "Artikel", None),
    ("unos / unas", "einige, ein paar", "Artikel", None),
    ("al", "an dem, zum", "Artikel", None),
    ("del", "von dem, vom", "Artikel", None),
    ("lo", "das (neutraler Artikel, z.B. 'lo importante')", "Artikel", None),

    # ---------------------------------------------------------------- Pronomen (38)
    ("yo", "ich", "Pronomen", None),
    ("tú", "du", "Pronomen", None),
    ("él", "er", "Pronomen", None),
    ("ella", "sie", "Pronomen", None),
    ("usted", "Sie (Höflichkeitsform)", "Pronomen", None),
    ("nosotros / nosotras", "wir", "Pronomen", None),
    ("vosotros / vosotras", "ihr", "Pronomen", None),
    ("ellos / ellas", "sie (Plural)", "Pronomen", None),
    ("ustedes", "Sie (Plural, Höflichkeitsform)", "Pronomen", None),
    ("me", "mich, mir", "Pronomen", None),
    ("te", "dich, dir", "Pronomen", None),
    ("se", "sich", "Pronomen", None),
    ("nos", "uns", "Pronomen", None),
    ("os", "euch", "Pronomen", None),
    ("lo / la", "ihn, es, sie (Objektpronomen)", "Pronomen", None),
    ("los / las", "sie (Objektpronomen, Plural)", "Pronomen", None),
    ("le / les", "ihm/ihr, ihnen (indirektes Objekt)", "Pronomen", None),
    ("mi / mis", "mein, meine", "Pronomen", None),
    ("tu / tus", "dein, deine", "Pronomen", None),
    ("su / sus", "sein/ihr, seine/ihre", "Pronomen", None),
    ("nuestro / nuestra", "unser, unsere", "Pronomen", None),
    ("vuestro / vuestra", "euer, eure", "Pronomen", None),
    ("este / esta", "dieser, diese", "Pronomen", None),
    ("ese / esa", "dieser/jener (da), diese/jene (da)", "Pronomen", None),
    ("aquel / aquella", "jener, jene (dort)", "Pronomen", None),
    ("esto", "dies (neutral)", "Pronomen", None),
    ("eso", "das (neutral)", "Pronomen", None),
    ("algo", "etwas", "Pronomen", None),
    ("alguien", "jemand", "Pronomen", None),
    ("nada", "nichts", "Pronomen", None),
    ("nadie", "niemand", "Pronomen", None),
    ("alguno / alguna", "irgendein, irgendeine", "Pronomen", None),
    ("ninguno / ninguna", "keiner, keine", "Pronomen", None),
    ("todo / toda", "alles, ganz", "Pronomen", None),
    ("otro / otra", "anderer, andere", "Pronomen", None),
    ("mismo / misma", "derselbe, dieselbe, selbst", "Pronomen", None),
    ("que", "der/die/das (Relativpronomen), dass", "Pronomen", None),
    ("quien", "wer (Relativpronomen)", "Pronomen", None),

    # ---------------------------------------------------------------- Fragewort (11)
    ("qué", "was", "Fragewort", None),
    ("quién", "wer", "Fragewort", None),
    ("cuál", "welcher, welche", "Fragewort", None),
    ("cuándo", "wann", "Fragewort", None),
    ("dónde", "wo", "Fragewort", None),
    ("adónde", "wohin", "Fragewort", None),
    ("cómo", "wie", "Fragewort", None),
    ("por qué", "warum", "Fragewort", None),
    ("para qué", "wofür, wozu", "Fragewort", None),
    ("cuánto / cuánta", "wie viel", "Fragewort", None),
    ("cuántos / cuántas", "wie viele", "Fragewort", None),

    # ---------------------------------------------------------------- Präposition (23)
    ("a", "zu, nach, an", "Präposition", None),
    ("de", "von, aus", "Präposition", None),
    ("en", "in, auf, an", "Präposition", None),
    ("con", "mit", "Präposition", None),
    ("sin", "ohne", "Präposition", None),
    ("por", "durch, wegen, für (Grund)", "Präposition", None),
    ("para", "für, um zu (Zweck)", "Präposition", None),
    ("sobre", "über, auf", "Präposition", None),
    ("entre", "zwischen", "Präposition", None),
    ("hasta", "bis", "Präposition", None),
    ("desde", "seit, von ... an", "Präposition", None),
    ("hacia", "in Richtung, gegen", "Präposition", None),
    ("contra", "gegen", "Präposition", None),
    ("durante", "während", "Präposition", None),
    ("según", "laut, gemäß", "Präposition", None),
    ("ante", "vor, angesichts", "Präposition", None),
    ("bajo", "unter", "Präposition", None),
    ("tras", "nach, hinter", "Präposition", None),
    ("dentro de", "innerhalb von", "Präposition", None),
    ("fuera de", "außerhalb von", "Präposition", None),
    ("cerca de", "in der Nähe von", "Präposition", None),
    ("lejos de", "weit weg von", "Präposition", None),
    ("encima de", "oben auf, über", "Präposition", None),

    # ---------------------------------------------------------------- Konjunktion (14)
    ("y", "und", "Konjunktion", None),
    ("o", "oder", "Konjunktion", None),
    ("pero", "aber", "Konjunktion", None),
    ("porque", "weil", "Konjunktion", None),
    ("si", "wenn, falls", "Konjunktion", None),
    ("aunque", "obwohl", "Konjunktion", None),
    ("cuando", "wenn, als", "Konjunktion", None),
    ("mientras", "während", "Konjunktion", None),
    ("entonces", "also, dann", "Konjunktion", None),
    ("además", "außerdem", "Konjunktion", None),
    ("sin embargo", "trotzdem, jedoch", "Konjunktion", None),
    ("por eso", "deshalb", "Konjunktion", None),
    ("así que", "also, sodass", "Konjunktion", None),
    ("ni", "noch, nicht einmal", "Konjunktion", None),

    # ---------------------------------------------------------------- Zahlwort (38)
    ("uno", "eins", "Zahlwort", None),
    ("dos", "zwei", "Zahlwort", None),
    ("tres", "drei", "Zahlwort", None),
    ("cuatro", "vier", "Zahlwort", None),
    ("cinco", "fünf", "Zahlwort", None),
    ("seis", "sechs", "Zahlwort", None),
    ("siete", "sieben", "Zahlwort", None),
    ("ocho", "acht", "Zahlwort", None),
    ("nueve", "neun", "Zahlwort", None),
    ("diez", "zehn", "Zahlwort", None),
    ("once", "elf", "Zahlwort", None),
    ("doce", "zwölf", "Zahlwort", None),
    ("trece", "dreizehn", "Zahlwort", None),
    ("catorce", "vierzehn", "Zahlwort", None),
    ("quince", "fünfzehn", "Zahlwort", None),
    ("dieciséis", "sechzehn", "Zahlwort", None),
    ("diecisiete", "siebzehn", "Zahlwort", None),
    ("dieciocho", "achtzehn", "Zahlwort", None),
    ("diecinueve", "neunzehn", "Zahlwort", None),
    ("veinte", "zwanzig", "Zahlwort", None),
    ("treinta", "dreißig", "Zahlwort", None),
    ("cuarenta", "vierzig", "Zahlwort", None),
    ("cincuenta", "fünfzig", "Zahlwort", None),
    ("sesenta", "sechzig", "Zahlwort", None),
    ("setenta", "siebzig", "Zahlwort", None),
    ("ochenta", "achtzig", "Zahlwort", None),
    ("noventa", "neunzig", "Zahlwort", None),
    ("cien", "hundert", "Zahlwort", None),
    ("doscientos / doscientas", "zweihundert", "Zahlwort", None),
    ("mil", "tausend", "Zahlwort", None),
    ("millón", "Million", "Zahlwort", None),
    ("primero / primera", "erster, erste", "Zahlwort", None),
    ("segundo / segunda", "zweiter, zweite", "Zahlwort", None),
    ("último / última", "letzter, letzte", "Zahlwort", None),
    ("medio / media", "halb, Hälfte", "Zahlwort", None),
    ("mucho / mucha", "viel", "Zahlwort", None),
    ("poco / poca", "wenig", "Zahlwort", None),
    ("varios / varias", "mehrere", "Zahlwort", None),

    # ---------------------------------------------------------------- Adverb (47)
    ("sí", "ja", "Adverb", None),
    ("no", "nein, nicht", "Adverb", None),
    ("también", "auch", "Adverb", None),
    ("tampoco", "auch nicht", "Adverb", None),
    ("muy", "sehr", "Adverb", None),
    ("más", "mehr", "Adverb", None),
    ("menos", "weniger", "Adverb", None),
    ("bien", "gut", "Adverb", None),
    ("mal", "schlecht", "Adverb", None),
    ("aquí", "hier", "Adverb", None),
    ("allí", "dort", "Adverb", None),
    ("ahí", "da", "Adverb", None),
    ("ahora", "jetzt", "Adverb", None),
    ("hoy", "heute", "Adverb", None),
    ("ayer", "gestern", "Adverb", None),
    ("mañana", "morgen", "Adverb", None),
    ("siempre", "immer", "Adverb", None),
    ("nunca", "nie", "Adverb", None),
    ("todavía", "noch, immer noch", "Adverb", None),
    ("ya", "schon, bereits", "Adverb", None),
    ("luego", "danach, gleich", "Adverb", None),
    ("después", "danach, später", "Adverb", None),
    ("antes", "vorher, davor", "Adverb", None),
    ("pronto", "bald", "Adverb", None),
    ("tarde", "spät", "Adverb", None),
    ("temprano", "früh", "Adverb", None),
    ("despacio", "langsam", "Adverb", None),
    ("rápido", "schnell", "Adverb", None),
    ("casi", "fast", "Adverb", None),
    ("solo", "nur, allein", "Adverb", None),
    ("incluso", "sogar", "Adverb", None),
    ("quizás", "vielleicht", "Adverb", None),
    ("tal vez", "vielleicht", "Adverb", None),
    ("realmente", "wirklich", "Adverb", None),
    ("especialmente", "besonders", "Adverb", None),
    ("generalmente", "im Allgemeinen", "Adverb", None),
    ("normalmente", "normalerweise", "Adverb", None),
    ("probablemente", "wahrscheinlich", "Adverb", None),
    ("verdaderamente", "wirklich, wahrhaftig", "Adverb", None),
    ("así", "so", "Adverb", None),
    ("bastante", "ziemlich, genug", "Adverb", None),
    ("demasiado", "zu viel, zu sehr", "Adverb", None),
    ("apenas", "kaum", "Adverb", None),
    ("arriba", "oben", "Adverb", None),
    ("abajo", "unten", "Adverb", None),
    ("adelante", "vorwärts", "Adverb", None),
    ("atrás", "zurück, hinten", "Adverb", None),

    # ---------------------------------------------------------------- Adjektiv (72)
    ("bueno / buena", "gut", "Adjektiv", None),
    ("malo / mala", "schlecht", "Adjektiv", None),
    ("grande", "groß", "Adjektiv", None),
    ("pequeño / pequeña", "klein", "Adjektiv", None),
    ("nuevo / nueva", "neu", "Adjektiv", None),
    ("viejo / vieja", "alt", "Adjektiv", None),
    ("joven", "jung", "Adjektiv", None),
    ("mayor", "älter, größer", "Adjektiv", None),
    ("menor", "jünger, kleiner", "Adjektiv", None),
    ("mejor", "besser", "Adjektiv", None),
    ("peor", "schlechter", "Adjektiv", None),
    ("bonito / bonita", "hübsch, schön", "Adjektiv", None),
    ("feo / fea", "hässlich", "Adjektiv", None),
    ("alto / alta", "groß, hoch", "Adjektiv", None),
    ("bajo / baja", "niedrig, klein (Körpergröße)", "Adjektiv", None),
    ("largo / larga", "lang", "Adjektiv", None),
    ("corto / corta", "kurz", "Adjektiv", None),
    ("ancho / ancha", "breit", "Adjektiv", None),
    ("estrecho / estrecha", "eng, schmal", "Adjektiv", None),
    ("gordo / gorda", "dick", "Adjektiv", None),
    ("delgado / delgada", "schlank", "Adjektiv", None),
    ("fuerte", "stark", "Adjektiv", None),
    ("débil", "schwach", "Adjektiv", None),
    ("rápido / rápida", "schnell", "Adjektiv", None),
    ("lento / lenta", "langsam", "Adjektiv", None),
    ("caliente", "heiß, warm", "Adjektiv", None),
    ("frío / fría", "kalt", "Adjektiv", None),
    ("caro / cara", "teuer", "Adjektiv", None),
    ("barato / barata", "billig", "Adjektiv", None),
    ("fácil", "einfach", "Adjektiv", None),
    ("difícil", "schwierig", "Adjektiv", None),
    ("importante", "wichtig", "Adjektiv", None),
    ("interesante", "interessant", "Adjektiv", None),
    ("aburrido / aburrida", "langweilig", "Adjektiv", None),
    ("feliz", "glücklich", "Adjektiv", None),
    ("triste", "traurig", "Adjektiv", None),
    ("cansado / cansada", "müde", "Adjektiv", None),
    ("ocupado / ocupada", "beschäftigt, besetzt", "Adjektiv", None),
    ("libre", "frei", "Adjektiv", None),
    ("seguro / segura", "sicher", "Adjektiv", None),
    ("peligroso / peligrosa", "gefährlich", "Adjektiv", None),
    ("limpio / limpia", "sauber", "Adjektiv", None),
    ("sucio / sucia", "schmutzig", "Adjektiv", None),
    ("lleno / llena", "voll", "Adjektiv", None),
    ("vacío / vacía", "leer", "Adjektiv", None),
    ("abierto / abierta", "offen, geöffnet", "Adjektiv", None),
    ("cerrado / cerrada", "geschlossen", "Adjektiv", None),
    ("rico / rica", "reich, lecker", "Adjektiv", None),
    ("pobre", "arm", "Adjektiv", None),
    ("guapo / guapa", "gutaussehend, hübsch", "Adjektiv", None),
    ("simpático / simpática", "sympathisch, nett", "Adjektiv", None),
    ("amable", "freundlich", "Adjektiv", None),
    ("inteligente", "intelligent", "Adjektiv", None),
    ("tonto / tonta", "dumm", "Adjektiv", None),
    ("loco / loca", "verrückt", "Adjektiv", None),
    ("extraño / extraña", "seltsam, fremd", "Adjektiv", None),
    ("normal", "normal", "Adjektiv", None),
    ("especial", "besonders", "Adjektiv", None),
    ("diferente", "anders, unterschiedlich", "Adjektiv", None),
    ("igual", "gleich", "Adjektiv", None),
    ("posible", "möglich", "Adjektiv", None),
    ("imposible", "unmöglich", "Adjektiv", None),
    ("necesario / necesaria", "nötig", "Adjektiv", None),
    ("perfecto / perfecta", "perfekt", "Adjektiv", None),
    ("correcto / correcta", "richtig, korrekt", "Adjektiv", None),
    ("verdadero / verdadera", "wahr, echt", "Adjektiv", None),
    ("falso / falsa", "falsch, unwahr", "Adjektiv", None),
    ("listo / lista", "fertig, clever", "Adjektiv", None),
    ("claro / clara", "klar, hell", "Adjektiv", None),
    ("oscuro / oscura", "dunkel", "Adjektiv", None),
    ("dulce", "süß", "Adjektiv", None),
    ("salado / salada", "salzig", "Adjektiv", None),
    ("picante", "scharf (Geschmack)", "Adjektiv", None),

    # ---------------------------------------------------------------- Verb (96)
    ("ser", "sein (dauerhaft)", "Verb", None),
    ("estar", "sein (Zustand, Ort)", "Verb", None),
    ("tener", "haben", "Verb", None),
    ("hacer", "machen, tun", "Verb", None),
    ("poder", "können", "Verb", None),
    ("decir", "sagen", "Verb", None),
    ("ir", "gehen, fahren", "Verb", None),
    ("ver", "sehen", "Verb", None),
    ("dar", "geben", "Verb", None),
    ("saber", "wissen, können", "Verb", None),
    ("querer", "wollen, mögen, lieben", "Verb", None),
    ("llegar", "ankommen", "Verb", None),
    ("pasar", "passieren, vorbeigehen, verbringen", "Verb", None),
    ("deber", "sollen, müssen, schulden", "Verb", None),
    ("poner", "stellen, legen, setzen", "Verb", None),
    ("parecer", "scheinen, aussehen wie", "Verb", None),
    ("quedar", "bleiben, sich verabreden", "Verb", None),
    ("creer", "glauben", "Verb", None),
    ("hablar", "sprechen, reden", "Verb", None),
    ("llevar", "tragen, bringen, mitnehmen", "Verb", None),
    ("dejar", "lassen, verlassen", "Verb", None),
    ("seguir", "folgen, weitermachen", "Verb", None),
    ("encontrar", "finden", "Verb", None),
    ("llamar", "rufen, anrufen, nennen", "Verb", None),
    ("venir", "kommen", "Verb", None),
    ("pensar", "denken", "Verb", None),
    ("salir", "hinausgehen, ausgehen, abfahren", "Verb", None),
    ("volver", "zurückkommen, wiederkehren", "Verb", None),
    ("tomar", "nehmen, trinken", "Verb", None),
    ("conocer", "kennen, kennenlernen", "Verb", None),
    ("vivir", "leben, wohnen", "Verb", None),
    ("sentir", "fühlen, spüren, bedauern", "Verb", None),
    ("tratar", "behandeln, versuchen", "Verb", None),
    ("mirar", "schauen, ansehen", "Verb", None),
    ("contar", "erzählen, zählen", "Verb", None),
    ("empezar", "anfangen", "Verb", None),
    ("esperar", "warten, hoffen", "Verb", None),
    ("buscar", "suchen", "Verb", None),
    ("entrar", "eintreten, hineingehen", "Verb", None),
    ("trabajar", "arbeiten", "Verb", None),
    ("escribir", "schreiben", "Verb", None),
    ("perder", "verlieren, verpassen", "Verb", None),
    ("entender", "verstehen", "Verb", None),
    ("pedir", "bitten, bestellen", "Verb", None),
    ("recibir", "empfangen, bekommen", "Verb", None),
    ("recordar", "sich erinnern", "Verb", None),
    ("terminar", "beenden, fertig sein", "Verb", None),
    ("permitir", "erlauben", "Verb", None),
    ("conseguir", "erreichen, bekommen", "Verb", None),
    ("comenzar", "beginnen", "Verb", None),
    ("servir", "dienen, servieren", "Verb", None),
    ("sacar", "herausnehmen, herausholen", "Verb", None),
    ("necesitar", "brauchen", "Verb", None),
    ("leer", "lesen", "Verb", None),
    ("caer", "fallen", "Verb", None),
    ("cambiar", "ändern, wechseln", "Verb", None),
    ("crear", "erschaffen", "Verb", None),
    ("abrir", "öffnen", "Verb", None),
    ("cerrar", "schließen", "Verb", None),
    ("considerar", "betrachten, überlegen", "Verb", None),
    ("oír", "hören", "Verb", None),
    ("escuchar", "zuhören", "Verb", None),
    ("acabar", "beenden, fertig werden", "Verb", None),
    ("ganar", "gewinnen, verdienen", "Verb", None),
    ("traer", "bringen, mitbringen", "Verb", None),
    ("morir", "sterben", "Verb", None),
    ("aceptar", "akzeptieren", "Verb", None),
    ("explicar", "erklären", "Verb", None),
    ("preguntar", "fragen", "Verb", None),
    ("tocar", "berühren, anfassen, spielen (Instrument)", "Verb", None),
    ("estudiar", "studieren, lernen", "Verb", None),
    ("nacer", "geboren werden", "Verb", None),
    ("correr", "laufen, rennen", "Verb", None),
    ("usar", "benutzen", "Verb", None),
    ("pagar", "bezahlen", "Verb", None),
    ("ayudar", "helfen", "Verb", None),
    ("gustar", "gefallen, mögen", "Verb", None),
    ("jugar", "spielen", "Verb", None),
    ("comer", "essen", "Verb", None),
    ("beber", "trinken", "Verb", None),
    ("dormir", "schlafen", "Verb", None),
    ("comprar", "kaufen", "Verb", None),
    ("vender", "verkaufen", "Verb", None),
    ("viajar", "reisen", "Verb", None),
    ("caminar", "gehen, laufen", "Verb", None),
    ("conducir", "fahren, lenken", "Verb", None),
    ("cocinar", "kochen", "Verb", None),
    ("limpiar", "putzen, reinigen", "Verb", None),
    ("lavar", "waschen", "Verb", None),
    ("ducharse", "duschen", "Verb", None),
    ("levantarse", "aufstehen", "Verb", None),
    ("acostarse", "sich hinlegen, schlafen gehen", "Verb", None),
    ("vestirse", "sich anziehen", "Verb", None),
    ("reír", "lachen", "Verb", None),
    ("llorar", "weinen", "Verb", None),
    ("bailar", "tanzen", "Verb", None),
    ("cantar", "singen", "Verb", None),
    ("enviar", "senden, schicken", "Verb", None),
    ("mandar", "schicken, befehlen", "Verb", None),

    # ---------------------------------------------------------------- Nomen (155)
    ("tiempo", "Zeit, Wetter", "Nomen", "m"),
    ("año", "Jahr", "Nomen", "m"),
    ("día", "Tag", "Nomen", "m"),
    ("vez", "Mal (z.B. 'eine Mal')", "Nomen", "f"),
    ("hombre", "Mann, Mensch", "Nomen", "m"),
    ("mujer", "Frau", "Nomen", "f"),
    ("mundo", "Welt", "Nomen", "m"),
    ("vida", "Leben", "Nomen", "f"),
    ("mano", "Hand", "Nomen", "f"),
    ("parte", "Teil", "Nomen", "f"),
    ("niño / niña", "Kind, Junge/Mädchen", "Nomen", "m"),
    ("ojo", "Auge", "Nomen", "m"),
    ("casa", "Haus", "Nomen", "f"),
    ("agua", "Wasser", "Nomen", "f"),
    ("trabajo", "Arbeit", "Nomen", "m"),
    ("país", "Land (Staat)", "Nomen", "m"),
    ("ciudad", "Stadt", "Nomen", "f"),
    ("problema", "Problem", "Nomen", "m"),
    ("punto", "Punkt", "Nomen", "m"),
    ("momento", "Moment", "Nomen", "m"),
    ("gobierno", "Regierung", "Nomen", "m"),
    ("palabra", "Wort", "Nomen", "f"),
    ("noche", "Nacht", "Nomen", "f"),
    ("tema", "Thema", "Nomen", "m"),
    ("madre", "Mutter", "Nomen", "f"),
    ("padre", "Vater", "Nomen", "m"),
    ("padres", "Eltern", "Nomen", "m"),
    ("historia", "Geschichte", "Nomen", "f"),
    ("lugar", "Ort", "Nomen", "m"),
    ("ejemplo", "Beispiel", "Nomen", "m"),
    ("dinero", "Geld", "Nomen", "m"),
    ("semana", "Woche", "Nomen", "f"),
    ("mes", "Monat", "Nomen", "m"),
    ("mesa", "Tisch", "Nomen", "f"),
    ("silla", "Stuhl", "Nomen", "f"),
    ("puerta", "Tür", "Nomen", "f"),
    ("ventana", "Fenster", "Nomen", "f"),
    ("coche", "Auto", "Nomen", "m"),
    ("calle", "Straße", "Nomen", "f"),
    ("escuela", "Schule", "Nomen", "f"),
    ("universidad", "Universität", "Nomen", "f"),
    ("libro", "Buch", "Nomen", "m"),
    ("papel", "Papier, Rolle", "Nomen", "m"),
    ("teléfono", "Telefon", "Nomen", "m"),
    ("cosa", "Sache, Ding", "Nomen", "f"),
    ("gente", "Leute", "Nomen", "f"),
    ("familia", "Familie", "Nomen", "f"),
    ("amigo / amiga", "Freund, Freundin", "Nomen", "m"),
    ("hijo / hija", "Sohn, Tochter", "Nomen", "m"),
    ("hermano / hermana", "Bruder, Schwester", "Nomen", "m"),
    ("nombre", "Name", "Nomen", "m"),
    ("número", "Nummer, Zahl", "Nomen", "m"),
    ("precio", "Preis", "Nomen", "m"),
    ("comida", "Essen", "Nomen", "f"),
    ("plato", "Teller, Gericht", "Nomen", "m"),
    ("restaurante", "Restaurant", "Nomen", "m"),
    ("hotel", "Hotel", "Nomen", "m"),
    ("habitación", "Zimmer", "Nomen", "f"),
    ("cama", "Bett", "Nomen", "f"),
    ("baño", "Bad, Toilette", "Nomen", "m"),
    ("cocina", "Küche", "Nomen", "f"),
    ("tienda", "Geschäft, Laden", "Nomen", "f"),
    ("mercado", "Markt", "Nomen", "m"),
    ("ropa", "Kleidung", "Nomen", "f"),
    ("zapato", "Schuh", "Nomen", "m"),
    ("tarjeta", "Karte", "Nomen", "f"),
    ("cuenta", "Rechnung, Konto", "Nomen", "f"),
    ("billete", "Fahrschein, Geldschein", "Nomen", "m"),
    ("pasaporte", "Reisepass", "Nomen", "m"),
    ("avión", "Flugzeug", "Nomen", "m"),
    ("tren", "Zug", "Nomen", "m"),
    ("autobús", "Bus", "Nomen", "m"),
    ("taxi", "Taxi", "Nomen", "m"),
    ("metro", "U-Bahn", "Nomen", "m"),
    ("aeropuerto", "Flughafen", "Nomen", "m"),
    ("estación", "Bahnhof, Station", "Nomen", "f"),
    ("playa", "Strand", "Nomen", "f"),
    ("montaña", "Berg", "Nomen", "f"),
    ("río", "Fluss", "Nomen", "m"),
    ("mar", "Meer", "Nomen", "m"),
    ("sol", "Sonne", "Nomen", "m"),
    ("luna", "Mond", "Nomen", "f"),
    ("estrella", "Stern", "Nomen", "f"),
    ("cielo", "Himmel", "Nomen", "m"),
    ("lluvia", "Regen", "Nomen", "f"),
    ("viento", "Wind", "Nomen", "m"),
    ("nieve", "Schnee", "Nomen", "f"),
    ("pueblo", "Dorf, Volk", "Nomen", "m"),
    ("barrio", "Stadtviertel", "Nomen", "m"),
    ("plaza", "Platz (Ort)", "Nomen", "f"),
    ("parque", "Park", "Nomen", "m"),
    ("iglesia", "Kirche", "Nomen", "f"),
    ("museo", "Museum", "Nomen", "m"),
    ("música", "Musik", "Nomen", "f"),
    ("canción", "Lied", "Nomen", "f"),
    ("fiesta", "Party, Fest", "Nomen", "f"),
    ("cumpleaños", "Geburtstag", "Nomen", "m"),
    ("regalo", "Geschenk", "Nomen", "m"),
    ("foto", "Foto", "Nomen", "f"),
    ("teléfono móvil", "Handy", "Nomen", "m"),
    ("internet", "Internet", "Nomen", "m"),
    ("correo", "Post, E-Mail", "Nomen", "m"),
    ("mensaje", "Nachricht", "Nomen", "m"),
    ("oficina", "Büro", "Nomen", "f"),
    ("jefe / jefa", "Chef, Chefin", "Nomen", "m"),
    ("empleado / empleada", "Angestellter, Angestellte", "Nomen", "m"),
    ("sueldo", "Lohn", "Nomen", "m"),
    ("reunión", "Treffen, Sitzung", "Nomen", "f"),
    ("cita", "Termin, Verabredung", "Nomen", "f"),
    ("hora", "Stunde, Uhrzeit", "Nomen", "f"),
    ("minuto", "Minute", "Nomen", "m"),
    ("segundo", "Sekunde", "Nomen", "m"),
    ("corazón", "Herz", "Nomen", "m"),
    ("cabeza", "Kopf", "Nomen", "f"),
    ("cara", "Gesicht", "Nomen", "f"),
    ("boca", "Mund", "Nomen", "f"),
    ("pelo", "Haar", "Nomen", "m"),
    ("brazo", "Arm", "Nomen", "m"),
    ("pierna", "Bein", "Nomen", "f"),
    ("pie", "Fuß", "Nomen", "m"),
    ("dedo", "Finger", "Nomen", "m"),
    ("cuerpo", "Körper", "Nomen", "m"),
    ("salud", "Gesundheit", "Nomen", "f"),
    ("enfermedad", "Krankheit", "Nomen", "f"),
    ("médico / médica", "Arzt, Ärztin", "Nomen", "m"),
    ("hospital", "Krankenhaus", "Nomen", "m"),
    ("dolor", "Schmerz", "Nomen", "m"),
    ("sueño", "Traum, Schläfrigkeit", "Nomen", "m"),
    ("hambre", "Hunger", "Nomen", "f"),
    ("sed", "Durst", "Nomen", "f"),
    ("amor", "Liebe", "Nomen", "m"),
    ("miedo", "Angst", "Nomen", "m"),
    ("alegría", "Freude", "Nomen", "f"),
    ("suerte", "Glück (Zufall)", "Nomen", "f"),
    ("verdad", "Wahrheit", "Nomen", "f"),
    ("idea", "Idee", "Nomen", "f"),
    ("opinión", "Meinung", "Nomen", "f"),
    ("pregunta", "Frage", "Nomen", "f"),
    ("respuesta", "Antwort", "Nomen", "f"),
    ("razón", "Grund, Vernunft", "Nomen", "f"),
    ("error", "Fehler", "Nomen", "m"),
    ("futuro", "Zukunft", "Nomen", "m"),
    ("final", "Ende", "Nomen", "m"),
    ("cambio", "Wechsel, Kleingeld", "Nomen", "m"),
    ("diferencia", "Unterschied", "Nomen", "f"),
    ("tipo", "Typ, Art", "Nomen", "m"),
    ("grupo", "Gruppe", "Nomen", "m"),
    ("equipo", "Team, Ausrüstung", "Nomen", "m"),
    ("estado", "Zustand, Staat", "Nomen", "m"),
    ("aire", "Luft", "Nomen", "m"),
    ("fin", "Ende, Zweck", "Nomen", "m"),
]

# Ergaenzt am Ende, damit die vorhergehende Liste unangetastet bleibt -
# 500 minus len(WOERTER) oben, siehe Skript-Ausgabe von pruefe().
