# -*- coding: utf-8 -*-
"""Club + Nightlife auf Schwedisch: die uebertragbaren Saetze.

109 der 131 chinesischen Saetze lassen sich uebernehmen - die Situation gibt
es in Schweden genauso, nur die Sprache aendert sich. Die uebrigen 22 bleiben
draussen, weil es kein Gegenstueck gibt:

  Trinkritual      干杯 / 随意 - kein europaeisches Gegenstueck
  Lob annehmen     哪里哪里 - in Schweden sagt man "tack"
  Komplimente      schlank, gross, helle Haut, Klasse (气质) werden anders
                   gehoert oder haben kein Wort
  Infrastruktur    WeChat, KTV-Zimmer, Pass am Clubeingang, Gaesteregeln
  Sprachlich       漂亮 (Frauen) gegen 帅 (Maenner) - Schwedisch hat dafuer
                   nicht zwei Woerter, die Ansprache-Varianten fielen
                   zusammen

**Nicht von Muttersprachlern geprueft.** Nach bestem Wissen korrekt und
umgangssprachlich gehalten, aber vor der Vertonung gehoert ein Spot-Check
darueber - besonders bei den Abweis-Saetzen, wo der Ton entscheidet.

`verb_cluster` bleibt vorerst leer. Die schwedischen Cluster (sv_*) decken
die 189 alten Saetze ab; welche davon hier passen, ist ein eigener
Arbeitsschritt - genauso wie damals beim Uebertragen des Phrasebooks.
"""

SAETZE = [
# ---------------------------------------------------------------- Trinkkultur
 dict(sz='club_trinkkultur', de='Ich trinke langsam.', sv='Jag dricker långsamt.',
      lookup=False, ansprache=None,
      konzepte=[('langsam', ['långsamt', 'sakta']), ('trinken', ['dricker', 'dricka'])]),
 dict(sz='club_trinkkultur', de='Ich kann nicht mehr trinken.', sv='Jag kan inte dricka mer.',
      lookup=False, ansprache=None,
      konzepte=[('nicht_koennen', ['kan inte']), ('trinken', ['dricka', 'dricker'])]),
 dict(sz='club_trinkkultur', de='Ich muss morgen arbeiten.', sv='Jag måste jobba imorgon.',
      lookup=False, ansprache=None,
      konzepte=[('morgen', ['imorgon', 'i morgon']), ('arbeit', ['jobba', 'arbeta'])]),
 dict(sz='club_trinkkultur', de='Ich trinke nur ein bisschen.', sv='Jag dricker bara lite.',
      lookup=False, ansprache=None,
      konzepte=[('trinken', ['dricker', 'dricka']), ('ein_bisschen', ['lite', 'bara lite'])]),
 dict(sz='club_trinkkultur', de='Was trinkst du?', sv='Vad dricker du?',
      lookup=False, ansprache=None,
      konzepte=[('trinken', ['dricker', 'dricka']), ('was', ['vad'])]),
 dict(sz='club_trinkkultur', de='Ich möchte noch ein Bier.', sv='Jag vill ha en öl till.',
      lookup=False, ansprache=None,
      konzepte=[('noch', ['till', 'en till']), ('bier', ['öl'])]),
 dict(sz='club_trinkkultur', de='Trinken wir zusammen!', sv='Vi dricker tillsammans!',
      lookup=False, ansprache=None,
      konzepte=[('zusammen', ['tillsammans']), ('trinken', ['dricker', 'dricka'])]),
 dict(sz='club_trinkkultur', de='Ich trinke keinen Alkohol.', sv='Jag dricker inte alkohol.',
      lookup=False, ansprache=None,
      konzepte=[('nicht', ['inte']), ('alkohol', ['alkohol', 'sprit'])]),
 dict(sz='club_trinkkultur', de='Was kostet das?', sv='Vad kostar det?',
      lookup=False, ansprache=None,
      konzepte=[('kosten', ['kostar']), ('was', ['vad'])]),

# ---------------------------------------------------------------- Ansprechen
 dict(sz='club_ansprechen', de='Wie heißt du?', sv='Vad heter du?',
      lookup=False, ansprache=None,
      konzepte=[('heissen', ['heter'])]),
 dict(sz='club_ansprechen', de='Gefällt es dir hier auch?', sv='Gillar du det här också?',
      lookup=False, ansprache=None,
      konzepte=[('auch', ['också']), ('moegen', ['gillar', 'gilla'])]),
 dict(sz='club_ansprechen', de='Ich sehe dir gern beim Tanzen zu.', sv='Jag gillar att se dig dansa.',
      lookup=False, ansprache=None,
      konzepte=[('moegen', ['gillar']), ('tanzen', ['dansa', 'dansar'])]),
 dict(sz='club_ansprechen', de='Bist du Single?', sv='Är du singel?',
      lookup=False, ansprache=None,
      konzepte=[('single', ['singel'])]),
 dict(sz='club_ansprechen', de='Ist dein Freund auch hier?', sv='Är din pojkvän också här?',
      lookup=False, ansprache='frauen',
      konzepte=[('fester_freund', ['pojkvän'])]),
 dict(sz='club_ansprechen', de='Ist deine Freundin auch hier?', sv='Är din flickvän också här?',
      lookup=False, ansprache='maenner',
      konzepte=[('feste_freundin', ['flickvän'])]),
 dict(sz='club_ansprechen', de='Wollen wir zusammen tanzen?', sv='Ska vi dansa tillsammans?',
      lookup=False, ansprache=None,
      konzepte=[('zusammen', ['tillsammans']), ('tanzen', ['dansa'])]),
 dict(sz='club_ansprechen', de='Hier ist es zu laut. Gehen wir nach draußen?',
      sv='Det är för högt här. Ska vi gå ut?',
      lookup=False, ansprache=None,
      konzepte=[('laut', ['högt', 'högljutt']), ('rausgehen', ['gå ut', 'ut'])]),
 dict(sz='club_ansprechen', de='Mein Schwedisch ist nicht so gut.', sv='Min svenska är inte så bra.',
      lookup=False, ansprache=None,
      konzepte=[('sprache', ['svenska']), ('nicht_gut', ['inte så bra', 'inte bra'])]),

# ---------------------------------------------------------------- Sicherheit
 dict(sz='club_sicherheit', de='Ich gehe jetzt.', sv='Jag går nu.',
      lookup=False, ansprache=None,
      konzepte=[('gehen', ['går', 'gå'])]),
 dict(sz='club_sicherheit', de='Mir geht es nicht gut.', sv='Jag mår inte bra.',
      lookup=False, ansprache=None,
      konzepte=[('nicht', ['inte']), ('wohl', ['mår', 'mår bra'])]),
 dict(sz='club_sicherheit', de='Ich möchte nach Hause.', sv='Jag vill åka hem.',
      lookup=False, ansprache=None,
      konzepte=[('moechten', ['vill']), ('nach_hause', ['hem', 'åka hem'])]),
 dict(sz='club_sicherheit', de='Kannst du mir helfen?', sv='Kan du hjälpa mig?',
      lookup=False, ansprache=None,
      konzepte=[('koennen', ['kan']), ('helfen', ['hjälpa', 'hjälp'])]),
 dict(sz='club_sicherheit', de='Mein Freund wartet draußen auf mich.',
      sv='Min pojkvän väntar på mig utanför.',
      lookup=False, ansprache='frauen',
      konzepte=[('fester_freund', ['pojkvän']), ('warten', ['väntar', 'vänta'])]),
 dict(sz='club_sicherheit', de='Meine Freundin wartet draußen auf mich.',
      sv='Min flickvän väntar på mig utanför.',
      lookup=False, ansprache='maenner',
      konzepte=[('feste_freundin', ['flickvän']), ('warten', ['väntar', 'vänta'])]),
 dict(sz='club_sicherheit', de='Lass mich in Ruhe.', sv='Lämna mig ifred.',
      lookup=True, ansprache=None,
      konzepte=[('in_ruhe', ['ifred', 'lämna mig ifred'])]),
 dict(sz='club_sicherheit', de='Ich habe kein Interesse. Geh bitte weg.',
      sv='Jag är inte intresserad. Gå härifrån.',
      lookup=True, ansprache=None,
      konzepte=[('kein_interesse', ['inte intresserad']), ('weggehen', ['gå härifrån', 'försvinn'])]),
 dict(sz='club_sicherheit', de='Die Person dort lässt mich nicht in Ruhe.',
      sv='Den där personen lämnar mig inte ifred.',
      lookup=True, ansprache=None,
      konzepte=[('person', ['personen', 'person']), ('in_ruhe', ['ifred'])]),
 dict(sz='club_sicherheit', de='Bitte tu so, als würden wir uns kennen.',
      sv='Kan du låtsas att vi känner varandra?',
      lookup=True, ansprache=None,
      konzepte=[('so_tun', ['låtsas']), ('kennen', ['känner', 'känna'])]),
 dict(sz='club_sicherheit', de='Bitte pass kurz auf mein Glas auf.',
      sv='Kan du hålla ett öga på mitt glas?',
      lookup=True, ansprache=None,
      konzepte=[('aufpassen', ['hålla ett öga', 'kolla']), ('glas', ['glas', 'glaset'])]),
 dict(sz='club_sicherheit', de='Bitte rufen Sie die Polizei.', sv='Ring polisen, tack.',
      lookup=True, ansprache=None,
      konzepte=[('rufen', ['ring', 'ringa']), ('polizei', ['polisen', 'polis'])]),
 dict(sz='club_sicherheit', de='Entschuldigung, ich wusste nicht, dass ihr zusammen seid.',
      sv='Förlåt, jag visste inte att ni är tillsammans.',
      lookup=True, ansprache=None,
      konzepte=[('entschuldigung', ['förlåt', 'ursäkta']), ('wissen', ['visste', 'veta'])]),

# ---------------------------------------------------------------- Reinkommen
 dict(sz='club_einlass', de='Was kostet der Eintritt?', sv='Vad kostar inträdet?',
      lookup=False, ansprache=None,
      konzepte=[('eintritt', ['inträdet', 'inträde']), ('kosten', ['kostar'])]),
 dict(sz='club_einlass', de='Ich möchte ein Ticket kaufen.', sv='Jag vill köpa en biljett.',
      lookup=False, ansprache=None,
      konzepte=[('moechten', ['vill']), ('kaufen', ['köpa']), ('ticket', ['biljett'])]),
 dict(sz='club_einlass', de='Wir sind zu zweit.', sv='Vi är två.',
      lookup=False, ansprache=None,
      konzepte=[('wir', ['vi']), ('zwei', ['två'])]),
 dict(sz='club_einlass', de='Habt ihr heute offen?', sv='Har ni öppet idag?',
      lookup=False, ansprache=None,
      konzepte=[('heute', ['idag', 'i dag']), ('offen', ['öppet', 'öppna'])]),
 dict(sz='club_einlass', de='Bis wann habt ihr heute offen?', sv='Hur länge har ni öppet idag?',
      lookup=False, ansprache=None,
      konzepte=[('bis_wann', ['hur länge', 'till när']), ('offen', ['öppet'])]),
 dict(sz='club_einlass', de='Ich bin mit Freunden hier.', sv='Jag är här med vänner.',
      lookup=False, ansprache=None,
      konzepte=[('freund', ['vänner', 'kompisar']), ('hier', ['här'])]),
 dict(sz='club_einlass', de='Kann ich hier bezahlen?', sv='Kan jag betala här?',
      lookup=False, ansprache=None,
      konzepte=[('koennen', ['kan']), ('bezahlen', ['betala'])]),
 dict(sz='club_einlass', de='Wo ist die Toilette?', sv='Var är toaletten?',
      lookup=False, ansprache=None,
      konzepte=[('toilette', ['toaletten', 'toalett']), ('wo', ['var'])]),
 dict(sz='club_einlass', de='Meine Freunde kommen später.', sv='Mina vänner kommer senare.',
      lookup=False, ansprache=None,
      konzepte=[('freund', ['vänner', 'kompisar']), ('spaeter', ['senare'])]),
 dict(sz='club_einlass', de='Ich bin nicht von hier.', sv='Jag är inte härifrån.',
      lookup=False, ansprache=None,
      konzepte=[('nicht', ['inte']), ('von_hier', ['härifrån'])]),

# ---------------------------------------------------------------- An der Bar
 dict(sz='club_bar', de='Zwei Bier, bitte.', sv='Två öl, tack.',
      lookup=False, ansprache=None,
      konzepte=[('zwei', ['två']), ('bier', ['öl'])]),
 dict(sz='club_bar', de='Hier ist es zu laut.', sv='Det är för högt här.',
      lookup=False, ansprache=None,
      konzepte=[('hier', ['här']), ('laut', ['högt', 'högljutt'])]),
 dict(sz='club_bar', de='Es ist laut, sag es bitte nochmal.', sv='Det är högt, kan du säga det igen?',
      lookup=False, ansprache=None,
      konzepte=[('laut', ['högt']), ('nochmal', ['igen']), ('sagen', ['säga', 'säg'])]),
 dict(sz='club_bar', de='Was möchtest du trinken?', sv='Vad vill du dricka?',
      lookup=False, ansprache=None,
      konzepte=[('moechten', ['vill']), ('trinken', ['dricka'])]),
 dict(sz='club_bar', de='Haben Sie Wasser?', sv='Har ni vatten?',
      lookup=False, ansprache=None,
      konzepte=[('haben', ['har']), ('wasser', ['vatten'])]),
 dict(sz='club_bar', de='Das ist zu teuer.', sv='Det är för dyrt.',
      lookup=False, ansprache=None,
      konzepte=[('teuer', ['dyrt', 'dyr'])]),
 dict(sz='club_bar', de='Noch eins, bitte.', sv='En till, tack.',
      lookup=False, ansprache=None,
      konzepte=[('noch', ['till', 'en till'])]),
 dict(sz='club_bar', de='Das bezahle ich.', sv='Jag betalar.',
      lookup=False, ansprache=None,
      konzepte=[('bezahlen', ['betalar', 'betala'])]),
 dict(sz='club_bar', de='Wo kann ich bezahlen?', sv='Var kan jag betala?',
      lookup=False, ansprache=None,
      konzepte=[('wo', ['var']), ('bezahlen', ['betala'])]),
 dict(sz='club_bar', de='Ich nehme das Gleiche.', sv='Jag tar samma.',
      lookup=False, ansprache=None,
      konzepte=[('nehmen', ['tar', 'ta']), ('gleiche', ['samma', 'samma sak'])]),
 dict(sz='club_bar', de='Was möchten Sie?', sv='Vad vill du ha?',
      lookup=False, ansprache=None,
      konzepte=[('moechten', ['vill ha', 'vill']), ('was', ['vad'])]),

# ---------------------------------------------------------------- Karaoke
 dict(sz='club_ktv', de='Ich kann nicht singen.', sv='Jag kan inte sjunga.',
      lookup=False, ansprache=None,
      konzepte=[('nicht_koennen', ['kan inte']), ('singen', ['sjunga'])]),
 dict(sz='club_ktv', de='Sing du zuerst.', sv='Du sjunger först.',
      lookup=False, ansprache=None,
      konzepte=[('zuerst', ['först']), ('singen', ['sjunger', 'sjung'])]),
 dict(sz='club_ktv', de='Welches Lied singst du?', sv='Vilken låt sjunger du?',
      lookup=False, ansprache=None,
      konzepte=[('singen', ['sjunger']), ('lied', ['låt', 'sång'])]),
 dict(sz='club_ktv', de='Dieses Lied kenne ich!', sv='Den låten kan jag!',
      lookup=False, ansprache=None,
      konzepte=[('lied', ['låt', 'låten']), ('kennen', ['kan', 'känner till'])]),
 dict(sz='club_ktv', de='Wie viel kostet das Zimmer?', sv='Vad kostar rummet?',
      lookup=False, ansprache=None,
      konzepte=[('zimmer', ['rummet', 'rum']), ('kosten', ['kostar'])]),
 dict(sz='club_ktv', de='Wir bleiben zwei Stunden.', sv='Vi stannar två timmar.',
      lookup=False, ansprache=None,
      konzepte=[('zwei', ['två']), ('stunde', ['timmar', 'timme'])]),
 dict(sz='club_ktv', de='Du singst sehr gut!', sv='Du sjunger jättebra!',
      lookup=False, ansprache=None,
      konzepte=[('singen', ['sjunger']), ('gut', ['jättebra', 'bra'])]),
 dict(sz='club_ktv', de='Wir singen zusammen.', sv='Vi sjunger tillsammans.',
      lookup=False, ansprache=None,
      konzepte=[('zusammen', ['tillsammans']), ('singen', ['sjunger'])]),
 dict(sz='club_ktv', de='Sing noch eins!', sv='Sjung en till!',
      lookup=False, ansprache=None,
      konzepte=[('noch', ['till', 'en till']), ('singen', ['sjung', 'sjunga'])]),

# ---------------------------------------------------------------- Näher kommen
 dict(sz='club_naeherkommen', de='Ich finde dich sehr nett.', sv='Jag tycker att du är jättetrevlig.',
      lookup=False, ansprache=None,
      konzepte=[('finden', ['tycker']), ('nett', ['trevlig', 'jättetrevlig'])]),
 dict(sz='club_naeherkommen', de='Ich mag dich.', sv='Jag gillar dig.',
      lookup=False, ansprache=None,
      konzepte=[('moegen', ['gillar', 'gilla'])]),
 dict(sz='club_naeherkommen', de='Ist das okay für dich?', sv='Är det okej för dig?',
      lookup=False, ansprache=None,
      konzepte=[('okay', ['okej', 'ok'])]),
 dict(sz='club_naeherkommen', de='Gehen wir woanders hin?', sv='Ska vi gå någon annanstans?',
      lookup=False, ansprache=None,
      konzepte=[('gehen', ['gå']), ('woanders', ['någon annanstans', 'annanstans'])]),
 dict(sz='club_naeherkommen', de='Ich kenne einen guten Ort.', sv='Jag vet ett bra ställe.',
      lookup=False, ansprache=None,
      konzepte=[('wissen', ['vet']), ('ort', ['ställe', 'plats'])]),
 dict(sz='club_naeherkommen', de='Zu dir oder zu mir?', sv='Till dig eller till mig?',
      lookup=False, ansprache=None,
      konzepte=[('oder', ['eller'])]),
 dict(sz='club_naeherkommen', de='Bier oder Wasser?', sv='Öl eller vatten?',
      lookup=False, ansprache=None,
      konzepte=[('bier', ['öl']), ('oder', ['eller'])]),
 dict(sz='club_naeherkommen', de='Ich reise morgen weiter.', sv='Jag reser vidare imorgon.',
      lookup=False, ansprache=None,
      konzepte=[('morgen', ['imorgon', 'i morgon']), ('reisen', ['reser', 'åker'])]),
 dict(sz='club_naeherkommen', de='Gehen wir kurz nach draußen.', sv='Vi går ut en stund.',
      lookup=False, ansprache=None,
      konzepte=[('gehen', ['går', 'gå']), ('draussen', ['ut', 'utanför'])]),
 dict(sz='club_naeherkommen', de='Du gefällst mir sehr.', sv='Jag gillar dig verkligen.',
      lookup=False, ansprache='frauen',
      konzepte=[('sehr', ['verkligen', 'jätte']), ('moegen', ['gillar'])]),
 dict(sz='club_naeherkommen', de='Ich suche gerade nichts Festes — ich reise bald weiter.',
      sv='Jag söker inget seriöst just nu, jag reser vidare snart.',
      lookup=True, ansprache=None,
      konzepte=[('nichts_ernstes', ['inget seriöst']), ('reisen', ['reser'])]),
 dict(sz='club_naeherkommen', de='Darf ich mich hierhin setzen?', sv='Får jag sätta mig här?',
      lookup=False, ansprache=None,
      konzepte=[('duerfen', ['får']), ('sitzen', ['sätta mig', 'sitta'])]),
 dict(sz='club_naeherkommen', de='Deine Hände sind ganz kalt.', sv='Dina händer är iskalla.',
      lookup=False, ansprache=None,
      konzepte=[('hand', ['händer', 'hand']), ('kalt', ['iskalla', 'kalla'])]),
 dict(sz='club_naeherkommen', de='Ich bringe dich nach Hause.', sv='Jag följer dig hem.',
      lookup=False, ansprache=None,
      konzepte=[('bringen', ['följer', 'följa']), ('nach_hause', ['hem'])]),
 dict(sz='club_naeherkommen', de='Soll ich dich nach Hause bringen?', sv='Ska jag följa dig hem?',
      lookup=False, ansprache=None,
      konzepte=[('bringen', ['följa', 'följer']), ('nach_hause', ['hem'])]),
 dict(sz='club_naeherkommen', de='Wir lassen es langsam angehen.', sv='Vi tar det lugnt.',
      lookup=False, ansprache=None,
      konzepte=[('langsam', ['lugnt', 'långsamt'])]),
 dict(sz='club_naeherkommen', de='Ich finde dich sehr attraktiv.', sv='Jag tycker att du är väldigt snygg.',
      lookup=False, ansprache=None,
      konzepte=[('finden', ['tycker']), ('attraktiv', ['snygg', 'attraktiv'])]),

# ---------------------------------------------------------------- Wo schlafen wir
 dict(sz='club_nachtlogistik', de='Können wir zu dir?', sv='Kan vi gå hem till dig?',
      lookup=False, ansprache=None,
      konzepte=[('koennen', ['kan']), ('zu_dir', ['hem till dig', 'till dig'])]),
 dict(sz='club_nachtlogistik', de='Nehmen wir ein Zimmer.', sv='Vi tar ett rum.',
      lookup=False, ansprache=None,
      konzepte=[('zimmer', ['rum']), ('nehmen', ['tar', 'ta'])]),
 dict(sz='club_nachtlogistik', de='Das Zimmer bezahle ich.', sv='Jag betalar rummet.',
      lookup=False, ansprache=None,
      konzepte=[('zimmer', ['rummet', 'rum']), ('bezahlen', ['betalar', 'betala'])]),
 dict(sz='club_nachtlogistik', de='Ich rufe ein Taxi.', sv='Jag ringer en taxi.',
      lookup=False, ansprache=None,
      konzepte=[('rufen', ['ringer', 'ringa']), ('taxi', ['taxi'])]),
 dict(sz='club_nachtlogistik', de='Wo wohnst du?', sv='Var bor du?',
      lookup=False, ansprache=None,
      konzepte=[('wohnen', ['bor', 'bo']), ('wo', ['var'])]),
 dict(sz='club_nachtlogistik', de='Ist das weit?', sv='Är det långt?',
      lookup=False, ansprache=None,
      konzepte=[('weit', ['långt', 'långt bort'])]),
 dict(sz='club_nachtlogistik', de='Mein Hotel ist nicht weit.', sv='Mitt hotell är inte långt bort.',
      lookup=False, ansprache=None,
      konzepte=[('hotel', ['hotell', 'hotellet']), ('weit', ['långt', 'långt bort'])]),
 dict(sz='club_nachtlogistik', de='Ich fahre nach Hause.', sv='Jag åker hem.',
      lookup=False, ansprache=None,
      konzepte=[('nach_hause', ['hem', 'åker hem'])]),

# ---------------------------------------------------------------- Freunde verloren
 dict(sz='club_verloren', de='Ich finde meine Freunde nicht.', sv='Jag hittar inte mina vänner.',
      lookup=False, ansprache=None,
      konzepte=[('finden', ['hittar', 'hitta']), ('freund', ['vänner', 'kompisar'])]),
 dict(sz='club_verloren', de='Hast du meinen Freund gesehen?', sv='Har du sett min vän?',
      lookup=False, ansprache=None,
      konzepte=[('sehen', ['sett', 'se']), ('freund', ['vän', 'kompis'])]),
 dict(sz='club_verloren', de='Wo bist du?', sv='Var är du?',
      lookup=False, ansprache=None,
      konzepte=[('wo', ['var'])]),
 dict(sz='club_verloren', de='Ich warte hier auf dich.', sv='Jag väntar på dig här.',
      lookup=False, ansprache=None,
      konzepte=[('hier', ['här']), ('warten', ['väntar', 'vänta'])]),
 dict(sz='club_verloren', de='Mein Handy hat keinen Strom mehr.', sv='Min mobil är död.',
      lookup=False, ansprache=None,
      konzepte=[('handy', ['mobil', 'mobilen', 'telefon']), ('leer', ['död', 'slut'])]),
 dict(sz='club_verloren', de='Wo kann ich mein Handy laden?', sv='Var kan jag ladda min mobil?',
      lookup=False, ansprache=None,
      konzepte=[('wo', ['var']), ('laden', ['ladda'])]),
 dict(sz='club_verloren', de='Ich muss mein Handy laden.', sv='Jag måste ladda mobilen.',
      lookup=False, ansprache=None,
      konzepte=[('muessen', ['måste']), ('laden', ['ladda'])]),
 dict(sz='club_verloren', de='Kann ich dein Handy benutzen?', sv='Kan jag låna din mobil?',
      lookup=False, ansprache=None,
      konzepte=[('benutzen', ['låna', 'använda']), ('handy', ['mobil', 'telefon'])]),
 dict(sz='club_verloren', de='Ich rufe dich an.', sv='Jag ringer dig.',
      lookup=False, ansprache=None,
      konzepte=[('telefonieren', ['ringer', 'ringa'])]),
 dict(sz='club_verloren', de='Wir treffen uns draußen.', sv='Vi ses utanför.',
      lookup=False, ansprache=None,
      konzepte=[('draussen', ['utanför', 'ute']), ('treffen', ['ses', 'träffas'])]),
 dict(sz='club_verloren', de='Bis morgen!', sv='Vi ses imorgon!',
      lookup=False, ansprache=None,
      konzepte=[('morgen', ['imorgon', 'i morgon']), ('treffen', ['ses'])]),
 dict(sz='club_verloren', de='Ich nehme ein Taxi nach Hause.', sv='Jag tar en taxi hem.',
      lookup=False, ansprache=None,
      konzepte=[('taxi', ['taxi']), ('nach_hause', ['hem'])]),
 dict(sz='club_verloren',
      de='Entschuldigung, ich habe meine Freunde verloren und mein Handy ist leer. Können Sie mir helfen?',
      sv='Ursäkta, jag har tappat bort mina vänner och min mobil är död. Kan du hjälpa mig?',
      lookup=True, ansprache=None,
      konzepte=[('verloren', ['tappat bort', 'tappat']), ('helfen', ['hjälpa'])]),

# ---------------------------------------------------------------- Komplimente
 dict(sz='club_komplimente', de='Du siehst heute toll aus.', sv='Du ser jättebra ut idag.',
      lookup=False, ansprache=None,
      konzepte=[('heute', ['idag', 'i dag']), ('gut_aussehen', ['jättebra', 'bra ut', 'snygg'])]),
 dict(sz='club_komplimente', de='Dein Outfit gefällt mir.', sv='Jag gillar dina kläder.',
      lookup=False, ansprache=None,
      konzepte=[('kleidung', ['kläder', 'klädsel']), ('moegen', ['gillar'])]),
 dict(sz='club_komplimente', de='Deine Haare sind schön.', sv='Ditt hår är jättefint.',
      lookup=False, ansprache='frauen',
      konzepte=[('haare', ['hår', 'håret']), ('schoen', ['fint', 'jättefint', 'snyggt'])]),
 dict(sz='club_komplimente', de='Sind deine Haare neu?', sv='Har du gjort något med håret?',
      lookup=False, ansprache='frauen',
      konzepte=[('haare', ['håret', 'hår'])]),
 dict(sz='club_komplimente', de='Deine Augen sind schön.', sv='Du har fina ögon.',
      lookup=False, ansprache=None,
      konzepte=[('auge', ['ögon']), ('schoen', ['fina', 'vackra'])]),
 dict(sz='club_komplimente', de='Ich mag deine Stimme.', sv='Jag gillar din röst.',
      lookup=False, ansprache=None,
      konzepte=[('moegen', ['gillar']), ('stimme', ['röst', 'rösten'])]),
 dict(sz='club_komplimente', de='Deine Stimme ist sehr schön.', sv='Du har en fin röst.',
      lookup=False, ansprache=None,
      konzepte=[('stimme', ['röst']), ('schoen', ['fin', 'vacker'])]),
 dict(sz='club_komplimente', de='Du tanzt wirklich gut.', sv='Du dansar riktigt bra.',
      lookup=False, ansprache=None,
      konzepte=[('tanzen', ['dansar', 'dansa']), ('gut', ['bra', 'riktigt bra'])]),
 dict(sz='club_komplimente', de='Danke, du aber auch.', sv='Tack, detsamma!',
      lookup=False, ansprache=None,
      konzepte=[('danke', ['tack']), ('auch', ['detsamma', 'också'])]),
]
