# -*- coding: utf-8 -*-
"""Entwurf Welle 2: die sechs restlichen Situationen von Club + Nightlife.

Noch NICHT in der Datenbank - Simon liest gegen.

Felder wie in welle1.py. Gebaut nach den drei Regeln aus pruefe_saetze.py:
baubar aus bekanntem Wortschatz, mehrheitlich kurz (echte Anfaenger), und
jedes neue Wort mindestens zweimal.

WIEDERAUFNAHME AUS WELLE 1: 吵 ("laut") stand dort nur in einem einzigen
Satz und war damit eine Vokabel zum Auswendiglernen statt ein Baustein. An
der Bar wird es ohnehin gebraucht - hier kommt es zweimal wieder.
"""

SAETZE = [
# ---------------------------------------------------------------- Reinkommen
 dict(sz='club_einlass', de='Was kostet der Eintritt?', zh='票多少钱？', hinweis=None, py='piào duōshao qián?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('ticket', ['票']), ('wieviel', ['多少'])]),
 dict(sz='club_einlass', de='Ich möchte ein Ticket kaufen.', zh='我想买票。', hinweis=None, py='wǒ xiǎng mǎi piào.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('moechten', ['想']), ('kaufen', ['买']), ('ticket', ['票'])]),
 dict(sz='club_einlass', de='Wir sind zu zweit.', zh='我们两个人。', hinweis=None, py='wǒmen liǎng ge rén.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wir', ['我们']), ('zwei', ['两'])]),
 dict(sz='club_einlass', de='Das ist mein Pass.', zh='这是我的护照。', hinweis='Ausländer müssen den Pass oft vorzeigen — auch am Clubeingang.', py='zhè shì wǒ de hùzhào.',
      neu=['护照'], lookup=False, ansprache=None,
      konzepte=[('pass', ['护照'])]),
 dict(sz='club_einlass', de='Habt ihr heute offen?', zh='今天开吗？', hinweis=None, py='jīntiān kāi ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('heute', ['今天']), ('offen', ['开'])]),
 dict(sz='club_einlass', de='Bis wann habt ihr heute offen?', zh='今天开到几点？', hinweis=None, py='jīntiān kāi dào jǐ diǎn?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('heute', ['今天']), ('bis', ['到']), ('wieviel_uhr', ['几点'])]),
 dict(sz='club_einlass', de='Ich bin mit Freunden hier.', zh='我和朋友们一起来的。', hinweis=None, py='wǒ hé péngyoumen yìqǐ lái de.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('freund', ['朋友']), ('zusammen', ['一起'])]),
 dict(sz='club_einlass', de='Kann ich hier bezahlen?', zh='我可以在这里给钱吗？', hinweis=None, py='wǒ kěyǐ zài zhèlǐ gěi qián ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('koennen', ['可以']), ('geld_geben', ['给钱'])]),
 dict(sz='club_einlass', de='Wo ist die Toilette?', zh='洗手间在哪里？', hinweis=None, py='xǐshǒujiān zài nǎli?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('toilette', ['洗手间']), ('wo', ['哪里'])]),
 dict(sz='club_einlass', de='Meine Freunde kommen später.', zh='我朋友晚点来。', hinweis=None, py='wǒ péngyou wǎn diǎn lái.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('freund', ['朋友']), ('spaeter', ['以后'])]),
 dict(sz='club_einlass', de='Ich bin nicht von hier.', zh='我不是这里人。', hinweis=None, py='wǒ bú shì zhèlǐ rén.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('nicht', ['不']), ('hier', ['这里'])]),

# ---------------------------------------------------------------- An der Bar
 dict(sz='club_bar', de='Zwei Bier, bitte.', zh='请给我两杯啤酒。', hinweis=None, py='qǐng gěi wǒ liǎng bēi píjiǔ.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('geben', ['给']), ('zwei', ['两']), ('bier', ['啤酒'])]),
 dict(sz='club_bar', de='Hier ist es zu laut.', zh='这里太吵了。', hinweis=None, py='zhèlǐ tài chǎo le.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('hier', ['这里']), ('laut', ['吵'])]),
 dict(sz='club_bar', de='Es ist laut, sag es bitte nochmal.', zh='太吵了，请再说一遍。', hinweis=None, py='tài chǎo le, qǐng zài shuō yí biàn.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('laut', ['吵']), ('nochmal', ['再']), ('sagen', ['说'])]),
 dict(sz='club_bar', de='Was möchtest du trinken?', zh='你想喝什么？', hinweis=None, py='nǐ xiǎng hē shénme?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('moechten', ['想']), ('trinken', ['喝']), ('was', ['什么'])]),
 dict(sz='club_bar', de='Haben Sie Wasser?', zh='有水吗？', hinweis=None, py='yǒu shuǐ ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('haben', ['有']), ('wasser', ['水'])]),
 dict(sz='club_bar', de='Das ist zu teuer.', zh='太贵了。', hinweis=None, py='tài guì le.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('teuer', ['贵'])]),
 dict(sz='club_bar', de='Noch eins, bitte.', zh='请再来一个。', hinweis=None, py='qǐng zài lái yí ge.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('nochmal', ['再']), ('kommen', ['来'])]),
 dict(sz='club_bar', de='Ich zahle mit WeChat.', zh='我用微信支付。', hinweis='Bargeld ist in China praktisch verschwunden. Bezahlt wird per QR-Code über WeChat oder Alipay.', py='wǒ yòng wēixìn zhīfù.',
      neu=['用'], lookup=False, ansprache=None,
      konzepte=[('benutzen', ['用']), ('wechat', ['微信'])]),
 dict(sz='club_bar', de='Das bezahle ich.', zh='这个我给钱。', hinweis=None, py='zhège wǒ gěi qián.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('geld_geben', ['给钱'])]),
 dict(sz='club_bar', de='Wo kann ich bezahlen?', zh='在哪里给钱？', hinweis=None, py='zài nǎli gěi qián?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wo', ['哪里']), ('geld_geben', ['给钱'])]),
 dict(sz='club_bar', de='Ich nehme das Gleiche.', zh='我也要一个。', hinweis=None, py='wǒ yě yào yí ge.',
      neu=['要'], lookup=False, ansprache=None,
      konzepte=[('auch', ['也']), ('wollen', ['要'])]),
 dict(sz='club_bar', de='Was möchten Sie?', zh='你要什么？', hinweis=None, py='nǐ yào shénme?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wollen', ['要']), ('was', ['什么'])]),

# ---------------------------------------------------------------- Karaoke
 dict(sz='club_ktv', de='Wollen wir Karaoke singen?', zh='我们一起去唱歌吧？', hinweis='Nachtleben heißt in China oft KTV: ein Privatraum zum Karaoke-Singen mit Freunden, keine Bühne vor Fremden.', py='wǒmen yìqǐ qù chànggē ba?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zusammen', ['一起']), ('singen', ['唱歌'])]),
 dict(sz='club_ktv', de='Ich kann nicht singen.', zh='我不会唱歌。', hinweis=None, py='wǒ bú huì chànggē.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('nicht_koennen', ['不会']), ('singen', ['唱歌'])]),
 dict(sz='club_ktv', de='Sing du zuerst.', zh='你先唱。', hinweis=None, py='nǐ xiān chàng.',
      neu=['先', '唱'], lookup=False, ansprache=None,
      konzepte=[('zuerst', ['先']), ('singen', ['唱'])]),
 dict(sz='club_ktv', de='Welches Lied singst du?', zh='你唱什么歌？', hinweis=None, py='nǐ chàng shénme gē?',
      neu=['歌'], lookup=False, ansprache=None,
      konzepte=[('singen', ['唱']), ('lied', ['歌'])]),
 dict(sz='club_ktv', de='Dieses Lied kenne ich!', zh='这个歌我知道！', hinweis=None, py='zhège gē wǒ zhīdào!',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('lied', ['歌']), ('wissen', ['知道'])]),
 dict(sz='club_ktv', de='Ein Zimmer für vier Personen.', zh='四个人，一个房间。', hinweis='Im KTV mietet man den Raum, nicht den Platz — der Preis gilt pro Stunde und Zimmer.', py='sì ge rén, yí ge fángjiān.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('vier', ['四']), ('zimmer', ['房间'])]),
 dict(sz='club_ktv', de='Wie viel kostet das Zimmer?', zh='房间多少钱？', hinweis=None, py='fángjiān duōshao qián?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zimmer', ['房间']), ('wieviel', ['多少'])]),
 dict(sz='club_ktv', de='Wir bleiben zwei Stunden.', zh='我们待两个小时。', hinweis=None, py='wǒmen dāi liǎng ge xiǎoshí.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zwei', ['两']), ('stunde', ['小时'])]),
 dict(sz='club_ktv', de='Du singst sehr gut!', zh='你唱得很好！', hinweis=None, py='nǐ chàng de hěn hǎo!',
      neu=['得'], lookup=False, ansprache=None,
      konzepte=[('singen', ['唱']), ('gut', ['好'])]),
 dict(sz='club_ktv', de='Wir singen zusammen.', zh='我们一起唱。', hinweis=None, py='wǒmen yìqǐ chàng.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zusammen', ['一起']), ('singen', ['唱'])]),
 dict(sz='club_ktv', de='Sing noch eins!', zh='再唱一个吧！', hinweis=None, py='zài chàng yí ge ba!',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('nochmal', ['再']), ('singen', ['唱'])]),

# ---------------------------------------------------------------- Näher kommen
 dict(sz='club_naeherkommen', de='Ich finde dich sehr nett.', zh='我觉得你很好。', hinweis=None, py='wǒ juéde nǐ hěn hǎo.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('finden', ['觉得']), ('gut', ['好'])]),
 dict(sz='club_naeherkommen', de='Ich mag dich.', zh='我喜欢你。', hinweis=None, py='wǒ xǐhuan nǐ.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('moegen', ['喜欢'])]),
 dict(sz='club_naeherkommen', de='Ist das okay für dich?', zh='你觉得可以吗？', hinweis=None, py='nǐ juéde kěyǐ ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('finden', ['觉得']), ('okay', ['可以'])]),
 dict(sz='club_naeherkommen', de='Gehen wir woanders hin?', zh='我们去别的地方吧？', hinweis=None, py='wǒmen qù bié de dìfang ba?',
      neu=['地方'], lookup=False, ansprache=None,
      konzepte=[('gehen', ['去']), ('ort', ['地方'])]),
 dict(sz='club_naeherkommen', de='Ich kenne einen guten Ort.', zh='我知道一个好地方。', hinweis=None, py='wǒ zhīdào yí ge hǎo dìfang.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wissen', ['知道']), ('ort', ['地方'])]),
 dict(sz='club_naeherkommen', de='Zu dir oder zu mir?', zh='去你家还是我家？', hinweis=None, py='qù nǐ jiā háishi wǒ jiā?',
      neu=['还是'], lookup=False, ansprache=None,
      konzepte=[('zuhause', ['家']), ('oder', ['还是'])]),
 dict(sz='club_naeherkommen', de='Bier oder Wasser?', zh='啤酒还是水？', hinweis=None, py='píjiǔ háishi shuǐ?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('bier', ['啤酒']), ('oder', ['还是'])]),
 dict(sz='club_naeherkommen', de='Ich reise morgen weiter.', zh='我明天走。', hinweis=None, py='wǒ míngtiān zǒu.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('morgen', ['明天']), ('gehen', ['走'])]),
 dict(sz='club_naeherkommen', de='Gehen wir kurz nach draußen.', zh='我们去外面吧。', hinweis=None, py='wǒmen qù wàimiàn ba.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('gehen', ['去']), ('draussen', ['外面'])]),
 dict(sz='club_naeherkommen', de='Du gefällst mir sehr.', zh='我很喜欢你。', hinweis=None, py='wǒ hěn xǐhuan nǐ.',
      neu=[], lookup=False, ansprache='frauen',
      konzepte=[('sehr', ['很']), ('moegen', ['喜欢'])]),
 dict(sz='club_naeherkommen', de='Du bist sehr gut aussehend.', zh='你很帅。', hinweis='Im Chinesischen zwei verschiedene Wörter: 帅 sagt man zu Männern, 漂亮 zu Frauen.', py='nǐ hěn shuài.',
      neu=[], lookup=False, ansprache='maenner',
      konzepte=[('gutaussehend', ['帅'])]),
 dict(sz='club_naeherkommen', de='Ich möchte nicht daten, ich werde sehr bald abreisen.',
      zh='我不想谈恋爱，我很快就要走了。', hinweis=None, py="wǒ bù xiǎng tán liàn'ài, wǒ hěn kuài jiù yào zǒu le.",
      neu=['就'], lookup=True, ansprache=None,
      konzepte=[('nicht_wollen', ['不想']), ('gehen', ['走'])]),

# ---------------------------------------------------------------- Wo schlafen wir
 dict(sz='club_nachtlogistik', de='Können wir zu dir?', zh='我们可以去你家吗？', hinweis=None, py='wǒmen kěyǐ qù nǐ jiā ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('koennen', ['可以']), ('zuhause', ['家'])]),
 dict(sz='club_nachtlogistik', de='Ich wohne im Hotel, ist nicht so praktisch', zh='我住酒店，不太方便。', hinweis='Viele Hotels und Hostels in China dürfen keine unangemeldeten Gäste aufs Zimmer lassen. Das ist Vorschrift, keine Ausrede.', py='wǒ zhù jiǔdiàn, bù tài fāngbiàn.',
      neu=['酒店'], lookup=False, ansprache=None,
      konzepte=[('hotel', ['酒店']), ('nicht_koennen', ['不可以'])]),
 dict(sz='club_nachtlogistik', de='Nehmen wir ein Zimmer.', zh='我们开一个房间吧。', hinweis=None, py='wǒmen kāi yí ge fángjiān ba.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zimmer', ['房间'])]),
 dict(sz='club_nachtlogistik', de='Das Zimmer bezahle ich.', zh='房间的钱我来付。', hinweis=None, py='fángjiān de qián wǒ lái fù.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zimmer', ['房间']), ('geld', ['钱'])]),
 dict(sz='club_nachtlogistik', de='Das Hotel will meinen Pass sehen.', zh='酒店想看我的护照。', hinweis=None, py='jiǔdiàn xiǎng kàn wǒ de hùzhào.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('hotel', ['酒店']), ('pass', ['护照'])]),
 dict(sz='club_nachtlogistik', de='Ich rufe ein Taxi.', zh='我叫出租车。', hinweis=None, py='wǒ jiào chūzūchē.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('rufen', ['叫']), ('taxi', ['出租车'])]),
 dict(sz='club_nachtlogistik', de='Zuerst zu dir, dann zu mir.', zh='先去你家，再去我家。', hinweis='Wichtig fürs Taxi: dem Fahrer gleich sagen, dass zwei Adressen angefahren werden.', py='xiān qù nǐ jiā, zài qù wǒ jiā.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('zuerst', ['先']), ('dann', ['再'])]),
 dict(sz='club_nachtlogistik', de='Wo wohnst du?', zh='你住在哪里？', hinweis=None, py='nǐ zhù zài nǎli?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wohnen', ['住']), ('wo', ['哪里'])]),
 dict(sz='club_nachtlogistik', de='Ist das weit?', zh='远吗？', hinweis=None, py='yuǎn ma?',
      neu=['远'], lookup=False, ansprache=None,
      konzepte=[('weit', ['远'])]),
 dict(sz='club_nachtlogistik', de='Mein Hotel ist nicht weit.', zh='我的酒店不远。', hinweis=None, py='wǒ de jiǔdiàn bù yuǎn.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('hotel', ['酒店']), ('weit', ['远'])]),
 dict(sz='club_nachtlogistik', de='Ich fahre nach Hause.', zh='我回家。', hinweis=None, py='wǒ huí jiā.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('nach_hause', ['回家'])]),

# ---------------------------------------------------------------- Freunde verloren
 dict(sz='club_verloren', de='Ich finde meine Freunde nicht.', zh='我找不到我的朋友。', hinweis=None, py='wǒ zhǎo bú dào wǒ de péngyou.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('suchen', ['找']), ('freund', ['朋友'])]),
 dict(sz='club_verloren', de='Hast du meinen Freund gesehen?', zh='你看到我朋友了吗？', hinweis=None, py='nǐ kàn dào wǒ péngyou le ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('sehen', ['看']), ('freund', ['朋友'])]),
 dict(sz='club_verloren', de='Wo bist du?', zh='你在哪里？', hinweis=None, py='nǐ zài nǎli?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('du', ['你']), ('wo', ['哪里'])]),
 dict(sz='club_verloren', de='Ich warte hier auf dich.', zh='我在这里等你。', hinweis=None, py='wǒ zài zhèlǐ děng nǐ.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('hier', ['这里']), ('warten', ['等'])]),
 dict(sz='club_verloren', de='Mein Handy hat keinen Strom mehr.', zh='我的手机没有电了。', hinweis=None, py='wǒ de shǒujī méiyǒu diàn le.',
      neu=['电'], lookup=False, ansprache=None,
      konzepte=[('handy', ['手机']), ('strom', ['电'])]),
 dict(sz='club_verloren', de='Wo kann ich mein Handy laden?', zh='哪里可以充电？', hinweis=None, py='nǎli kěyǐ chōngdiàn?',
      neu=['充电'], lookup=False, ansprache=None,
      konzepte=[('wo', ['哪里']), ('laden', ['充电'])]),
 dict(sz='club_verloren', de='Ich muss mein Handy laden.', zh='我要充电。', hinweis=None, py='wǒ yào chōngdiàn.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('wollen', ['要']), ('laden', ['充电'])]),
 dict(sz='club_verloren', de='Kann ich dein Handy benutzen?', zh='我可以用你的手机吗？', hinweis=None, py='wǒ kěyǐ yòng nǐ de shǒujī ma?',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('benutzen', ['用']), ('handy', ['手机'])]),
 dict(sz='club_verloren', de='Ich rufe dich an.', zh='我给你打电话。', hinweis=None, py='wǒ gěi nǐ dǎ diànhuà.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('telefonieren', ['打电话'])]),
 dict(sz='club_verloren', de='Wir treffen uns draußen.', zh='我们在外面见。', hinweis=None, py='wǒmen zài wàimiàn jiàn.',
      neu=['见'], lookup=False, ansprache=None,
      konzepte=[('draussen', ['外面']), ('treffen', ['见'])]),
 dict(sz='club_verloren', de='Bis morgen!', zh='明天见！', hinweis=None, py='míngtiān jiàn!',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('morgen', ['明天']), ('treffen', ['见'])]),
 dict(sz='club_verloren', de='Ich nehme ein Taxi nach Hause.', zh='我叫出租车回家。', hinweis=None, py='wǒ jiào chūzūchē huí jiā.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('taxi', ['出租车']), ('nach_hause', ['回家'])]),
 dict(sz='club_verloren', de='Entschuldigung, ich kann meine Freunde nicht mehr finden. Mein Handy hat auch keinen Akku mehr. Kannst du mir helfen?',
      zh='对不起，我找不到朋友，手机也没有电了。你能帮我吗？', hinweis=None,
      py='duìbuqǐ, wǒ zhǎo bú dào péngyou, shǒujī yě méiyǒu diàn le. nǐ néng bāng wǒ ma?',
      neu=[], lookup=True, ansprache=None,
      konzepte=[('suchen', ['找']), ('helfen', ['帮'])]),
]
