# -*- coding: utf-8 -*-
"""Gesundheit/Notfall und Job auf Englisch.

Zusammen 118 Master-Saetze - health_emergency (76), job_work (42).

**VIER SAETZE SIND CHINA-SPEZIFISCH:**

  Rufen Sie bitte 120 an.     **120 ist der chinesische Rettungsdienst.**
                              In Grossbritannien ist es die **999** - die
                              aelteste Notrufnummer der Welt und die, die
                              jeder Brite kennt. Die europaeische 112
                              funktioniert dort ebenfalls und wird auf
                              dieselbe Leitstelle geroutet, aber 999 ist
                              das, was man ruft. Ersetzt (`neu=True`).
  Ich moechte westliche       Der Gegensatz zur TCM traegt in
  Medizin.                    Grossbritannien nicht. Beide ersatzlos
  Ist das westliche Medizin?  ausgelassen.
  Ich spreche kein            Zielsprache im Satz - ersetzt durch
  Chinesisch. ...             "Ich spreche kein Englisch."

**116 uebersetzt, 4 ausgelassen, 2 neu.**

**Das britische Gesundheitssystem faellt anders als das deutsche**, und
zwar an genau der Stelle, wo der Master-Satz von Versicherungskarte und
Bezahlen spricht: der NHS ist kostenlos an der Nutzungsstelle. Es gibt
keine Karte vorzuzeigen und meist nichts zu bezahlen - wohl aber eine
Anmeldung beim `GP` (Hausarzt), ohne die man im Nicht-Notfall nirgends
hinkommt. Die Bezahl-Saetze stehen trotzdem alle da (der Master
entscheidet, nicht diese Datei), aber mit Hinweis, dass sie eher fuer
Privatpraxen und die USA gelten.
"""

KATEGORIEN = ['health_emergency', 'job_work']

SAETZE = [

# ========================================================== health_emergency
 dict(kat='health_emergency', de='Ich bin allergisch gegen Penizillin.', en="I'm allergic to penicillin.",
      k=[('allergisch', ['allergic']),
         ('penizillin', ['penicillin'])]),
 dict(kat='health_emergency', de='Ich habe eine Allergie.', en='I have an allergy.',
      k=[('allergie', ['allergy'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen dieses Medikament.', en="I'm allergic to this medication.",
      k=[('allergisch', ['allergic']),
         ('medikament', ['medication', 'medicine', 'drug'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen Erdnüsse.', en="I'm allergic to peanuts.",
      k=[('allergisch', ['allergic']),
         ('erdnuesse', ['peanuts'])]),
 dict(kat='health_emergency', de='Ich kann keine Erdnüsse essen.', en="I can't eat peanuts.",
      k=[('nicht_essen', ["can't eat", 'cannot eat']),
         ('erdnuesse', ['peanuts'])]),
 dict(kat='health_emergency', de='Sind da Erdnüsse drin?', en='Does this contain peanuts?',
      k=[('erdnuesse', ['peanuts'])]),
 dict(kat='health_emergency', de='Bitte ohne Erdnüsse.', en='Without peanuts, please.',
      k=[('ohne', ['without', 'no']),
         ('erdnuesse', ['peanuts'])]),
 dict(kat='health_emergency', de='Bitte ohne Milch.', en='Without milk, please.',
      k=[('ohne', ['without', 'no']),
         ('milch', ['milk', 'dairy'])]),
 dict(kat='health_emergency', de='Ich vertrage keine Milch.', en="I'm lactose intolerant.",
      k=[('milch_vertragen', ['lactose intolerant', 'lactose', "can't have dairy"])]),
 dict(kat='health_emergency', de='Was ist da drin?', en="What's in it?",
      k=[('was_drin', ["what's in it", 'ingredients', 'contains'])]),
 dict(kat='health_emergency', de='Ich habe mein Allergiemedikament dabei.', en='I have my allergy medication with me.',
      k=[('allergiemedikament', ['allergy medication', 'epipen', 'antihistamine'])]),
 dict(kat='health_emergency', de='Das ist für mich sehr gefährlich.', en="That's very dangerous for me.",
      k=[('gefaehrlich', ['very dangerous', 'dangerous'])]),
 dict(kat='health_emergency', de='Ist das gefährlich?', en='Is that dangerous?',
      k=[('gefaehrlich', ['dangerous'])]),
 dict(kat='health_emergency', de='Ich habe meine Versicherungskarte vergessen.', en="I've forgotten my insurance card.",
      k=[('versicherungskarte', ['insurance card', 'ehic', 'insurance'])],
      h='Der NHS ist an der Nutzungsstelle kostenlos — eine Karte vorzuzeigen '
        'ist im Notfall gar nicht nötig. Was du brauchst, ist eine Anmeldung '
        'beim „GP" (Hausarzt) für alles, was kein Notfall ist.'),
 dict(kat='health_emergency', de='Wie viel kostet das?', en='How much does it cost?',
      k=[('kosten', ['how much', 'cost'])]),
 dict(kat='health_emergency', de='Ich habe eine Versicherung.', en='I have insurance.',
      k=[('versicherung', ['insurance'])]),
 dict(kat='health_emergency', de='Nehmen Sie meine Versicherung?', en='Do you accept my insurance?',
      k=[('versicherung_akzeptiert', ['accept my insurance', 'accept', 'insurance'])]),
 dict(kat='health_emergency', de='Muss ich vorher bezahlen?', en='Do I have to pay in advance?',
      k=[('vorher_bezahlen', ['pay in advance', 'in advance', 'upfront'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir eine Quittung.', en='Could I have a receipt, please?',
      k=[('quittung', ['receipt'])]),
 dict(kat='health_emergency', de='Ich brauche die Quittung für meine Versicherung.', en='I need the receipt for my insurance.',
      k=[('quittung', ['receipt']),
         ('versicherung', ['insurance'])]),
 dict(kat='health_emergency', de='Kann ich mit dem Handy bezahlen?', en='Can I pay with my phone?',
      k=[('handy_bezahlen', ['with my phone', 'phone', 'contactless'])]),
 dict(kat='health_emergency', de='Nehmen Sie auch Karte?', en='Do you take card?',
      k=[('karte', ['card'])]),
 dict(kat='health_emergency', de='Hier ist meine Karte.', en="Here's my card.",
      k=[('meine_karte', ["here's my card", 'my card', 'card'])]),
 dict(kat='health_emergency', de='Zuerst anmelden, dann bezahlen?', en='Register first, then pay?',
      k=[('anmelden', ['register', 'check in']),
         ('bezahlen', ['pay'])]),
 dict(kat='health_emergency', de='Wo bekomme ich die Quittung?', en='Where do I get the receipt?',
      k=[('quittung', ['receipt'])]),
 dict(kat='health_emergency', de='Wo kann ich bezahlen?', en='Where can I pay?',
      k=[('wo_bezahlen', ['where can i pay', 'pay'])]),
 dict(kat='health_emergency', de='Das ist zu teuer.', en="That's too expensive.",
      k=[('zu_teuer', ['too expensive'])]),
 dict(kat='health_emergency', de='Ich habe nicht genug Geld dabei.', en="I don't have enough money on me.",
      k=[('nicht_genug_geld', ["don't have enough money", 'enough money', 'money'])]),
 dict(kat='health_emergency', de='Reicht das?', en='Is that enough?',
      k=[('reicht', ['is that enough', 'enough'])]),
 dict(kat='health_emergency', de='Ich habe meine Tabletten vergessen.', en="I've forgotten my tablets.",
      k=[('tabletten_vergessen', ['forgotten my tablets', 'tablets', 'pills'])]),
 dict(kat='health_emergency', de='Wie oft muss ich das Medikament nehmen?', en='How often do I take this medication?',
      k=[('medikament_haeufigkeit', ['how often', 'take this medication', 'medication'])]),
 dict(kat='health_emergency', de='Wo ist das Krankenhaus?', en='Where is the hospital?',
      k=[('krankenhaus', ['hospital'])]),
 dict(kat='health_emergency', de='Ich möchte zum Arzt.', en="I'd like to see a doctor.",
      k=[('arzt', ['doctor', 'gp'])],
      h='Der Hausarzt heißt „GP" (general practitioner) — bei ihm musst du '
        'dich anmelden („register with a GP"), bevor du einen Termin '
        'bekommst. Für Akutes gibt es „A&E" (Notaufnahme) und die 111 als '
        'Beratungsnummer.'),
 dict(kat='health_emergency', de='Wo melde ich mich an?', en='Where do I check in?',
      k=[('anmelden', ['check in', 'register', 'reception'])]),
 dict(kat='health_emergency', de='Ich möchte mich anmelden.', en="I'd like to register.",
      k=[('anmelden', ['register', 'check in'])]),
 dict(kat='health_emergency', de='Ich habe keinen Termin.', en="I don't have an appointment.",
      k=[('kein_termin', ["don't have an appointment", 'appointment'])]),
 dict(kat='health_emergency', de='Kann ich einen Termin bekommen?', en='Can I get an appointment?',
      k=[('termin', ['appointment'])]),
 dict(kat='health_emergency', de='Wie lange muss ich warten?', en='How long do I have to wait?',
      k=[('warten', ['how long do i have to wait', 'wait'])]),
 dict(kat='health_emergency', de='Wie lange dauert das?', en='How long does it take?',
      k=[('dauer', ['how long does it take', 'how long'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir ein Medikament.', en='Could you give me some medication?',
      k=[('medikament', ['medication', 'medicine'])]),
 dict(kat='health_emergency', de='Wie nehme ich das Medikament?', en='How do I take this medication?',
      k=[('medikament_einnahme', ['how do i take', 'take this medication', 'medication'])]),
 dict(kat='health_emergency', de='Wie komme ich dorthin?', en='How do I get there?',
      k=[('wie_dorthin', ['how do i get there', 'get there'])]),
 dict(kat='health_emergency', de='Ich brauche einen Arzt.', en='I need a doctor.',
      k=[('arzt', ['doctor'])]),
 dict(kat='health_emergency', de='Wo ist die nächste Apotheke?', en='Where is the nearest pharmacy?',
      k=[('apotheke', ['pharmacy', 'chemist'])],
      h='In Großbritannien heißt die Apotheke im Alltag „chemist" — „Boots" '
        'ist die Kette, die jeder meint.'),
 dict(kat='health_emergency', de='Ich brauche dringend Hilfe.', en='I need help urgently.',
      k=[('dringend_hilfe', ['urgently', 'urgent help', 'help'])]),
 dict(kat='health_emergency', de='Wo ist das nächste Krankenhaus?', en='Where is the nearest hospital?',
      k=[('krankenhaus', ['hospital'])]),
 dict(kat='health_emergency', de='Bitte helfen Sie mir!', en='Please help me!',
      k=[('helfen', ['help me', 'help'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie einen Krankenwagen!', en='Please call an ambulance!',
      k=[('krankenwagen', ['ambulance'])]),
 dict(kat='health_emergency', de='Ist der Krankenwagen schon unterwegs?', en='Is the ambulance on its way?',
      k=[('krankenwagen', ['ambulance']),
         ('unterwegs', ['on its way', 'coming'])]),
 dict(kat='health_emergency', de='Jemand ist verletzt.', en='Someone is injured.',
      k=[('verletzt', ['injured', 'hurt'])]),
 dict(kat='health_emergency', de='Ich bin verletzt.', en="I'm injured.",
      k=[('verletzt', ['injured', 'hurt'])]),
 dict(kat='health_emergency', de='Schnell, bitte!', en='Quickly, please!',
      k=[('schnell', ['quickly', 'quick', 'hurry'])]),
 dict(kat='health_emergency', de='Ich brauche etwas aus der Apotheke.', en='I need something from the pharmacy.',
      k=[('apotheke', ['pharmacy', 'chemist'])]),
 dict(kat='health_emergency', de='Ich bin allein hier.', en="I'm here on my own.",
      k=[('allein', ['on my own', 'alone', 'by myself'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie meinen Freund an.', en='Please call my friend.',
      k=[('anrufen', ['call']),
         ('freund', ['my friend', 'friend'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie die Polizei!', en='Please call the police!',
      k=[('polizei', ['police'])]),
 dict(kat='health_emergency', de='Ich möchte die Polizei rufen.', en='I want to call the police.',
      k=[('polizei', ['police'])]),
 dict(kat='health_emergency', de='Mir geht es nicht gut.', en="I don't feel well.",
      k=[('nicht_gut', ["don't feel well", 'not well', 'unwell'])]),
 dict(kat='health_emergency', de='Ich habe Kopfschmerzen.', en='I have a headache.',
      k=[('kopfschmerzen', ['headache'])],
      h='Schmerzen sind im Englischen ein Nomen mit „have a": a headache, a '
        'stomach ache, a sore throat. „I have pain" klingt medizinisch.'),
 dict(kat='health_emergency', de='Ich habe Fieber.', en="I have a temperature.",
      k=[('fieber', ['temperature', 'fever'])]),
 dict(kat='health_emergency', de='Ich habe mir den Fuß verletzt.', en="I've hurt my foot.",
      k=[('fuss_verletzt', ['hurt my foot', 'foot'])]),
 dict(kat='health_emergency', de='Ich fühle mich schwindelig.', en='I feel dizzy.',
      k=[('schwindelig', ['dizzy', 'light-headed'])]),
 dict(kat='health_emergency', de='Ich bin krank.', en="I'm ill.",
      k=[('krank', ['ill', 'sick'])],
      h='„Ill" ist britisch, „sick" amerikanisch — in Großbritannien heißt '
        '„sick" eher, dass einem übel ist.'),
 dict(kat='health_emergency', de='Ich bin erkältet.', en="I've got a cold.",
      k=[('erkaeltet', ['a cold', 'cold'])]),
 dict(kat='health_emergency', de='Ich habe Bauchschmerzen.', en='I have a stomach ache.',
      k=[('bauchschmerzen', ['stomach ache', 'tummy ache', 'stomach'])]),
 dict(kat='health_emergency', de='Mein Bein tut weh.', en='My leg hurts.',
      k=[('bein_weh', ['my leg hurts', 'leg'])]),
 dict(kat='health_emergency', de='Hier tut es weh.', en='It hurts here.',
      k=[('hier_weh', ['it hurts here', 'hurts here', 'here'])]),
 dict(kat='health_emergency', de='Mir geht es sehr schlecht.', en="I feel really bad.",
      k=[('sehr_schlecht', ['really bad', 'very bad', 'awful'])]),
 dict(kat='health_emergency', de='Ich bin sehr müde.', en="I'm very tired.",
      k=[('muede', ['very tired', 'tired', 'exhausted'])]),
 dict(kat='health_emergency', de='Mir ist kalt.', en="I'm cold.",
      k=[('kalt', ["i'm cold", 'cold', 'freezing'])]),
 dict(kat='health_emergency', de='Seit gestern.', en='Since yesterday.',
      k=[('seit_gestern', ['since yesterday', 'yesterday'])]),
 dict(kat='health_emergency', de='Seit heute Morgen.', en='Since this morning.',
      k=[('seit_heute_morgen', ['since this morning', 'this morning'])]),
 dict(kat='health_emergency', de='Rufen Sie bitte 999 an.', en='Please call 999.',
      neu=True, sz='health_notfall',
      k=[('notruf', ['999', 'nine nine nine', '112'])],
      h='999 ist die älteste Notrufnummer der Welt und die, die jeder Brite '
        'ruft — für Polizei, Feuerwehr und Krankenwagen. Die europäische 112 '
        'funktioniert dort ebenfalls und landet auf derselben Leitstelle. '
        'Für Nicht-Notfälle gibt es die 111.'),
 dict(kat='health_emergency', de='Ich spreche kein Englisch. Können Sie es aufschreiben?',
      en="I don't speak English. Could you write it down?",
      neu=True, sz='health_krankenhaus',
      k=[('kein_englisch', ["don't speak english", "don't speak"]),
         ('aufschreiben', ['write it down', 'write'])]),

# ================================================================== job_work
 dict(kat='job_work', de='Ich kann heute nicht kommen.', en="I can't come in today.",
      k=[('nicht_koennen', ["can't", 'cannot']),
         ('heute', ['today']),
         ('kommen', ['come in', 'come'])]),
 dict(kat='job_work', de='Ich bin krank und bleibe zu Hause.', en="I'm ill and staying at home.",
      k=[('krank', ['ill', 'sick']),
         ('zu_hause', ['at home', 'home'])],
      h='„To call in sick" ist die feste Wendung fürs Krankmelden. Bis zu '
        'sieben Tage reicht die Selbstauskunft („self-certification"), erst '
        'danach braucht es eine „sick note" vom GP.'),
 dict(kat='job_work', de='Ich komme später.', en="I'll be late.",
      k=[('kommen', ["i'll be", 'coming']),
         ('spaeter', ['late', 'later'])]),
 dict(kat='job_work', de='Ich brauche einen Tag frei.', en='I need a day off.',
      k=[('brauchen', ['i need', 'need']),
         ('tag_frei', ['a day off', 'day off'])]),
 dict(kat='job_work', de='Ich habe einen Arzttermin.', en="I've got a doctor's appointment.",
      k=[('arzttermin', ["doctor's appointment", 'appointment'])]),
 dict(kat='job_work', de='Ich habe schon in einem Restaurant gearbeitet.', en="I've worked in a restaurant before.",
      k=[('gearbeitet', ["i've worked", 'worked']),
         ('restaurant', ['restaurant'])]),
 dict(kat='job_work', de='Ich habe keine Erfahrung.', en="I don't have any experience.",
      k=[('keine', ["don't have any", 'no']),
         ('erfahrung', ['experience'])]),
 dict(kat='job_work', de='Ich lerne schnell.', en="I'm a fast learner.",
      k=[('lernen', ['learner', 'learn']),
         ('schnell', ['fast', 'quick'])],
      h='„I am a fast learner" ist die feste Formel im Bewerbungsgespräch — '
        '„I learn fast" klingt daneben roh.'),
 dict(kat='job_work', de='Ich kann am Wochenende arbeiten.', en='I can work weekends.',
      k=[('koennen', ['i can', 'can']),
         ('wochenende', ['weekends', 'weekend']),
         ('arbeiten', ['work'])]),
 dict(kat='job_work', de='Wann kann ich anfangen?', en='When can I start?',
      k=[('wann', ['when']),
         ('anfangen', ['start', 'begin'])]),
 dict(kat='job_work', de='Brauche ich eine Arbeitserlaubnis?', en='Do I need a work permit?',
      k=[('brauchen', ['do i need', 'need']),
         ('arbeitserlaubnis', ['work permit', 'visa', 'right to work'])],
      h='Seit dem Brexit brauchen EU-Bürger für Großbritannien ein Visum — '
        'die Freizügigkeit gilt dort nicht mehr. Der Arbeitgeber prüft das '
        '„right to work", bevor er einstellt.'),
 dict(kat='job_work', de='Ich bin neu hier.', en="I'm new here.",
      k=[('neu', ['new']),
         ('hier', ['here'])]),
 dict(kat='job_work', de='Kannst du mir kurz helfen?', en='Could you give me a hand?',
      k=[('koennen', ['could you', 'can you']),
         ('helfen', ['give me a hand', 'help me', 'help'])]),
 dict(kat='job_work', de='Wie macht man das?', en='How do you do this?',
      k=[('wie', ['how']),
         ('machen', ['do this', 'do'])]),
 dict(kat='job_work', de='Das habe ich noch nie gemacht.', en="I've never done this before.",
      k=[('nie', ['never']),
         ('gemacht', ['done'])]),
 dict(kat='job_work', de='Wo finde ich das?', en='Where can I find that?',
      k=[('wo', ['where']),
         ('finden', ['find'])]),
 dict(kat='job_work', de='Ich mache Pause.', en="I'm taking a break.",
      k=[('pause', ['break'])]),
 dict(kat='job_work', de='Danke für deine Hilfe.', en='Thanks for your help.',
      k=[('danke', ['thanks', 'thank you']),
         ('hilfe', ['your help', 'help'])]),
 dict(kat='job_work', de='Kann ich Ihnen helfen?', en='Can I help you?',
      k=[('koennen', ['can i']),
         ('helfen', ['help you', 'help'])],
      h='Im Laden hört man eher „are you alright there?" — das ist keine '
        'Frage nach dem Befinden, sondern das britische „kann ich helfen?"'),
 dict(kat='job_work', de='Der Nächste, bitte!', en='Next, please!',
      k=[('naechste', ['next'])]),
 dict(kat='job_work', de='Möchten Sie noch etwas?', en='Anything else?',
      k=[('moechten', ['would you like', 'anything']),
         ('noch_etwas', ['anything else', 'else'])]),
 dict(kat='job_work', de='Zahlen Sie bar oder mit Karte?', en='Are you paying by cash or card?',
      k=[('bar', ['cash']),
         ('karte', ['card'])]),
 dict(kat='job_work', de='Tut mir leid, das haben wir nicht.', en="Sorry, we don't have that.",
      k=[('leid', ['sorry']),
         ('nicht_haben', ["don't have that", "don't have"])]),
 dict(kat='job_work', de='Ich hole meinen Kollegen.', en="I'll get my colleague.",
      k=[('holen', ["i'll get", 'get']),
         ('kollege', ['colleague', 'coworker'])]),
 dict(kat='job_work', de='Kommen Sie gerne wieder!', en='Come again soon!',
      k=[('wiederkommen', ['come again', 'come back'])]),
 dict(kat='job_work', de='Wie viel verdiene ich pro Stunde?', en='How much do I earn per hour?',
      k=[('verdienen', ['earn', 'get paid']),
         ('stunde', ['per hour', 'an hour', 'hour'])],
      h='Der gesetzliche Mindestlohn heißt „National Living Wage" und ist '
        'nach Alter gestaffelt — unter 21 bekommt man weniger.'),
 dict(kat='job_work', de='Wann bekomme ich mein Geld?', en='When do I get paid?',
      k=[('wann', ['when']),
         ('geld', ['get paid', 'paid', 'wages'])]),
 dict(kat='job_work', de='Werde ich bar bezahlt?', en='Am I paid in cash?',
      k=[('bar', ['cash', 'in cash']),
         ('bezahlt', ['paid', 'am i paid'])]),
 dict(kat='job_work', de='Ich habe zehn Stunden gearbeitet.', en="I've worked ten hours.",
      k=[('zehn', ['ten']),
         ('stunden', ['hours']),
         ('gearbeitet', ["i've worked", 'worked'])]),
 dict(kat='job_work', de='Wann fange ich an?', en='When do I start?',
      k=[('wann', ['when']),
         ('anfangen', ['start'])]),
 dict(kat='job_work', de='Wann habe ich frei?', en="When is my day off?",
      k=[('wann', ['when']),
         ('frei', ['day off', 'off'])]),
 dict(kat='job_work', de='Wie lange dauert die Schicht?', en='How long is the shift?',
      k=[('wie_lange', ['how long']),
         ('schicht', ['shift'])]),
 dict(kat='job_work', de='Kann ich am Montag frei haben?', en='Can I have Monday off?',
      k=[('montag', ['monday']),
         ('frei', ['off', 'day off'])]),
 dict(kat='job_work', de='Kann ich die Schicht tauschen?', en='Can I swap shifts?',
      k=[('schicht', ['shift', 'shifts']),
         ('tauschen', ['swap', 'switch'])]),
 dict(kat='job_work', de='Ich komme morgen früher.', en="I'll come in earlier tomorrow.",
      k=[('morgen', ['tomorrow']),
         ('frueher', ['earlier'])]),
 dict(kat='job_work', de='Wo ist der Dienstplan?', en='Where is the rota?',
      k=[('wo', ['where']),
         ('dienstplan', ['rota', 'schedule', 'shift schedule'])],
      h='„Rota" ist das britische Wort für den Dienstplan — in den USA sagt '
        'man „schedule". Wer „rota" nicht kennt, versteht die halbe '
        'Schichtplanung nicht.'),
 dict(kat='job_work', de='Ich suche Arbeit.', en="I'm looking for work.",
      k=[('suchen', ['looking for']),
         ('arbeit', ['work', 'a job'])]),
 dict(kat='job_work', de='Suchen Sie noch Leute?', en='Are you still hiring?',
      k=[('suchen', ['hiring', 'looking for']),
         ('leute', ['staff', 'people'])]),
 dict(kat='job_work', de='Haben Sie eine Stelle frei?', en='Do you have any vacancies?',
      k=[('stelle', ['vacancies', 'vacancy', 'position']),
         ('frei', ['any', 'available'])]),
 dict(kat='job_work', de='Brauchen Sie Hilfe in der Küche?', en='Do you need help in the kitchen?',
      k=[('brauchen', ['do you need', 'need']),
         ('hilfe', ['help']),
         ('kueche', ['kitchen'])]),
 dict(kat='job_work', de='Ich kann sofort anfangen.', en='I can start straight away.',
      k=[('koennen', ['i can', 'can']),
         ('sofort', ['straight away', 'immediately', 'right away']),
         ('anfangen', ['start'])]),
 dict(kat='job_work', de='Ich bin für drei Monate hier.', en="I'm here for three months.",
      k=[('drei_monate', ['three months']),
         ('hier', ['here'])]),
]

AUSGELASSEN = [
    # 120 ist der CHINESISCHE Rettungsdienst - in Grossbritannien ist es die
    # 999 (112 funktioniert ebenfalls). Ersetzt, siehe Kopfkommentar.
    'Rufen Sie bitte 120 an.',
    # Den Gegensatz westliche Medizin / TCM gibt es in Grossbritannien nicht.
    'Ich möchte westliche Medizin.',
    'Ist das westliche Medizin?',
    # Zielsprache steht im Satz - ersetzt durch die englische Fassung.
    'Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
]
