# -*- coding: utf-8 -*-
"""Gesundheit/Notfall und Job auf Polnisch.

Zusammen 118 Master-Saetze - health_emergency (76), job_work (42).

**VIER SAETZE SIND CHINA-SPEZIFISCH:**

  Rufen Sie bitte 120 an.     **120 ist der chinesische Rettungsdienst.**
                              In Polen ist es die **112** (europaeischer
                              Notruf, deckt alles ab); die alte 999 fuer
                              den Rettungsdienst (`pogotowie`) gilt
                              daneben weiter. Ersetzt (`neu=True`).
  Ich moechte westliche       Der Gegensatz zur TCM traegt in Polen
  Medizin.                    nicht. Beide ersatzlos ausgelassen.
  Ist das westliche Medizin?
  Ich spreche kein            Zielsprache im Satz - ersetzt.
  Chinesisch. ...

**116 uebersetzt, 4 ausgelassen, 2 neu.**

**Vergangenheitsformen tragen das Geschlecht des Sprechers**
(zgubiłem/zgubiłam, pracowałem/pracowałam) - dieselbe Falle wie im
Russischen. Wo ein Satz in der Vergangenheit steht, nennt der Hinweis
beide Formen.

**Das polnische Gesundheitssystem** kennt die staatliche `NFZ`-Versorgung
(mit langen Wartezeiten) und private Praxen, in denen man direkt zahlt und
schnell drankommt. Fuer Reisende ist Letzteres oft der praktischere Weg -
deshalb sind die Bezahl-Saetze hier keine Theorie.
"""

KATEGORIEN = ['health_emergency', 'job_work']

SAETZE = [

# ========================================================== health_emergency
 dict(kat='health_emergency', de='Ich bin allergisch gegen Penizillin.', pl='Jestem uczulony na penicylinę.',
      k=[('allergisch', ['uczulony', 'uczulona', 'alergia']),
         ('penizillin', ['penicylinę', 'penicylina'])],
      h='Als Frau: „uczulona". Das Adjektiv richtet sich nach dem Sprecher.'),
 dict(kat='health_emergency', de='Ich habe eine Allergie.', pl='Mam alergię.',
      k=[('allergie', ['alergię', 'alergia'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen dieses Medikament.', pl='Jestem uczulony na ten lek.',
      k=[('allergisch', ['uczulony', 'uczulona']),
         ('medikament', ['lek', 'lekarstwo'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen Erdnüsse.', pl='Jestem uczulony na orzeszki ziemne.',
      k=[('allergisch', ['uczulony', 'uczulona']),
         ('erdnuesse', ['orzeszki ziemne', 'orzeszki'])]),
 dict(kat='health_emergency', de='Ich kann keine Erdnüsse essen.', pl='Nie mogę jeść orzeszków.',
      k=[('nicht_essen', ['nie mogę jeść', 'nie mogę']),
         ('erdnuesse', ['orzeszków', 'orzeszki'])]),
 dict(kat='health_emergency', de='Sind da Erdnüsse drin?', pl='Czy są tam orzeszki?',
      k=[('erdnuesse', ['orzeszki'])]),
 dict(kat='health_emergency', de='Bitte ohne Erdnüsse.', pl='Bez orzeszków, proszę.',
      k=[('ohne', ['bez']),
         ('erdnuesse', ['orzeszków', 'orzeszki'])]),
 dict(kat='health_emergency', de='Bitte ohne Milch.', pl='Bez mleka, proszę.',
      k=[('ohne', ['bez']),
         ('milch', ['mleka', 'mleko'])]),
 dict(kat='health_emergency', de='Ich vertrage keine Milch.', pl='Nie toleruję laktozy.',
      k=[('milch_vertragen', ['nie toleruję laktozy', 'laktozy', 'mleka'])]),
 dict(kat='health_emergency', de='Was ist da drin?', pl='Co jest w środku?',
      k=[('was_drin', ['co jest w środku', 'w środku', 'skład'])]),
 dict(kat='health_emergency', de='Ich habe mein Allergiemedikament dabei.', pl='Mam ze sobą lek na alergię.',
      k=[('allergiemedikament', ['lek na alergię', 'na alergię'])]),
 dict(kat='health_emergency', de='Das ist für mich sehr gefährlich.', pl='To jest dla mnie bardzo niebezpieczne.',
      k=[('gefaehrlich', ['niebezpieczne', 'bardzo niebezpieczne'])]),
 dict(kat='health_emergency', de='Ist das gefährlich?', pl='Czy to jest niebezpieczne?',
      k=[('gefaehrlich', ['niebezpieczne'])]),
 dict(kat='health_emergency', de='Ich habe meine Versicherungskarte vergessen.', pl='Zapomniałem karty ubezpieczenia.',
      k=[('versicherungskarte', ['karty ubezpieczenia', 'ubezpieczenia', 'ekuz'])],
      h='Die europäische Krankenversicherungskarte heißt in Polen „EKUZ" — '
        'die Rückseite deiner deutschen Karte wird dort akzeptiert.'),
 dict(kat='health_emergency', de='Wie viel kostet das?', pl='Ile to kosztuje?',
      k=[('kosten', ['ile to kosztuje', 'ile kosztuje'])]),
 dict(kat='health_emergency', de='Ich habe eine Versicherung.', pl='Mam ubezpieczenie.',
      k=[('versicherung', ['ubezpieczenie'])]),
 dict(kat='health_emergency', de='Nehmen Sie meine Versicherung?', pl='Czy przyjmujecie moje ubezpieczenie?',
      k=[('versicherung_akzeptiert', ['przyjmujecie', 'ubezpieczenie'])]),
 dict(kat='health_emergency', de='Muss ich vorher bezahlen?', pl='Czy muszę zapłacić z góry?',
      k=[('vorher_bezahlen', ['zapłacić z góry', 'z góry'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir eine Quittung.', pl='Poproszę paragon.',
      k=[('quittung', ['paragon', 'rachunek'])]),
 dict(kat='health_emergency', de='Ich brauche die Quittung für meine Versicherung.', pl='Potrzebuję paragonu do ubezpieczenia.',
      k=[('quittung', ['paragonu', 'paragon', 'rachunek']),
         ('versicherung', ['ubezpieczenia', 'ubezpieczenie'])]),
 dict(kat='health_emergency', de='Kann ich mit dem Handy bezahlen?', pl='Czy mogę zapłacić telefonem?',
      k=[('handy_bezahlen', ['telefonem', 'blikiem', 'telefon'])]),
 dict(kat='health_emergency', de='Nehmen Sie auch Karte?', pl='Czy przyjmujecie karty?',
      k=[('karte', ['karty', 'karta'])]),
 dict(kat='health_emergency', de='Hier ist meine Karte.', pl='Oto moja karta.',
      k=[('meine_karte', ['oto moja karta', 'moja karta', 'karta'])]),
 dict(kat='health_emergency', de='Zuerst anmelden, dann bezahlen?', pl='Najpierw rejestracja, potem płatność?',
      k=[('anmelden', ['rejestracja', 'zarejestrować']),
         ('bezahlen', ['płatność', 'zapłacić'])]),
 dict(kat='health_emergency', de='Wo bekomme ich die Quittung?', pl='Gdzie dostanę paragon?',
      k=[('quittung', ['paragon', 'rachunek'])]),
 dict(kat='health_emergency', de='Wo kann ich bezahlen?', pl='Gdzie mogę zapłacić?',
      k=[('wo_bezahlen', ['gdzie mogę zapłacić', 'zapłacić', 'kasa'])]),
 dict(kat='health_emergency', de='Das ist zu teuer.', pl='To za drogo.',
      k=[('zu_teuer', ['za drogo', 'drogo'])]),
 dict(kat='health_emergency', de='Ich habe nicht genug Geld dabei.', pl='Nie mam przy sobie tyle pieniędzy.',
      k=[('nicht_genug_geld', ['nie mam tyle pieniędzy', 'pieniędzy', 'nie mam'])]),
 dict(kat='health_emergency', de='Reicht das?', pl='Czy to wystarczy?',
      k=[('reicht', ['wystarczy'])]),
 dict(kat='health_emergency', de='Ich habe meine Tabletten vergessen.', pl='Zapomniałem tabletek.',
      k=[('tabletten_vergessen', ['zapomniałem tabletek', 'zapomniałam', 'tabletek'])]),
 dict(kat='health_emergency', de='Wie oft muss ich das Medikament nehmen?', pl='Jak często mam brać ten lek?',
      k=[('medikament_haeufigkeit', ['jak często', 'brać ten lek', 'lek'])]),
 dict(kat='health_emergency', de='Wo ist das Krankenhaus?', pl='Gdzie jest szpital?',
      k=[('krankenhaus', ['szpital'])]),
 dict(kat='health_emergency', de='Ich möchte zum Arzt.', pl='Chcę iść do lekarza.',
      k=[('arzt', ['lekarza', 'lekarz', 'doktora'])],
      h='Im staatlichen System (NFZ) wartet man oft lange; private Praxen '
        '(„prywatnie") nehmen einen meist am selben Tag und kosten '
        'überschaubar.'),
 dict(kat='health_emergency', de='Wo melde ich mich an?', pl='Gdzie jest rejestracja?',
      k=[('anmelden', ['rejestracja', 'zarejestrować się'])]),
 dict(kat='health_emergency', de='Ich möchte mich anmelden.', pl='Chcę się zarejestrować.',
      k=[('anmelden', ['zarejestrować', 'rejestracja'])]),
 dict(kat='health_emergency', de='Ich habe keinen Termin.', pl='Nie mam wizyty.',
      k=[('kein_termin', ['nie mam wizyty', 'wizyty', 'wizyta'])]),
 dict(kat='health_emergency', de='Kann ich einen Termin bekommen?', pl='Czy mogę umówić wizytę?',
      k=[('termin', ['umówić wizytę', 'wizytę', 'wizyta'])]),
 dict(kat='health_emergency', de='Wie lange muss ich warten?', pl='Jak długo muszę czekać?',
      k=[('warten', ['jak długo muszę czekać', 'czekać'])]),
 dict(kat='health_emergency', de='Wie lange dauert das?', pl='Jak długo to potrwa?',
      k=[('dauer', ['jak długo', 'potrwa'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir ein Medikament.', pl='Poproszę jakiś lek.',
      k=[('medikament', ['lek', 'lekarstwo'])]),
 dict(kat='health_emergency', de='Wie nehme ich das Medikament?', pl='Jak mam brać ten lek?',
      k=[('medikament_einnahme', ['jak brać', 'brać ten lek', 'lek'])]),
 dict(kat='health_emergency', de='Wie komme ich dorthin?', pl='Jak tam dojadę?',
      k=[('wie_dorthin', ['jak tam dojadę', 'dojadę', 'jak dojść'])]),
 dict(kat='health_emergency', de='Ich brauche einen Arzt.', pl='Potrzebuję lekarza.',
      k=[('arzt', ['lekarza', 'lekarz'])]),
 dict(kat='health_emergency', de='Wo ist die nächste Apotheke?', pl='Gdzie jest najbliższa apteka?',
      k=[('apotheke', ['apteka'])],
      h='In größeren Städten gibt es „apteka całodobowa" — rund um die Uhr '
        'geöffnet.'),
 dict(kat='health_emergency', de='Ich brauche dringend Hilfe.', pl='Pilnie potrzebuję pomocy.',
      k=[('dringend_hilfe', ['pilnie potrzebuję pomocy', 'pilnie', 'pomocy'])]),
 dict(kat='health_emergency', de='Wo ist das nächste Krankenhaus?', pl='Gdzie jest najbliższy szpital?',
      k=[('krankenhaus', ['szpital'])]),
 dict(kat='health_emergency', de='Bitte helfen Sie mir!', pl='Proszę mi pomóc!',
      k=[('helfen', ['proszę mi pomóc', 'pomóc', 'pomocy'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie einen Krankenwagen!', pl='Proszę wezwać karetkę!',
      k=[('krankenwagen', ['karetkę', 'karetka', 'pogotowie'])],
      h='„Karetka" ist der Wagen, „pogotowie" der Rettungsdienst — beides '
        'wird verstanden.'),
 dict(kat='health_emergency', de='Ist der Krankenwagen schon unterwegs?', pl='Czy karetka już jedzie?',
      k=[('krankenwagen', ['karetka', 'pogotowie']),
         ('unterwegs', ['już jedzie', 'jedzie'])]),
 dict(kat='health_emergency', de='Jemand ist verletzt.', pl='Ktoś jest ranny.',
      k=[('verletzt', ['ranny', 'ranna', 'poszkodowany'])]),
 dict(kat='health_emergency', de='Ich bin verletzt.', pl='Jestem ranny.',
      k=[('verletzt', ['ranny', 'ranna'])]),
 dict(kat='health_emergency', de='Schnell, bitte!', pl='Szybko, proszę!',
      k=[('schnell', ['szybko', 'prędko'])]),
 dict(kat='health_emergency', de='Ich brauche etwas aus der Apotheke.', pl='Potrzebuję czegoś z apteki.',
      k=[('apotheke', ['apteki', 'apteka'])]),
 dict(kat='health_emergency', de='Ich bin allein hier.', pl='Jestem tu sam.',
      k=[('allein', ['sam', 'sama'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie meinen Freund an.', pl='Proszę zadzwonić do mojego kolegi.',
      k=[('anrufen', ['zadzwonić']),
         ('freund', ['kolegi', 'kolega', 'przyjaciela'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie die Polizei!', pl='Proszę wezwać policję!',
      k=[('polizei', ['policję', 'policja'])]),
 dict(kat='health_emergency', de='Ich möchte die Polizei rufen.', pl='Chcę wezwać policję.',
      k=[('polizei', ['policję', 'policja'])]),
 dict(kat='health_emergency', de='Mir geht es nicht gut.', pl='Źle się czuję.',
      k=[('nicht_gut', ['źle się czuję', 'źle', 'niedobrze'])]),
 dict(kat='health_emergency', de='Ich habe Kopfschmerzen.', pl='Boli mnie głowa.',
      k=[('kopfschmerzen', ['boli mnie głowa', 'głowa'])],
      h='Wörtlich „mich schmerzt der Kopf" — das Körperteil ist das Subjekt, '
        'wie im Russischen. Nach demselben Muster: boli mnie brzuch (Bauch), '
        'gardło (Hals).'),
 dict(kat='health_emergency', de='Ich habe Fieber.', pl='Mam gorączkę.',
      k=[('fieber', ['gorączkę', 'gorączka', 'temperaturę'])]),
 dict(kat='health_emergency', de='Ich habe mir den Fuß verletzt.', pl='Zraniłem sobie stopę.',
      k=[('fuss_verletzt', ['zraniłem stopę', 'zraniłam', 'stopę'])]),
 dict(kat='health_emergency', de='Ich fühle mich schwindelig.', pl='Kręci mi się w głowie.',
      k=[('schwindelig', ['kręci mi się w głowie', 'kręci się', 'zawroty'])]),
 dict(kat='health_emergency', de='Ich bin krank.', pl='Jestem chory.',
      k=[('krank', ['chory', 'chora'])]),
 dict(kat='health_emergency', de='Ich bin erkältet.', pl='Jestem przeziębiony.',
      k=[('erkaeltet', ['przeziębiony', 'przeziębiona', 'przeziębienie'])]),
 dict(kat='health_emergency', de='Ich habe Bauchschmerzen.', pl='Boli mnie brzuch.',
      k=[('bauchschmerzen', ['boli mnie brzuch', 'brzuch'])]),
 dict(kat='health_emergency', de='Mein Bein tut weh.', pl='Boli mnie noga.',
      k=[('bein_weh', ['boli mnie noga', 'noga'])]),
 dict(kat='health_emergency', de='Hier tut es weh.', pl='Tutaj boli.',
      k=[('hier_weh', ['tutaj boli', 'boli'])]),
 dict(kat='health_emergency', de='Mir geht es sehr schlecht.', pl='Czuję się bardzo źle.',
      k=[('sehr_schlecht', ['bardzo źle', 'źle'])]),
 dict(kat='health_emergency', de='Ich bin sehr müde.', pl='Jestem bardzo zmęczony.',
      k=[('muede', ['zmęczony', 'zmęczona'])]),
 dict(kat='health_emergency', de='Mir ist kalt.', pl='Jest mi zimno.',
      k=[('kalt', ['jest mi zimno', 'zimno'])],
      h='Wie im Russischen ein Dativ: „jest mi zimno" — mir ist kalt. „Jestem '
        'zimny" hieße, du seist ein kalter Mensch.'),
 dict(kat='health_emergency', de='Seit gestern.', pl='Od wczoraj.',
      k=[('seit_gestern', ['od wczoraj', 'wczoraj'])]),
 dict(kat='health_emergency', de='Seit heute Morgen.', pl='Od dzisiejszego rana.',
      k=[('seit_heute_morgen', ['od dzisiejszego rana', 'od rana', 'rana'])]),
 dict(kat='health_emergency', de='Rufen Sie bitte 112 an.', pl='Proszę zadzwonić na 112.',
      neu=True, sz='health_notfall',
      k=[('notruf', ['112', 'sto dwanaście', '999'])],
      h='112 ist der europäische Notruf und deckt in Polen alles ab. Die alte '
        '999 (pogotowie ratunkowe) funktioniert daneben weiter, ebenso 998 '
        '(Feuerwehr) und 997 (Polizei).'),
 dict(kat='health_emergency', de='Ich spreche kein Polnisch. Können Sie es aufschreiben?',
      pl='Nie mówię po polsku. Czy może pan to zapisać?',
      neu=True, sz='health_krankenhaus',
      k=[('kein_polnisch', ['nie mówię po polsku', 'nie mówię']),
         ('aufschreiben', ['zapisać', 'napisać'])]),

# ================================================================== job_work
 dict(kat='job_work', de='Ich kann heute nicht kommen.', pl='Nie mogę dzisiaj przyjść.',
      k=[('nicht_koennen', ['nie mogę']),
         ('heute', ['dzisiaj', 'dziś']),
         ('kommen', ['przyjść'])]),
 dict(kat='job_work', de='Ich bin krank und bleibe zu Hause.', pl='Jestem chory i zostaję w domu.',
      k=[('krank', ['chory', 'chora']),
         ('zu_hause', ['w domu', 'zostaję w domu'])],
      h='Krankschreibungen laufen in Polen elektronisch („e-zwolnienie") — '
        'der Arzt schickt sie direkt an den Arbeitgeber, du bekommst nichts '
        'in die Hand.'),
 dict(kat='job_work', de='Ich komme später.', pl='Przyjdę później.',
      k=[('kommen', ['przyjdę']),
         ('spaeter', ['później'])]),
 dict(kat='job_work', de='Ich brauche einen Tag frei.', pl='Potrzebuję dnia wolnego.',
      k=[('brauchen', ['potrzebuję']),
         ('tag_frei', ['dnia wolnego', 'wolne', 'dzień wolny'])]),
 dict(kat='job_work', de='Ich habe einen Arzttermin.', pl='Mam wizytę u lekarza.',
      k=[('arzttermin', ['wizytę u lekarza', 'u lekarza', 'wizytę'])]),
 dict(kat='job_work', de='Ich habe schon in einem Restaurant gearbeitet.', pl='Pracowałem już w restauracji.',
      k=[('gearbeitet', ['pracowałem', 'pracowałam']),
         ('restaurant', ['restauracji', 'restauracja'])]),
 dict(kat='job_work', de='Ich habe keine Erfahrung.', pl='Nie mam doświadczenia.',
      k=[('keine', ['nie mam']),
         ('erfahrung', ['doświadczenia', 'doświadczenie'])]),
 dict(kat='job_work', de='Ich lerne schnell.', pl='Szybko się uczę.',
      k=[('lernen', ['się uczę', 'uczę']),
         ('schnell', ['szybko'])]),
 dict(kat='job_work', de='Ich kann am Wochenende arbeiten.', pl='Mogę pracować w weekendy.',
      k=[('koennen', ['mogę']),
         ('wochenende', ['w weekendy', 'weekend']),
         ('arbeiten', ['pracować'])]),
 dict(kat='job_work', de='Wann kann ich anfangen?', pl='Kiedy mogę zacząć?',
      k=[('wann', ['kiedy']),
         ('anfangen', ['zacząć'])]),
 dict(kat='job_work', de='Brauche ich eine Arbeitserlaubnis?', pl='Czy potrzebuję pozwolenia na pracę?',
      k=[('brauchen', ['potrzebuję', 'czy potrzebuję']),
         ('arbeitserlaubnis', ['pozwolenia na pracę', 'pozwolenie'])],
      h='Als EU-Bürger brauchst du keine Arbeitserlaubnis, aber eine '
        'Steuernummer („PESEL" oder „NIP") — ohne die läuft nichts.'),
 dict(kat='job_work', de='Ich bin neu hier.', pl='Jestem tu nowy.',
      k=[('neu', ['nowy', 'nowa']),
         ('hier', ['tu', 'tutaj'])]),
 dict(kat='job_work', de='Kannst du mir kurz helfen?', pl='Możesz mi pomóc?',
      k=[('koennen', ['możesz']),
         ('helfen', ['pomóc', 'mi pomóc'])]),
 dict(kat='job_work', de='Wie macht man das?', pl='Jak się to robi?',
      k=[('wie', ['jak']),
         ('machen', ['się to robi', 'robi'])]),
 dict(kat='job_work', de='Das habe ich noch nie gemacht.', pl='Nigdy tego nie robiłem.',
      k=[('nie', ['nigdy']),
         ('gemacht', ['nie robiłem', 'robiłem', 'robiłam'])]),
 dict(kat='job_work', de='Wo finde ich das?', pl='Gdzie to znajdę?',
      k=[('wo', ['gdzie']),
         ('finden', ['znajdę'])]),
 dict(kat='job_work', de='Ich mache Pause.', pl='Robię przerwę.',
      k=[('pause', ['przerwę', 'przerwa'])]),
 dict(kat='job_work', de='Danke für deine Hilfe.', pl='Dziękuję za pomoc.',
      k=[('danke', ['dziękuję', 'dzięki']),
         ('hilfe', ['za pomoc', 'pomoc'])]),
 dict(kat='job_work', de='Kann ich Ihnen helfen?', pl='Czy mogę pomóc?',
      k=[('koennen', ['czy mogę', 'mogę']),
         ('helfen', ['pomóc'])],
      h='Im Laden hört man „w czym mogę pomóc?" — wörtlich „worin kann ich '
        'helfen?"'),
 dict(kat='job_work', de='Der Nächste, bitte!', pl='Następny, proszę!',
      k=[('naechste', ['następny', 'następna'])]),
 dict(kat='job_work', de='Möchten Sie noch etwas?', pl='Czy coś jeszcze?',
      k=[('moechten', ['czy coś', 'życzy pan']),
         ('noch_etwas', ['coś jeszcze', 'jeszcze'])]),
 dict(kat='job_work', de='Zahlen Sie bar oder mit Karte?', pl='Gotówką czy kartą?',
      k=[('bar', ['gotówką', 'gotówka']),
         ('karte', ['kartą', 'karta'])]),
 dict(kat='job_work', de='Tut mir leid, das haben wir nicht.', pl='Przykro mi, nie mamy tego.',
      k=[('leid', ['przykro mi', 'niestety']),
         ('nicht_haben', ['nie mamy', 'nie ma'])]),
 dict(kat='job_work', de='Ich hole meinen Kollegen.', pl='Zawołam kolegę.',
      k=[('holen', ['zawołam', 'zawołać']),
         ('kollege', ['kolegę', 'kolega'])]),
 dict(kat='job_work', de='Kommen Sie gerne wieder!', pl='Zapraszamy ponownie!',
      k=[('wiederkommen', ['zapraszamy ponownie', 'zapraszamy'])]),
 dict(kat='job_work', de='Wie viel verdiene ich pro Stunde?', pl='Ile zarabiam na godzinę?',
      k=[('verdienen', ['zarabiam', 'zarabiać']),
         ('stunde', ['na godzinę', 'godzinę'])],
      h='Polen hat einen gesetzlichen Stundenmindestlohn („minimalna stawka '
        'godzinowa"), der auch für Werkverträge gilt.'),
 dict(kat='job_work', de='Wann bekomme ich mein Geld?', pl='Kiedy dostanę wypłatę?',
      k=[('wann', ['kiedy']),
         ('geld', ['wypłatę', 'wypłata', 'pieniądze'])]),
 dict(kat='job_work', de='Werde ich bar bezahlt?', pl='Czy dostanę wypłatę gotówką?',
      k=[('bar', ['gotówką', 'gotówka']),
         ('bezahlt', ['wypłatę', 'dostanę'])]),
 dict(kat='job_work', de='Ich habe zehn Stunden gearbeitet.', pl='Pracowałem dziesięć godzin.',
      k=[('zehn', ['dziesięć']),
         ('stunden', ['godzin', 'godziny']),
         ('gearbeitet', ['pracowałem', 'pracowałam'])]),
 dict(kat='job_work', de='Wann fange ich an?', pl='Kiedy zaczynam?',
      k=[('wann', ['kiedy']),
         ('anfangen', ['zaczynam', 'zacząć'])]),
 dict(kat='job_work', de='Wann habe ich frei?', pl='Kiedy mam wolne?',
      k=[('wann', ['kiedy']),
         ('frei', ['wolne'])]),
 dict(kat='job_work', de='Wie lange dauert die Schicht?', pl='Ile trwa zmiana?',
      k=[('wie_lange', ['ile trwa', 'ile']),
         ('schicht', ['zmiana', 'zmianę'])]),
 dict(kat='job_work', de='Kann ich am Montag frei haben?', pl='Czy mogę mieć wolne w poniedziałek?',
      k=[('montag', ['poniedziałek']),
         ('frei', ['wolne'])]),
 dict(kat='job_work', de='Kann ich die Schicht tauschen?', pl='Czy mogę zamienić się zmianą?',
      k=[('schicht', ['zmianą', 'zmiana']),
         ('tauschen', ['zamienić się', 'zamienić'])]),
 dict(kat='job_work', de='Ich komme morgen früher.', pl='Jutro przyjdę wcześniej.',
      k=[('morgen', ['jutro']),
         ('frueher', ['wcześniej'])]),
 dict(kat='job_work', de='Wo ist der Dienstplan?', pl='Gdzie jest grafik?',
      k=[('wo', ['gdzie']),
         ('dienstplan', ['grafik', 'harmonogram'])],
      h='„Grafik" ist der Dienstplan — nicht die Grafik im deutschen Sinn. '
        'Einer der häufigsten falschen Freunde im polnischen Arbeitsalltag.'),
 dict(kat='job_work', de='Ich suche Arbeit.', pl='Szukam pracy.',
      k=[('suchen', ['szukam']),
         ('arbeit', ['pracy', 'praca'])]),
 dict(kat='job_work', de='Suchen Sie noch Leute?', pl='Czy szukacie jeszcze ludzi?',
      k=[('suchen', ['szukacie', 'szukać']),
         ('leute', ['ludzi', 'pracowników'])]),
 dict(kat='job_work', de='Haben Sie eine Stelle frei?', pl='Czy jest wolny etat?',
      k=[('stelle', ['etat', 'stanowisko', 'praca']),
         ('frei', ['wolny', 'wolne'])]),
 dict(kat='job_work', de='Brauchen Sie Hilfe in der Küche?', pl='Czy potrzebujecie pomocy w kuchni?',
      k=[('brauchen', ['potrzebujecie', 'potrzeba']),
         ('hilfe', ['pomocy', 'pomoc']),
         ('kueche', ['w kuchni', 'kuchnia'])]),
 dict(kat='job_work', de='Ich kann sofort anfangen.', pl='Mogę zacząć od zaraz.',
      k=[('koennen', ['mogę']),
         ('sofort', ['od zaraz', 'zaraz', 'natychmiast']),
         ('anfangen', ['zacząć'])]),
 dict(kat='job_work', de='Ich bin für drei Monate hier.', pl='Jestem tu na trzy miesiące.',
      k=[('drei_monate', ['trzy miesiące', 'na trzy miesiące']),
         ('hier', ['tu', 'tutaj'])]),
]

AUSGELASSEN = [
    # 120 ist der CHINESISCHE Rettungsdienst - in Polen die 112 (999 fuer
    # den Rettungsdienst gilt daneben weiter). Ersetzt.
    'Rufen Sie bitte 120 an.',
    # Den Gegensatz westliche Medizin / TCM gibt es in Polen nicht.
    'Ich möchte westliche Medizin.',
    'Ist das westliche Medizin?',
    # Zielsprache steht im Satz - ersetzt durch die polnische Fassung.
    'Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
]
