# -*- coding: utf-8 -*-
"""Gesundheit/Notfall und Job auf Italienisch.

Zusammen 118 Master-Saetze - health_emergency (76), job_work (42).

**VIER SAETZE SIND CHINA-SPEZIFISCH und wandern NICHT woertlich mit.**
Sie stammen aus dem chinesischen Ausbau und stehen im Master, weil Deutsch
und Chinesisch sie teilen. Woertlich uebersetzt waeren sie hier zwischen
sinnlos und gefaehrlich:

  Rufen Sie bitte 120 an.     **120 ist der chinesische Rettungsdienst.**
                              In Italien ist es die 112 (europaeische
                              Notrufnummer, loest auch Krankenwagen aus;
                              die alte 118 gilt vielerorts noch parallel).
                              Einem Reisenden im Notfall die falsche Nummer
                              beizubringen, ist der eine Fehler, den diese
                              Kategorie nicht machen darf - deshalb
                              ausgelassen und durch die richtige Nummer
                              ersetzt (`neu=True`).
  Ich moechte westliche       Der Gegensatz westliche Medizin / TCM
  Medizin.                    existiert in Italien nicht. Beide Saetze
  Ist das westliche Medizin?  ersatzlos ausgelassen - es gibt keine Frage,
                              die sie hier beantworten wuerden.
  Ich spreche kein            Zielsprache im Satz, wie im Grundwortschatz -
  Chinesisch. ...             durch die italienische Fassung ersetzt.

**116 Saetze uebersetzt, 4 ausgelassen, 2 neu.**

**Nachschlage-Saetze** (`lookup_only` im Master) sind die Notfall-Saetze,
die man nicht auswendig koennen muss, sondern im Ernstfall vorzeigt. Sie
werden mit uebersetzt - der Master entscheidet ueber das Kennzeichen, nicht
diese Datei.

**Du oder Sie:** Arzt, Apotheke, Amt und Kundengespraech auf `Lei`,
Kollegen unter sich auf `tu`. Bei "Kann ich Ihnen helfen?" ist das `Lei`
zwingend - es ist der Satz zum Kunden.

**Nicht von Muttersprachlern geprueft.**
"""

KATEGORIEN = ['health_emergency', 'job_work']

SAETZE = [

# ========================================================== health_emergency
 dict(kat='health_emergency', de='Ich bin allergisch gegen Penizillin.', it='Sono allergico alla penicillina.',
      k=[('allergisch', ['allergico', 'allergica']),
         ('penizillin', ['penicillina'])]),
 dict(kat='health_emergency', de='Ich habe eine Allergie.', it='Ho un\'allergia.',
      k=[('allergie', ['allergia'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen dieses Medikament.', it='Sono allergico a questo farmaco.',
      k=[('allergisch', ['allergico', 'allergica']),
         ('medikament', ['farmaco', 'medicina', 'medicinale'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen Erdnüsse.', it='Sono allergico alle arachidi.',
      k=[('allergisch', ['allergico', 'allergica']),
         ('erdnuesse', ['arachidi', 'noccioline'])]),
 dict(kat='health_emergency', de='Ich kann keine Erdnüsse essen.', it='Non posso mangiare le arachidi.',
      k=[('nicht_essen', ['non posso mangiare', 'non posso']),
         ('erdnuesse', ['arachidi', 'noccioline'])]),
 dict(kat='health_emergency', de='Sind da Erdnüsse drin?', it='Ci sono arachidi dentro?',
      k=[('erdnuesse', ['arachidi', 'noccioline'])]),
 dict(kat='health_emergency', de='Bitte ohne Erdnüsse.', it='Senza arachidi, per favore.',
      k=[('ohne', ['senza']),
         ('erdnuesse', ['arachidi', 'noccioline'])]),
 dict(kat='health_emergency', de='Bitte ohne Milch.', it='Senza latte, per favore.',
      k=[('ohne', ['senza']),
         ('milch', ['latte'])]),
 dict(kat='health_emergency', de='Ich vertrage keine Milch.', it='Sono intollerante al lattosio.',
      k=[('milch_vertragen', ['intollerante al lattosio', 'lattosio', 'latte'])],
      h='„Intollerante al lattosio" ist der Begriff, den jeder Kellner '
        'sofort einordnet — er steht in Italien auf vielen Speisekarten '
        'als Kennzeichnung.'),
 dict(kat='health_emergency', de='Was ist da drin?', it='Cosa c\'è dentro?',
      k=[('was_drin', ['cosa c\'è dentro', 'cosa c\'è', 'ingredienti'])]),
 dict(kat='health_emergency', de='Ich habe mein Allergiemedikament dabei.', it='Ho con me il mio farmaco per l\'allergia.',
      k=[('allergiemedikament', ['farmaco per l\'allergia', 'medicina per l\'allergia', 'antistaminico'])]),
 dict(kat='health_emergency', de='Das ist für mich sehr gefährlich.', it='Per me è molto pericoloso.',
      k=[('gefaehrlich', ['molto pericoloso', 'pericoloso'])]),
 dict(kat='health_emergency', de='Ist das gefährlich?', it='È pericoloso?',
      k=[('gefaehrlich', ['pericoloso'])]),
 dict(kat='health_emergency', de='Ich habe meine Versicherungskarte vergessen.', it='Ho dimenticato la tessera sanitaria.',
      k=[('versicherungskarte', ['tessera sanitaria', 'tessera', 'assicurazione'])],
      h='Die „tessera sanitaria" ist die italienische Gesundheitskarte. Als '
        'EU-Reisender zeigst du stattdessen die europäische '
        'Krankenversicherungskarte („TEAM") — die Rückseite deiner '
        'deutschen Karte.'),
 dict(kat='health_emergency', de='Wie viel kostet das?', it='Quanto costa?',
      k=[('kosten', ['quanto costa'])]),
 dict(kat='health_emergency', de='Ich habe eine Versicherung.', it='Ho un\'assicurazione.',
      k=[('versicherung', ['assicurazione'])]),
 dict(kat='health_emergency', de='Nehmen Sie meine Versicherung?', it='Accettate la mia assicurazione?',
      k=[('versicherung_akzeptiert', ['accettate', 'assicurazione'])]),
 dict(kat='health_emergency', de='Muss ich vorher bezahlen?', it='Devo pagare prima?',
      k=[('vorher_bezahlen', ['pagare prima', 'prima'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir eine Quittung.', it='Mi dia una ricevuta, per favore.',
      k=[('quittung', ['ricevuta', 'scontrino'])]),
 dict(kat='health_emergency', de='Ich brauche die Quittung für meine Versicherung.', it='Mi serve la ricevuta per l\'assicurazione.',
      k=[('quittung', ['ricevuta', 'scontrino']),
         ('versicherung', ['assicurazione'])]),
 dict(kat='health_emergency', de='Kann ich mit dem Handy bezahlen?', it='Posso pagare con il telefono?',
      k=[('handy_bezahlen', ['con il telefono', 'telefono'])]),
 dict(kat='health_emergency', de='Nehmen Sie auch Karte?', it='Accettate anche la carta?',
      k=[('karte', ['carta'])]),
 dict(kat='health_emergency', de='Hier ist meine Karte.', it='Ecco la mia carta.',
      k=[('meine_karte', ['ecco la mia carta', 'la mia carta', 'carta'])]),
 dict(kat='health_emergency', de='Zuerst anmelden, dann bezahlen?', it='Prima l\'accettazione, poi il pagamento?',
      k=[('anmelden', ['accettazione', 'registrarsi']),
         ('bezahlen', ['pagamento', 'pagare'])]),
 dict(kat='health_emergency', de='Wo bekomme ich die Quittung?', it='Dove ritiro la ricevuta?',
      k=[('quittung', ['ricevuta', 'scontrino'])]),
 dict(kat='health_emergency', de='Wo kann ich bezahlen?', it='Dove posso pagare?',
      k=[('wo_bezahlen', ['dove posso pagare', 'pagare'])]),
 dict(kat='health_emergency', de='Das ist zu teuer.', it='È troppo caro.',
      k=[('zu_teuer', ['troppo caro'])]),
 dict(kat='health_emergency', de='Ich habe nicht genug Geld dabei.', it='Non ho abbastanza soldi con me.',
      k=[('nicht_genug_geld', ['non ho abbastanza soldi', 'abbastanza soldi', 'soldi'])]),
 dict(kat='health_emergency', de='Reicht das?', it='Basta così?',
      k=[('reicht', ['basta', 'basta così'])]),
 dict(kat='health_emergency', de='Ich habe meine Tabletten vergessen.', it='Ho dimenticato le mie pastiglie.',
      k=[('tabletten_vergessen', ['dimenticato le pastiglie', 'pastiglie', 'pillole'])]),
 dict(kat='health_emergency', de='Wie oft muss ich das Medikament nehmen?', it='Quante volte devo prendere il farmaco?',
      k=[('medikament_haeufigkeit', ['quante volte', 'prendere il farmaco', 'farmaco'])]),
 dict(kat='health_emergency', de='Wo ist das Krankenhaus?', it='Dov\'è l\'ospedale?',
      k=[('krankenhaus', ['ospedale'])]),
 dict(kat='health_emergency', de='Ich möchte zum Arzt.', it='Vorrei vedere un medico.',
      k=[('arzt', ['medico', 'dottore'])]),
 dict(kat='health_emergency', de='Wo melde ich mich an?', it='Dove devo registrarmi?',
      k=[('anmelden', ['registrarmi', 'accettazione'])]),
 dict(kat='health_emergency', de='Ich möchte mich anmelden.', it='Vorrei registrarmi.',
      k=[('anmelden', ['registrarmi', 'accettazione'])]),
 dict(kat='health_emergency', de='Ich habe keinen Termin.', it='Non ho un appuntamento.',
      k=[('kein_termin', ['non ho un appuntamento', 'appuntamento'])]),
 dict(kat='health_emergency', de='Kann ich einen Termin bekommen?', it='Posso avere un appuntamento?',
      k=[('termin', ['appuntamento'])]),
 dict(kat='health_emergency', de='Wie lange muss ich warten?', it='Quanto devo aspettare?',
      k=[('warten', ['quanto devo aspettare', 'aspettare'])]),
 dict(kat='health_emergency', de='Wie lange dauert das?', it='Quanto tempo ci vuole?',
      k=[('dauer', ['quanto tempo', 'ci vuole'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir ein Medikament.', it='Mi dia una medicina, per favore.',
      k=[('medikament', ['medicina', 'farmaco'])]),
 dict(kat='health_emergency', de='Wie nehme ich das Medikament?', it='Come devo prendere questa medicina?',
      k=[('medikament_einnahme', ['come devo prendere', 'prendere', 'medicina'])]),
 dict(kat='health_emergency', de='Wie komme ich dorthin?', it='Come ci arrivo?',
      k=[('wie_dorthin', ['come ci arrivo', 'come arrivo'])]),
 dict(kat='health_emergency', de='Ich brauche einen Arzt.', it='Ho bisogno di un medico.',
      k=[('arzt', ['medico', 'dottore'])]),
 dict(kat='health_emergency', de='Wo ist die nächste Apotheke?', it='Dov\'è la farmacia più vicina?',
      k=[('apotheke', ['farmacia'])],
      h='Italienische Apotheken erkennt man am grünen Kreuz. Nachts und '
        'sonntags hat immer eine „farmacia di turno" offen — welche, steht '
        'an jeder geschlossenen Apotheke aushängend.'),
 dict(kat='health_emergency', de='Ich brauche dringend Hilfe.', it='Ho bisogno di aiuto urgente.',
      k=[('dringend_hilfe', ['aiuto urgente', 'urgente', 'aiuto'])]),
 dict(kat='health_emergency', de='Wo ist das nächste Krankenhaus?', it='Dov\'è l\'ospedale più vicino?',
      k=[('krankenhaus', ['ospedale'])]),
 dict(kat='health_emergency', de='Bitte helfen Sie mir!', it='Mi aiuti, per favore!',
      k=[('helfen', ['mi aiuti', 'aiuto', 'aiutatemi'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie einen Krankenwagen!', it='Chiami un\'ambulanza, per favore!',
      k=[('krankenwagen', ['ambulanza'])]),
 dict(kat='health_emergency', de='Ist der Krankenwagen schon unterwegs?', it='L\'ambulanza sta già arrivando?',
      k=[('krankenwagen', ['ambulanza']),
         ('unterwegs', ['sta arrivando', 'arrivando'])]),
 dict(kat='health_emergency', de='Jemand ist verletzt.', it='C\'è un ferito.',
      k=[('verletzt', ['ferito', 'c\'è un ferito'])]),
 dict(kat='health_emergency', de='Ich bin verletzt.', it='Sono ferito.',
      k=[('verletzt', ['ferito', 'ferita'])]),
 dict(kat='health_emergency', de='Schnell, bitte!', it='Presto, per favore!',
      k=[('schnell', ['presto', 'veloce', 'subito'])]),
 dict(kat='health_emergency', de='Ich brauche etwas aus der Apotheke.', it='Mi serve qualcosa in farmacia.',
      k=[('apotheke', ['farmacia'])]),
 dict(kat='health_emergency', de='Ich bin allein hier.', it='Sono qui da solo.',
      k=[('allein', ['da solo', 'da sola', 'solo'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie meinen Freund an.', it='Chiami il mio amico, per favore.',
      k=[('anrufen', ['chiami', 'chiamare']),
         ('freund', ['il mio amico', 'amico'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie die Polizei!', it='Chiami la polizia, per favore!',
      k=[('polizei', ['polizia'])]),
 dict(kat='health_emergency', de='Ich möchte die Polizei rufen.', it='Voglio chiamare la polizia.',
      k=[('polizei', ['polizia'])]),
 dict(kat='health_emergency', de='Mir geht es nicht gut.', it='Non mi sento bene.',
      k=[('nicht_gut', ['non mi sento bene', 'non sto bene'])]),
 dict(kat='health_emergency', de='Ich habe Kopfschmerzen.', it='Ho mal di testa.',
      k=[('kopfschmerzen', ['mal di testa'])],
      h='Schmerzen laufen im Italienischen über „ho mal di ..." — Kopf '
        '(testa), Bauch (pancia), Hals (gola), Zähne (denti). Ein Muster für '
        'alle Fälle.'),
 dict(kat='health_emergency', de='Ich habe Fieber.', it='Ho la febbre.',
      k=[('fieber', ['febbre'])]),
 dict(kat='health_emergency', de='Ich habe mir den Fuß verletzt.', it='Mi sono fatto male al piede.',
      k=[('fuss_verletzt', ['male al piede', 'piede', 'fatto male'])]),
 dict(kat='health_emergency', de='Ich fühle mich schwindelig.', it='Mi gira la testa.',
      k=[('schwindelig', ['mi gira la testa', 'gira la testa', 'capogiro'])]),
 dict(kat='health_emergency', de='Ich bin krank.', it='Sono malato.',
      k=[('krank', ['malato', 'malata'])]),
 dict(kat='health_emergency', de='Ich bin erkältet.', it='Ho il raffreddore.',
      k=[('erkaeltet', ['raffreddore'])]),
 dict(kat='health_emergency', de='Ich habe Bauchschmerzen.', it='Ho mal di pancia.',
      k=[('bauchschmerzen', ['mal di pancia', 'mal di stomaco'])]),
 dict(kat='health_emergency', de='Mein Bein tut weh.', it='Mi fa male la gamba.',
      k=[('bein_weh', ['mi fa male la gamba', 'gamba'])]),
 dict(kat='health_emergency', de='Hier tut es weh.', it='Mi fa male qui.',
      k=[('hier_weh', ['mi fa male qui', 'fa male qui', 'qui'])]),
 dict(kat='health_emergency', de='Mir geht es sehr schlecht.', it='Sto molto male.',
      k=[('sehr_schlecht', ['sto molto male', 'molto male'])]),
 dict(kat='health_emergency', de='Ich bin sehr müde.', it='Sono molto stanco.',
      k=[('muede', ['stanco', 'stanca'])]),
 dict(kat='health_emergency', de='Mir ist kalt.', it='Ho freddo.',
      k=[('kalt', ['ho freddo', 'freddo'])],
      h='„Ho freddo" (ich habe Kälte) — wie beim Alter läuft auch das '
        'Befinden über „avere", nicht über „essere". „Sono freddo" hieße, '
        'du seist ein kühler Typ.'),
 dict(kat='health_emergency', de='Seit gestern.', it='Da ieri.',
      k=[('seit_gestern', ['da ieri', 'ieri'])]),
 dict(kat='health_emergency', de='Seit heute Morgen.', it='Da stamattina.',
      k=[('seit_heute_morgen', ['da stamattina', 'stamattina'])]),
 dict(kat='health_emergency', de='Rufen Sie bitte 112 an.', it='Chiami il 112, per favore.',
      neu=True, sz='health_notfall',
      k=[('notruf', ['112', 'cento dodici'])],
      h='112 ist die europäische Notrufnummer und gilt in ganz Italien für '
        'Polizei, Feuerwehr und Krankenwagen. Die alte Nummer 118 (nur '
        'Rettungsdienst) funktioniert vielerorts noch, 112 ist die sichere '
        'Wahl.'),
 dict(kat='health_emergency', de='Ich spreche kein Italienisch. Können Sie es aufschreiben?',
      it='Non parlo italiano. Può scriverlo?',
      neu=True, sz='health_krankenhaus',
      k=[('kein_italienisch', ['non parlo italiano', 'non parlo']),
         ('aufschreiben', ['scriverlo', 'scrivere'])]),

# ================================================================== job_work
 dict(kat='job_work', de='Ich kann heute nicht kommen.', it='Oggi non posso venire.',
      k=[('nicht_koennen', ['non posso']),
         ('heute', ['oggi']),
         ('kommen', ['venire'])]),
 dict(kat='job_work', de='Ich bin krank und bleibe zu Hause.', it='Sono malato e resto a casa.',
      k=[('krank', ['malato', 'malata']),
         ('zu_hause', ['a casa', 'resto a casa'])]),
 dict(kat='job_work', de='Ich komme später.', it='Arrivo più tardi.',
      k=[('kommen', ['arrivo', 'vengo']),
         ('spaeter', ['più tardi', 'tardi'])]),
 dict(kat='job_work', de='Ich brauche einen Tag frei.', it='Ho bisogno di un giorno libero.',
      k=[('brauchen', ['ho bisogno', 'mi serve']),
         ('tag_frei', ['giorno libero', 'libero'])]),
 dict(kat='job_work', de='Ich habe einen Arzttermin.', it='Ho un appuntamento dal medico.',
      k=[('arzttermin', ['appuntamento dal medico', 'dal medico', 'appuntamento'])]),
 dict(kat='job_work', de='Ich habe schon in einem Restaurant gearbeitet.', it='Ho già lavorato in un ristorante.',
      k=[('gearbeitet', ['ho lavorato', 'lavorato']),
         ('restaurant', ['ristorante'])]),
 dict(kat='job_work', de='Ich habe keine Erfahrung.', it='Non ho esperienza.',
      k=[('keine', ['non ho']),
         ('erfahrung', ['esperienza'])]),
 dict(kat='job_work', de='Ich lerne schnell.', it='Imparo in fretta.',
      k=[('lernen', ['imparo', 'imparare']),
         ('schnell', ['in fretta', 'velocemente', 'presto'])]),
 dict(kat='job_work', de='Ich kann am Wochenende arbeiten.', it='Posso lavorare nel weekend.',
      k=[('koennen', ['posso']),
         ('wochenende', ['weekend', 'fine settimana']),
         ('arbeiten', ['lavorare'])]),
 dict(kat='job_work', de='Wann kann ich anfangen?', it='Quando posso iniziare?',
      k=[('wann', ['quando']),
         ('anfangen', ['iniziare', 'cominciare'])]),
 dict(kat='job_work', de='Brauche ich eine Arbeitserlaubnis?', it='Mi serve un permesso di lavoro?',
      k=[('brauchen', ['mi serve', 'ho bisogno']),
         ('arbeitserlaubnis', ['permesso di lavoro', 'permesso'])],
      h='Als EU-Bürger brauchst du in Italien keine Arbeitserlaubnis, aber '
        'eine Steuernummer („codice fiscale") — ohne die stellt dich '
        'niemand ein. Sie ist kostenlos und schnell zu bekommen.'),
 dict(kat='job_work', de='Ich bin neu hier.', it='Sono nuovo qui.',
      k=[('neu', ['nuovo', 'nuova']),
         ('hier', ['qui'])]),
 dict(kat='job_work', de='Kannst du mir kurz helfen?', it='Mi puoi dare una mano?',
      k=[('koennen', ['mi puoi', 'puoi']),
         ('helfen', ['dare una mano', 'aiutare', 'aiutarmi'])],
      h='„Dare una mano" (eine Hand geben) ist unter Kollegen die '
        'natürlichere Formel als „aiutare".'),
 dict(kat='job_work', de='Wie macht man das?', it='Come si fa?',
      k=[('wie', ['come']),
         ('machen', ['si fa', 'fare'])]),
 dict(kat='job_work', de='Das habe ich noch nie gemacht.', it='Non l\'ho mai fatto.',
      k=[('nie', ['mai']),
         ('gemacht', ['fatto'])]),
 dict(kat='job_work', de='Wo finde ich das?', it='Dove lo trovo?',
      k=[('wo', ['dove']),
         ('finden', ['trovo', 'trovare'])]),
 dict(kat='job_work', de='Ich mache Pause.', it='Faccio una pausa.',
      k=[('pause', ['pausa'])]),
 dict(kat='job_work', de='Danke für deine Hilfe.', it='Grazie del tuo aiuto.',
      k=[('danke', ['grazie']),
         ('hilfe', ['aiuto'])]),
 dict(kat='job_work', de='Kann ich Ihnen helfen?', it='Posso aiutarla?',
      k=[('koennen', ['posso']),
         ('helfen', ['aiutarla', 'aiutare'])],
      h='Zum Kunden gehört das „Lei": „posso aiutarla?". Mit „aiutarti" '
        'würdest du duzen — im Laden unpassend.'),
 dict(kat='job_work', de='Der Nächste, bitte!', it='Il prossimo, per favore!',
      k=[('naechste', ['il prossimo', 'prossimo', 'avanti'])]),
 dict(kat='job_work', de='Möchten Sie noch etwas?', it='Desidera altro?',
      k=[('moechten', ['desidera', 'vuole']),
         ('noch_etwas', ['altro', 'qualcos\'altro'])]),
 dict(kat='job_work', de='Zahlen Sie bar oder mit Karte?', it='Paga in contanti o con la carta?',
      k=[('bar', ['contanti']),
         ('karte', ['carta'])]),
 dict(kat='job_work', de='Tut mir leid, das haben wir nicht.', it='Mi dispiace, non ce l\'abbiamo.',
      k=[('leid', ['mi dispiace']),
         ('nicht_haben', ['non ce l\'abbiamo', 'non abbiamo'])]),
 dict(kat='job_work', de='Ich hole meinen Kollegen.', it='Chiamo il mio collega.',
      k=[('holen', ['chiamo', 'vado a chiamare']),
         ('kollege', ['collega'])]),
 dict(kat='job_work', de='Kommen Sie gerne wieder!', it='Torni presto!',
      k=[('wiederkommen', ['torni', 'tornare', 'arrivederci'])]),
 dict(kat='job_work', de='Wie viel verdiene ich pro Stunde?', it='Quanto guadagno all\'ora?',
      k=[('verdienen', ['guadagno', 'guadagnare']),
         ('stunde', ['all\'ora', 'ora'])]),
 dict(kat='job_work', de='Wann bekomme ich mein Geld?', it='Quando ricevo lo stipendio?',
      k=[('wann', ['quando']),
         ('geld', ['stipendio', 'soldi', 'paga'])]),
 dict(kat='job_work', de='Werde ich bar bezahlt?', it='Mi pagate in contanti?',
      k=[('bar', ['contanti']),
         ('bezahlt', ['mi pagate', 'pagate', 'pagato'])]),
 dict(kat='job_work', de='Ich habe zehn Stunden gearbeitet.', it='Ho lavorato dieci ore.',
      k=[('zehn', ['dieci']),
         ('stunden', ['ore']),
         ('gearbeitet', ['ho lavorato', 'lavorato'])]),
 dict(kat='job_work', de='Wann fange ich an?', it='Quando inizio?',
      k=[('wann', ['quando']),
         ('anfangen', ['inizio', 'comincio'])]),
 dict(kat='job_work', de='Wann habe ich frei?', it='Quando ho il giorno libero?',
      k=[('wann', ['quando']),
         ('frei', ['giorno libero', 'libero'])]),
 dict(kat='job_work', de='Wie lange dauert die Schicht?', it='Quanto dura il turno?',
      k=[('wie_lange', ['quanto dura', 'quanto']),
         ('schicht', ['turno'])]),
 dict(kat='job_work', de='Kann ich am Montag frei haben?', it='Posso avere lunedì libero?',
      k=[('montag', ['lunedì']),
         ('frei', ['libero'])]),
 dict(kat='job_work', de='Kann ich die Schicht tauschen?', it='Posso cambiare turno?',
      k=[('schicht', ['turno']),
         ('tauschen', ['cambiare', 'scambiare'])]),
 dict(kat='job_work', de='Ich komme morgen früher.', it='Domani arrivo prima.',
      k=[('morgen', ['domani']),
         ('frueher', ['prima', 'più presto'])]),
 dict(kat='job_work', de='Wo ist der Dienstplan?', it='Dov\'è il turno di servizio?',
      k=[('wo', ['dov\'è', 'dove']),
         ('dienstplan', ['turno di servizio', 'turni', 'orario'])]),
 dict(kat='job_work', de='Ich suche Arbeit.', it='Cerco lavoro.',
      k=[('suchen', ['cerco', 'cercare']),
         ('arbeit', ['lavoro'])]),
 dict(kat='job_work', de='Suchen Sie noch Leute?', it='Cercate ancora personale?',
      k=[('suchen', ['cercate', 'cercare']),
         ('leute', ['personale', 'gente'])]),
 dict(kat='job_work', de='Haben Sie eine Stelle frei?', it='Avete un posto libero?',
      k=[('stelle', ['posto']),
         ('frei', ['libero'])]),
 dict(kat='job_work', de='Brauchen Sie Hilfe in der Küche?', it='Vi serve aiuto in cucina?',
      k=[('brauchen', ['vi serve', 'avete bisogno']),
         ('hilfe', ['aiuto']),
         ('kueche', ['cucina'])]),
 dict(kat='job_work', de='Ich kann sofort anfangen.', it='Posso iniziare subito.',
      k=[('koennen', ['posso']),
         ('sofort', ['subito']),
         ('anfangen', ['iniziare', 'cominciare'])]),
 dict(kat='job_work', de='Ich bin für drei Monate hier.', it='Sono qui per tre mesi.',
      k=[('drei_monate', ['tre mesi']),
         ('hier', ['qui'])]),
]

AUSGELASSEN = [
    # 120 ist der CHINESISCHE Rettungsdienst - in Italien gilt die 112.
    # Ersetzt durch die richtige Nummer (neu=True oben). Siehe Kopfkommentar.
    'Rufen Sie bitte 120 an.',
    # Den Gegensatz westliche Medizin / TCM gibt es in Italien nicht - die
    # beiden Saetze beantworten hier keine Frage.
    'Ich möchte westliche Medizin.',
    'Ist das westliche Medizin?',
    # Zielsprache steht im Satz - ersetzt durch die italienische Fassung.
    'Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
]
