# -*- coding: utf-8 -*-
"""Gesundheit/Notfall und Job auf Norwegisch (Bokmaal).

Zusammen 118 Master-Saetze - health_emergency (76), job_work (42).

**VIER SAETZE SIND CHINA-SPEZIFISCH und wandern NICHT woertlich mit** -
dieselben vier wie im italienischen Gegenstueck, aber mit anderer
Ersatzloesung:

  Rufen Sie bitte 120 an.     **120 ist der chinesische Rettungsdienst.**
                              Norwegen hat KEINE einheitliche Notrufnummer:
                              113 Rettung, 112 Polizei, 110 Feuerwehr. Der
                              Satz meint den Krankenwagen, also **113** -
                              und genau deshalb steht hier nicht dieselbe
                              Zahl wie in Italien. Wer die drei Nummern
                              verwechselt, verliert im Ernstfall Zeit.
  Ich moechte westliche       Der Gegensatz westliche Medizin / TCM
  Medizin.                    existiert in Norwegen nicht. Beide Saetze
  Ist das westliche Medizin?  ersatzlos ausgelassen.
  Ich spreche kein            Zielsprache im Satz - durch die norwegische
  Chinesisch. ...             Fassung ersetzt.

**116 Saetze uebersetzt, 4 ausgelassen, 2 neu.**

**Kein Sie**, auch nicht beim Arzt und nicht zum Kunden: "Kann ich Ihnen
helfen?" ist schlicht "Kan jeg hjelpe deg?". Das ist der auffaelligste
Unterschied zum italienischen und russischen Gegenstueck derselben Saetze.

**Nicht von Muttersprachlern geprueft.**
"""

KATEGORIEN = ['health_emergency', 'job_work']

SAETZE = [

# ========================================================== health_emergency
 dict(kat='health_emergency', de='Ich bin allergisch gegen Penizillin.', no='Jeg er allergisk mot penicillin.',
      k=[('allergisch', ['allergisk']),
         ('penizillin', ['penicillin'])]),
 dict(kat='health_emergency', de='Ich habe eine Allergie.', no='Jeg har en allergi.',
      k=[('allergie', ['allergi'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen dieses Medikament.', no='Jeg er allergisk mot denne medisinen.',
      k=[('allergisch', ['allergisk']),
         ('medikament', ['medisinen', 'medisin'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen Erdnüsse.', no='Jeg er allergisk mot peanøtter.',
      k=[('allergisch', ['allergisk']),
         ('erdnuesse', ['peanøtter'])]),
 dict(kat='health_emergency', de='Ich kann keine Erdnüsse essen.', no='Jeg kan ikke spise peanøtter.',
      k=[('nicht_essen', ['kan ikke spise', 'kan ikke']),
         ('erdnuesse', ['peanøtter'])]),
 dict(kat='health_emergency', de='Sind da Erdnüsse drin?', no='Er det peanøtter i dette?',
      k=[('erdnuesse', ['peanøtter'])]),
 dict(kat='health_emergency', de='Bitte ohne Erdnüsse.', no='Uten peanøtter, takk.',
      k=[('ohne', ['uten']),
         ('erdnuesse', ['peanøtter'])]),
 dict(kat='health_emergency', de='Bitte ohne Milch.', no='Uten melk, takk.',
      k=[('ohne', ['uten']),
         ('milch', ['melk'])]),
 dict(kat='health_emergency', de='Ich vertrage keine Milch.', no='Jeg tåler ikke melk.',
      k=[('milch_vertragen', ['tåler ikke melk', 'laktoseintolerant', 'melk'])]),
 dict(kat='health_emergency', de='Was ist da drin?', no='Hva er det i dette?',
      k=[('was_drin', ['hva er det i', 'innhold', 'ingredienser'])]),
 dict(kat='health_emergency', de='Ich habe mein Allergiemedikament dabei.', no='Jeg har med allergimedisinen min.',
      k=[('allergiemedikament', ['allergimedisin', 'allergimedisinen'])]),
 dict(kat='health_emergency', de='Das ist für mich sehr gefährlich.', no='Det er veldig farlig for meg.',
      k=[('gefaehrlich', ['farlig', 'veldig farlig'])]),
 dict(kat='health_emergency', de='Ist das gefährlich?', no='Er det farlig?',
      k=[('gefaehrlich', ['farlig'])]),
 dict(kat='health_emergency', de='Ich habe meine Versicherungskarte vergessen.', no='Jeg har glemt helsetrygdkortet.',
      k=[('versicherungskarte', ['helsetrygdkortet', 'helsetrygdkort', 'forsikringskort'])],
      h='Das „helsetrygdkort" ist die europäische '
        'Krankenversicherungskarte — die Rückseite deiner deutschen Karte. '
        'Ohne sie zahlst du beim Arzt erst mal alles selbst.'),
 dict(kat='health_emergency', de='Wie viel kostet das?', no='Hva koster det?',
      k=[('kosten', ['hva koster det'])]),
 dict(kat='health_emergency', de='Ich habe eine Versicherung.', no='Jeg har forsikring.',
      k=[('versicherung', ['forsikring'])]),
 dict(kat='health_emergency', de='Nehmen Sie meine Versicherung?', no='Tar dere imot forsikringen min?',
      k=[('versicherung_akzeptiert', ['tar dere imot', 'forsikringen', 'forsikring'])]),
 dict(kat='health_emergency', de='Muss ich vorher bezahlen?', no='Må jeg betale på forhånd?',
      k=[('vorher_bezahlen', ['betale på forhånd', 'på forhånd'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir eine Quittung.', no='Kan jeg få en kvittering?',
      k=[('quittung', ['kvittering'])]),
 dict(kat='health_emergency', de='Ich brauche die Quittung für meine Versicherung.', no='Jeg trenger kvitteringen til forsikringen.',
      k=[('quittung', ['kvittering', 'kvitteringen']),
         ('versicherung', ['forsikringen', 'forsikring'])]),
 dict(kat='health_emergency', de='Kann ich mit dem Handy bezahlen?', no='Kan jeg betale med mobilen?',
      k=[('handy_bezahlen', ['med mobilen', 'mobilen', 'vipps'])]),
 dict(kat='health_emergency', de='Nehmen Sie auch Karte?', no='Tar dere kort?',
      k=[('karte', ['kort'])]),
 dict(kat='health_emergency', de='Hier ist meine Karte.', no='Her er kortet mitt.',
      k=[('meine_karte', ['her er kortet', 'kortet mitt', 'kort'])]),
 dict(kat='health_emergency', de='Zuerst anmelden, dann bezahlen?', no='Først registrere, så betale?',
      k=[('anmelden', ['registrere', 'melde seg']),
         ('bezahlen', ['betale'])]),
 dict(kat='health_emergency', de='Wo bekomme ich die Quittung?', no='Hvor får jeg kvitteringen?',
      k=[('quittung', ['kvitteringen', 'kvittering'])]),
 dict(kat='health_emergency', de='Wo kann ich bezahlen?', no='Hvor kan jeg betale?',
      k=[('wo_bezahlen', ['hvor kan jeg betale', 'betale'])]),
 dict(kat='health_emergency', de='Das ist zu teuer.', no='Det er for dyrt.',
      k=[('zu_teuer', ['for dyrt', 'dyrt'])]),
 dict(kat='health_emergency', de='Ich habe nicht genug Geld dabei.', no='Jeg har ikke nok penger med meg.',
      k=[('nicht_genug_geld', ['ikke nok penger', 'nok penger', 'penger'])]),
 dict(kat='health_emergency', de='Reicht das?', no='Holder det?',
      k=[('reicht', ['holder det', 'holder', 'er det nok'])]),
 dict(kat='health_emergency', de='Ich habe meine Tabletten vergessen.', no='Jeg har glemt tablettene mine.',
      k=[('tabletten_vergessen', ['glemt tablettene', 'tablettene', 'tabletter'])]),
 dict(kat='health_emergency', de='Wie oft muss ich das Medikament nehmen?', no='Hvor ofte skal jeg ta medisinen?',
      k=[('medikament_haeufigkeit', ['hvor ofte', 'ta medisinen', 'medisinen'])]),
 dict(kat='health_emergency', de='Wo ist das Krankenhaus?', no='Hvor er sykehuset?',
      k=[('krankenhaus', ['sykehuset', 'sykehus'])]),
 dict(kat='health_emergency', de='Ich möchte zum Arzt.', no='Jeg vil gjerne til legen.',
      k=[('arzt', ['legen', 'lege'])],
      h='Der erste Weg führt in Norwegen fast nie ins Krankenhaus, sondern '
        'zum „fastlege" (Hausarzt) oder zur „legevakt" — dem '
        'Bereitschaftsdienst für alles, was nicht bis morgen warten kann.'),
 dict(kat='health_emergency', de='Wo melde ich mich an?', no='Hvor melder jeg meg?',
      k=[('anmelden', ['melder jeg meg', 'melde seg', 'registrere'])]),
 dict(kat='health_emergency', de='Ich möchte mich anmelden.', no='Jeg vil gjerne melde meg.',
      k=[('anmelden', ['melde meg', 'registrere meg'])]),
 dict(kat='health_emergency', de='Ich habe keinen Termin.', no='Jeg har ikke time.',
      k=[('kein_termin', ['har ikke time', 'ikke time', 'time'])],
      h='Der Arzttermin heißt „time" (wörtlich: Stunde) — „å bestille time" '
        'ist einen Termin machen.'),
 dict(kat='health_emergency', de='Kann ich einen Termin bekommen?', no='Kan jeg få en time?',
      k=[('termin', ['time', 'få en time'])]),
 dict(kat='health_emergency', de='Wie lange muss ich warten?', no='Hvor lenge må jeg vente?',
      k=[('warten', ['hvor lenge må jeg vente', 'vente'])]),
 dict(kat='health_emergency', de='Wie lange dauert das?', no='Hvor lang tid tar det?',
      k=[('dauer', ['hvor lang tid', 'tar det'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir ein Medikament.', no='Kan jeg få en medisin?',
      k=[('medikament', ['medisin'])]),
 dict(kat='health_emergency', de='Wie nehme ich das Medikament?', no='Hvordan skal jeg ta medisinen?',
      k=[('medikament_einnahme', ['hvordan skal jeg ta', 'ta medisinen', 'medisinen'])]),
 dict(kat='health_emergency', de='Wie komme ich dorthin?', no='Hvordan kommer jeg dit?',
      k=[('wie_dorthin', ['hvordan kommer jeg dit', 'kommer jeg dit'])]),
 dict(kat='health_emergency', de='Ich brauche einen Arzt.', no='Jeg trenger en lege.',
      k=[('arzt', ['lege'])]),
 dict(kat='health_emergency', de='Wo ist die nächste Apotheke?', no='Hvor er nærmeste apotek?',
      k=[('apotheke', ['apotek'])]),
 dict(kat='health_emergency', de='Ich brauche dringend Hilfe.', no='Jeg trenger hjelp med en gang.',
      k=[('dringend_hilfe', ['hjelp med en gang', 'akutt hjelp', 'hjelp'])]),
 dict(kat='health_emergency', de='Wo ist das nächste Krankenhaus?', no='Hvor er nærmeste sykehus?',
      k=[('krankenhaus', ['sykehus', 'sykehuset'])]),
 dict(kat='health_emergency', de='Bitte helfen Sie mir!', no='Kan du hjelpe meg?',
      k=[('helfen', ['hjelpe meg', 'hjelp'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie einen Krankenwagen!', no='Ring en ambulanse!',
      k=[('krankenwagen', ['ambulanse'])]),
 dict(kat='health_emergency', de='Ist der Krankenwagen schon unterwegs?', no='Er ambulansen på vei?',
      k=[('krankenwagen', ['ambulansen', 'ambulanse']),
         ('unterwegs', ['på vei'])]),
 dict(kat='health_emergency', de='Jemand ist verletzt.', no='Noen er skadet.',
      k=[('verletzt', ['skadet', 'noen er skadet'])]),
 dict(kat='health_emergency', de='Ich bin verletzt.', no='Jeg er skadet.',
      k=[('verletzt', ['skadet'])]),
 dict(kat='health_emergency', de='Schnell, bitte!', no='Fort, er du snill!',
      k=[('schnell', ['fort', 'raskt', 'skynd deg'])]),
 dict(kat='health_emergency', de='Ich brauche etwas aus der Apotheke.', no='Jeg trenger noe fra apoteket.',
      k=[('apotheke', ['apoteket', 'apotek'])]),
 dict(kat='health_emergency', de='Ich bin allein hier.', no='Jeg er alene her.',
      k=[('allein', ['alene'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie meinen Freund an.', no='Kan du ringe vennen min?',
      k=[('anrufen', ['ringe']),
         ('freund', ['vennen min', 'venn'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie die Polizei!', no='Ring politiet!',
      k=[('polizei', ['politiet', 'politi'])]),
 dict(kat='health_emergency', de='Ich möchte die Polizei rufen.', no='Jeg vil ringe politiet.',
      k=[('polizei', ['politiet', 'politi'])]),
 dict(kat='health_emergency', de='Mir geht es nicht gut.', no='Jeg føler meg ikke bra.',
      k=[('nicht_gut', ['føler meg ikke bra', 'ikke bra'])]),
 dict(kat='health_emergency', de='Ich habe Kopfschmerzen.', no='Jeg har hodepine.',
      k=[('kopfschmerzen', ['hodepine'])],
      h='Schmerzen sind im Norwegischen ein zusammengesetztes Wort mit '
        '„-pine": hodepine (Kopf), magepine (Bauch), tannpine (Zahn).'),
 dict(kat='health_emergency', de='Ich habe Fieber.', no='Jeg har feber.',
      k=[('fieber', ['feber'])]),
 dict(kat='health_emergency', de='Ich habe mir den Fuß verletzt.', no='Jeg har skadet foten.',
      k=[('fuss_verletzt', ['skadet foten', 'foten'])]),
 dict(kat='health_emergency', de='Ich fühle mich schwindelig.', no='Jeg er svimmel.',
      k=[('schwindelig', ['svimmel'])]),
 dict(kat='health_emergency', de='Ich bin krank.', no='Jeg er syk.',
      k=[('krank', ['syk'])]),
 dict(kat='health_emergency', de='Ich bin erkältet.', no='Jeg er forkjølet.',
      k=[('erkaeltet', ['forkjølet'])]),
 dict(kat='health_emergency', de='Ich habe Bauchschmerzen.', no='Jeg har vondt i magen.',
      k=[('bauchschmerzen', ['vondt i magen', 'magen', 'magepine'])]),
 dict(kat='health_emergency', de='Mein Bein tut weh.', no='Jeg har vondt i beinet.',
      k=[('bein_weh', ['vondt i beinet', 'beinet'])]),
 dict(kat='health_emergency', de='Hier tut es weh.', no='Det gjør vondt her.',
      k=[('hier_weh', ['gjør vondt her', 'vondt her', 'her'])]),
 dict(kat='health_emergency', de='Mir geht es sehr schlecht.', no='Jeg har det veldig dårlig.',
      k=[('sehr_schlecht', ['veldig dårlig', 'dårlig'])]),
 dict(kat='health_emergency', de='Ich bin sehr müde.', no='Jeg er veldig trøtt.',
      k=[('muede', ['trøtt', 'veldig trøtt'])]),
 dict(kat='health_emergency', de='Mir ist kalt.', no='Jeg fryser.',
      k=[('kalt', ['jeg fryser', 'fryser', 'kaldt'])],
      h='„Jeg fryser" heißt „mir ist kalt" — nicht, dass man einfriert. Für '
        'das Wetter sagt man „det er kaldt".'),
 dict(kat='health_emergency', de='Seit gestern.', no='Siden i går.',
      k=[('seit_gestern', ['siden i går', 'i går'])]),
 dict(kat='health_emergency', de='Seit heute Morgen.', no='Siden i morges.',
      k=[('seit_heute_morgen', ['siden i morges', 'i morges'])]),
 dict(kat='health_emergency', de='Rufen Sie bitte 113 an.', no='Ring 113!',
      neu=True, sz='health_notfall',
      k=[('notruf', ['113', 'hundre og tretten'])],
      h='Norwegen hat drei Notrufnummern statt einer: 113 Rettungsdienst, '
        '112 Polizei, 110 Feuerwehr. Für den Krankenwagen ist es die 113 — '
        'die 112, die in Italien alles abdeckt, wäre hier die Polizei.'),
 dict(kat='health_emergency', de='Ich spreche kein Norwegisch. Können Sie es aufschreiben?',
      no='Jeg snakker ikke norsk. Kan du skrive det ned?',
      neu=True, sz='health_krankenhaus',
      k=[('kein_norwegisch', ['snakker ikke norsk', 'ikke norsk']),
         ('aufschreiben', ['skrive det ned', 'skrive ned'])]),

# ================================================================== job_work
 dict(kat='job_work', de='Ich kann heute nicht kommen.', no='Jeg kan ikke komme i dag.',
      k=[('nicht_koennen', ['kan ikke']),
         ('heute', ['i dag']),
         ('kommen', ['komme'])]),
 dict(kat='job_work', de='Ich bin krank und bleibe zu Hause.', no='Jeg er syk og blir hjemme.',
      k=[('krank', ['syk']),
         ('zu_hause', ['hjemme', 'blir hjemme'])],
      h='In Norwegen darf man sich für ein paar Tage selbst krankmelden '
        '(„egenmelding") — ganz ohne Attest. Ein Anruf am Morgen reicht.'),
 dict(kat='job_work', de='Ich komme später.', no='Jeg kommer senere.',
      k=[('kommen', ['kommer']),
         ('spaeter', ['senere'])]),
 dict(kat='job_work', de='Ich brauche einen Tag frei.', no='Jeg trenger en fridag.',
      k=[('brauchen', ['trenger']),
         ('tag_frei', ['fridag', 'fri'])]),
 dict(kat='job_work', de='Ich habe einen Arzttermin.', no='Jeg har legetime.',
      k=[('arzttermin', ['legetime', 'time hos legen'])]),
 dict(kat='job_work', de='Ich habe schon in einem Restaurant gearbeitet.', no='Jeg har jobbet på restaurant før.',
      k=[('gearbeitet', ['har jobbet', 'jobbet']),
         ('restaurant', ['restaurant'])]),
 dict(kat='job_work', de='Ich habe keine Erfahrung.', no='Jeg har ingen erfaring.',
      k=[('keine', ['ingen', 'har ingen']),
         ('erfahrung', ['erfaring'])]),
 dict(kat='job_work', de='Ich lerne schnell.', no='Jeg lærer fort.',
      k=[('lernen', ['lærer']),
         ('schnell', ['fort', 'raskt'])]),
 dict(kat='job_work', de='Ich kann am Wochenende arbeiten.', no='Jeg kan jobbe i helga.',
      k=[('koennen', ['jeg kan', 'kan']),
         ('wochenende', ['helga', 'helgen']),
         ('arbeiten', ['jobbe'])]),
 dict(kat='job_work', de='Wann kann ich anfangen?', no='Når kan jeg begynne?',
      k=[('wann', ['når']),
         ('anfangen', ['begynne', 'starte'])]),
 dict(kat='job_work', de='Brauche ich eine Arbeitserlaubnis?', no='Trenger jeg arbeidstillatelse?',
      k=[('brauchen', ['trenger jeg', 'trenger']),
         ('arbeitserlaubnis', ['arbeidstillatelse', 'tillatelse'])],
      h='Als EU-Bürger brauchst du keine Arbeitserlaubnis, aber eine '
        'norwegische Personennummer und eine Steuerkarte („skattekort") — '
        'ohne die zieht der Arbeitgeber 50 % Steuer ab.'),
 dict(kat='job_work', de='Ich bin neu hier.', no='Jeg er ny her.',
      k=[('neu', ['ny']),
         ('hier', ['her'])]),
 dict(kat='job_work', de='Kannst du mir kurz helfen?', no='Kan du hjelpe meg litt?',
      k=[('koennen', ['kan du']),
         ('helfen', ['hjelpe meg', 'hjelpe'])]),
 dict(kat='job_work', de='Wie macht man das?', no='Hvordan gjør man det?',
      k=[('wie', ['hvordan']),
         ('machen', ['gjør man', 'gjøre'])]),
 dict(kat='job_work', de='Das habe ich noch nie gemacht.', no='Det har jeg aldri gjort før.',
      k=[('nie', ['aldri']),
         ('gemacht', ['gjort'])]),
 dict(kat='job_work', de='Wo finde ich das?', no='Hvor finner jeg det?',
      k=[('wo', ['hvor']),
         ('finden', ['finner jeg', 'finne'])]),
 dict(kat='job_work', de='Ich mache Pause.', no='Jeg tar pause.',
      k=[('pause', ['pause'])]),
 dict(kat='job_work', de='Danke für deine Hilfe.', no='Takk for hjelpen.',
      k=[('danke', ['takk']),
         ('hilfe', ['hjelpen', 'hjelp'])]),
 dict(kat='job_work', de='Kann ich Ihnen helfen?', no='Kan jeg hjelpe deg?',
      k=[('koennen', ['kan jeg']),
         ('helfen', ['hjelpe deg', 'hjelpe'])],
      h='Auch zum Kunden wird geduzt — „kan jeg hjelpe deg?". Ein „De" '
        'würde hier befremdlich wirken, nicht höflich.'),
 dict(kat='job_work', de='Der Nächste, bitte!', no='Neste, takk!',
      k=[('naechste', ['neste'])]),
 dict(kat='job_work', de='Möchten Sie noch etwas?', no='Var det noe mer?',
      k=[('moechten', ['var det', 'ønsker du']),
         ('noch_etwas', ['noe mer', 'mer'])]),
 dict(kat='job_work', de='Zahlen Sie bar oder mit Karte?', no='Betaler du kontant eller med kort?',
      k=[('bar', ['kontant', 'kontanter']),
         ('karte', ['kort'])]),
 dict(kat='job_work', de='Tut mir leid, das haben wir nicht.', no='Beklager, det har vi ikke.',
      k=[('leid', ['beklager']),
         ('nicht_haben', ['har vi ikke', 'ikke'])]),
 dict(kat='job_work', de='Ich hole meinen Kollegen.', no='Jeg henter kollegaen min.',
      k=[('holen', ['henter', 'hente']),
         ('kollege', ['kollegaen', 'kollega'])]),
 dict(kat='job_work', de='Kommen Sie gerne wieder!', no='Velkommen tilbake!',
      k=[('wiederkommen', ['velkommen tilbake', 'kom igjen', 'tilbake'])]),
 dict(kat='job_work', de='Wie viel verdiene ich pro Stunde?', no='Hvor mye tjener jeg i timen?',
      k=[('verdienen', ['tjener', 'tjene']),
         ('stunde', ['i timen', 'timen'])]),
 dict(kat='job_work', de='Wann bekomme ich mein Geld?', no='Når får jeg lønna?',
      k=[('wann', ['når']),
         ('geld', ['lønna', 'lønn', 'penger'])]),
 dict(kat='job_work', de='Werde ich bar bezahlt?', no='Får jeg betalt kontant?',
      k=[('bar', ['kontant', 'kontanter']),
         ('bezahlt', ['betalt', 'får jeg betalt'])],
      h='Schwarzarbeit gegen Bargeld ist in Norwegen selten und riskant — '
        'Lohn kommt praktisch immer aufs Konto, mit Lohnzettel und '
        'abgezogener Steuer.'),
 dict(kat='job_work', de='Ich habe zehn Stunden gearbeitet.', no='Jeg har jobbet ti timer.',
      k=[('zehn', ['ti']),
         ('stunden', ['timer']),
         ('gearbeitet', ['har jobbet', 'jobbet'])]),
 dict(kat='job_work', de='Wann fange ich an?', no='Når begynner jeg?',
      k=[('wann', ['når']),
         ('anfangen', ['begynner', 'starter'])]),
 dict(kat='job_work', de='Wann habe ich frei?', no='Når har jeg fri?',
      k=[('wann', ['når']),
         ('frei', ['fri'])]),
 dict(kat='job_work', de='Wie lange dauert die Schicht?', no='Hvor lenge varer vakta?',
      k=[('wie_lange', ['hvor lenge', 'varer']),
         ('schicht', ['vakta', 'vakt'])]),
 dict(kat='job_work', de='Kann ich am Montag frei haben?', no='Kan jeg få fri på mandag?',
      k=[('montag', ['mandag']),
         ('frei', ['fri'])]),
 dict(kat='job_work', de='Kann ich die Schicht tauschen?', no='Kan jeg bytte vakt?',
      k=[('schicht', ['vakt', 'vakta']),
         ('tauschen', ['bytte'])]),
 dict(kat='job_work', de='Ich komme morgen früher.', no='Jeg kommer tidligere i morgen.',
      k=[('morgen', ['i morgen']),
         ('frueher', ['tidligere'])]),
 dict(kat='job_work', de='Wo ist der Dienstplan?', no='Hvor er vaktlista?',
      k=[('wo', ['hvor er', 'hvor']),
         ('dienstplan', ['vaktlista', 'vaktliste', 'turnus'])]),
 dict(kat='job_work', de='Ich suche Arbeit.', no='Jeg ser etter jobb.',
      k=[('suchen', ['ser etter', 'leter etter']),
         ('arbeit', ['jobb', 'arbeid'])]),
 dict(kat='job_work', de='Suchen Sie noch Leute?', no='Trenger dere flere folk?',
      k=[('suchen', ['trenger dere', 'trenger']),
         ('leute', ['folk', 'flere folk'])]),
 dict(kat='job_work', de='Haben Sie eine Stelle frei?', no='Har dere en ledig stilling?',
      k=[('stelle', ['stilling', 'jobb']),
         ('frei', ['ledig'])]),
 dict(kat='job_work', de='Brauchen Sie Hilfe in der Küche?', no='Trenger dere hjelp på kjøkkenet?',
      k=[('brauchen', ['trenger dere', 'trenger']),
         ('hilfe', ['hjelp']),
         ('kueche', ['kjøkkenet', 'kjøkken'])]),
 dict(kat='job_work', de='Ich kann sofort anfangen.', no='Jeg kan begynne med en gang.',
      k=[('koennen', ['jeg kan', 'kan']),
         ('sofort', ['med en gang', 'straks']),
         ('anfangen', ['begynne', 'starte'])]),
 dict(kat='job_work', de='Ich bin für drei Monate hier.', no='Jeg er her i tre måneder.',
      k=[('drei_monate', ['tre måneder']),
         ('hier', ['her'])]),
]

AUSGELASSEN = [
    # 120 ist der CHINESISCHE Rettungsdienst. Norwegen hat drei getrennte
    # Notrufnummern - fuer den Krankenwagen die 113, siehe Kopfkommentar.
    'Rufen Sie bitte 120 an.',
    # Den Gegensatz westliche Medizin / TCM gibt es in Norwegen nicht.
    'Ich möchte westliche Medizin.',
    'Ist das westliche Medizin?',
    # Zielsprache steht im Satz - ersetzt durch die norwegische Fassung.
    'Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
]
