# -*- coding: utf-8 -*-
"""Reise, Hotel und Uni auf Russisch, in einer Datei.

Zusammen 85 Saetze - travel_transportation (36), hotel_accommodation (25),
university_studying (24). Aufbau wie `kleine_kategorien_ru.py`.

**Lautschrift-Regeln** stehen im Kopf von `grundwortschatz_ru.py`.

**Nichts ausgelassen.**

Was hier eigene Wirklichkeit ist und in den Hinweisen steht:

  Muenchen              `Мюнхен` - keine Falle wie im Italienischen, aber
                        die Aussprache (Mjúnchen) lohnt den Hinweis nicht;
                        stattdessen steht der Hinweis am Zug-Satz, weil
                        russische Fernzuege anders funktionieren.
  Credits               heissen `зачётные единицы`, im Studentenmund
                        einfach `зачёты`. Das englische "credits" hilft
                        nicht weiter.
  Hoersaal              ist die `аудитория` - falscher Freund fuer Deutsche,
                        die dabei an "Auditorium/Publikum" denken.
  Dozent                `преподаватель`, und angeredet wird mit VORNAME +
                        VATERSNAME (Iwán Petrówitsch), nie mit dem
                        Nachnamen. Das ist die auffaelligste Uni-Regel und
                        steht als Hinweis am Satz.
  Bahnhof               `вокзал` ist der Fernbahnhof, `станция` die
                        Metro-/Nahverkehrsstation - zwei verschiedene
                        Woerter fuer das eine deutsche.

**Nicht von Muttersprachlern geprueft** - bei Russisch faellt das staerker
ins Gewicht, weil die Lautschrift eine zusaetzliche Fehlerquelle ist.
"""

KATEGORIEN = ['travel_transportation', 'hotel_accommodation', 'university_studying']

SAETZE = [

# ======================================================== hotel_accommodation
 dict(kat='hotel_accommodation', de='Ich möchte auschecken.', ru='Я хочу выселиться.',
      py='Ja chatschú wysselítsa.',
      k=[('checkout', ['выселиться', 'выехать'])]),
 dict(kat='hotel_accommodation', de='Können Sie mir ein Taxi rufen?', ru='Вы можете вызвать мне такси?',
      py='Wy móshetje wýswat mnje taksí?',
      k=[('taxi', ['такси'])]),
 dict(kat='hotel_accommodation', de='Ich habe eine Reservierung.', ru='У меня есть бронь.',
      py='U menjá jest bron.',
      k=[('reservierung', ['бронь', 'бронирование'])]),
 dict(kat='hotel_accommodation', de='Haben Sie noch ein Zimmer frei?', ru='У вас есть свободный номер?',
      py='U was jest swabódnyj nómer?',
      k=[('zimmer_frage', ['свободный номер', 'номер'])],
      h='Das Hotelzimmer heißt „номер" (wörtlich: Nummer), nicht „комната" '
        '— das wäre das Zimmer in einer Wohnung.'),
 dict(kat='hotel_accommodation', de='Ich möchte ein Einzelzimmer, bitte.', ru='Я хочу одноместный номер.',
      py='Ja chatschú adnaméstnyj nómer.',
      k=[('einzelzimmer', ['одноместный номер', 'одноместный'])]),
 dict(kat='hotel_accommodation', de='Wie viel kostet die Nacht?', ru='Сколько стоит ночь?',
      py='Skólka stóit notsch?',
      k=[('preis_nacht', ['стоит ночь', 'ночь', 'за ночь'])]),
 dict(kat='hotel_accommodation', de='Wann ist der Check-in?', ru='Во сколько заселение?',
      py='Wa skólka sasseljénije?',
      k=[('checkin', ['заселение', 'заселиться'])]),
 dict(kat='hotel_accommodation', de='Ist das ein Mehrbettzimmer?', ru='Это общий номер?',
      py='Éta óbschtschij nómer?',
      k=[('mehrbettzimmer', ['общий номер', 'общий', 'хостел'])]),
 dict(kat='hotel_accommodation', de='Wie viele Betten hat der Schlafsaal?', ru='Сколько кроватей в комнате?',
      py='Skólka krawátej w kómnatje?',
      k=[('wie_viele', ['сколько']),
         ('schlafsaal', ['кроватей', 'в комнате', 'комната'])]),
 dict(kat='hotel_accommodation', de='Ich hätte gern das untere Bett.', ru='Я хотел бы нижнюю кровать.',
      py='Ja chatjél by nishnjuju krawát.',
      k=[('unteres_bett', ['нижнюю кровать', 'нижнюю', 'нижняя'])]),
 dict(kat='hotel_accommodation', de='Gibt es Schließfächer für das Gepäck?', ru='Есть ли шкафчики для вещей?',
      py='Jest li schkáftschiki dlja weschtschéj?',
      k=[('schliessfaecher', ['шкафчики', 'камера хранения'])]),
 dict(kat='hotel_accommodation', de='Ist Bettwäsche im Preis inbegriffen?', ru='Постельное бельё входит в цену?',
      py='Pastélnaje beljó wchódit w zénu?',
      k=[('bettwaesche', ['постельное бельё', 'бельё']),
         ('inbegriffen', ['входит в цену', 'входит', 'включено'])]),
 dict(kat='hotel_accommodation', de='Kann ich ein Handtuch leihen?', ru='Можно взять полотенце?',
      py='Móshna wsjat palatjénze?',
      k=[('handtuch', ['полотенце']),
         ('leihen', ['взять', 'можно взять'])]),
 dict(kat='hotel_accommodation', de='Gibt es eine Gemeinschaftsküche?', ru='Есть общая кухня?',
      py='Jest óbschtschaja kúchnja?',
      k=[('gemeinschaftskueche', ['общая кухня', 'кухня'])]),
 dict(kat='hotel_accommodation', de='Gibt es eine Nachtruhe?', ru='Есть тихий час ночью?',
      py='Jest tíchij tschas nótschju?',
      k=[('nachtruhe', ['тихий час', 'тишина', 'комендантский час'])]),
 dict(kat='hotel_accommodation', de='Habt ihr einen Frauenschlafsaal?', ru='У вас есть женский номер?',
      py='U was jest shénskij nómer?',
      k=[('frauenschlafsaal', ['женский номер', 'женский', 'только для женщин'])]),
 dict(kat='hotel_accommodation', de='Muss ich eine Kaution hinterlegen?', ru='Нужно оставить залог?',
      py='Núshna astáwit salóg?',
      k=[('kaution', ['залог']),
         ('hinterlegen', ['оставить', 'нужно оставить'])]),
 dict(kat='hotel_accommodation', de='Mein Zimmer ist nicht sauber.', ru='В моём номере не убрано.',
      py='W majóm nómerje nje úbrana.',
      k=[('nicht_sauber', ['не убрано', 'грязно'])]),
 dict(kat='hotel_accommodation', de='Die Klimaanlage funktioniert nicht.', ru='Кондиционер не работает.',
      py='Kandizianér nje rabótajet.',
      k=[('klimaanlage_kaputt', ['кондиционер', 'не работает'])]),
 dict(kat='hotel_accommodation', de='Ich habe meinen Schlüssel verloren.', ru='Я потерял ключ.',
      py='Ja patjerjál kljutsch.',
      k=[('schluessel_verloren', ['потерял ключ', 'ключ', 'потерял'])]),
 dict(kat='hotel_accommodation', de='Ist das Frühstück inklusive?', ru='Завтрак включён?',
      py='Sáwtrak wkljutschón?',
      k=[('fruehstueck', ['завтрак'])]),
 dict(kat='hotel_accommodation', de='Gibt es hier WLAN?', ru='Здесь есть вай-фай?',
      py='Sdjes jest waj-faj?',
      k=[('wlan', ['вай-фай', 'wifi', 'интернет'])]),
 dict(kat='hotel_accommodation', de='Wie ist das Passwort für das WLAN?', ru='Какой пароль от вай-фая?',
      py='Kakój paról at waj-fája?',
      k=[('wlan_passwort', ['пароль', 'пароль от вай-фая'])]),
 dict(kat='hotel_accommodation', de='Wo ist der Aufzug?', ru='Где лифт?',
      py='Gdje lift?',
      k=[('aufzug', ['лифт'])]),
 dict(kat='hotel_accommodation', de='Das Zimmer ist sehr sauber.', ru='Номер очень чистый.',
      py='Nómer ótschen tschístyj.',
      k=[('zimmer_sauber', ['номер', 'чистый'])]),

# ===================================================== travel_transportation
 dict(kat='travel_transportation', de='Wo ist die Bushaltestelle?', ru='Где автобусная остановка?',
      py='Gdje awtóbusnaja astanówka?',
      k=[('bushaltestelle', ['остановка', 'автобусная остановка'])]),
 dict(kat='travel_transportation', de='Welcher Bus fährt zum Flughafen?', ru='Какой автобус идёт в аэропорт?',
      py='Kakój awtóbus idjót w aerapórt?',
      k=[('bus_flughafen', ['какой автобус', 'автобус']),
         ('flughafen', ['аэропорт'])]),
 dict(kat='travel_transportation', de='Wir haben den Bus erwischt.', ru='Мы успели на автобус.',
      py='My uspjéli na awtóbus.',
      k=[('bus_erwischt', ['успели на автобус', 'успели', 'автобус'])]),
 dict(kat='travel_transportation', de='Ich habe meinen Flug verpasst.', ru='Я опоздал на рейс.',
      py='Ja apasdál na rejs.',
      k=[('flug_verpasst', ['опоздал на рейс', 'рейс', 'опоздал'])]),
 dict(kat='travel_transportation', de='Wo ist der Check-in-Schalter?', ru='Где стойка регистрации?',
      py='Gdje stójka registrázii?',
      k=[('checkin_schalter', ['стойка регистрации', 'регистрация', 'стойка'])]),
 dict(kat='travel_transportation', de='Wo kann ich mein Gepäck aufgeben?', ru='Где можно сдать багаж?',
      py='Gdje móshna sdat bagásh?',
      k=[('gepaeck_aufgeben', ['сдать багаж', 'багаж'])]),
 dict(kat='travel_transportation', de='Mein Gepäck ist nicht angekommen.', ru='Мой багаж не пришёл.',
      py='Moj bagásh nje prischól.',
      k=[('gepaeck_fehlt', ['багаж не пришёл', 'багаж', 'не пришёл'])]),
 dict(kat='travel_transportation', de='Wie komme ich zum Hafen?', ru='Как добраться до порта?',
      py='Kak dabrátsa da pórta?',
      k=[('hafen', ['порта', 'порт'])]),
 dict(kat='travel_transportation', de='Ich war letztes Jahr in Frankreich.', ru='В прошлом году я был во Франции.',
      py='W próschlam gadú ja byl wa Fránzii.',
      k=[('frankreich', ['франции', 'франция'])]),
 dict(kat='travel_transportation', de='Nächstes Jahr fahre ich nach Italien.', ru='В следующем году я поеду в Италию.',
      py='W slédujuschtschem gadú ja pajédu w Itáliju.',
      k=[('italien', ['италию', 'италия'])]),
 dict(kat='travel_transportation', de='Wo wollt ihr hin?', ru='Куда вы идёте?',
      py='Kudá wy idjótje?',
      k=[('wohin', ['куда вы идёте', 'куда'])]),
 dict(kat='travel_transportation', de='Warte an der Kreuzung auf mich.', ru='Жди меня на перекрёстке.',
      py='Shdi menjá na perekrjóstkje.',
      k=[('kreuzung', ['перекрёстке', 'перекрёсток']),
         ('warten', ['жди меня', 'жди'])]),
 dict(kat='travel_transportation', de='Ich möchte eine Fahrkarte nach München, bitte.',
      ru='Мне нужен билет до Мюнхена, пожалуйста.',
      py='Mnje núshen biljét da Mjúnchena, pashálusta.',
      k=[('fahrkarte', ['билет']),
         ('muenchen', ['мюнхена', 'мюнхен'])]),
 dict(kat='travel_transportation', de='Ich möchte einen Mietwagen buchen.', ru='Я хочу арендовать машину.',
      py='Ja chatschú arendawát maschýnu.',
      k=[('mietwagen', ['арендовать машину', 'машину напрокат', 'машину'])]),
 dict(kat='travel_transportation', de='Wie viel kostet die Fahrt zum Flughafen?', ru='Сколько стоит поездка в аэропорт?',
      py='Skólka stóit pajéstka w aerapórt?',
      k=[('fahrt_kosten', ['сколько стоит поездка', 'поездка', 'сколько стоит']),
         ('flughafen', ['аэропорт'])]),
 dict(kat='travel_transportation', de='Ich möchte ein Ticket.', ru='Мне нужен билет.',
      py='Mnje núshen biljét.',
      k=[('ticket', ['билет'])]),
 dict(kat='travel_transportation', de='Wo ist der Bahnhof?', ru='Где вокзал?',
      py='Gdje wagsál?',
      k=[('bahnhof', ['вокзал', 'станция'])],
      h='„Вокзал" ist der Fernbahnhof, „станция" die Metro- oder '
        'Nahverkehrsstation — das eine deutsche Wort „Bahnhof" deckt im '
        'Russischen zwei verschiedene ab.'),
 dict(kat='travel_transportation', de='Wann fährt der nächste Zug nach Berlin?', ru='Когда следующий поезд в Берлин?',
      py='Kagdá slédujuschtschij pójesd w Berlín?',
      k=[('naechster_zug', ['следующий поезд', 'поезд']),
         ('berlin', ['берлин'])],
      h='Russische Fernzüge fahren oft über Nacht, und man bucht keinen '
        'Sitz-, sondern einen Liegeplatz: „купе" (Viererabteil) oder '
        '„плацкарт" (offener Schlafwagen).'),
 dict(kat='travel_transportation', de='Ist dieser Platz frei?', ru='Это место свободно?',
      py='Éta mjésta swabódna?',
      k=[('platz_frei', ['место свободно', 'свободно'])]),
 dict(kat='travel_transportation', de='Muss ich umsteigen?', ru='Мне нужно делать пересадку?',
      py='Mnje núshna djélat perissátku?',
      k=[('umsteigen', ['пересадку', 'пересадка'])]),
 dict(kat='travel_transportation', de='Von welchem Gleis fährt der Zug ab?', ru='С какого пути отходит поезд?',
      py='S kakówa putí atchódit pójesd?',
      k=[('gleis', ['пути', 'путь', 'платформа'])]),
 dict(kat='travel_transportation', de='Der Zug hat Verspätung.', ru='Поезд опаздывает.',
      py='Pójesd apásdywajet.',
      k=[('verspaetung', ['опаздывает', 'задерживается'])]),
 dict(kat='travel_transportation', de='Gehen Sie geradeaus.', ru='Идите прямо.',
      py='Idítje prjáma.',
      k=[('geradeaus', ['прямо'])]),
 dict(kat='travel_transportation', de='Biegen Sie links ab.', ru='Поверните налево.',
      py='Pawernítje naljéwa.',
      k=[('links', ['налево', 'слева'])]),
 dict(kat='travel_transportation', de='Biegen Sie rechts ab.', ru='Поверните направо.',
      py='Pawernítje napráwa.',
      k=[('rechts', ['направо', 'справа'])]),
 dict(kat='travel_transportation', de='Es ist gleich um die Ecke.', ru='Это сразу за углом.',
      py='Éta srásu sa uglóm.',
      k=[('um_die_ecke', ['за углом', 'углом'])]),
 dict(kat='travel_transportation', de='Nehmen Sie die zweite Straße rechts.', ru='Поверните на вторую улицу направо.',
      py='Pawernítje na wtarúju úlizu napráwa.',
      k=[('zweite_strasse', ['вторую улицу', 'вторая улица'])]),
 dict(kat='travel_transportation', de='Das Museum liegt gegenüber der Kirche.', ru='Музей напротив церкви.',
      py='Musjéj naprótiw zérkwi.',
      k=[('museum', ['музей']),
         ('kirche', ['церкви', 'церковь'])]),
 dict(kat='travel_transportation', de='Entschuldigung, wie komme ich zum Bahnhof?', ru='Извините, как пройти к вокзалу?',
      py='Iswinítje, kak prajtí k wagsálu?',
      k=[('bahnhof', ['вокзалу', 'вокзал'])]),
 dict(kat='travel_transportation', de='Ist das weit von hier?', ru='Это далеко отсюда?',
      py='Éta daljekó atsjúda?',
      k=[('weit', ['далеко'])]),
 dict(kat='travel_transportation', de='Können Sie mir das auf der Karte zeigen?', ru='Вы можете показать это на карте?',
      py='Wy móshetje pakasát éta na kártje?',
      k=[('auf_karte', ['на карте', 'карте', 'карта'])]),
 dict(kat='travel_transportation', de='Ich habe mich verlaufen.', ru='Я заблудился.',
      py='Ja sabludílsja.',
      k=[('verlaufen', ['заблудился', 'заблудилась'])],
      h='Als Frau: „заблудилась" (sabludílas). Wie bei jeder '
        'Vergangenheitsform richtet sich die Endung nach dem Sprecher.'),
 dict(kat='travel_transportation', de='Wie weit ist es zu Fuß?', ru='Сколько идти пешком?',
      py='Skólka ittí peschkóm?',
      k=[('zu_fuss', ['пешком'])]),
 dict(kat='travel_transportation', de='Wo ist der nächste Supermarkt?', ru='Где ближайший магазин?',
      py='Gdje blishájschij magasín?',
      k=[('supermarkt', ['магазин', 'ближайший магазин', 'супермаркет'])]),
 dict(kat='travel_transportation', de='Ist das in der Nähe?', ru='Это рядом?',
      py='Éta rjádam?',
      k=[('in_der_naehe', ['рядом', 'близко'])]),
 dict(kat='travel_transportation', de='Können Sie mir den Weg zeigen?', ru='Вы можете показать дорогу?',
      py='Wy móshetje pakasát darógu?',
      k=[('weg_zeigen', ['показать дорогу', 'дорогу'])]),

# ======================================================== university_studying
 dict(kat='university_studying', de='Ich habe drei Bücher.', ru='У меня три книги.',
      py='U menjá tri knígi.',
      k=[('drei_buecher', ['три книги', 'книги'])]),
 dict(kat='university_studying', de='Ist hier noch ein Platz frei?', ru='Здесь свободно?',
      py='Sdjes swabódna?',
      k=[('platz_frei', ['свободно', 'место свободно'])]),
 dict(kat='university_studying', de='Darf ich mich dazusetzen?', ru='Можно к вам присесть?',
      py='Móshna k wam prissjést?',
      k=[('dazusetzen', ['присесть', 'можно присесть'])]),
 dict(kat='university_studying', de='Bist du auch neu hier?', ru='Ты тоже здесь новенький?',
      py='Ty tósche sdjes nówenkij?',
      k=[('neu', ['новенький', 'новенькая', 'новый']),
         ('hier', ['здесь', 'тоже'])]),
 dict(kat='university_studying', de='Ich bin auch im ersten Semester.', ru='Я тоже на первом курсе.',
      py='Ja tósche na pjérwam kúrsje.',
      k=[('erstes_semester', ['на первом курсе', 'первый курс', 'первом'])],
      h='Russische Studierende zählen in „курс" (Studienjahr), nicht in '
        'Semestern — „первый курс" ist das erste Jahr.'),
 dict(kat='university_studying', de='Was studierst du?', ru='Что ты изучаешь?',
      py='Schto ty isutschájesch?',
      k=[('studieren', ['что ты изучаешь', 'изучаешь', 'учишься'])]),
 dict(kat='university_studying', de='Gehst du auch zur nächsten Vorlesung?', ru='Ты тоже пойдёшь на следующую лекцию?',
      py='Ty tósche pajdjósch na slédujuschtschuju ljékziju?',
      k=[('vorlesung', ['лекцию', 'лекция'])]),
 dict(kat='university_studying', de='Wollen wir uns nach der Vorlesung treffen?', ru='Встретимся после лекции?',
      py='Wstrjétimsja póslje ljékzii?',
      k=[('treffen', ['встретимся', 'встретиться']),
         ('nach_vorlesung', ['после лекции', 'лекции'])]),
 dict(kat='university_studying', de='Gibt es hier eine Gruppe für Austauschstudierende?',
      ru='Здесь есть группа для студентов по обмену?',
      py='Sdjes jest grúppa dlja studjéntaw pa obmjénu?',
      k=[('austauschstudierende', ['студентов по обмену', 'по обмену', 'обмен'])]),
 dict(kat='university_studying', de='Ich studiere Informatik.', ru='Я изучаю информатику.',
      py='Ja isutscháju informátiku.',
      k=[('studiere', ['изучаю', 'учусь']),
         ('informatik', ['информатику', 'информатика'])]),
 dict(kat='university_studying', de='In welchem Semester bist du?', ru='На каком ты курсе?',
      py='Na kakóm ty kúrsje?',
      k=[('semester_frage', ['на каком курсе', 'курс', 'курсе'])]),
 dict(kat='university_studying', de='Wann ist die Anmeldefrist?', ru='Когда срок подачи заявления?',
      py='Kagdá srok padátschi sajawlénija?',
      k=[('anmeldefrist', ['срок подачи', 'срок', 'заявления'])]),
 dict(kat='university_studying', de='Wie viele Credits brauche ich?', ru='Сколько зачётных единиц мне нужно?',
      py='Skólka satschótnych jedíniz mnje núshna?',
      k=[('credits', ['зачётных единиц', 'зачёты', 'кредиты'])],
      h='Offiziell „зачётные единицы", im Studentenmund einfach „зачёты". '
        'Das englische „credits" hilft nicht weiter.'),
 dict(kat='university_studying', de='Wo ist der Hörsaal?', ru='Где аудитория?',
      py='Gdje auditórija?',
      k=[('hoersaal', ['аудитория'])],
      h='„Аудитория" ist der Hörsaal, nicht das Publikum — ein falscher '
        'Freund für alle, die dabei an „Auditorium" denken.'),
 dict(kat='university_studying', de='Wann beginnt die Vorlesung?', ru='Когда начинается лекция?',
      py='Kagdá natschinájetsa ljékzija?',
      k=[('vorlesung_beginn', ['когда начинается', 'лекция'])]),
 dict(kat='university_studying', de='Wo finde ich die Bibliothek?', ru='Где находится библиотека?',
      py='Gdje nachóditsa bibliatjéka?',
      k=[('bibliothek', ['библиотека'])]),
 dict(kat='university_studying', de='Wer ist der Dozent für diesen Kurs?', ru='Кто преподаёт этот курс?',
      py='Kto prepadajót état kurs?',
      k=[('dozent', ['преподаёт', 'преподаватель'])],
      h='Dozenten spricht man mit VORNAME + VATERSNAME an — „Иван '
        'Петрович", nie mit dem Nachnamen und nie nur mit dem Vornamen. '
        'Das ist die auffälligste Regel des russischen Uni-Alltags.'),
 dict(kat='university_studying', de='Ich habe die Prüfung bestanden.', ru='Я сдал экзамен.',
      py='Ja sdal ekzámen.',
      k=[('pruefung_bestanden', ['сдал экзамен', 'сдала', 'сдал'])],
      h='„Сдать" heißt bestehen, „сдавать" nur ablegen — ein Buchstabe '
        'Unterschied entscheidet, ob du bestanden hast oder gerade erst '
        'antrittst.'),
 dict(kat='university_studying', de='Ich habe morgen eine Prüfung.', ru='Завтра у меня экзамен.',
      py='Sáwtra u menjá ekzámen.',
      k=[('pruefung_morgen', ['завтра экзамен', 'экзамен'])]),
 dict(kat='university_studying', de='Ich habe die Hausaufgabe vergessen.', ru='Я забыл домашнее задание.',
      py='Ja sabýl damáschneje sadánije.',
      k=[('hausaufgabe_vergessen', ['забыл домашнее задание', 'домашнее задание', 'домашку'])]),
 dict(kat='university_studying', de='Ich brauche mehr Zeit für die Hausarbeit.', ru='Мне нужно больше времени на работу.',
      py='Mnje núshna bólsche wrjémeni na rabótu.',
      k=[('mehr_zeit_hausarbeit', ['больше времени', 'работу', 'реферат'])]),
 dict(kat='university_studying', de='Kann ich dieses Buch ausleihen?', ru='Можно взять эту книгу?',
      py='Móshna wsjat étu knígu?',
      k=[('ausleihen', ['взять', 'можно взять'])]),
 dict(kat='university_studying', de='Können wir zusammen lernen?', ru='Давай готовиться вместе?',
      py='Dawáj gatówitsa wmjéstje?',
      k=[('zusammen_lernen', ['вместе', 'готовиться вместе', 'заниматься вместе'])]),
 dict(kat='university_studying', de='Ich unterrichte Chinesisch.', ru='Я преподаю китайский.',
      py='Ja prepadajú kitájskij.',
      k=[('unterrichte_chinesisch', ['преподаю китайский', 'китайский'])]),
]

AUSGELASSEN = []
