# -*- coding: utf-8 -*-
"""Die 500 haeufigsten russischen Woerter.

**Eigenstaendige Liste, KEINE Uebersetzung** - dieselbe Begruendung wie bei
`vokabeln_it.py`: Haeufigkeitslisten sind sprachgebunden.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen.

**KEINE ARTIKEL - und das ist kein Versehen.** Russisch hat weder einen
bestimmten noch einen unbestimmten Artikel; "стол" heisst je nach Kontext
Tisch, der Tisch oder ein Tisch. Die acht Artikel-Plaetze, die Italienisch
und Norwegisch belegen, gehen hier an Pronomen. Wer im Wortart-Filter der
Woerter-Wiederholung nach "Artikel" sucht, findet fuer Russisch deshalb
nichts - richtigerweise.

**Lautschrift ist Pflicht** (`py`) und folgt exakt den Regeln aus
`grundwortschatz_ru.py`: deutsch gelesen (ш=sch, ч=tsch, ж=sh, х=ch, в=w,
з=s, ц=z, ы=y), mit Betonungszeichen und mitgeschriebener Vokalreduktion
(unbetontes о wird a). Gelernt wird ueber die Umschrift, das Kyrillische
laeuft passiv mit.

**Verben stehen im Infinitiv.** Der russische Aspekt (vollendet/unvollendet)
ist an dieser Stelle bewusst NICHT abgebildet: eine Vokabelliste mit 500
Eintraegen wuerde sich verdoppeln, und fuer den Einstieg reicht die
unvollendete Form, die auch die Gegenwart bildet. Wo beide Formen im Alltag
gleich haeufig sind, steht ein Hinweis am Wort.
"""

WOERTER = [

# --------------------------------------------------------------- Pronomen
 dict(w='я', py='ja', de='ich', k='Pronomen', rang=1),
 dict(w='ты', py='ty', de='du', k='Pronomen', rang=2),
 dict(w='он', py='on', de='er', k='Pronomen', rang=3),
 dict(w='она', py='aná', de='sie', k='Pronomen', rang=4),
 dict(w='оно', py='anó', de='es', k='Pronomen', rang=5),
 dict(w='мы', py='my', de='wir', k='Pronomen', rang=6),
 dict(w='вы', py='wy', de='ihr, Sie', k='Pronomen', rang=7,
      hin='Dasselbe Wort fuer ihr und die hoefliche Sie-Anrede.'),
 dict(w='они', py='aní', de='sie (Mehrzahl)', k='Pronomen', rang=8),
 dict(w='меня', py='menjá', de='mich', k='Pronomen', rang=9),
 dict(w='мне', py='mnje', de='mir', k='Pronomen', rang=10),
 dict(w='тебя', py='tjebjá', de='dich', k='Pronomen', rang=11),
 dict(w='тебе', py='tjebjé', de='dir', k='Pronomen', rang=12),
 dict(w='его', py='jewó', de='ihn, sein', k='Pronomen', rang=13,
      hin='Geschrieben mit г, gesprochen mit w: jewó.'),
 dict(w='её', py='jejó', de='sie, ihr', k='Pronomen', rang=14),
 dict(w='нас', py='nas', de='uns', k='Pronomen', rang=15),
 dict(w='вас', py='was', de='euch, Sie', k='Pronomen', rang=16),
 dict(w='им', py='im', de='ihnen', k='Pronomen', rang=17),
 dict(w='себя', py='sebjá', de='sich', k='Pronomen', rang=18),
 dict(w='мой', py='moj', de='mein', k='Pronomen', rang=19),
 dict(w='твой', py='twoj', de='dein', k='Pronomen', rang=20),
 dict(w='наш', py='nasch', de='unser', k='Pronomen', rang=21),
 dict(w='ваш', py='wasch', de='euer, Ihr', k='Pronomen', rang=22),
 dict(w='свой', py='swoj', de='sein eigener', k='Pronomen', rang=23),
 dict(w='это', py='éta', de='das, dies', k='Pronomen', rang=24),
 dict(w='этот', py='état', de='dieser', k='Pronomen', rang=25),
 dict(w='тот', py='tot', de='jener', k='Pronomen', rang=26),
 dict(w='который', py='katóryj', de='welcher', k='Pronomen', rang=27),
 dict(w='весь', py='wjes', de='ganz, alles', k='Pronomen', rang=28),
 dict(w='все', py='wsje', de='alle', k='Pronomen', rang=29),
 dict(w='всё', py='wsjo', de='alles', k='Pronomen', rang=30),
 dict(w='кто-то', py='któ-ta', de='jemand', k='Pronomen', rang=31),
 dict(w='что-то', py='schtó-ta', de='etwas', k='Pronomen', rang=32),
 dict(w='никто', py='niktó', de='niemand', k='Pronomen', rang=33),
 dict(w='ничего', py='nitschewó', de='nichts', k='Pronomen', rang=34),
 dict(w='другой', py='drugój', de='anderer', k='Pronomen', rang=35),
 dict(w='такой', py='takój', de='solcher', k='Pronomen', rang=36),
 dict(w='каждый', py='káshdyj', de='jeder', k='Pronomen', rang=37),
 dict(w='сам', py='sam', de='selbst', k='Pronomen', rang=38),
 dict(w='оба', py='óba', de='beide', k='Pronomen', rang=39),
 dict(w='друг друга', py='drug drúga', de='einander', k='Pronomen', rang=40),

# -------------------------------------------------------------- Fragewort
 dict(w='что', py='schto', de='was', k='Fragewort', rang=41,
      hin='Geschrieben mit ч, gesprochen schto - nicht tschto.'),
 dict(w='где', py='gdje', de='wo', k='Fragewort', rang=42),
 dict(w='когда', py='kagdá', de='wann', k='Fragewort', rang=43),
 dict(w='как', py='kak', de='wie', k='Fragewort', rang=44),
 dict(w='почему', py='patschemú', de='warum', k='Fragewort', rang=45),
 dict(w='кто', py='kto', de='wer', k='Fragewort', rang=46),
 dict(w='сколько', py='skólka', de='wie viel', k='Fragewort', rang=47),
 dict(w='какой', py='kakój', de='welcher', k='Fragewort', rang=48),
 dict(w='куда', py='kudá', de='wohin', k='Fragewort', rang=49),

# ------------------------------------------------------------ Konjunktion
 dict(w='и', py='i', de='und', k='Konjunktion', rang=50),
 dict(w='или', py='íli', de='oder', k='Konjunktion', rang=51),
 dict(w='но', py='no', de='aber', k='Konjunktion', rang=52),
 dict(w='если', py='jésli', de='wenn, falls', k='Konjunktion', rang=53),
 dict(w='потому что', py='patamú schto', de='weil', k='Konjunktion', rang=54),
 dict(w='а', py='a', de='und, aber', k='Konjunktion', rang=55,
      hin='Der leise Gegensatz - "ich bin hier, а du dort". Nicht so stark wie но.'),
 dict(w='чтобы', py='schtóby', de='damit', k='Konjunktion', rang=56),
 dict(w='пока', py='paká', de='waehrend, tschuess', k='Konjunktion', rang=57),
 dict(w='хотя', py='chatjá', de='obwohl', k='Konjunktion', rang=58),
 dict(w='поэтому', py='paétamu', de='deshalb', k='Konjunktion', rang=59),
 dict(w='тоже', py='tósche', de='auch', k='Konjunktion', rang=60),
 dict(w='также', py='tákshe', de='ebenfalls', k='Konjunktion', rang=61),
 dict(w='зато', py='sató', de='dafuer aber', k='Konjunktion', rang=62),
 dict(w='значит', py='snátschit', de='also', k='Konjunktion', rang=63),

# ----------------------------------------------------------- Praeposition
 dict(w='в', py='w', de='in', k='Praeposition', rang=64),
 dict(w='на', py='na', de='auf', k='Praeposition', rang=65),
 dict(w='с', py='s', de='mit', k='Praeposition', rang=66),
 dict(w='у', py='u', de='bei', k='Praeposition', rang=67,
      hin='Traegt das russische Haben: у меня есть - bei mir ist, also ich habe.'),
 dict(w='из', py='is', de='aus', k='Praeposition', rang=68),
 dict(w='от', py='at', de='von', k='Praeposition', rang=69),
 dict(w='до', py='da', de='bis', k='Praeposition', rang=70),
 dict(w='для', py='dlja', de='fuer', k='Praeposition', rang=71),
 dict(w='по', py='pa', de='entlang, gemaess', k='Praeposition', rang=72),
 dict(w='за', py='sa', de='hinter, fuer', k='Praeposition', rang=73),
 dict(w='под', py='pad', de='unter', k='Praeposition', rang=74),
 dict(w='над', py='nad', de='ueber', k='Praeposition', rang=75),
 dict(w='перед', py='pjéred', de='vor', k='Praeposition', rang=76),
 dict(w='после', py='póslje', de='nach', k='Praeposition', rang=77),
 dict(w='между', py='méshdu', de='zwischen', k='Praeposition', rang=78),
 dict(w='без', py='bes', de='ohne', k='Praeposition', rang=79),
 dict(w='около', py='ókala', de='neben, ungefaehr', k='Praeposition', rang=80),
 dict(w='через', py='tschéres', de='durch, in (Zeit)', k='Praeposition', rang=81),
 dict(w='про', py='pra', de='ueber (Thema)', k='Praeposition', rang=82),
 dict(w='вокруг', py='wakrúg', de='um herum', k='Praeposition', rang=83),
 dict(w='против', py='prótiw', de='gegen', k='Praeposition', rang=84),
 dict(w='вместо', py='wmjésta', de='anstatt', k='Praeposition', rang=85),
 dict(w='кроме', py='krómje', de='ausser', k='Praeposition', rang=86),

# ----------------------------------------------------------------- Adverb
 dict(w='не', py='nje', de='nicht', k='Adverb', rang=87),
 dict(w='да', py='da', de='ja', k='Adverb', rang=88),
 dict(w='нет', py='njet', de='nein', k='Adverb', rang=89),
 dict(w='очень', py='ótschen', de='sehr', k='Adverb', rang=90),
 dict(w='много', py='mnóga', de='viel', k='Adverb', rang=91),
 dict(w='мало', py='mála', de='wenig', k='Adverb', rang=92),
 dict(w='немного', py='nemnóga', de='ein bisschen', k='Adverb', rang=93),
 dict(w='больше', py='bólsche', de='mehr', k='Adverb', rang=94),
 dict(w='меньше', py='ménsche', de='weniger', k='Adverb', rang=95),
 dict(w='хорошо', py='charaschó', de='gut', k='Adverb', rang=96),
 dict(w='плохо', py='plócha', de='schlecht', k='Adverb', rang=97),
 dict(w='здесь', py='sdjes', de='hier', k='Adverb', rang=98),
 dict(w='там', py='tam', de='dort', k='Adverb', rang=99),
 dict(w='сейчас', py='sitschás', de='jetzt', k='Adverb', rang=100),
 dict(w='сегодня', py='sewódnja', de='heute', k='Adverb', rang=101,
      hin='Wieder das г als w: sewódnja.'),
 dict(w='вчера', py='wtscherá', de='gestern', k='Adverb', rang=102),
 dict(w='завтра', py='sáwtra', de='morgen', k='Adverb', rang=103),
 dict(w='всегда', py='wsegdá', de='immer', k='Adverb', rang=104),
 dict(w='никогда', py='nikagdá', de='nie', k='Adverb', rang=105),
 dict(w='часто', py='tschásta', de='oft', k='Adverb', rang=106),
 dict(w='редко', py='rjétka', de='selten', k='Adverb', rang=107),
 dict(w='скоро', py='skóra', de='bald', k='Adverb', rang=108),
 dict(w='ещё', py='jeschtschó', de='noch', k='Adverb', rang=109),
 dict(w='уже', py='ushé', de='schon', k='Adverb', rang=110),
 dict(w='рано', py='rána', de='frueh', k='Adverb', rang=111),
 dict(w='поздно', py='pósna', de='spaet', k='Adverb', rang=112),
 dict(w='вместе', py='wmjéstje', de='zusammen', k='Adverb', rang=113),
 dict(w='только', py='tólka', de='nur', k='Adverb', rang=114),
 dict(w='может быть', py='móshet byt', de='vielleicht', k='Adverb', rang=115),
 dict(w='правда', py='práwda', de='wirklich', k='Adverb', rang=116),
 dict(w='так', py='tak', de='so', k='Adverb', rang=117),
 dict(w='достаточно', py='dastátatschna', de='genug', k='Adverb', rang=118),
 dict(w='почти', py='patschtí', de='fast', k='Adverb', rang=119),
 dict(w='именно', py='ímenna', de='genau', k='Adverb', rang=120),
 dict(w='конечно', py='kanjéschna', de='natuerlich', k='Adverb', rang=121,
      hin='Geschrieben mit ч, gesprochen mit sch: kanjéschna.'),
 dict(w='медленно', py='mjédlenna', de='langsam', k='Adverb', rang=122),
 dict(w='быстро', py='býstra', de='schnell', k='Adverb', rang=123),
 dict(w='опять', py='apját', de='wieder', k='Adverb', rang=124),
 dict(w='снова', py='snówa', de='erneut', k='Adverb', rang=125),
 dict(w='дома', py='dóma', de='zu Hause', k='Adverb', rang=126),
 dict(w='домой', py='damój', de='nach Hause', k='Adverb', rang=127),
 dict(w='сюда', py='sjudá', de='hierher', k='Adverb', rang=128),
 dict(w='рядом', py='rjádam', de='daneben, in der Naehe', k='Adverb', rang=129),
 dict(w='далеко', py='daljekó', de='weit', k='Adverb', rang=130),
 dict(w='близко', py='blíska', de='nah', k='Adverb', rang=131),
 dict(w='сразу', py='srásu', de='sofort', k='Adverb', rang=132),
 dict(w='наконец', py='nakanjéz', de='endlich', k='Adverb', rang=133),

# --------------------------------------------------------------- Zahlwort
 dict(w='ноль', py='nol', de='null', k='Zahlwort', rang=134),
 dict(w='один', py='adín', de='eins', k='Zahlwort', rang=135),
 dict(w='два', py='dwa', de='zwei', k='Zahlwort', rang=136),
 dict(w='три', py='tri', de='drei', k='Zahlwort', rang=137),
 dict(w='четыре', py='tschetýrje', de='vier', k='Zahlwort', rang=138),
 dict(w='пять', py='pjat', de='fuenf', k='Zahlwort', rang=139),
 dict(w='шесть', py='schest', de='sechs', k='Zahlwort', rang=140),
 dict(w='семь', py='sjem', de='sieben', k='Zahlwort', rang=141),
 dict(w='восемь', py='wóssem', de='acht', k='Zahlwort', rang=142),
 dict(w='девять', py='djéwjat', de='neun', k='Zahlwort', rang=143),
 dict(w='десять', py='djésjat', de='zehn', k='Zahlwort', rang=144),
 dict(w='одиннадцать', py='adínnadzat', de='elf', k='Zahlwort', rang=145),
 dict(w='двенадцать', py='dwenádzat', de='zwoelf', k='Zahlwort', rang=146),
 dict(w='тринадцать', py='trinádzat', de='dreizehn', k='Zahlwort', rang=147),
 dict(w='четырнадцать', py='tschetýrnadzat', de='vierzehn', k='Zahlwort', rang=148),
 dict(w='пятнадцать', py='pjatnádzat', de='fuenfzehn', k='Zahlwort', rang=149),
 dict(w='шестнадцать', py='schesnádzat', de='sechzehn', k='Zahlwort', rang=150),
 dict(w='семнадцать', py='semnádzat', de='siebzehn', k='Zahlwort', rang=151),
 dict(w='восемнадцать', py='wossemnádzat', de='achtzehn', k='Zahlwort', rang=152),
 dict(w='девятнадцать', py='dewjatnádzat', de='neunzehn', k='Zahlwort', rang=153),
 dict(w='двадцать', py='dwádzat', de='zwanzig', k='Zahlwort', rang=154),
 dict(w='тридцать', py='trídzat', de='dreissig', k='Zahlwort', rang=155),
 dict(w='сорок', py='sórak', de='vierzig', k='Zahlwort', rang=156),
 dict(w='пятьдесят', py='pjatdessját', de='fuenfzig', k='Zahlwort', rang=157),
 dict(w='шестьдесят', py='schesdessját', de='sechzig', k='Zahlwort', rang=158),
 dict(w='семьдесят', py='sjémdessjat', de='siebzig', k='Zahlwort', rang=159),
 dict(w='восемьдесят', py='wóssemdessjat', de='achtzig', k='Zahlwort', rang=160),
 dict(w='девяносто', py='dewjanósta', de='neunzig', k='Zahlwort', rang=161),
 dict(w='сто', py='sto', de='hundert', k='Zahlwort', rang=162),
 dict(w='тысяча', py='týssjatscha', de='tausend', k='Zahlwort', rang=163),
 dict(w='первый', py='pjérwyj', de='erster', k='Zahlwort', rang=164),
 dict(w='второй', py='wtarój', de='zweiter', k='Zahlwort', rang=165),
 dict(w='третий', py='trétij', de='dritter', k='Zahlwort', rang=166),
 dict(w='последний', py='paslédnij', de='letzter', k='Zahlwort', rang=167),
 dict(w='половина', py='palawína', de='Haelfte', k='Zahlwort', rang=168),
 dict(w='двойной', py='dwajnój', de='doppelt', k='Zahlwort', rang=169),
 dict(w='пара', py='pára', de='Paar', k='Zahlwort', rang=170),
 dict(w='миллион', py='millión', de='Million', k='Zahlwort', rang=171),

# -------------------------------------------------------------------- Verb
 dict(w='быть', py='byt', de='sein', k='Verb', rang=172,
      hin='In der Gegenwart faellt es weg: "я студент" heisst ich bin Student.'),
 dict(w='мочь', py='motsch', de='koennen', k='Verb', rang=173),
 dict(w='хотеть', py='chatjét', de='wollen', k='Verb', rang=174),
 dict(w='должен', py='dólshen', de='muessen', k='Verb', rang=175,
      hin='Grammatisch ein Adjektiv: должен / должна je nach Sprecher.'),
 dict(w='знать', py='snat', de='wissen', k='Verb', rang=176),
 dict(w='говорить', py='gawarít', de='sprechen', k='Verb', rang=177),
 dict(w='сказать', py='skasát', de='sagen', k='Verb', rang=178),
 dict(w='делать', py='djélat', de='machen', k='Verb', rang=179),
 dict(w='идти', py='ittí', de='gehen', k='Verb', rang=180),
 dict(w='ехать', py='jéchat', de='fahren', k='Verb', rang=181,
      hin='Russisch trennt gehen und fahren streng - идти zu Fuss, ехать mit Fahrzeug.'),
 dict(w='приходить', py='prichadít', de='kommen', k='Verb', rang=182),
 dict(w='видеть', py='wídjet', de='sehen', k='Verb', rang=183),
 dict(w='смотреть', py='smatrjét', de='schauen', k='Verb', rang=184),
 dict(w='давать', py='dawát', de='geben', k='Verb', rang=185),
 dict(w='брать', py='brat', de='nehmen', k='Verb', rang=186),
 dict(w='находить', py='nachadít', de='finden', k='Verb', rang=187),
 dict(w='слышать', py='slýschat', de='hoeren', k='Verb', rang=188),
 dict(w='класть', py='klast', de='legen', k='Verb', rang=189),
 dict(w='думать', py='dúmat', de='denken', k='Verb', rang=190),
 dict(w='верить', py='wjérit', de='glauben', k='Verb', rang=191),
 dict(w='понимать', py='panimát', de='verstehen', k='Verb', rang=192),
 dict(w='спрашивать', py='spráschiwat', de='fragen', k='Verb', rang=193),
 dict(w='отвечать', py='atwetschát', de='antworten', k='Verb', rang=194),
 dict(w='звать', py='swat', de='rufen, nennen', k='Verb', rang=195),
 dict(w='работать', py='rabótat', de='arbeiten', k='Verb', rang=196),
 dict(w='есть', py='jest', de='essen', k='Verb', rang=197,
      hin='Dasselbe Wort heisst auch "es gibt" - у меня есть, ich habe.'),
 dict(w='пить', py='pit', de='trinken', k='Verb', rang=198),
 dict(w='спать', py='spat', de='schlafen', k='Verb', rang=199),
 dict(w='жить', py='shyt', de='leben, wohnen', k='Verb', rang=200),
 dict(w='покупать', py='pakupát', de='kaufen', k='Verb', rang=201),
 dict(w='платить', py='platít', de='bezahlen', k='Verb', rang=202),
 dict(w='стоить', py='stóit', de='kosten', k='Verb', rang=203),
 dict(w='открывать', py='atkrywát', de='oeffnen', k='Verb', rang=204),
 dict(w='закрывать', py='sakrywát', de='schliessen', k='Verb', rang=205),
 dict(w='уезжать', py='ujeshát', de='abfahren', k='Verb', rang=206),
 dict(w='приезжать', py='prijeshát', de='ankommen', k='Verb', rang=207),
 dict(w='возвращаться', py='woswraschtschátsa', de='zurueckkehren', k='Verb', rang=208),
 dict(w='выходить', py='wychadít', de='hinausgehen', k='Verb', rang=209),
 dict(w='входить', py='wchadít', de='hineingehen', k='Verb', rang=210),
 dict(w='оставаться', py='astawátsa', de='bleiben', k='Verb', rang=211),
 dict(w='ждать', py='shdat', de='warten', k='Verb', rang=212),
 dict(w='искать', py='iskát', de='suchen', k='Verb', rang=213),
 dict(w='носить', py='nassít', de='tragen', k='Verb', rang=214),
 dict(w='использовать', py='ispólsawat', de='benutzen', k='Verb', rang=215),
 dict(w='помогать', py='pamagát', de='helfen', k='Verb', rang=216),
 dict(w='нравиться', py='nráwitsa', de='gefallen', k='Verb', rang=217,
      hin='Umgekehrt gebaut: мне нравится heisst woertlich es gefaellt mir.'),
 dict(w='любить', py='ljubít', de='lieben, moegen', k='Verb', rang=218),
 dict(w='учиться', py='utschítsa', de='lernen, studieren', k='Verb', rang=219),
 dict(w='изучать', py='isutschát', de='studieren', k='Verb', rang=220),
 dict(w='преподавать', py='prepadawát', de='unterrichten', k='Verb', rang=221),
 dict(w='читать', py='tschitát', de='lesen', k='Verb', rang=222),
 dict(w='писать', py='pissát', de='schreiben', k='Verb', rang=223),
 dict(w='помнить', py='pómnit', de='sich erinnern', k='Verb', rang=224),
 dict(w='забывать', py='sabywát', de='vergessen', k='Verb', rang=225),
 dict(w='начинать', py='natschinát', de='anfangen', k='Verb', rang=226),
 dict(w='кончать', py='kantschát', de='beenden', k='Verb', rang=227),
 dict(w='продолжать', py='pradalshát', de='fortsetzen', k='Verb', rang=228),
 dict(w='пробовать', py='próbawat', de='versuchen, probieren', k='Verb', rang=229),
 dict(w='терять', py='terját', de='verlieren', k='Verb', rang=230),
 dict(w='выигрывать', py='wyígrywat', de='gewinnen', k='Verb', rang=231),
 dict(w='играть', py='igrát', de='spielen', k='Verb', rang=232),
 dict(w='петь', py='pjet', de='singen', k='Verb', rang=233),
 dict(w='танцевать', py='tanzewát', de='tanzen', k='Verb', rang=234),
 dict(w='бегать', py='bjégat', de='rennen', k='Verb', rang=235),
 dict(w='водить', py='wadít', de='fahren, lenken', k='Verb', rang=236),
 dict(w='путешествовать', py='puteschéstwawat', de='reisen', k='Verb', rang=237),
 dict(w='посещать', py='passeschtschát', de='besuchen', k='Verb', rang=238),
 dict(w='встречать', py='wstretschát', de='treffen', k='Verb', rang=239),
 dict(w='знакомиться', py='snakómitsa', de='kennenlernen', k='Verb', rang=240),
 dict(w='жениться', py='shenítsa', de='heiraten', k='Verb', rang=241),
 dict(w='родиться', py='radítsa', de='geboren werden', k='Verb', rang=242),
 dict(w='умирать', py='umirát', de='sterben', k='Verb', rang=243),
 dict(w='менять', py='menját', de='aendern, wechseln', k='Verb', rang=244),
 dict(w='становиться', py='stanawítsa', de='werden', k='Verb', rang=245),
 dict(w='казаться', py='kasátsa', de='scheinen', k='Verb', rang=246),
 dict(w='случаться', py='slutschátsa', de='geschehen', k='Verb', rang=247),
 dict(w='нуждаться', py='nushdátsa', de='brauchen', k='Verb', rang=248),
 dict(w='надеяться', py='nadjéjatsa', de='hoffen', k='Verb', rang=249),
 dict(w='заказывать', py='sakásywat', de='bestellen', k='Verb', rang=250),
 dict(w='бронировать', py='branírawat', de='reservieren', k='Verb', rang=251),
 dict(w='снимать', py='snimát', de='mieten, abnehmen', k='Verb', rang=252),
 dict(w='подписывать', py='padpíssywat', de='unterschreiben', k='Verb', rang=253),
 dict(w='мыть', py='myt', de='waschen', k='Verb', rang=254),
 dict(w='готовить', py='gatówit', de='kochen, vorbereiten', k='Verb', rang=255),
 dict(w='убирать', py='ubirát', de='aufraeumen', k='Verb', rang=256),
 dict(w='смеяться', py='smejátsa', de='lachen', k='Verb', rang=257),
 dict(w='плакать', py='plákat', de='weinen', k='Verb', rang=258),
 dict(w='извинять', py='iswinját', de='entschuldigen', k='Verb', rang=259),
 dict(w='благодарить', py='blagadarít', de='danken', k='Verb', rang=260),
 dict(w='здороваться', py='sdarówatsa', de='gruessen', k='Verb', rang=261),
 dict(w='звонить', py='swanít', de='anrufen', k='Verb', rang=262),
 dict(w='показывать', py='pakásywat', de='zeigen', k='Verb', rang=263),
 dict(w='рассказывать', py='rasskásywat', de='erzaehlen', k='Verb', rang=264),
 dict(w='получать', py='palutschát', de='bekommen', k='Verb', rang=265),
 dict(w='держать', py='dershát', de='halten', k='Verb', rang=266),
 dict(w='останавливаться', py='astanáwliwatsa', de='anhalten', k='Verb', rang=267),
 dict(w='переезжать', py='pereeshát', de='umziehen', k='Verb', rang=268),
 dict(w='сидеть', py='ssidjét', de='sitzen', k='Verb', rang=269),
 dict(w='стоять', py='stajat', de='stehen', k='Verb', rang=270),

# ---------------------------------------------------------------- Adjektiv
 dict(w='хороший', py='charóschij', de='gut', k='Adjektiv', rang=271),
 dict(w='плохой', py='plachój', de='schlecht', k='Adjektiv', rang=272),
 dict(w='большой', py='balschój', de='gross', k='Adjektiv', rang=273),
 dict(w='маленький', py='málenkij', de='klein', k='Adjektiv', rang=274),
 dict(w='новый', py='nówyj', de='neu', k='Adjektiv', rang=275),
 dict(w='старый', py='stáryj', de='alt', k='Adjektiv', rang=276),
 dict(w='молодой', py='maladój', de='jung', k='Adjektiv', rang=277),
 dict(w='красивый', py='krassívyj', de='schoen', k='Adjektiv', rang=278),
 dict(w='длинный', py='dlínnyj', de='lang', k='Adjektiv', rang=279),
 dict(w='короткий', py='karótkij', de='kurz', k='Adjektiv', rang=280),
 dict(w='высокий', py='wyssókij', de='hoch, gross', k='Adjektiv', rang=281),
 dict(w='низкий', py='nískij', de='niedrig', k='Adjektiv', rang=282),
 dict(w='тёплый', py='tjóplyj', de='warm', k='Adjektiv', rang=283),
 dict(w='холодный', py='chalódnyj', de='kalt', k='Adjektiv', rang=284),
 dict(w='горячий', py='garjátschij', de='heiss', k='Adjektiv', rang=285),
 dict(w='лёгкий', py='ljóchkij', de='leicht, einfach', k='Adjektiv', rang=286),
 dict(w='трудный', py='trúdnyj', de='schwierig', k='Adjektiv', rang=287),
 dict(w='важный', py='wáshnyj', de='wichtig', k='Adjektiv', rang=288),
 dict(w='возможный', py='wasmóshnyj', de='moeglich', k='Adjektiv', rang=289),
 dict(w='настоящий', py='nastajáschtschij', de='echt, wahr', k='Adjektiv', rang=290),
 dict(w='неправильный', py='neprávilnyj', de='falsch', k='Adjektiv', rang=291),
 dict(w='правильный', py='práwilnyj', de='richtig', k='Adjektiv', rang=292),
 dict(w='дорогой', py='daragój', de='teuer, lieb', k='Adjektiv', rang=293),
 dict(w='дешёвый', py='deschówyj', de='billig', k='Adjektiv', rang=294),
 dict(w='бесплатный', py='besplátnyj', de='kostenlos', k='Adjektiv', rang=295),
 dict(w='полный', py='pólnyj', de='voll', k='Adjektiv', rang=296),
 dict(w='пустой', py='pustój', de='leer', k='Adjektiv', rang=297),
 dict(w='открытый', py='atkrýtyj', de='offen', k='Adjektiv', rang=298),
 dict(w='закрытый', py='sakrýtyj', de='geschlossen', k='Adjektiv', rang=299),
 dict(w='свободный', py='swabódnyj', de='frei', k='Adjektiv', rang=300),
 dict(w='занятый', py='sanjátyj', de='besetzt', k='Adjektiv', rang=301),
 dict(w='готовый', py='gatówyj', de='bereit', k='Adjektiv', rang=302),
 dict(w='усталый', py='ustályj', de='muede', k='Adjektiv', rang=303),
 dict(w='больной', py='balnój', de='krank', k='Adjektiv', rang=304),
 dict(w='здоровый', py='sdarówyj', de='gesund', k='Adjektiv', rang=305),
 dict(w='счастливый', py='schtschastlívyj', de='gluecklich', k='Adjektiv', rang=306),
 dict(w='грустный', py='grúsnyj', de='traurig', k='Adjektiv', rang=307),
 dict(w='довольный', py='dawólnyj', de='zufrieden', k='Adjektiv', rang=308),
 dict(w='злой', py='slój', de='wuetend, boese', k='Adjektiv', rang=309),
 dict(w='милый', py='mílyj', de='lieb, suess', k='Adjektiv', rang=310),
 dict(w='добрый', py='dóbryj', de='gut, guetig', k='Adjektiv', rang=311),
 dict(w='сильный', py='sílnyj', de='stark', k='Adjektiv', rang=312),
 dict(w='слабый', py='slábyj', de='schwach', k='Adjektiv', rang=313),
 dict(w='быстрый', py='býstryj', de='schnell', k='Adjektiv', rang=314),
 dict(w='медленный', py='mjédlennyj', de='langsam', k='Adjektiv', rang=315),
 dict(w='тяжёлый', py='tjashólyj', de='schwer', k='Adjektiv', rang=316),
 dict(w='чистый', py='tschístyj', de='sauber', k='Adjektiv', rang=317),
 dict(w='грязный', py='grjásnyj', de='schmutzig', k='Adjektiv', rang=318),
 dict(w='свежий', py='swjéshij', de='frisch', k='Adjektiv', rang=319),
 dict(w='сладкий', py='slátkij', de='suess', k='Adjektiv', rang=320),
 dict(w='солёный', py='saljónyj', de='salzig', k='Adjektiv', rang=321),
 dict(w='острый', py='óstryj', de='scharf', k='Adjektiv', rang=322),
 dict(w='вкусный', py='wkúsnyj', de='lecker', k='Adjektiv', rang=323),
 dict(w='белый', py='bjélyj', de='weiss', k='Adjektiv', rang=324),
 dict(w='чёрный', py='tschórnyj', de='schwarz', k='Adjektiv', rang=325),
 dict(w='красный', py='krásnyj', de='rot', k='Adjektiv', rang=326),
 dict(w='синий', py='sínij', de='blau', k='Adjektiv', rang=327),
 dict(w='зелёный', py='seljónyj', de='gruen', k='Adjektiv', rang=328),
 dict(w='жёлтый', py='shóltyj', de='gelb', k='Adjektiv', rang=329),
 dict(w='серый', py='sséryj', de='grau', k='Adjektiv', rang=330),
 dict(w='коричневый', py='karítschnewyj', de='braun', k='Adjektiv', rang=331),
 dict(w='русский', py='rússkij', de='russisch', k='Adjektiv', rang=332),
 dict(w='немецкий', py='nemjézkij', de='deutsch', k='Adjektiv', rang=333),
 dict(w='английский', py='anglíjskij', de='englisch', k='Adjektiv', rang=334),
 dict(w='иностранный', py='inastránnyj', de='auslaendisch', k='Adjektiv', rang=335),
 dict(w='следующий', py='slédujuschtschij', de='naechster', k='Adjektiv', rang=336),
 dict(w='прошлый', py='próschlyj', de='vergangener', k='Adjektiv', rang=337),
 dict(w='обычный', py='abýtschnyj', de='ueblich', k='Adjektiv', rang=338),
 dict(w='интересный', py='interjésnyj', de='interessant', k='Adjektiv', rang=339),
 dict(w='скучный', py='skúschnyj', de='langweilig', k='Adjektiv', rang=340),
 dict(w='опасный', py='apásnyj', de='gefaehrlich', k='Adjektiv', rang=341),
 dict(w='нужный', py='núshnyj', de='noetig', k='Adjektiv', rang=342),
 dict(w='весёлый', py='wessjólyj', de='froehlich', k='Adjektiv', rang=343),

# ------------------------------------------------------------------- Nomen
 dict(w='человек', py='tschelawjék', de='Mensch', k='Nomen', g='m', rang=344),
 dict(w='мужчина', py='muschtschína', de='Mann', k='Nomen', g='m', rang=345),
 dict(w='женщина', py='shénschtschina', de='Frau', k='Nomen', g='f', rang=346),
 dict(w='парень', py='párjen', de='Junge, fester Freund', k='Nomen', g='m', rang=347),
 dict(w='девушка', py='djéwuschka', de='Maedchen, feste Freundin', k='Nomen', g='f', rang=348),
 dict(w='ребёнок', py='rebjónak', de='Kind', k='Nomen', g='m', rang=349),
 dict(w='люди', py='ljúdi', de='Leute', k='Nomen', g='m', rang=350),
 dict(w='друг', py='drug', de='Freund', k='Nomen', g='m', rang=351),
 dict(w='семья', py='semjá', de='Familie', k='Nomen', g='f', rang=352),
 dict(w='отец', py='atjéz', de='Vater', k='Nomen', g='m', rang=353),
 dict(w='мать', py='mat', de='Mutter', k='Nomen', g='f', rang=354),
 dict(w='сын', py='syn', de='Sohn', k='Nomen', g='m', rang=355),
 dict(w='дочь', py='dotsch', de='Tochter', k='Nomen', g='f', rang=356),
 dict(w='брат', py='brat', de='Bruder', k='Nomen', g='m', rang=357),
 dict(w='сестра', py='sestrá', de='Schwester', k='Nomen', g='f', rang=358),
 dict(w='муж', py='mush', de='Ehemann', k='Nomen', g='m', rang=359),
 dict(w='жена', py='shená', de='Ehefrau', k='Nomen', g='f', rang=360),
 dict(w='имя', py='ímja', de='Name', k='Nomen', g='n', rang=361),
 dict(w='год', py='god', de='Jahr', k='Nomen', g='m', rang=362),
 dict(w='месяц', py='méssjaz', de='Monat', k='Nomen', g='m', rang=363),
 dict(w='неделя', py='nedjélja', de='Woche', k='Nomen', g='f', rang=364),
 dict(w='день', py='djen', de='Tag', k='Nomen', g='m', rang=365),
 dict(w='час', py='tschas', de='Stunde', k='Nomen', g='m', rang=366),
 dict(w='минута', py='minúta', de='Minute', k='Nomen', g='f', rang=367),
 dict(w='время', py='wrjémja', de='Zeit', k='Nomen', g='n', rang=368),
 dict(w='утро', py='útra', de='Morgen', k='Nomen', g='n', rang=369),
 dict(w='вечер', py='wjétscher', de='Abend', k='Nomen', g='m', rang=370),
 dict(w='ночь', py='notsch', de='Nacht', k='Nomen', g='f', rang=371),
 dict(w='выходные', py='wychadnýje', de='Wochenende', k='Nomen', g='m', rang=372),
 dict(w='дом', py='dom', de='Haus', k='Nomen', g='m', rang=373),
 dict(w='квартира', py='kwartíra', de='Wohnung', k='Nomen', g='f', rang=374),
 dict(w='комната', py='kómnata', de='Zimmer', k='Nomen', g='f', rang=375),
 dict(w='дверь', py='dwjer', de='Tuer', k='Nomen', g='f', rang=376),
 dict(w='окно', py='aknó', de='Fenster', k='Nomen', g='n', rang=377),
 dict(w='стол', py='stol', de='Tisch', k='Nomen', g='m', rang=378),
 dict(w='кровать', py='krawát', de='Bett', k='Nomen', g='f', rang=379),
 dict(w='кухня', py='kúchnja', de='Kueche', k='Nomen', g='f', rang=380),
 dict(w='туалет', py='tualjét', de='Toilette', k='Nomen', g='m', rang=381),
 dict(w='город', py='górad', de='Stadt', k='Nomen', g='m', rang=382),
 dict(w='страна', py='straná', de='Land', k='Nomen', g='f', rang=383),
 dict(w='улица', py='úliza', de='Strasse', k='Nomen', g='f', rang=384),
 dict(w='дорога', py='daróga', de='Weg', k='Nomen', g='f', rang=385),
 dict(w='место', py='mjésta', de='Platz, Ort', k='Nomen', g='n', rang=386),
 dict(w='магазин', py='magasín', de='Geschaeft', k='Nomen', g='m', rang=387),
 dict(w='рынок', py='rýnak', de='Markt', k='Nomen', g='m', rang=388),
 dict(w='ресторан', py='restarán', de='Restaurant', k='Nomen', g='m', rang=389),
 dict(w='кафе', py='kafé', de='Cafe', k='Nomen', g='n', rang=390),
 dict(w='отель', py='atél', de='Hotel', k='Nomen', g='m', rang=391),
 dict(w='больница', py='balníza', de='Krankenhaus', k='Nomen', g='f', rang=392),
 dict(w='аптека', py='aptjéka', de='Apotheke', k='Nomen', g='f', rang=393),
 dict(w='вокзал', py='wagsál', de='Bahnhof', k='Nomen', g='m', rang=394,
      hin='Der Fernbahnhof. Die Metro-Station heisst станция.'),
 dict(w='аэропорт', py='aerapórt', de='Flughafen', k='Nomen', g='m', rang=395),
 dict(w='поезд', py='pójesd', de='Zug', k='Nomen', g='m', rang=396),
 dict(w='автобус', py='awtóbus', de='Bus', k='Nomen', g='m', rang=397),
 dict(w='машина', py='maschýna', de='Auto', k='Nomen', g='f', rang=398),
 dict(w='билет', py='biljét', de='Fahrkarte', k='Nomen', g='m', rang=399),
 dict(w='багаж', py='bagásh', de='Gepaeck', k='Nomen', g='m', rang=400),
 dict(w='паспорт', py='páspart', de='Pass', k='Nomen', g='m', rang=401),
 dict(w='деньги', py='djéngi', de='Geld', k='Nomen', g='m', rang=402),
 dict(w='цена', py='zená', de='Preis', k='Nomen', g='f', rang=403),
 dict(w='счёт', py='schtschot', de='Rechnung', k='Nomen', g='m', rang=404),
 dict(w='карта', py='kárta', de='Karte', k='Nomen', g='f', rang=405),
 dict(w='работа', py='rabóta', de='Arbeit', k='Nomen', g='f', rang=406),
 dict(w='школа', py='schkóla', de='Schule', k='Nomen', g='f', rang=407),
 dict(w='университет', py='uniwersitjét', de='Universitaet', k='Nomen', g='m', rang=408),
 dict(w='студент', py='studjént', de='Student', k='Nomen', g='m', rang=409),
 dict(w='лекция', py='ljékzija', de='Vorlesung', k='Nomen', g='f', rang=410),
 dict(w='экзамен', py='ekzámen', de='Pruefung', k='Nomen', g='m', rang=411),
 dict(w='книга', py='kníga', de='Buch', k='Nomen', g='f', rang=412),
 dict(w='слово', py='slówa', de='Wort', k='Nomen', g='n', rang=413),
 dict(w='язык', py='jasýk', de='Sprache, Zunge', k='Nomen', g='m', rang=414),
 dict(w='вопрос', py='wapróss', de='Frage', k='Nomen', g='m', rang=415),
 dict(w='ответ', py='atwjét', de='Antwort', k='Nomen', g='m', rang=416),
 dict(w='проблема', py='prabljéma', de='Problem', k='Nomen', g='f', rang=417),
 dict(w='вещь', py='weschtsch', de='Sache, Ding', k='Nomen', g='f', rang=418),
 dict(w='вода', py='wadá', de='Wasser', k='Nomen', g='f', rang=419),
 dict(w='вино', py='winó', de='Wein', k='Nomen', g='n', rang=420),
 dict(w='пиво', py='píwa', de='Bier', k='Nomen', g='n', rang=421),
 dict(w='чай', py='tschaj', de='Tee', k='Nomen', g='m', rang=422),
 dict(w='кофе', py='kófje', de='Kaffee', k='Nomen', g='m', rang=423),
 dict(w='молоко', py='malakó', de='Milch', k='Nomen', g='n', rang=424),
 dict(w='хлеб', py='chljeb', de='Brot', k='Nomen', g='m', rang=425),
 dict(w='сыр', py='syr', de='Kaese', k='Nomen', g='m', rang=426),
 dict(w='мясо', py='mjássa', de='Fleisch', k='Nomen', g='n', rang=427),
 dict(w='рыба', py='rýba', de='Fisch', k='Nomen', g='f', rang=428),
 dict(w='фрукты', py='frúkty', de='Obst', k='Nomen', g='m', rang=429),
 dict(w='овощи', py='ówaschtschi', de='Gemuese', k='Nomen', g='m', rang=430),
 dict(w='сахар', py='sáchar', de='Zucker', k='Nomen', g='m', rang=431),
 dict(w='соль', py='sol', de='Salz', k='Nomen', g='f', rang=432),
 dict(w='еда', py='jedá', de='Essen', k='Nomen', g='f', rang=433),
 dict(w='завтрак', py='sáwtrak', de='Fruehstueck', k='Nomen', g='m', rang=434),
 dict(w='обед', py='abjéd', de='Mittagessen', k='Nomen', g='m', rang=435),
 dict(w='ужин', py='úshyn', de='Abendessen', k='Nomen', g='m', rang=436),
 dict(w='меню', py='menjú', de='Speisekarte', k='Nomen', g='n', rang=437),
 dict(w='тарелка', py='taréljka', de='Teller', k='Nomen', g='f', rang=438),
 dict(w='стакан', py='stakán', de='Glas', k='Nomen', g='m', rang=439),
 dict(w='бутылка', py='butýlka', de='Flasche', k='Nomen', g='f', rang=440),
 dict(w='голова', py='galawá', de='Kopf', k='Nomen', g='f', rang=441),
 dict(w='рука', py='ruká', de='Hand, Arm', k='Nomen', g='f', rang=442,
      hin='Ein Wort fuer Hand UND Arm - Russisch trennt die beiden nicht.'),
 dict(w='нога', py='nagá', de='Bein, Fuss', k='Nomen', g='f', rang=443,
      hin='Ebenso: ein Wort fuer Bein und Fuss.'),
 dict(w='глаз', py='glas', de='Auge', k='Nomen', g='m', rang=444),
 dict(w='рот', py='rot', de='Mund', k='Nomen', g='m', rang=445),
 dict(w='волосы', py='wólassy', de='Haare', k='Nomen', g='m', rang=446),
 dict(w='тело', py='téla', de='Koerper', k='Nomen', g='n', rang=447),
 dict(w='врач', py='wratsch', de='Arzt', k='Nomen', g='m', rang=448),
 dict(w='лекарство', py='lekárstwa', de='Medikament', k='Nomen', g='n', rang=449),
 dict(w='боль', py='bol', de='Schmerz', k='Nomen', g='f', rang=450),
 dict(w='температура', py='temperatúra', de='Fieber, Temperatur', k='Nomen', g='f', rang=451),
 dict(w='телефон', py='teljefón', de='Telefon, Handy', k='Nomen', g='m', rang=452),
 dict(w='номер', py='nómer', de='Nummer, Hotelzimmer', k='Nomen', g='m', rang=453),
 dict(w='музыка', py='músyka', de='Musik', k='Nomen', g='f', rang=454),
 dict(w='фильм', py='film', de='Film', k='Nomen', g='m', rang=455),
 dict(w='праздник', py='prásnik', de='Fest', k='Nomen', g='m', rang=456),
 dict(w='жизнь', py='shysn', de='Leben', k='Nomen', g='f', rang=457),
 dict(w='мир', py='mir', de='Welt, Frieden', k='Nomen', g='m', rang=458),
 dict(w='солнце', py='sónze', de='Sonne', k='Nomen', g='n', rang=459,
      hin='Das л faellt weg: sónze, nicht solnze.'),
 dict(w='дождь', py='doshd', de='Regen', k='Nomen', g='m', rang=460),
 dict(w='снег', py='snjeg', de='Schnee', k='Nomen', g='m', rang=461),
 dict(w='погода', py='pagóda', de='Wetter', k='Nomen', g='f', rang=462),
 dict(w='море', py='mórje', de='Meer', k='Nomen', g='n', rang=463),
 dict(w='гора', py='gará', de='Berg', k='Nomen', g='f', rang=464),
 dict(w='лес', py='ljes', de='Wald', k='Nomen', g='m', rang=465),
 dict(w='воздух', py='wósduch', de='Luft', k='Nomen', g='m', rang=466),
 dict(w='собака', py='ssabáka', de='Hund', k='Nomen', g='f', rang=467),
 dict(w='кошка', py='kóschka', de='Katze', k='Nomen', g='f', rang=468),
 dict(w='одежда', py='adjéshda', de='Kleidung', k='Nomen', g='f', rang=469),
 dict(w='платье', py='plátje', de='Kleid', k='Nomen', g='n', rang=470),
 dict(w='обувь', py='óbuw', de='Schuhe', k='Nomen', g='f', rang=471),
 dict(w='сумка', py='súmka', de='Tasche', k='Nomen', g='f', rang=472),
 dict(w='ключ', py='kljutsch', de='Schluessel', k='Nomen', g='m', rang=473),
 dict(w='подарок', py='padárak', de='Geschenk', k='Nomen', g='m', rang=474),
 dict(w='любовь', py='ljubów', de='Liebe', k='Nomen', g='f', rang=475),
 dict(w='часть', py='tschast', de='Teil', k='Nomen', g='f', rang=476),
 dict(w='конец', py='kanjéz', de='Ende', k='Nomen', g='m', rang=477),
 dict(w='начало', py='natschála', de='Anfang', k='Nomen', g='n', rang=478),
 dict(w='способ', py='spóssab', de='Art, Weise', k='Nomen', g='m', rang=479),
 dict(w='причина', py='pritschína', de='Grund', k='Nomen', g='f', rang=480),
 dict(w='пример', py='primjér', de='Beispiel', k='Nomen', g='m', rang=481),
 dict(w='идея', py='idjéja', de='Idee', k='Nomen', g='f', rang=482),
 dict(w='история', py='istórija', de='Geschichte', k='Nomen', g='f', rang=483),
 dict(w='страх', py='strach', de='Angst', k='Nomen', g='m', rang=484),
 dict(w='голод', py='gólad', de='Hunger', k='Nomen', g='m', rang=485),
 dict(w='сон', py='son', de='Schlaf, Traum', k='Nomen', g='m', rang=486),
 dict(w='скидка', py='skídka', de='Rabatt', k='Nomen', g='f', rang=487),
 dict(w='размер', py='rasmjér', de='Groesse', k='Nomen', g='m', rang=488),
 dict(w='вход', py='wchod', de='Eingang', k='Nomen', g='m', rang=489),
 dict(w='выход', py='wýchad', de='Ausgang', k='Nomen', g='m', rang=490),
 dict(w='помощь', py='pómaschtsch', de='Hilfe', k='Nomen', g='f', rang=491),
 dict(w='полиция', py='polízija', de='Polizei', k='Nomen', g='f', rang=492),
 dict(w='смена', py='smjéna', de='Schicht', k='Nomen', g='f', rang=493),
 dict(w='коллега', py='kalljéga', de='Kollege', k='Nomen', g='m', rang=494),
 dict(w='клиент', py='klijént', de='Kunde', k='Nomen', g='m', rang=495),
 dict(w='зарплата', py='sarpláta', de='Lohn', k='Nomen', g='f', rang=496),
 dict(w='отпуск', py='ótpusk', de='Urlaub', k='Nomen', g='m', rang=497),
 dict(w='перерыв', py='pererýw', de='Pause', k='Nomen', g='m', rang=498),
 dict(w='договор', py='dagawór', de='Vertrag', k='Nomen', g='m', rang=499),
 dict(w='встреча', py='wstrjétscha', de='Treffen, Termin', k='Nomen', g='f', rang=500),
]
