# -*- coding: utf-8 -*-
"""Die 500 haeufigsten italienischen Woerter.

**Eigenstaendige Liste, KEINE Uebersetzung.** Die 500 haeufigsten Woerter
des Italienischen sind nicht die Uebersetzungen der 500 haeufigsten
deutschen - deshalb hat auch keine der bestehenden Vokabeltabellen
denselben deutschen Bestand (spanisch_vocab und franz_vocab ueberlappen im
deutschen Feld nur zu rund 40%, gezaehlt am 2026-09-03). Die Reihenfolge
folgt der ueblichen Frequenzverteilung: Funktionswoerter zuerst, dann
Verben, dann Alltagsnomen.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen - dieselbe Einschraenkung wie bei der
HSK-Erweiterung fuer Chinesisch (siehe CLAUDE.md). Welche Woerter
dazugehoeren, ist belastbar; die genaue Rangfolge innerhalb eines
Zehnerblocks nicht.

**Der `rang` ist die Sortierung der Woerter-Wiederholung**, nicht mehr - er
entscheidet, was zuerst geuebt wird, und traegt keine Aussage darueber
hinaus.

**Nomen tragen IMMER ein Genus.** Ohne den Artikel ist ein italienisches
Nomen halb gelernt; das Pruefwerkzeug lehnt Nomen ohne `g` ab.

**Verben stehen im Infinitiv**, Adjektive in der maennlichen Einzahl - das
ist die Nennform, in der man sie nachschlaegt und lernt.
"""

WOERTER = [

# ---------------------------------------------------------------- Artikel
 dict(w='il', de='der', k='Artikel', rang=1),
 dict(w='la', de='die', k='Artikel', rang=2),
 dict(w='i', de='die (Mehrzahl, maennlich)', k='Artikel', rang=3),
 dict(w='le', de='die (Mehrzahl, weiblich)', k='Artikel', rang=4),
 dict(w='un', de='ein', k='Artikel', rang=5),
 dict(w='una', de='eine', k='Artikel', rang=6),
 dict(w='lo', de='der (vor s+Konsonant)', k='Artikel', rang=7),
 dict(w='gli', de='die (Mehrzahl, vor Vokal)', k='Artikel', rang=8),

# --------------------------------------------------------------- Pronomen
 dict(w='io', de='ich', k='Pronomen', rang=9),
 dict(w='tu', de='du', k='Pronomen', rang=10),
 dict(w='lui', de='er', k='Pronomen', rang=11),
 dict(w='lei', de='sie', k='Pronomen', rang=12,
      hin='Grossgeschrieben (Lei) ist es die Sie-Anrede.'),
 dict(w='noi', de='wir', k='Pronomen', rang=13),
 dict(w='voi', de='ihr', k='Pronomen', rang=14),
 dict(w='loro', de='sie (Mehrzahl)', k='Pronomen', rang=15),
 dict(w='mi', de='mir, mich', k='Pronomen', rang=16),
 dict(w='ti', de='dir, dich', k='Pronomen', rang=17),
 dict(w='ci', de='uns', k='Pronomen', rang=18),
 dict(w='vi', de='euch', k='Pronomen', rang=19),
 dict(w='entrambi', de='beide', k='Pronomen', rang=20),
 dict(w='ne', de='davon', k='Pronomen', rang=21),
 dict(w='questo', de='dieser', k='Pronomen', rang=22),
 dict(w='quello', de='jener', k='Pronomen', rang=23),
 dict(w='che', de='der, die, das', k='Pronomen', rang=24),
 dict(w='chi', de='wer', k='Pronomen', rang=25),
 dict(w='tutto', de='alles', k='Pronomen', rang=26),
 dict(w='qualcosa', de='etwas', k='Pronomen', rang=27),
 dict(w='qualcuno', de='jemand', k='Pronomen', rang=28),
 dict(w='niente', de='nichts', k='Pronomen', rang=29),
 dict(w='nessuno', de='niemand', k='Pronomen', rang=30),
 dict(w='altro', de='anderer', k='Pronomen', rang=31),
 dict(w='stesso', de='selbe', k='Pronomen', rang=32),
 dict(w='ognuno', de='jeder', k='Pronomen', rang=33),
 dict(w='mio', de='mein', k='Pronomen', rang=34),
 dict(w='tuo', de='dein', k='Pronomen', rang=35),
 dict(w='suo', de='sein, ihr', k='Pronomen', rang=36),
 dict(w='nostro', de='unser', k='Pronomen', rang=37),
 dict(w='vostro', de='euer', k='Pronomen', rang=38),
 dict(w='ciascuno', de='jeder einzelne', k='Pronomen', rang=39),
 dict(w='alcuni', de='einige', k='Pronomen', rang=40),

# -------------------------------------------------------------- Fragewort
 dict(w='cosa', de='was', k='Fragewort', rang=41,
      hin='Als Nomen (la cosa) heisst es Sache oder Ding.'),
 dict(w='dove', de='wo', k='Fragewort', rang=42),
 dict(w='quando', de='wann', k='Fragewort', rang=43),
 dict(w='come', de='wie', k='Fragewort', rang=44),
 dict(w='perche', de='warum', k='Fragewort', rang=45,
      ok=['warum', 'weil'],
      hin='Dasselbe Wort heisst warum UND weil - Frage und Antwort teilen sich eins.'),
 dict(w='quanto', de='wie viel', k='Fragewort', rang=46),
 dict(w='quale', de='welcher', k='Fragewort', rang=47),
 dict(w='quanti', de='wie viele', k='Fragewort', rang=48),
 dict(w='chissa', de='wer weiss', k='Fragewort', rang=49),

# ------------------------------------------------------------ Konjunktion
 dict(w='e', de='und', k='Konjunktion', rang=50),
 dict(w='o', de='oder', k='Konjunktion', rang=51),
 dict(w='ma', de='aber', k='Konjunktion', rang=52),
 dict(w='se', de='wenn', k='Konjunktion', rang=53),
 dict(w='anche', de='auch', k='Konjunktion', rang=54),
 dict(w='pero', de='jedoch', k='Konjunktion', rang=55),
 dict(w='quindi', de='also', k='Konjunktion', rang=56),
 dict(w='mentre', de='waehrend', k='Konjunktion', rang=57),
 dict(w='oppure', de='oder aber', k='Konjunktion', rang=58),
 dict(w='allora', de='dann', k='Konjunktion', rang=59),
 dict(w='invece', de='stattdessen', k='Konjunktion', rang=60),
 dict(w='comunque', de='jedenfalls', k='Konjunktion', rang=61),
 dict(w='siccome', de='da, weil', k='Konjunktion', rang=62),
 dict(w='benche', de='obwohl', k='Konjunktion', rang=63),

# ----------------------------------------------------------- Praeposition
 dict(w='di', de='von', k='Praeposition', rang=64),
 dict(w='a', de='zu, nach', k='Praeposition', rang=65),
 dict(w='da', de='von, seit', k='Praeposition', rang=66),
 dict(w='in', de='in', k='Praeposition', rang=67),
 dict(w='con', de='mit', k='Praeposition', rang=68),
 dict(w='su', de='auf', k='Praeposition', rang=69),
 dict(w='per', de='fuer', k='Praeposition', rang=70),
 dict(w='tra', de='zwischen', k='Praeposition', rang=71),
 dict(w='senza', de='ohne', k='Praeposition', rang=72),
 dict(w='sopra', de='ueber', k='Praeposition', rang=73),
 dict(w='sotto', de='unter', k='Praeposition', rang=74),
 dict(w='dopo', de='nach', k='Praeposition', rang=75),
 dict(w='prima', de='vor', k='Praeposition', rang=76),
 dict(w='davanti', de='vor, gegenueber', k='Praeposition', rang=77),
 dict(w='dietro', de='hinter', k='Praeposition', rang=78),
 dict(w='dentro', de='drinnen', k='Praeposition', rang=79),
 dict(w='fuori', de='draussen', k='Praeposition', rang=80),
 dict(w='accanto', de='neben', k='Praeposition', rang=81),
 dict(w='verso', de='Richtung', k='Praeposition', rang=82),
 dict(w='fino', de='bis', k='Praeposition', rang=83),
 dict(w='durante', de='waehrend', k='Praeposition', rang=84),
 dict(w='contro', de='gegen', k='Praeposition', rang=85),
 dict(w='vicino', de='nahe', k='Praeposition', rang=86),

# ----------------------------------------------------------------- Adverb
 dict(w='non', de='nicht', k='Adverb', rang=87),
 dict(w='si', de='ja', k='Adverb', rang=88,
      hin='Als unbetontes si heisst es ausserdem sich (si chiama) - gleiches Wort, andere Rolle.'),
 dict(w='no', de='nein', k='Adverb', rang=89),
 dict(w='piu', de='mehr', k='Adverb', rang=90),
 dict(w='meno', de='weniger', k='Adverb', rang=91),
 dict(w='molto', de='sehr, viel', k='Adverb', rang=92),
 dict(w='poco', de='wenig', k='Adverb', rang=93),
 dict(w='troppo', de='zu viel', k='Adverb', rang=94),
 dict(w='bene', de='gut', k='Adverb', rang=95),
 dict(w='male', de='schlecht', k='Adverb', rang=96),
 dict(w='qui', de='hier', k='Adverb', rang=97),
 dict(w='li', de='dort', k='Adverb', rang=98),
 dict(w='poi', de='dann, danach', k='Adverb', rang=99),
 dict(w='adesso', de='jetzt, sofort', k='Adverb', rang=100),
 dict(w='oggi', de='heute', k='Adverb', rang=101),
 dict(w='ieri', de='gestern', k='Adverb', rang=102),
 dict(w='domani', de='morgen', k='Adverb', rang=103),
 dict(w='sempre', de='immer', k='Adverb', rang=104),
 dict(w='mai', de='nie', k='Adverb', rang=105),
 dict(w='spesso', de='oft', k='Adverb', rang=106),
 dict(w='subito', de='sofort', k='Adverb', rang=107),
 dict(w='ancora', de='noch', k='Adverb', rang=108),
 dict(w='gia', de='schon', k='Adverb', rang=109),
 dict(w='presto', de='frueh, bald', k='Adverb', rang=110),
 dict(w='tardi', de='spaet', k='Adverb', rang=111),
 dict(w='insieme', de='zusammen', k='Adverb', rang=112),
 dict(w='solo', de='nur', k='Adverb', rang=113),
 dict(w='forse', de='vielleicht', k='Adverb', rang=114),
 dict(w='davvero', de='wirklich', k='Adverb', rang=115),
 dict(w='cosi', de='so', k='Adverb', rang=116),
 dict(w='abbastanza', de='genug', k='Adverb', rang=117),
 dict(w='quasi', de='fast', k='Adverb', rang=118),
 dict(w='proprio', de='genau, gerade', k='Adverb', rang=119),
 dict(w='certo', de='sicher', k='Adverb', rang=120),
 dict(w='sicuramente', de='bestimmt', k='Adverb', rang=121),
 dict(w='veramente', de='tatsaechlich', k='Adverb', rang=122),
 dict(w='lentamente', de='langsam', k='Adverb', rang=123),
 dict(w='velocemente', de='schnell', k='Adverb', rang=124),
 dict(w='volentieri', de='gerne', k='Adverb', rang=125),
 dict(w='purtroppo', de='leider', k='Adverb', rang=126),
 dict(w='magari', de='hoffentlich', k='Adverb', rang=127),
 dict(w='almeno', de='wenigstens', k='Adverb', rang=128),
 dict(w='soprattutto', de='vor allem', k='Adverb', rang=129),
 dict(w='dopodomani', de='uebermorgen', k='Adverb', rang=130),
 dict(w='stasera', de='heute Abend', k='Adverb', rang=131),
 dict(w='stamattina', de='heute Morgen', k='Adverb', rang=132),
 dict(w='sempre piu', de='immer mehr', k='Adverb', rang=133),

# --------------------------------------------------------------- Zahlwort
 dict(w='zero', de='null', k='Zahlwort', rang=134),
 dict(w='uno', de='eins', k='Zahlwort', rang=135),
 dict(w='due', de='zwei', k='Zahlwort', rang=136),
 dict(w='tre', de='drei', k='Zahlwort', rang=137),
 dict(w='quattro', de='vier', k='Zahlwort', rang=138),
 dict(w='cinque', de='fuenf', k='Zahlwort', rang=139),
 dict(w='sei', de='sechs', k='Zahlwort', rang=140),
 dict(w='sette', de='sieben', k='Zahlwort', rang=141),
 dict(w='otto', de='acht', k='Zahlwort', rang=142),
 dict(w='nove', de='neun', k='Zahlwort', rang=143),
 dict(w='dieci', de='zehn', k='Zahlwort', rang=144),
 dict(w='undici', de='elf', k='Zahlwort', rang=145),
 dict(w='dodici', de='zwoelf', k='Zahlwort', rang=146),
 dict(w='tredici', de='dreizehn', k='Zahlwort', rang=147),
 dict(w='quattordici', de='vierzehn', k='Zahlwort', rang=148),
 dict(w='quindici', de='fuenfzehn', k='Zahlwort', rang=149),
 dict(w='sedici', de='sechzehn', k='Zahlwort', rang=150),
 dict(w='diciassette', de='siebzehn', k='Zahlwort', rang=151),
 dict(w='diciotto', de='achtzehn', k='Zahlwort', rang=152),
 dict(w='diciannove', de='neunzehn', k='Zahlwort', rang=153),
 dict(w='venti', de='zwanzig', k='Zahlwort', rang=154),
 dict(w='trenta', de='dreissig', k='Zahlwort', rang=155),
 dict(w='quaranta', de='vierzig', k='Zahlwort', rang=156),
 dict(w='cinquanta', de='fuenfzig', k='Zahlwort', rang=157),
 dict(w='sessanta', de='sechzig', k='Zahlwort', rang=158),
 dict(w='settanta', de='siebzig', k='Zahlwort', rang=159),
 dict(w='ottanta', de='achtzig', k='Zahlwort', rang=160),
 dict(w='novanta', de='neunzig', k='Zahlwort', rang=161),
 dict(w='cento', de='hundert', k='Zahlwort', rang=162),
 dict(w='mille', de='tausend', k='Zahlwort', rang=163),
 dict(w='primo', de='erster', k='Zahlwort', rang=164),
 dict(w='secondo', de='zweiter', k='Zahlwort', rang=165),
 dict(w='terzo', de='dritter', k='Zahlwort', rang=166),
 dict(w='ultimo', de='letzter', k='Zahlwort', rang=167),
 dict(w='mezzo', de='halb', k='Zahlwort', rang=168),
 dict(w='doppio', de='doppelt', k='Zahlwort', rang=169),
 dict(w='paio', de='Paar', k='Zahlwort', rang=170),
 dict(w='milione', de='Million', k='Zahlwort', rang=171),

# -------------------------------------------------------------------- Verb
 dict(w='essere', de='sein', k='Verb', rang=172),
 dict(w='avere', de='haben', k='Verb', rang=173),
 dict(w='fare', de='machen, tun', k='Verb', rang=174),
 dict(w='dire', de='sagen', k='Verb', rang=175),
 dict(w='potere', de='koennen', k='Verb', rang=176),
 dict(w='volere', de='wollen', k='Verb', rang=177),
 dict(w='dovere', de='muessen', k='Verb', rang=178),
 dict(w='sapere', de='wissen, koennen', k='Verb', rang=179),
 dict(w='andare', de='gehen, fahren', k='Verb', rang=180),
 dict(w='venire', de='kommen', k='Verb', rang=181),
 dict(w='vedere', de='sehen', k='Verb', rang=182),
 dict(w='dare', de='geben', k='Verb', rang=183),
 dict(w='stare', de='sein, bleiben', k='Verb', rang=184,
      hin='Fuer Befinden und Orte: sto bene, sto a casa. "Essere" ist die Eigenschaft.'),
 dict(w='parlare', de='sprechen', k='Verb', rang=185),
 dict(w='prendere', de='nehmen', k='Verb', rang=186),
 dict(w='trovare', de='finden', k='Verb', rang=187),
 dict(w='sentire', de='hoeren, fuehlen', k='Verb', rang=188),
 dict(w='mettere', de='setzen, legen', k='Verb', rang=189),
 dict(w='guardare', de='schauen', k='Verb', rang=190),
 dict(w='pensare', de='denken', k='Verb', rang=191),
 dict(w='credere', de='glauben', k='Verb', rang=192),
 dict(w='capire', de='verstehen', k='Verb', rang=193),
 dict(w='chiedere', de='fragen', k='Verb', rang=194),
 dict(w='rispondere', de='antworten', k='Verb', rang=195),
 dict(w='chiamare', de='rufen, nennen', k='Verb', rang=196),
 dict(w='lavorare', de='arbeiten', k='Verb', rang=197),
 dict(w='mangiare', de='essen', k='Verb', rang=198),
 dict(w='bere', de='trinken', k='Verb', rang=199),
 dict(w='dormire', de='schlafen', k='Verb', rang=200),
 dict(w='vivere', de='leben', k='Verb', rang=201),
 dict(w='abitare', de='wohnen', k='Verb', rang=202),
 dict(w='comprare', de='kaufen', k='Verb', rang=203),
 dict(w='pagare', de='bezahlen', k='Verb', rang=204),
 dict(w='costare', de='kosten', k='Verb', rang=205),
 dict(w='aprire', de='oeffnen', k='Verb', rang=206),
 dict(w='chiudere', de='schliessen', k='Verb', rang=207),
 dict(w='partire', de='abfahren', k='Verb', rang=208),
 dict(w='arrivare', de='ankommen', k='Verb', rang=209),
 dict(w='tornare', de='zurueckkehren', k='Verb', rang=210),
 dict(w='uscire', de='hinausgehen', k='Verb', rang=211),
 dict(w='entrare', de='hineingehen', k='Verb', rang=212),
 dict(w='restare', de='bleiben', k='Verb', rang=213),
 dict(w='aspettare', de='warten', k='Verb', rang=214),
 dict(w='cercare', de='suchen', k='Verb', rang=215),
 dict(w='portare', de='bringen, tragen', k='Verb', rang=216),
 dict(w='usare', de='benutzen', k='Verb', rang=217),
 dict(w='aiutare', de='helfen', k='Verb', rang=218),
 dict(w='piacere', de='gefallen', k='Verb', rang=219,
      hin='Umgekehrt gebaut: "mi piace" heisst woertlich "es gefaellt mir".'),
 dict(w='amare', de='lieben', k='Verb', rang=220),
 dict(w='conoscere', de='kennen', k='Verb', rang=221),
 dict(w='studiare', de='studieren, lernen', k='Verb', rang=222),
 dict(w='imparare', de='lernen', k='Verb', rang=223),
 dict(w='insegnare', de='unterrichten', k='Verb', rang=224),
 dict(w='leggere', de='lesen', k='Verb', rang=225),
 dict(w='scrivere', de='schreiben', k='Verb', rang=226),
 dict(w='ricordare', de='sich erinnern', k='Verb', rang=227),
 dict(w='dimenticare', de='vergessen', k='Verb', rang=228),
 dict(w='cominciare', de='anfangen', k='Verb', rang=229),
 dict(w='finire', de='beenden', k='Verb', rang=230),
 dict(w='continuare', de='fortsetzen', k='Verb', rang=231),
 dict(w='provare', de='versuchen, probieren', k='Verb', rang=232),
 dict(w='riuscire', de='schaffen', k='Verb', rang=233),
 dict(w='perdere', de='verlieren', k='Verb', rang=234),
 dict(w='vincere', de='gewinnen', k='Verb', rang=235),
 dict(w='giocare', de='spielen', k='Verb', rang=236),
 dict(w='cantare', de='singen', k='Verb', rang=237),
 dict(w='ballare', de='tanzen', k='Verb', rang=238),
 dict(w='camminare', de='laufen, gehen', k='Verb', rang=239),
 dict(w='correre', de='rennen', k='Verb', rang=240),
 dict(w='guidare', de='fahren, lenken', k='Verb', rang=241),
 dict(w='viaggiare', de='reisen', k='Verb', rang=242),
 dict(w='visitare', de='besuchen', k='Verb', rang=243),
 dict(w='incontrare', de='treffen', k='Verb', rang=244),
 dict(w='conoscersi', de='sich kennenlernen', k='Verb', rang=245),
 dict(w='sposare', de='heiraten', k='Verb', rang=246),
 dict(w='nascere', de='geboren werden', k='Verb', rang=247),
 dict(w='morire', de='sterben', k='Verb', rang=248),
 dict(w='cambiare', de='aendern, wechseln', k='Verb', rang=249),
 dict(w='diventare', de='werden', k='Verb', rang=250),
 dict(w='sembrare', de='scheinen', k='Verb', rang=251),
 dict(w='succedere', de='geschehen', k='Verb', rang=252),
 dict(w='servire', de='dienen, brauchen', k='Verb', rang=253),
 dict(w='bisognare', de='noetig sein', k='Verb', rang=254),
 dict(w='preferire', de='bevorzugen', k='Verb', rang=255),
 dict(w='sperare', de='hoffen', k='Verb', rang=256),
 dict(w='ordinare', de='bestellen', k='Verb', rang=257),
 dict(w='prenotare', de='reservieren', k='Verb', rang=258),
 dict(w='affittare', de='mieten', k='Verb', rang=259),
 dict(w='firmare', de='unterschreiben', k='Verb', rang=260),
 dict(w='lavare', de='waschen', k='Verb', rang=261),
 dict(w='cucinare', de='kochen', k='Verb', rang=262),
 dict(w='pulire', de='putzen', k='Verb', rang=263),
 dict(w='ridere', de='lachen', k='Verb', rang=264),
 dict(w='piangere', de='weinen', k='Verb', rang=265),
 dict(w='dispiacere', de='leidtun', k='Verb', rang=266),
 dict(w='scusare', de='entschuldigen', k='Verb', rang=267),
 dict(w='ringraziare', de='danken', k='Verb', rang=268),
 dict(w='salutare', de='gruessen', k='Verb', rang=269),
 dict(w='telefonare', de='telefonieren', k='Verb', rang=270),

# ---------------------------------------------------------------- Adjektiv
 dict(w='buono', de='gut', k='Adjektiv', rang=271),
 dict(w='cattivo', de='schlecht, boese', k='Adjektiv', rang=272),
 dict(w='grande', de='gross', k='Adjektiv', rang=273),
 dict(w='piccolo', de='klein', k='Adjektiv', rang=274),
 dict(w='nuovo', de='neu', k='Adjektiv', rang=275),
 dict(w='vecchio', de='alt', k='Adjektiv', rang=276),
 dict(w='giovane', de='jung', k='Adjektiv', rang=277),
 dict(w='bello', de='schoen', k='Adjektiv', rang=278),
 dict(w='brutto', de='haesslich', k='Adjektiv', rang=279),
 dict(w='lungo', de='lang', k='Adjektiv', rang=280),
 dict(w='corto', de='kurz', k='Adjektiv', rang=281),
 dict(w='alto', de='hoch, gross', k='Adjektiv', rang=282),
 dict(w='basso', de='niedrig, klein', k='Adjektiv', rang=283),
 dict(w='caldo', de='warm, heiss', k='Adjektiv', rang=284),
 dict(w='freddo', de='kalt', k='Adjektiv', rang=285,
      hin='Als Nomen die Kaelte: ho freddo (mir ist kalt), fa freddo (es ist kalt).'),
 dict(w='facile', de='einfach', k='Adjektiv', rang=286),
 dict(w='difficile', de='schwierig', k='Adjektiv', rang=287),
 dict(w='importante', de='wichtig', k='Adjektiv', rang=288),
 dict(w='possibile', de='moeglich', k='Adjektiv', rang=289),
 dict(w='vero', de='wahr', k='Adjektiv', rang=290),
 dict(w='falso', de='falsch', k='Adjektiv', rang=291),
 dict(w='giusto', de='richtig', k='Adjektiv', rang=292),
 dict(w='sbagliato', de='verkehrt', k='Adjektiv', rang=293),
 dict(w='caro', de='teuer, lieb', k='Adjektiv', rang=294),
 dict(w='economico', de='guenstig', k='Adjektiv', rang=295),
 dict(w='gratis', de='kostenlos', k='Adjektiv', rang=296),
 dict(w='pieno', de='voll', k='Adjektiv', rang=297),
 dict(w='vuoto', de='leer', k='Adjektiv', rang=298),
 dict(w='aperto', de='offen', k='Adjektiv', rang=299),
 dict(w='chiuso', de='geschlossen', k='Adjektiv', rang=300),
 dict(w='libero', de='frei', k='Adjektiv', rang=301),
 dict(w='occupato', de='besetzt', k='Adjektiv', rang=302),
 dict(w='pronto', de='bereit, fertig', k='Adjektiv', rang=303),
 dict(w='stanco', de='muede', k='Adjektiv', rang=304),
 dict(w='malato', de='krank', k='Adjektiv', rang=305),
 dict(w='sano', de='gesund', k='Adjektiv', rang=306),
 dict(w='felice', de='gluecklich', k='Adjektiv', rang=307),
 dict(w='triste', de='traurig', k='Adjektiv', rang=308),
 dict(w='contento', de='zufrieden', k='Adjektiv', rang=309),
 dict(w='arrabbiato', de='wuetend', k='Adjektiv', rang=310),
 dict(w='simpatico', de='sympathisch', k='Adjektiv', rang=311),
 dict(w='gentile', de='freundlich', k='Adjektiv', rang=312),
 dict(w='bravo', de='tuechtig, gut', k='Adjektiv', rang=313),
 dict(w='forte', de='stark, laut', k='Adjektiv', rang=314),
 dict(w='debole', de='schwach', k='Adjektiv', rang=315),
 dict(w='veloce', de='schnell', k='Adjektiv', rang=316),
 dict(w='lento', de='langsam', k='Adjektiv', rang=317),
 dict(w='pesante', de='schwer', k='Adjektiv', rang=318),
 dict(w='leggero', de='leicht', k='Adjektiv', rang=319),
 dict(w='pulito', de='sauber', k='Adjektiv', rang=320),
 dict(w='sporco', de='schmutzig', k='Adjektiv', rang=321),
 dict(w='fresco', de='frisch, kuehl', k='Adjektiv', rang=322),
 dict(w='dolce', de='suess', k='Adjektiv', rang=323),
 dict(w='salato', de='salzig', k='Adjektiv', rang=324),
 dict(w='piccante', de='scharf', k='Adjektiv', rang=325),
 dict(w='buonissimo', de='sehr gut', k='Adjektiv', rang=326),
 dict(w='primo piano', de='erster Stock', k='Adjektiv', rang=327),
 dict(w='ultimo posto', de='letzter Platz', k='Adjektiv', rang=328),
 dict(w='bianco', de='weiss', k='Adjektiv', rang=329),
 dict(w='nero', de='schwarz', k='Adjektiv', rang=330),
 dict(w='rosso', de='rot', k='Adjektiv', rang=331),
 dict(w='blu', de='blau', k='Adjektiv', rang=332),
 dict(w='verde', de='gruen', k='Adjektiv', rang=333),
 dict(w='giallo', de='gelb', k='Adjektiv', rang=334),
 dict(w='grigio', de='grau', k='Adjektiv', rang=335),
 dict(w='marrone', de='braun', k='Adjektiv', rang=336),
 dict(w='italiano', de='italienisch', k='Adjektiv', rang=337),
 dict(w='tedesco', de='deutsch', k='Adjektiv', rang=338),
 dict(w='inglese', de='englisch', k='Adjektiv', rang=339),
 dict(w='straniero', de='auslaendisch', k='Adjektiv', rang=340),
 dict(w='prossimo', de='naechster', k='Adjektiv', rang=341),
 dict(w='scorso', de='letzter, vergangener', k='Adjektiv', rang=342),
 dict(w='solito', de='ueblich', k='Adjektiv', rang=343),

# ------------------------------------------------------------------- Nomen
 dict(w='uomo', de='Mann, Mensch', k='Nomen', g='m', rang=344),
 dict(w='donna', de='Frau', k='Nomen', g='f', rang=345),
 dict(w='ragazzo', de='Junge, fester Freund', k='Nomen', g='m', rang=346),
 dict(w='ragazza', de='Maedchen, feste Freundin', k='Nomen', g='f', rang=347),
 dict(w='bambino', de='Kind', k='Nomen', g='m', rang=348),
 dict(w='persona', de='Person', k='Nomen', g='f', rang=349),
 dict(w='gente', de='Leute', k='Nomen', g='f', rang=350),
 dict(w='amico', de='Freund', k='Nomen', g='m', rang=351),
 dict(w='famiglia', de='Familie', k='Nomen', g='f', rang=352),
 dict(w='padre', de='Vater', k='Nomen', g='m', rang=353),
 dict(w='madre', de='Mutter', k='Nomen', g='f', rang=354),
 dict(w='figlio', de='Sohn', k='Nomen', g='m', rang=355),
 dict(w='figlia', de='Tochter', k='Nomen', g='f', rang=356),
 dict(w='fratello', de='Bruder', k='Nomen', g='m', rang=357),
 dict(w='sorella', de='Schwester', k='Nomen', g='f', rang=358),
 dict(w='marito', de='Ehemann', k='Nomen', g='m', rang=359),
 dict(w='moglie', de='Ehefrau', k='Nomen', g='f', rang=360),
 dict(w='nome', de='Name', k='Nomen', g='m', rang=361),
 dict(w='anno', de='Jahr', k='Nomen', g='m', rang=362),
 dict(w='mese', de='Monat', k='Nomen', g='m', rang=363),
 dict(w='settimana', de='Woche', k='Nomen', g='f', rang=364),
 dict(w='giorno', de='Tag', k='Nomen', g='m', rang=365),
 dict(w='ora', de='Stunde, Uhrzeit', k='Nomen', g='f', rang=366,
      hin='Heisst als Adverb auch jetzt: ora vado - ich gehe jetzt.'),
 dict(w='minuto', de='Minute', k='Nomen', g='m', rang=367),
 dict(w='tempo', de='Zeit, Wetter', k='Nomen', g='m', rang=368,
      ok=['Zeit', 'Wetter'],
      hin='Dasselbe Wort fuer Zeit und Wetter - der Kontext entscheidet.'),
 dict(w='mattina', de='Morgen', k='Nomen', g='f', rang=369),
 dict(w='pomeriggio', de='Nachmittag', k='Nomen', g='m', rang=370),
 dict(w='sera', de='Abend', k='Nomen', g='f', rang=371),
 dict(w='notte', de='Nacht', k='Nomen', g='f', rang=372),
 dict(w='casa', de='Haus, Zuhause', k='Nomen', g='f', rang=373),
 dict(w='appartamento', de='Wohnung', k='Nomen', g='m', rang=374),
 dict(w='camera', de='Zimmer', k='Nomen', g='f', rang=375),
 dict(w='porta', de='Tuer', k='Nomen', g='f', rang=376),
 dict(w='finestra', de='Fenster', k='Nomen', g='f', rang=377),
 dict(w='tavolo', de='Tisch', k='Nomen', g='m', rang=378),
 dict(w='letto', de='Bett', k='Nomen', g='m', rang=379),
 dict(w='bagno', de='Bad, Toilette', k='Nomen', g='m', rang=380),
 dict(w='cucina', de='Kueche', k='Nomen', g='f', rang=381),
 dict(w='citta', de='Stadt', k='Nomen', g='f', rang=382),
 dict(w='paese', de='Dorf, Land', k='Nomen', g='m', rang=383),
 dict(w='via', de='Strasse', k='Nomen', g='f', rang=384),
 dict(w='strada', de='Weg, Strasse', k='Nomen', g='f', rang=385),
 dict(w='piazza', de='Platz', k='Nomen', g='f', rang=386),
 dict(w='posto', de='Platz, Ort', k='Nomen', g='m', rang=387),
 dict(w='negozio', de='Geschaeft', k='Nomen', g='m', rang=388),
 dict(w='mercato', de='Markt', k='Nomen', g='m', rang=389),
 dict(w='ristorante', de='Restaurant', k='Nomen', g='m', rang=390),
 dict(w='bar', de='Bar, Cafe', k='Nomen', g='m', rang=391,
      hin='Der italienische "bar" ist tagsueber das Cafe - dort gibt es Espresso, nicht nur Alkohol.'),
 dict(w='albergo', de='Hotel', k='Nomen', g='m', rang=392),
 dict(w='ospedale', de='Krankenhaus', k='Nomen', g='m', rang=393),
 dict(w='farmacia', de='Apotheke', k='Nomen', g='f', rang=394),
 dict(w='stazione', de='Bahnhof', k='Nomen', g='f', rang=395),
 dict(w='aeroporto', de='Flughafen', k='Nomen', g='m', rang=396),
 dict(w='treno', de='Zug', k='Nomen', g='m', rang=397),
 dict(w='autobus', de='Bus', k='Nomen', g='m', rang=398),
 dict(w='macchina', de='Auto', k='Nomen', g='f', rang=399),
 dict(w='biglietto', de='Fahrkarte, Ticket', k='Nomen', g='m', rang=400),
 dict(w='valigia', de='Koffer', k='Nomen', g='f', rang=401),
 dict(w='passaporto', de='Pass', k='Nomen', g='m', rang=402),
 dict(w='soldi', de='Geld', k='Nomen', g='m', rang=403),
 dict(w='prezzo', de='Preis', k='Nomen', g='m', rang=404),
 dict(w='conto', de='Rechnung', k='Nomen', g='m', rang=405),
 dict(w='carta', de='Karte, Papier', k='Nomen', g='f', rang=406),
 dict(w='lavoro', de='Arbeit', k='Nomen', g='m', rang=407),
 dict(w='scuola', de='Schule', k='Nomen', g='f', rang=408),
 dict(w='universita', de='Universitaet', k='Nomen', g='f', rang=409),
 dict(w='studente', de='Student', k='Nomen', g='m', rang=410),
 dict(w='lezione', de='Vorlesung, Unterricht', k='Nomen', g='f', rang=411),
 dict(w='esame', de='Pruefung', k='Nomen', g='m', rang=412),
 dict(w='libro', de='Buch', k='Nomen', g='m', rang=413),
 dict(w='parola', de='Wort', k='Nomen', g='f', rang=414),
 dict(w='lingua', de='Sprache, Zunge', k='Nomen', g='f', rang=415),
 dict(w='domanda', de='Frage', k='Nomen', g='f', rang=416),
 dict(w='risposta', de='Antwort', k='Nomen', g='f', rang=417),
 dict(w='problema', de='Problem', k='Nomen', g='m', rang=418,
      hin='Endet auf -a, ist aber MAENNLICH: il problema. Gilt fuer viele Woerter auf -ma.'),
 dict(w='momento', de='Moment, Augenblick', k='Nomen', g='m', rang=419),
 dict(w='acqua', de='Wasser', k='Nomen', g='f', rang=420),
 dict(w='vino', de='Wein', k='Nomen', g='m', rang=421),
 dict(w='birra', de='Bier', k='Nomen', g='f', rang=422),
 dict(w='caffe', de='Kaffee', k='Nomen', g='m', rang=423),
 dict(w='latte', de='Milch', k='Nomen', g='m', rang=424),
 dict(w='pane', de='Brot', k='Nomen', g='m', rang=425),
 dict(w='pasta', de='Nudeln, Teig', k='Nomen', g='f', rang=426),
 dict(w='pizza', de='Pizza', k='Nomen', g='f', rang=427),
 dict(w='carne', de='Fleisch', k='Nomen', g='f', rang=428),
 dict(w='pesce', de='Fisch', k='Nomen', g='m', rang=429),
 dict(w='frutta', de='Obst', k='Nomen', g='f', rang=430),
 dict(w='verdura', de='Gemuese', k='Nomen', g='f', rang=431),
 dict(w='formaggio', de='Kaese', k='Nomen', g='m', rang=432),
 dict(w='zucchero', de='Zucker', k='Nomen', g='m', rang=433),
 dict(w='sale', de='Salz', k='Nomen', g='m', rang=434),
 dict(w='colazione', de='Fruehstueck', k='Nomen', g='f', rang=435),
 dict(w='pranzo', de='Mittagessen', k='Nomen', g='m', rang=436),
 dict(w='cena', de='Abendessen', k='Nomen', g='f', rang=437),
 dict(w='cibo', de='Essen', k='Nomen', g='m', rang=438),
 dict(w='menu', de='Speisekarte', k='Nomen', g='m', rang=439),
 dict(w='piatto', de='Teller, Gericht', k='Nomen', g='m', rang=440),
 dict(w='bicchiere', de='Glas', k='Nomen', g='m', rang=441),
 dict(w='bottiglia', de='Flasche', k='Nomen', g='f', rang=442),
 dict(w='testa', de='Kopf', k='Nomen', g='f', rang=443),
 dict(w='mano', de='Hand', k='Nomen', g='f', rang=444,
      hin='Endet auf -o, ist aber WEIBLICH: la mano. Eine der wenigen Ausnahmen.'),
 dict(w='piede', de='Fuss', k='Nomen', g='m', rang=445),
 dict(w='occhio', de='Auge', k='Nomen', g='m', rang=446),
 dict(w='bocca', de='Mund', k='Nomen', g='f', rang=447),
 dict(w='braccio', de='Arm', k='Nomen', g='m', rang=448),
 dict(w='gamba', de='Bein', k='Nomen', g='f', rang=449),
 dict(w='capelli', de='Haare', k='Nomen', g='m', rang=450),
 dict(w='corpo', de='Koerper', k='Nomen', g='m', rang=451),
 dict(w='medico', de='Arzt', k='Nomen', g='m', rang=452),
 dict(w='medicina', de='Medizin', k='Nomen', g='f', rang=453),
 dict(w='dolore', de='Schmerz', k='Nomen', g='m', rang=454),
 dict(w='febbre', de='Fieber', k='Nomen', g='f', rang=455),
 dict(w='telefono', de='Telefon, Handy', k='Nomen', g='m', rang=456),
 dict(w='numero', de='Nummer, Zahl', k='Nomen', g='m', rang=457),
 dict(w='musica', de='Musik', k='Nomen', g='f', rang=458),
 dict(w='film', de='Film', k='Nomen', g='m', rang=459),
 dict(w='festa', de='Fest, Party', k='Nomen', g='f', rang=460),
 dict(w='vita', de='Leben', k='Nomen', g='f', rang=461),
 dict(w='mondo', de='Welt', k='Nomen', g='m', rang=462),
 dict(w='sole', de='Sonne', k='Nomen', g='m', rang=463),
 dict(w='pioggia', de='Regen', k='Nomen', g='f', rang=464),
 dict(w='mare', de='Meer', k='Nomen', g='m', rang=465),
 dict(w='montagna', de='Berg', k='Nomen', g='f', rang=466),
 dict(w='aria', de='Luft', k='Nomen', g='f', rang=467),
 dict(w='fuoco', de='Feuer', k='Nomen', g='m', rang=468),
 dict(w='cane', de='Hund', k='Nomen', g='m', rang=469),
 dict(w='gatto', de='Katze', k='Nomen', g='m', rang=470),
 dict(w='vestito', de='Kleid, Anzug', k='Nomen', g='m', rang=471),
 dict(w='scarpa', de='Schuh', k='Nomen', g='f', rang=472),
 dict(w='borsa', de='Tasche', k='Nomen', g='f', rang=473),
 dict(w='chiave', de='Schluessel', k='Nomen', g='f', rang=474),
 dict(w='regalo', de='Geschenk', k='Nomen', g='m', rang=475),
 dict(w='amore', de='Liebe', k='Nomen', g='m', rang=476),
 dict(w='parte', de='Teil', k='Nomen', g='f', rang=477),
 dict(w='fine', de='Ende', k='Nomen', g='f', rang=478),
 dict(w='inizio', de='Anfang', k='Nomen', g='m', rang=479),
 dict(w='modo', de='Art, Weise', k='Nomen', g='m', rang=480),
 dict(w='motivo', de='Grund', k='Nomen', g='m', rang=481),
 dict(w='esempio', de='Beispiel', k='Nomen', g='m', rang=482),
 dict(w='idea', de='Idee', k='Nomen', g='f', rang=483),
 dict(w='storia', de='Geschichte', k='Nomen', g='f', rang=484),
 dict(w='paura', de='Angst', k='Nomen', g='f', rang=485),
 dict(w='fame', de='Hunger', k='Nomen', g='f', rang=486),
 dict(w='sete', de='Durst', k='Nomen', g='f', rang=487),
 dict(w='sonno', de='Schlaf', k='Nomen', g='m', rang=488),
 dict(w='vento', de='Wind', k='Nomen', g='m', rang=489),
 dict(w='sconto', de='Rabatt', k='Nomen', g='m', rang=490),
 dict(w='taglia', de='Kleidergroesse', k='Nomen', g='f', rang=491),
 dict(w='ingresso', de='Eintritt, Eingang', k='Nomen', g='m', rang=492),
 dict(w='uscita', de='Ausgang', k='Nomen', g='f', rang=493),
 dict(w='aiuto', de='Hilfe', k='Nomen', g='m', rang=494),
 dict(w='polizia', de='Polizei', k='Nomen', g='f', rang=495),
 dict(w='documento', de='Dokument', k='Nomen', g='m', rang=496),
 dict(w='lavoratore', de='Arbeiter', k='Nomen', g='m', rang=497),
 dict(w='collega', de='Kollege', k='Nomen', g='m', rang=498),
 dict(w='cliente', de='Kunde', k='Nomen', g='m', rang=499),
 dict(w='turno', de='Schicht', k='Nomen', g='m', rang=500),
]
