# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/job_work (Deutsch).

42 Saetze. Zwei Konjunktionen: "oder" (543), "und" (548).
"""

TAGS = [
    {"id": 514, "tags": [{"w": "Ich", "c": None}, {"w": "suche", "c": "v"}, {"w": "Arbeit.", "c": "n"}]},
    {"id": 515, "tags": [{"w": "Suchen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "noch", "c": None},
                          {"w": "Leute?", "c": "n"}]},
    {"id": 516, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "eine", "c": None},
                          {"w": "Stelle", "c": "n"}, {"w": "frei?", "c": "a"}]},
    {"id": 517, "tags": [{"w": "Brauchen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "Hilfe", "c": "n"},
                          {"w": "in", "c": None}, {"w": "der", "c": None}, {"w": "Küche?", "c": "n"}]},
    {"id": 518, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "sofort", "c": None},
                          {"w": "anfangen.", "c": "v"}]},
    {"id": 519, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "für", "c": None},
                          {"w": "drei", "c": None}, {"w": "Monate", "c": "n"}, {"w": "hier.", "c": None}]},
    {"id": 520, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "schon", "c": None},
                          {"w": "in", "c": None}, {"w": "einem", "c": None}, {"w": "Restaurant", "c": "n"},
                          {"w": "gearbeitet.", "c": "v"}]},
    {"id": 521, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "keine", "c": None},
                          {"w": "Erfahrung.", "c": "n"}]},
    {"id": 522, "tags": [{"w": "Ich", "c": None}, {"w": "lerne", "c": "v"}, {"w": "schnell.", "c": "a"}]},
    {"id": 523, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "am", "c": None},
                          {"w": "Wochenende", "c": "n"}, {"w": "arbeiten.", "c": "v"}]},
    {"id": 524, "tags": [{"w": "Wann", "c": None}, {"w": "kann", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "anfangen?", "c": "v"}]},
    {"id": 525, "tags": [{"w": "Brauche", "c": "v"}, {"w": "ich", "c": None}, {"w": "eine", "c": None},
                          {"w": "Arbeitserlaubnis?", "c": "n"}]},
    {"id": 526, "tags": [{"w": "Wann", "c": None}, {"w": "fange", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "an?", "c": None}]},
    {"id": 527, "tags": [{"w": "Wann", "c": None}, {"w": "habe", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "frei?", "c": "a"}]},
    {"id": 528, "tags": [{"w": "Wie", "c": None}, {"w": "lange", "c": None}, {"w": "dauert", "c": "v"},
                          {"w": "die", "c": None}, {"w": "Schicht?", "c": "n"}]},
    {"id": 529, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "am", "c": None},
                          {"w": "Montag", "c": "n"}, {"w": "frei", "c": "a"}, {"w": "haben?", "c": "v"}]},
    {"id": 530, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "die", "c": None},
                          {"w": "Schicht", "c": "n"}, {"w": "tauschen?", "c": "v"}]},
    {"id": 531, "tags": [{"w": "Ich", "c": None}, {"w": "komme", "c": "v"}, {"w": "morgen", "c": None},
                          {"w": "früher.", "c": "a"}]},
    {"id": 532, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                          {"w": "Dienstplan?", "c": "n"}]},
    {"id": 533, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "neu", "c": "a"},
                          {"w": "hier.", "c": None}]},
    {"id": 534, "tags": [{"w": "Kannst", "c": "v"}, {"w": "du", "c": None}, {"w": "mir", "c": None},
                          {"w": "kurz", "c": "a"}, {"w": "helfen?", "c": "v"}]},
    {"id": 535, "tags": [{"w": "Wie", "c": None}, {"w": "macht", "c": "v"}, {"w": "man", "c": None},
                          {"w": "das?", "c": None}]},
    {"id": 536, "tags": [{"w": "Das", "c": None}, {"w": "habe", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "noch", "c": None}, {"w": "nie", "c": None}, {"w": "gemacht.", "c": "v"}]},
    {"id": 537, "tags": [{"w": "Wo", "c": None}, {"w": "finde", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "das?", "c": None}]},
    {"id": 538, "tags": [{"w": "Ich", "c": None}, {"w": "mache", "c": "v"}, {"w": "Pause.", "c": "n"}]},
    {"id": 539, "tags": [{"w": "Danke", "c": "v"}, {"w": "für", "c": None}, {"w": "deine", "c": None},
                          {"w": "Hilfe.", "c": "n"}]},
    {"id": 540, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "Ihnen", "c": None},
                          {"w": "helfen?", "c": "v"}]},
    {"id": 541, "tags": [{"w": "Der", "c": None}, {"w": "Nächste,", "c": "n"}, {"w": "bitte!", "c": None}]},
    {"id": 542, "tags": [{"w": "Möchten", "c": "v"}, {"w": "Sie", "c": None}, {"w": "noch", "c": None},
                          {"w": "etwas?", "c": None}]},
    {"id": 543, "tags": [{"w": "Zahlen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "bar", "c": "a"},
                          {"w": "oder", "c": "k"}, {"w": "mit", "c": None}, {"w": "Karte?", "c": "n"}]},
    {"id": 544, "tags": [{"w": "Tut", "c": "v"}, {"w": "mir", "c": None}, {"w": "leid,", "c": "a"},
                          {"w": "das", "c": None}, {"w": "haben", "c": "v"}, {"w": "wir", "c": None},
                          {"w": "nicht.", "c": None}]},
    {"id": 545, "tags": [{"w": "Ich", "c": None}, {"w": "hole", "c": "v"}, {"w": "meinen", "c": None},
                          {"w": "Kollegen.", "c": "n"}]},
    {"id": 546, "tags": [{"w": "Kommen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "gerne", "c": None},
                          {"w": "wieder!", "c": None}]},
    {"id": 547, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "heute", "c": None},
                          {"w": "nicht", "c": None}, {"w": "kommen.", "c": "v"}]},
    {"id": 548, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "krank", "c": "a"},
                          {"w": "und", "c": "k"}, {"w": "bleibe", "c": "v"}, {"w": "zu", "c": None},
                          {"w": "Hause.", "c": "n"}]},
    {"id": 549, "tags": [{"w": "Ich", "c": None}, {"w": "komme", "c": "v"}, {"w": "später.", "c": "a"}]},
    {"id": 550, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "einen", "c": None},
                          {"w": "Tag", "c": "n"}, {"w": "frei.", "c": "a"}]},
    {"id": 551, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "einen", "c": None},
                          {"w": "Arzttermin.", "c": "n"}]},
    {"id": 552, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "verdiene", "c": "v"},
                          {"w": "ich", "c": None}, {"w": "pro", "c": None}, {"w": "Stunde?", "c": "n"}]},
    {"id": 553, "tags": [{"w": "Wann", "c": None}, {"w": "bekomme", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "mein", "c": None}, {"w": "Geld?", "c": "n"}]},
    {"id": 554, "tags": [{"w": "Werde", "c": "v"}, {"w": "ich", "c": None}, {"w": "bar", "c": "a"},
                          {"w": "bezahlt?", "c": "v"}]},
    {"id": 555, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "zehn", "c": None},
                          {"w": "Stunden", "c": "n"}, {"w": "gearbeitet.", "c": "v"}]},
]
