# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/drinking_dining (Deutsch).

92 Saetze. Eine Konjunktion: "oder" (499).
"""

TAGS = [
    {"id": 79, "tags": [{"w": "Ich", "c": None}, {"w": "hätte", "c": "v"}, {"w": "gern", "c": None},
                         {"w": "einen", "c": None}, {"w": "Tisch", "c": "n"}, {"w": "für", "c": None},
                         {"w": "zwei", "c": None}, {"w": "Personen.", "c": "n"}]},
    {"id": 80, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "einen", "c": None},
                         {"w": "Tisch", "c": "n"}, {"w": "frei?", "c": "a"}]},
    {"id": 81, "tags": [{"w": "Die", "c": None}, {"w": "Speisekarte,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 82, "tags": [{"w": "Was", "c": None}, {"w": "empfehlen", "c": "v"}, {"w": "Sie?", "c": None}]},
    {"id": 83, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "Vegetarier.", "c": "n"}]},
    {"id": 84, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "eine", "c": None},
                         {"w": "Allergie", "c": "n"}, {"w": "gegen", "c": None}, {"w": "Nüsse.", "c": "n"}]},
    {"id": 85, "tags": [{"w": "Ich", "c": None}, {"w": "hätte", "c": "v"}, {"w": "gern", "c": None},
                         {"w": "ein", "c": None}, {"w": "Wasser,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 86, "tags": [{"w": "Was", "c": None}, {"w": "möchten", "c": "v"}, {"w": "Sie", "c": None},
                         {"w": "trinken?", "c": "v"}]},
    {"id": 87, "tags": [{"w": "Guten", "c": "a"}, {"w": "Appetit!", "c": "n"}]},
    {"id": 88, "tags": [{"w": "Das", "c": None}, {"w": "Essen", "c": "n"}, {"w": "schmeckt", "c": "v"},
                         {"w": "sehr", "c": None}, {"w": "gut.", "c": "a"}]},
    {"id": 89, "tags": [{"w": "Können", "c": "v"}, {"w": "wir", "c": None}, {"w": "bitte", "c": None},
                         {"w": "zahlen?", "c": "v"}]},
    {"id": 90, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "im", "c": None},
                         {"w": "Preis", "c": "n"}, {"w": "inbegriffen?", "c": "a"}]},
    {"id": 91, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "etwas", "c": None},
                         {"w": "bestellen.", "c": "v"}]},
    {"id": 93, "tags": [{"w": "Das", "c": None}, {"w": "habe", "c": "v"}, {"w": "ich", "c": None},
                         {"w": "nicht", "c": None}, {"w": "bestellt.", "c": "v"}]},
    {"id": 94, "tags": [{"w": "Können", "c": "v"}, {"w": "Sie", "c": None}, {"w": "mir", "c": None},
                         {"w": "die", "c": None}, {"w": "Rechnung", "c": "n"}, {"w": "getrennt", "c": "a"},
                         {"w": "bringen?", "c": "v"}]},
    {"id": 95, "tags": [{"w": "Gestern", "c": None}, {"w": "habe", "c": "v"}, {"w": "ich", "c": None},
                         {"w": "in", "c": None}, {"w": "einem", "c": None}, {"w": "Restaurant", "c": "n"},
                         {"w": "gegessen.", "c": "v"}]},
    {"id": 96, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "einen", "c": None},
                         {"w": "Tisch", "c": "n"}, {"w": "für", "c": None}, {"w": "morgen", "c": None},
                         {"w": "Abend", "c": "n"}, {"w": "reservieren.", "c": "v"}]},
    {"id": 97, "tags": [{"w": "Ist", "c": "v"}, {"w": "dieser", "c": None}, {"w": "Tisch", "c": "n"},
                         {"w": "schon", "c": None}, {"w": "reserviert?", "c": "a"}]},
    {"id": 98, "tags": [{"w": "Das", "c": None}, {"w": "war", "c": "v"}, {"w": "sehr", "c": None},
                         {"w": "lecker.", "c": "a"}]},
    {"id": 407, "tags": [{"w": "Was", "c": None}, {"w": "ist", "c": "v"}, {"w": "das?", "c": None}]},
    {"id": 408, "tags": [{"w": "Ich", "c": None}, {"w": "nehme", "c": "v"}, {"w": "das.", "c": None}]},
    {"id": 409, "tags": [{"w": "Eine", "c": None}, {"w": "Portion,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 410, "tags": [{"w": "Zwei", "c": None}, {"w": "davon,", "c": None}, {"w": "bitte.", "c": None}]},
    {"id": 411, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "kostet", "c": "v"},
                          {"w": "eine", "c": None}, {"w": "Portion?", "c": "n"}]},
    {"id": 412, "tags": [{"w": "Zum", "c": None}, {"w": "Mitnehmen,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 413, "tags": [{"w": "Ich", "c": None}, {"w": "esse", "c": "v"}, {"w": "hier.", "c": None}]},
    {"id": 414, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "frisch?", "c": "a"}]},
    {"id": 415, "tags": [{"w": "Was", "c": None}, {"w": "essen", "c": "v"}, {"w": "die", "c": None},
                          {"w": "anderen?", "c": None}]},
    {"id": 416, "tags": [{"w": "Das", "c": None}, {"w": "Gleiche,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 417, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "scharf?", "c": "a"}]},
    {"id": 418, "tags": [{"w": "Nicht", "c": None}, {"w": "scharf,", "c": "a"}, {"w": "bitte.", "c": None}]},
    {"id": 419, "tags": [{"w": "Ein", "c": None}, {"w": "bisschen", "c": None}, {"w": "scharf", "c": "a"},
                          {"w": "ist", "c": "v"}, {"w": "okay.", "c": "a"}]},
    {"id": 420, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "nicht", "c": None},
                          {"w": "scharf", "c": "a"}, {"w": "essen.", "c": "v"}]},
    {"id": 421, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "zu", "c": None},
                          {"w": "scharf!", "c": "a"}]},
    {"id": 422, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "etwas", "c": None},
                          {"w": "ohne", "c": None}, {"w": "Chili?", "c": "n"}]},
    {"id": 423, "tags": [{"w": "Wasser,", "c": "n"}, {"w": "schnell!", "c": "a"}]},
    {"id": 424, "tags": [{"w": "Wir", "c": None}, {"w": "essen", "c": "v"}, {"w": "zusammen.", "c": None}]},
    {"id": 425, "tags": [{"w": "Noch", "c": None}, {"w": "eine", "c": None}, {"w": "Schüssel", "c": "n"},
                          {"w": "Reis,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 426, "tags": [{"w": "Iss", "c": "v"}, {"w": "mehr!", "c": None}]},
    {"id": 427, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "satt.", "c": "a"}]},
    {"id": 428, "tags": [{"w": "Nimm", "c": "v"}, {"w": "doch!", "c": None}]},
    {"id": 429, "tags": [{"w": "Sollen", "c": "v"}, {"w": "wir", "c": None}, {"w": "noch", "c": None},
                          {"w": "etwas", "c": None}, {"w": "bestellen?", "c": "v"}]},
    {"id": 430, "tags": [{"w": "Ich", "c": None}, {"w": "lade", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "ein.", "c": None}]},
    {"id": 431, "tags": [{"w": "Danke", "c": "v"}, {"w": "fürs", "c": None}, {"w": "Einladen!", "c": "n"}]},
    {"id": 432, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "für", "c": None},
                          {"w": "alle.", "c": None}]},
    {"id": 433, "tags": [{"w": "Was", "c": None}, {"w": "haben", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "zu", "c": None}, {"w": "trinken?", "c": "v"}]},
    {"id": 434, "tags": [{"w": "Kaltes", "c": "a"}, {"w": "Wasser,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 435, "tags": [{"w": "Heißes", "c": "a"}, {"w": "Wasser,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 436, "tags": [{"w": "Ohne", "c": None}, {"w": "Eis,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 437, "tags": [{"w": "Ein", "c": None}, {"w": "Bier,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 438, "tags": [{"w": "Einen", "c": None}, {"w": "Tee,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 439, "tags": [{"w": "Ohne", "c": None}, {"w": "Zucker,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 440, "tags": [{"w": "Noch", "c": None}, {"w": "eins,", "c": None}, {"w": "bitte.", "c": None}]},
    {"id": 441, "tags": [{"w": "Für", "c": None}, {"w": "wie", "c": None}, {"w": "viele", "c": None},
                          {"w": "Personen?", "c": "n"}]},
    {"id": 442, "tags": [{"w": "Können", "c": "v"}, {"w": "wir", "c": None}, {"w": "draußen", "c": None},
                          {"w": "sitzen?", "c": "v"}]},
    {"id": 443, "tags": [{"w": "Wir", "c": None}, {"w": "warten.", "c": "v"}]},
    {"id": 444, "tags": [{"w": "Wie", "c": None}, {"w": "lange", "c": None}, {"w": "müssen", "c": "v"},
                          {"w": "wir", "c": None}, {"w": "warten?", "c": "v"}]},
    {"id": 445, "tags": [{"w": "Einen", "c": None}, {"w": "Moment,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 446, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "alles,", "c": None},
                          {"w": "danke.", "c": "v"}]},
    {"id": 447, "tags": [{"w": "Was", "c": None}, {"w": "ist", "c": "v"}, {"w": "in", "c": None},
                          {"w": "diesem", "c": None}, {"w": "Gericht?", "c": "n"}]},
    {"id": 448, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "eine", "c": None},
                          {"w": "Karte", "c": "n"}, {"w": "mit", "c": None}, {"w": "Bildern?", "c": "n"}]},
    {"id": 449, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "etwas", "c": None},
                          {"w": "Warmes.", "c": "a"}]},
    {"id": 450, "tags": [{"w": "Zusammen,", "c": None}, {"w": "bitte.", "c": None}]},
    {"id": 451, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "mit", "c": None},
                          {"w": "dem", "c": None}, {"w": "Handy", "c": "n"}, {"w": "bezahlen?", "c": "v"}]},
    {"id": 452, "tags": [{"w": "Stimmt", "c": "v"}, {"w": "so.", "c": None}]},
    {"id": 453, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "macht", "c": "v"},
                          {"w": "das?", "c": None}]},
    {"id": 454, "tags": [{"w": "Das", "c": None}, {"w": "mag", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "sehr.", "c": None}]},
    {"id": 455, "tags": [{"w": "Das", "c": None}, {"w": "mag", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "nicht.", "c": None}]},
    {"id": 456, "tags": [{"w": "Was", "c": None}, {"w": "ist", "c": "v"}, {"w": "das", "c": None},
                          {"w": "für", "c": None}, {"w": "ein", "c": None}, {"w": "Fleisch?", "c": "n"}]},
    {"id": 457, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "mir", "c": None},
                          {"w": "zu", "c": None}, {"w": "salzig.", "c": "a"}]},
    {"id": 458, "tags": [{"w": "Zwei", "c": None}, {"w": "Personen.", "c": "n"}]},
    {"id": 459, "tags": [{"w": "Zwei", "c": None}, {"w": "Portionen,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 460, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "frisch.", "c": "a"}]},
    {"id": 461, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "das", "c": None},
                          {"w": "Gleiche.", "c": "n"}]},
    {"id": 462, "tags": [{"w": "Können", "c": "v"}, {"w": "wir", "c": None}, {"w": "das", "c": None},
                          {"w": "einpacken?", "c": "v"}]},
    {"id": 463, "tags": [{"w": "Bist", "c": "v"}, {"w": "du", "c": None}, {"w": "satt?", "c": "a"}]},
    {"id": 464, "tags": [{"w": "Noch", "c": None}, {"w": "eine", "c": None}, {"w": "Schüssel,", "c": "n"},
                          {"w": "bitte.", "c": None}]},
    {"id": 465, "tags": [{"w": "Heute", "c": None}, {"w": "lade", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "ein.", "c": None}]},
    {"id": 466, "tags": [{"w": "Alle", "c": None}, {"w": "zusammen!", "c": None}]},
    {"id": 467, "tags": [{"w": "Zwei", "c": None}, {"w": "Flaschen,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 468, "tags": [{"w": "Mit", "c": None}, {"w": "Eis,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 469, "tags": [{"w": "Ein", "c": None}, {"w": "bisschen", "c": None}, {"w": "Zucker,", "c": "n"},
                          {"w": "bitte.", "c": None}]},
    {"id": 470, "tags": [{"w": "Nicht", "c": None}, {"w": "zu", "c": None}, {"w": "salzig,", "c": "a"},
                          {"w": "bitte.", "c": None}]},
    {"id": 471, "tags": [{"w": "Zeigen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "mir", "c": None},
                          {"w": "das", "c": None}, {"w": "mal.", "c": None}]},
    {"id": 472, "tags": [{"w": "Diese", "c": None}, {"w": "hier,", "c": None}, {"w": "bitte.", "c": None}]},
    {"id": 473, "tags": [{"w": "Wie", "c": None}, {"w": "lange", "c": None}, {"w": "dauert", "c": "v"},
                          {"w": "es?", "c": None}]},
    {"id": 474, "tags": [{"w": "Die", "c": None}, {"w": "anderen", "c": None}, {"w": "essen", "c": "v"},
                          {"w": "schon.", "c": None}]},
    {"id": 475, "tags": [{"w": "Kannst", "c": "v"}, {"w": "du", "c": None}, {"w": "scharf", "c": "a"},
                          {"w": "essen?", "c": "v"}]},
    {"id": 476, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "davon", "c": None},
                          {"w": "ein", "c": None}, {"w": "Bild?", "c": "n"}]},
    {"id": 497, "tags": [{"w": "Was", "c": None}, {"w": "gibt", "c": "v"}, {"w": "es", "c": None},
                          {"w": "gutes", "c": "a"}, {"w": "zu", "c": None}, {"w": "Essen?", "c": "n"}]},
    {"id": 498, "tags": [{"w": "Dieses", "c": None}, {"w": "Restaurant", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "sehr", "c": None}, {"w": "gut.", "c": "a"}]},
    {"id": 499, "tags": [{"w": "Trinkst", "c": "v"}, {"w": "du", "c": None}, {"w": "Kaffee", "c": "n"},
                          {"w": "oder", "c": "k"}, {"w": "Tee?", "c": "n"}]},
]
