# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/health_emergency (Deutsch).

76 Saetze, keine Konjunktion.
"""

TAGS = [
    {"id": 128, "tags": [{"w": "Mir", "c": None}, {"w": "geht", "c": "v"}, {"w": "es", "c": None},
                          {"w": "nicht", "c": None}, {"w": "gut.", "c": "a"}]},
    {"id": 129, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "Kopfschmerzen.", "c": "n"}]},
    {"id": 130, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "Fieber.", "c": "n"}]},
    {"id": 131, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "einen", "c": None},
                          {"w": "Arzt.", "c": "n"}]},
    {"id": 132, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "die", "c": None},
                          {"w": "nächste", "c": "a"}, {"w": "Apotheke?", "c": "n"}]},
    {"id": 133, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "allergisch", "c": "a"},
                          {"w": "gegen", "c": None}, {"w": "Penizillin.", "c": "n"}]},
    {"id": 134, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "mir", "c": None},
                          {"w": "den", "c": None}, {"w": "Fuß", "c": "n"}, {"w": "verletzt.", "c": "v"}]},
    {"id": 137, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "dringend", "c": "a"},
                          {"w": "Hilfe.", "c": "n"}]},
    {"id": 138, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "das", "c": None},
                          {"w": "nächste", "c": "a"}, {"w": "Krankenhaus?", "c": "n"}]},
    {"id": 139, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "meine", "c": None},
                          {"w": "Tabletten", "c": "n"}, {"w": "vergessen.", "c": "v"}]},
    {"id": 140, "tags": [{"w": "Wie", "c": None}, {"w": "oft", "c": None}, {"w": "muss", "c": "v"},
                          {"w": "ich", "c": None}, {"w": "das", "c": None}, {"w": "Medikament", "c": "n"},
                          {"w": "nehmen?", "c": "v"}]},
    {"id": 141, "tags": [{"w": "Ich", "c": None}, {"w": "fühle", "c": "v"}, {"w": "mich", "c": None},
                          {"w": "schwindelig.", "c": "a"}]},
    {"id": 145, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "meine", "c": None},
                          {"w": "Versicherungskarte", "c": "n"}, {"w": "vergessen.", "c": "v"}]},
    {"id": 322, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "krank.", "c": "a"}]},
    {"id": 323, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "erkältet.", "c": "a"}]},
    {"id": 324, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "Bauchschmerzen.", "c": "n"}]},
    {"id": 325, "tags": [{"w": "Mein", "c": None}, {"w": "Bein", "c": "n"}, {"w": "tut", "c": "v"},
                          {"w": "weh.", "c": "a"}]},
    {"id": 326, "tags": [{"w": "Hier", "c": None}, {"w": "tut", "c": "v"}, {"w": "es", "c": None},
                          {"w": "weh.", "c": "a"}]},
    {"id": 327, "tags": [{"w": "Mir", "c": None}, {"w": "geht", "c": "v"}, {"w": "es", "c": None},
                          {"w": "sehr", "c": None}, {"w": "schlecht.", "c": "a"}]},
    {"id": 328, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "müde.", "c": "a"}]},
    {"id": 329, "tags": [{"w": "Mir", "c": None}, {"w": "ist", "c": "v"}, {"w": "kalt.", "c": "a"}]},
    {"id": 330, "tags": [{"w": "Seit", "c": None}, {"w": "gestern.", "c": None}]},
    {"id": 331, "tags": [{"w": "Seit", "c": None}, {"w": "heute", "c": None}, {"w": "Morgen.", "c": "n"}]},
    {"id": 332, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "das", "c": None},
                          {"w": "Krankenhaus?", "c": "n"}]},
    {"id": 333, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "zum", "c": None},
                          {"w": "Arzt.", "c": "n"}]},
    {"id": 334, "tags": [{"w": "Wo", "c": None}, {"w": "melde", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "mich", "c": None}, {"w": "an?", "c": None}]},
    {"id": 335, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "mich", "c": None},
                          {"w": "anmelden.", "c": "v"}]},
    {"id": 336, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "keinen", "c": None},
                          {"w": "Termin.", "c": "n"}]},
    {"id": 337, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "einen", "c": None},
                          {"w": "Termin", "c": "n"}, {"w": "bekommen?", "c": "v"}]},
    {"id": 338, "tags": [{"w": "Wie", "c": None}, {"w": "lange", "c": None}, {"w": "muss", "c": "v"},
                          {"w": "ich", "c": None}, {"w": "warten?", "c": "v"}]},
    {"id": 339, "tags": [{"w": "Wie", "c": None}, {"w": "lange", "c": None}, {"w": "dauert", "c": "v"},
                          {"w": "das?", "c": None}]},
    {"id": 340, "tags": [{"w": "Bitte", "c": None}, {"w": "geben", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "mir", "c": None}, {"w": "ein", "c": None}, {"w": "Medikament.", "c": "n"}]},
    {"id": 341, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "westliche", "c": "a"},
                          {"w": "Medizin.", "c": "n"}]},
    {"id": 342, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "westliche", "c": "a"},
                          {"w": "Medizin?", "c": "n"}]},
    {"id": 343, "tags": [{"w": "Wie", "c": None}, {"w": "nehme", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "das", "c": None}, {"w": "Medikament?", "c": "n"}]},
    {"id": 344, "tags": [{"w": "Wie", "c": None}, {"w": "komme", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "dorthin?", "c": None}]},
    {"id": 345, "tags": [{"w": "Ich", "c": None}, {"w": "spreche", "c": "v"}, {"w": "kein", "c": None},
                          {"w": "Chinesisch.", "c": "n"}, {"w": "Können", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "es", "c": None}, {"w": "aufschreiben?", "c": "v"}]},
    {"id": 346, "tags": [{"w": "Bitte", "c": None}, {"w": "helfen", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "mir!", "c": None}]},
    {"id": 347, "tags": [{"w": "Bitte", "c": None}, {"w": "rufen", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "einen", "c": None}, {"w": "Krankenwagen!", "c": "n"}]},
    {"id": 348, "tags": [{"w": "Ist", "c": "v"}, {"w": "der", "c": None}, {"w": "Krankenwagen", "c": "n"},
                          {"w": "schon", "c": None}, {"w": "unterwegs?", "c": None}]},
    {"id": 349, "tags": [{"w": "Rufen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "bitte", "c": None},
                          {"w": "120", "c": None}, {"w": "an.", "c": None}]},
    {"id": 350, "tags": [{"w": "Jemand", "c": None}, {"w": "ist", "c": "v"}, {"w": "verletzt.", "c": "a"}]},
    {"id": 351, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "verletzt.", "c": "a"}]},
    {"id": 352, "tags": [{"w": "Schnell,", "c": "a"}, {"w": "bitte!", "c": None}]},
    {"id": 353, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "etwas", "c": None},
                          {"w": "aus", "c": None}, {"w": "der", "c": None}, {"w": "Apotheke.", "c": "n"}]},
    {"id": 354, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "allein", "c": "a"},
                          {"w": "hier.", "c": None}]},
    {"id": 355, "tags": [{"w": "Bitte", "c": None}, {"w": "rufen", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "meinen", "c": None}, {"w": "Freund", "c": "n"}, {"w": "an.", "c": None}]},
    {"id": 356, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "eine", "c": None},
                          {"w": "Allergie.", "c": "n"}]},
    {"id": 357, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "allergisch", "c": "a"},
                          {"w": "gegen", "c": None}, {"w": "dieses", "c": None}, {"w": "Medikament.", "c": "n"}]},
    {"id": 358, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "allergisch", "c": "a"},
                          {"w": "gegen", "c": None}, {"w": "Erdnüsse.", "c": "n"}]},
    {"id": 359, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "keine", "c": None},
                          {"w": "Erdnüsse", "c": "n"}, {"w": "essen.", "c": "v"}]},
    {"id": 360, "tags": [{"w": "Sind", "c": "v"}, {"w": "da", "c": None}, {"w": "Erdnüsse", "c": "n"},
                          {"w": "drin?", "c": None}]},
    {"id": 361, "tags": [{"w": "Bitte", "c": None}, {"w": "ohne", "c": None}, {"w": "Erdnüsse.", "c": "n"}]},
    {"id": 362, "tags": [{"w": "Bitte", "c": None}, {"w": "ohne", "c": None}, {"w": "Milch.", "c": "n"}]},
    {"id": 363, "tags": [{"w": "Ich", "c": None}, {"w": "vertrage", "c": "v"}, {"w": "keine", "c": None},
                          {"w": "Milch.", "c": "n"}]},
    {"id": 364, "tags": [{"w": "Was", "c": None}, {"w": "ist", "c": "v"}, {"w": "da", "c": None},
                          {"w": "drin?", "c": None}]},
    {"id": 365, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "mein", "c": None},
                          {"w": "Allergiemedikament", "c": "n"}, {"w": "dabei.", "c": None}]},
    {"id": 366, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "für", "c": None},
                          {"w": "mich", "c": None}, {"w": "sehr", "c": None}, {"w": "gefährlich.", "c": "a"}]},
    {"id": 367, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "gefährlich?", "c": "a"}]},
    {"id": 368, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "kostet", "c": "v"},
                          {"w": "das?", "c": None}]},
    {"id": 369, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "eine", "c": None},
                          {"w": "Versicherung.", "c": "n"}]},
    {"id": 370, "tags": [{"w": "Nehmen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "meine", "c": None},
                          {"w": "Versicherung?", "c": "n"}]},
    {"id": 371, "tags": [{"w": "Muss", "c": "v"}, {"w": "ich", "c": None}, {"w": "vorher", "c": None},
                          {"w": "bezahlen?", "c": "v"}]},
    {"id": 372, "tags": [{"w": "Bitte", "c": None}, {"w": "geben", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "mir", "c": None}, {"w": "eine", "c": None}, {"w": "Quittung.", "c": "n"}]},
    {"id": 373, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Quittung", "c": "n"}, {"w": "für", "c": None}, {"w": "meine", "c": None},
                          {"w": "Versicherung.", "c": "n"}]},
    {"id": 374, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "mit", "c": None},
                          {"w": "dem", "c": None}, {"w": "Handy", "c": "n"}, {"w": "bezahlen?", "c": "v"}]},
    {"id": 375, "tags": [{"w": "Nehmen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "auch", "c": None},
                          {"w": "Karte?", "c": "n"}]},
    {"id": 376, "tags": [{"w": "Hier", "c": None}, {"w": "ist", "c": "v"}, {"w": "meine", "c": None},
                          {"w": "Karte.", "c": "n"}]},
    {"id": 377, "tags": [{"w": "Zuerst", "c": None}, {"w": "anmelden,", "c": "v"}, {"w": "dann", "c": None},
                          {"w": "bezahlen?", "c": "v"}]},
    {"id": 378, "tags": [{"w": "Wo", "c": None}, {"w": "bekomme", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "die", "c": None}, {"w": "Quittung?", "c": "n"}]},
    {"id": 379, "tags": [{"w": "Wo", "c": None}, {"w": "kann", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "bezahlen?", "c": "v"}]},
    {"id": 380, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "zu", "c": None},
                          {"w": "teuer.", "c": "a"}]},
    {"id": 381, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "nicht", "c": None},
                          {"w": "genug", "c": None}, {"w": "Geld", "c": "n"}, {"w": "dabei.", "c": None}]},
    {"id": 382, "tags": [{"w": "Reicht", "c": "v"}, {"w": "das?", "c": None}]},
    {"id": 495, "tags": [{"w": "Bitte", "c": None}, {"w": "rufen", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "die", "c": None}, {"w": "Polizei!", "c": "n"}]},
    {"id": 496, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Polizei", "c": "n"}, {"w": "rufen.", "c": "v"}]},
]
