# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/university_studying (Deutsch).

24 Saetze, keine Konjunktion.
"""

TAGS = [
    {"id": 160, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                          {"w": "Hörsaal?", "c": "n"}]},
    {"id": 161, "tags": [{"w": "Wann", "c": None}, {"w": "beginnt", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Vorlesung?", "c": "n"}]},
    {"id": 162, "tags": [{"w": "Ich", "c": None}, {"w": "studiere", "c": "v"}, {"w": "Informatik.", "c": "n"}]},
    {"id": 163, "tags": [{"w": "In", "c": None}, {"w": "welchem", "c": None}, {"w": "Semester", "c": "n"},
                          {"w": "bist", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 164, "tags": [{"w": "Wann", "c": None}, {"w": "ist", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Anmeldefrist?", "c": "n"}]},
    {"id": 165, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Prüfung", "c": "n"}, {"w": "bestanden.", "c": "v"}]},
    {"id": 166, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "morgen", "c": None},
                          {"w": "eine", "c": None}, {"w": "Prüfung.", "c": "n"}]},
    {"id": 167, "tags": [{"w": "Wo", "c": None}, {"w": "finde", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "die", "c": None}, {"w": "Bibliothek?", "c": "n"}]},
    {"id": 168, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "dieses", "c": None},
                          {"w": "Buch", "c": "n"}, {"w": "ausleihen?", "c": "v"}]},
    {"id": 169, "tags": [{"w": "Wie", "c": None}, {"w": "viele", "c": None}, {"w": "Credits", "c": "n"},
                          {"w": "brauche", "c": "v"}, {"w": "ich?", "c": None}]},
    {"id": 170, "tags": [{"w": "Wer", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                          {"w": "Dozent", "c": "n"}, {"w": "für", "c": None}, {"w": "diesen", "c": None},
                          {"w": "Kurs?", "c": "n"}]},
    {"id": 171, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Hausaufgabe", "c": "n"}, {"w": "vergessen.", "c": "v"}]},
    {"id": 172, "tags": [{"w": "Können", "c": "v"}, {"w": "wir", "c": None}, {"w": "zusammen", "c": None},
                          {"w": "lernen?", "c": "v"}]},
    {"id": 173, "tags": [{"w": "Ich", "c": None}, {"w": "brauche", "c": "v"}, {"w": "mehr", "c": None},
                          {"w": "Zeit", "c": "n"}, {"w": "für", "c": None}, {"w": "die", "c": None},
                          {"w": "Hausarbeit.", "c": "n"}]},
    {"id": 510, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "drei", "c": None},
                          {"w": "Bücher.", "c": "n"}]},
    {"id": 511, "tags": [{"w": "Ich", "c": None}, {"w": "unterrichte", "c": "v"}, {"w": "Chinesisch.", "c": "n"}]},
    {"id": 574, "tags": [{"w": "Ist", "c": "v"}, {"w": "hier", "c": None}, {"w": "noch", "c": None},
                          {"w": "ein", "c": None}, {"w": "Platz", "c": "n"}, {"w": "frei?", "c": "a"}]},
    {"id": 575, "tags": [{"w": "Darf", "c": "v"}, {"w": "ich", "c": None}, {"w": "mich", "c": None},
                          {"w": "dazusetzen?", "c": "v"}]},
    {"id": 576, "tags": [{"w": "Bist", "c": "v"}, {"w": "du", "c": None}, {"w": "auch", "c": None},
                          {"w": "neu", "c": "a"}, {"w": "hier?", "c": None}]},
    {"id": 577, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "auch", "c": None},
                          {"w": "im", "c": None}, {"w": "ersten", "c": None}, {"w": "Semester.", "c": "n"}]},
    {"id": 578, "tags": [{"w": "Was", "c": None}, {"w": "studierst", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 579, "tags": [{"w": "Gehst", "c": "v"}, {"w": "du", "c": None}, {"w": "auch", "c": None},
                          {"w": "zur", "c": None}, {"w": "nächsten", "c": "a"}, {"w": "Vorlesung?", "c": "n"}]},
    {"id": 580, "tags": [{"w": "Wollen", "c": "v"}, {"w": "wir", "c": None}, {"w": "uns", "c": None},
                          {"w": "nach", "c": None}, {"w": "der", "c": None}, {"w": "Vorlesung", "c": "n"},
                          {"w": "treffen?", "c": "v"}]},
    {"id": 581, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "hier", "c": None},
                          {"w": "eine", "c": None}, {"w": "Gruppe", "c": "n"}, {"w": "für", "c": None},
                          {"w": "Austauschstudierende?", "c": "n"}]},
]
