# -*- coding: utf-8 -*-
"""Drinking + Dining, Ausbau (2026-08-22).

Vier neue Situationen plus Ausbau der duennen. Anders als die
Uebersetzungsdatei sind das NEUE Saetze - also `UEBERSETZUNG = False`, und
die Regel "baubar >= 90%" gilt verbindlich. Bei neuen Saetzen ist sie auch
fair: man kann die Formulierung waehlen.

**Warum gerade diese vier Situationen** (Zielgruppe: Backpacker in China):

- `essen_strassenessen` - die Garkuechen sind der Ort, an dem die Zielgruppe
  tatsaechlich isst. Dort gibt es keine Karte, man zeigt und fragt.
- `essen_schaerfe` - 辣 ist DAS Thema. In Sichuan und Hunan entscheidet der
  Satz "nicht scharf" ueber den ganzen Abend, und er ist kurz genug fuer
  Tag eins.
- `essen_teilen` - gegessen wird gemeinsam von gemeinsamen Schuesseln. Wer
  das nicht kann, sitzt vor seinem eigenen Teller und wirkt unhoeflich.
- `essen_getraenke` - Wasser kommt heiss. Kalt muss man ausdruecklich
  erbitten, und Eis noch einmal getrennt.

**Was NICHT hierher kommt:** Allergien und Unvertraeglichkeiten. Die leiht
die Kategorie seit dem 2026-08-22 aus `health_allergie` (siehe
geliehen.ts) - dort stehen 13 fertige Saetze, die im Restaurant wortgleich
stimmen.
"""

UEBERSETZUNG = False

SAETZE = [
# ============================================================ An der Garküche
 dict(sz='essen_strassenessen', de='Was ist das?', zh='这是什么？', py='zhè shì shénme?',
      hinweis='An der Garküche der wichtigste Satz überhaupt. Es gibt keine Karte, gezeigt wird auf den Topf.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('was', ['was ist das', 'was'])],
      konzepte=[('was', ['什么'])]),
 dict(sz='essen_strassenessen', de='Ich nehme das.', zh='我要这个。', py='wǒ yào zhège.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('nehmen', ['nehme', 'möchte', 'hätte gern'])],
      konzepte=[('wollen', ['要']), ('das', ['这个'])]),
 dict(sz='essen_strassenessen', de='Eine Portion, bitte.', zh='一份，谢谢。', py='yí fèn, xièxie.',
      hinweis=None, neu=['份'], lookup=False, ansprache=None,
      de_konzepte=[('portion', ['portion', 'eine'])],
      konzepte=[('portion', ['份'])]),
 dict(sz='essen_strassenessen', de='Zwei davon, bitte.', zh='这个来两个。',
      py='zhège lái liǎng ge.',
      hinweis='来 heißt hier nicht „kommen", sondern „her damit" — die knappste Art zu bestellen.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zwei', ['zwei'])],
      konzepte=[('das', ['这个']), ('zwei', ['两'])]),
 dict(sz='essen_strassenessen', de='Wie viel kostet eine Portion?', zh='一份多少钱？',
      py='yí fèn duōshao qián?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('wieviel', ['wie viel', 'wieviel'])],
      konzepte=[('portion', ['份']), ('wieviel', ['多少'])]),
 dict(sz='essen_strassenessen', de='Zum Mitnehmen, bitte.', zh='打包。', py='dǎbāo.',
      hinweis='Ein Wort reicht. 打包 gilt auch für Reste im Restaurant — die mitzunehmen ist normal, nicht peinlich.',
      neu=['打包'], lookup=False, ansprache=None,
      de_konzepte=[('mitnehmen', ['mitnehmen', 'zum mitnehmen'])],
      konzepte=[('mitnehmen', ['打包'])]),
 dict(sz='essen_strassenessen', de='Ich esse hier.', zh='在这里吃。', py='zài zhèli chī.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('hier', ['hier']), ('essen', ['esse'])],
      konzepte=[('hier', ['这里']), ('essen', ['吃'])]),
 dict(sz='essen_strassenessen', de='Ist das frisch?', zh='新鲜吗？', py='xīnxiān ma?',
      hinweis=None, neu=['新鲜'], lookup=False, ansprache=None,
      de_konzepte=[('frisch', ['frisch'])],
      konzepte=[('frisch', ['新鲜'])]),
 dict(sz='essen_strassenessen', de='Was essen die anderen?', zh='别人吃什么？',
      py='biérén chī shénme?',
      hinweis='Die ehrlichste Bestellhilfe: schauen, was die Einheimischen nehmen, und dasselbe verlangen.',
      neu=['别人'], lookup=False, ansprache=None,
      de_konzepte=[('andere', ['anderen', 'andere'])],
      konzepte=[('andere_leute', ['别人']), ('essen', ['吃'])]),
 dict(sz='essen_strassenessen', de='Das Gleiche, bitte.', zh='一样的，谢谢。',
      py='yíyàng de, xièxie.',
      hinweis=None, neu=['一样'], lookup=False, ansprache=None,
      de_konzepte=[('gleiche', ['gleiche', 'dasselbe'])],
      konzepte=[('gleich', ['一样'])]),

# ============================================================ Wie scharf?
 dict(sz='essen_schaerfe', de='Ist das scharf?', zh='辣吗？', py='là ma?',
      hinweis=None, neu=['辣'], lookup=False, ansprache=None,
      de_konzepte=[('scharf', ['scharf'])],
      konzepte=[('scharf', ['辣'])]),
 dict(sz='essen_schaerfe', de='Nicht scharf, bitte.', zh='不要辣。', py='bú yào là.',
      hinweis='Der wichtigste Satz in Sichuan und Hunan. Achtung: „nicht scharf" heißt dort oft immer noch scharf — im Zweifel zweimal sagen.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('nicht_scharf', ['nicht scharf', 'ohne schärfe'])],
      konzepte=[('nicht_wollen', ['不要']), ('scharf', ['辣'])]),
 dict(sz='essen_schaerfe', de='Ein bisschen scharf ist okay.', zh='一点辣可以。',
      py='yìdiǎn là kěyǐ.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('bisschen', ['bisschen', 'ein wenig'])],
      konzepte=[('ein_bisschen', ['一点']), ('scharf', ['辣'])]),
 dict(sz='essen_schaerfe', de='Ich kann nicht scharf essen.', zh='我不能吃辣。',
      py='wǒ bù néng chī là.',
      hinweis=None, neu=['能'], lookup=False, ansprache=None,
      de_konzepte=[('nicht_koennen', ['kann nicht', 'nicht']), ('scharf', ['scharf'])],
      konzepte=[('nicht_koennen', ['不能']), ('scharf', ['辣'])]),
 dict(sz='essen_schaerfe', de='Das ist zu scharf!', zh='太辣了！', py='tài là le!',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zu_scharf', ['zu scharf'])],
      konzepte=[('zu_sehr', ['太']), ('scharf', ['辣'])]),
 dict(sz='essen_schaerfe', de='Haben Sie etwas ohne Chili?', zh='有不辣的吗？',
      py='yǒu bú là de ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('ohne_scharf', ['ohne chili', 'nicht scharf'])],
      konzepte=[('haben', ['有']), ('nicht_scharf', ['不辣'])]),
 dict(sz='essen_schaerfe', de='Wasser, schnell!', zh='水，快！', py='shuǐ, kuài!',
      hinweis='Milch oder Reis helfen besser als Wasser — aber wer gerade brennt, ruft nach Wasser.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('wasser', ['wasser'])],
      konzepte=[('wasser', ['水']), ('schnell', ['快'])]),

# ============================================================ Gemeinsam essen
 dict(sz='essen_teilen', de='Wir essen zusammen.', zh='我们一起吃。', py='wǒmen yìqǐ chī.',
      hinweis='In China wird von gemeinsamen Schüsseln gegessen. Wer nur seinen eigenen Teller anrührt, wirkt verschlossen.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zusammen', ['zusammen', 'gemeinsam'])],
      konzepte=[('zusammen', ['一起']), ('essen', ['吃'])]),
 dict(sz='essen_teilen', de='Noch eine Schüssel Reis, bitte.', zh='再来一碗米饭。',
      py='zài lái yì wǎn mǐfàn.',
      hinweis=None, neu=['碗'], lookup=False, ansprache=None,
      de_konzepte=[('reis', ['reis']), ('noch', ['noch'])],
      konzepte=[('nochmal', ['再']), ('reis', ['米饭'])]),
 dict(sz='essen_teilen', de='Iss mehr!', zh='多吃点！', py='duō chī diǎn!',
      hinweis='Die Aufforderung, die man als Gast ständig hört. Sie ist ernst gemeint — höflich abwehren geht mit 我饱了.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('mehr_essen', ['iss mehr', 'mehr'])],
      konzepte=[('mehr', ['多']), ('essen', ['吃'])]),
 dict(sz='essen_teilen', de='Ich bin satt.', zh='我饱了。', py='wǒ bǎo le.',
      hinweis=None, neu=['饱'], lookup=False, ansprache=None,
      de_konzepte=[('satt', ['satt'])],
      konzepte=[('satt', ['饱'])]),
 dict(sz='essen_teilen', de='Nimm doch!', zh='你吃吧！', py='nǐ chī ba!',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('nimm', ['nimm', 'iss'])],
      konzepte=[('essen', ['吃'])]),
 dict(sz='essen_teilen', de='Sollen wir noch etwas bestellen?', zh='再点一个菜吗？',
      py='zài diǎn yí ge cài ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('bestellen', ['bestellen']), ('noch', ['noch'])],
      konzepte=[('nochmal', ['再']), ('bestellen', ['点'])]),
 dict(sz='essen_teilen', de='Ich lade dich ein.', zh='我请你。', py='wǒ qǐng nǐ.',
      hinweis='Wer einlädt, zahlt für alle. Das Angebot wird zwei-, dreimal abgelehnt, bevor es angenommen wird — das gehört dazu.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('einladen', ['lade dich ein', 'einladen'])],
      konzepte=[('einladen', ['请'])]),
 dict(sz='essen_teilen', de='Danke fürs Einladen!', zh='谢谢你请客！', py='xièxie nǐ qǐngkè!',
      hinweis=None, neu=['请客'], lookup=False, ansprache=None,
      de_konzepte=[('danke', ['danke'])],
      konzepte=[('danke', ['谢谢']), ('einladen', ['请客'])]),
 dict(sz='essen_teilen', de='Das ist für alle.', zh='这是大家的。', py='zhè shì dàjiā de.',
      hinweis=None, neu=['大家'], lookup=False, ansprache=None,
      de_konzepte=[('alle', ['alle'])],
      konzepte=[('alle', ['大家'])]),

# ============================================================ Getränke
 dict(sz='essen_getraenke', de='Was haben Sie zu trinken?', zh='您有什么喝的？',
      py='nín yǒu shénme hē de?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('trinken', ['trinken'])],
      konzepte=[('haben', ['有']), ('trinken', ['喝'])]),
 dict(sz='essen_getraenke', de='Wasser mit Eis, bitte.', zh='要冰水。', py='yào bīng shuǐ.',
      hinweis='Wasser kommt in China heiß — kaltes muss man ausdrücklich verlangen, und in kleinen Lokalen gibt es oft gar keines.',
      neu=['冰'], lookup=False, ansprache=None,
      de_konzepte=[('kalt', ['kalt', 'kaltes']), ('wasser', ['wasser'])],
      konzepte=[('kalt', ['冰']), ('wasser', ['水'])]),
 dict(sz='essen_getraenke', de='Heißes Wasser, bitte.', zh='要热水。', py='yào rè shuǐ.',
      hinweis='Der Standard. Überall stehen Wasserspender mit kochendem Wasser — im Zug, am Flughafen, in jedem Hostel.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('heiss', ['heiß', 'heißes']), ('wasser', ['wasser'])],
      konzepte=[('heiss', ['热']), ('wasser', ['水'])]),
 dict(sz='essen_getraenke', de='Ohne Eis, bitte.', zh='不要冰。', py='bú yào bīng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('ohne_eis', ['ohne eis', 'kein eis'])],
      konzepte=[('nicht_wollen', ['不要']), ('eis', ['冰'])]),
 dict(sz='essen_getraenke', de='Ein Bier, bitte.', zh='要一瓶啤酒。', py='yào yì píng píjiǔ.',
      hinweis=None, neu=['瓶'], lookup=False, ansprache=None,
      de_konzepte=[('bier', ['bier'])],
      konzepte=[('flasche', ['瓶']), ('bier', ['啤酒'])]),
 dict(sz='essen_getraenke', de='Einen Tee, bitte.', zh='要一杯茶。', py='yào yì bēi chá.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('tee', ['tee'])],
      konzepte=[('glas', ['杯']), ('tee', ['茶'])]),
 dict(sz='essen_getraenke', de='Ohne Zucker, bitte.', zh='不要糖。', py='bú yào táng.',
      hinweis='Bei Bubble Tea wird nach der Süße gefragt — 三分糖 („dreißig Prozent") ist die übliche Antwort, wenn man es nicht sehr süß mag.',
      neu=['糖'], lookup=False, ansprache=None,
      de_konzepte=[('ohne_zucker', ['ohne zucker', 'kein zucker'])],
      konzepte=[('nicht_wollen', ['不要']), ('zucker', ['糖'])]),
 dict(sz='essen_getraenke', de='Noch eins, bitte.', zh='再来一个。', py='zài lái yí ge.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('noch_eins', ['noch eins', 'noch eines'])],
      konzepte=[('nochmal', ['再'])]),

# ============================================================ Ausbau der dünnen Situationen
 dict(sz='essen_platz', de='Für wie viele Personen?', zh='几位？', py='jǐ wèi?',
      hinweis='Die Frage, mit der man an der Tür empfangen wird. 位 ist das höfliche Zählwort für Personen.',
      neu=['位'], lookup=False, ansprache=None,
      de_konzepte=[('wie_viele', ['wie viele', 'wieviele'])],
      konzepte=[('wie_viele', ['几']), ('person', ['位'])]),
 dict(sz='essen_platz', de='Können wir draußen sitzen?', zh='可以在外面坐吗？',
      py='kěyǐ zài wàimiàn zuò ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('draussen', ['draußen'])],
      konzepte=[('draussen', ['外面']), ('sitzen', ['坐'])]),
 dict(sz='essen_platz', de='Wir warten.', zh='我们等。', py='wǒmen děng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('warten', ['warten'])],
      konzepte=[('warten', ['等'])]),
 dict(sz='essen_platz', de='Wie lange müssen wir warten?', zh='要等多久？',
      py='yào děng duōjiǔ?',
      hinweis=None, neu=['多久'], lookup=False, ansprache=None,
      de_konzepte=[('wie_lange', ['wie lange']), ('warten', ['warten'])],
      konzepte=[('warten', ['等']), ('wie_lange', ['多久'])]),

 dict(sz='essen_bestellen', de='Einen Moment, bitte.', zh='等一下。', py='děng yíxià.',
      hinweis='Wenn man die Karte noch liest. Ohne diesen Satz steht die Bedienung wartend am Tisch.',
      neu=['一下'], lookup=False, ansprache=None,
      de_konzepte=[('moment', ['moment', 'augenblick'])],
      konzepte=[('warten', ['等'])]),
 dict(sz='essen_bestellen', de='Das ist alles, danke.', zh='就这些，谢谢。',
      py='jiù zhèxiē, xièxie.',
      hinweis=None, neu=['这些'], lookup=False, ansprache=None,
      de_konzepte=[('alles', ['alles', 'das ist alles'])],
      konzepte=[('diese', ['这些'])]),
 dict(sz='essen_bestellen', de='Was ist in diesem Gericht?', zh='这个菜有什么？',
      py='zhège cài yǒu shénme?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('was_drin', ['was ist drin', 'was'])],
      konzepte=[('gericht', ['菜']), ('was', ['什么'])]),
 dict(sz='essen_bestellen', de='Haben Sie eine Speisekarte mit Bildern?', zh='您有图片的菜单吗？',
      py='nín yǒu túpiàn de càidān ma?',
      hinweis='Die Rettung, wenn nichts anderes hilft — und in Touristengegenden fast immer vorhanden.',
      neu=['图片'], lookup=False, ansprache=None,
      de_konzepte=[('bilder', ['bilder', 'bildern'])],
      konzepte=[('bild', ['图片']), ('speisekarte', ['菜单'])]),
 dict(sz='essen_bestellen', de='Ich möchte etwas Warmes.', zh='我要热的。', py='wǒ yào rè de.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('warm', ['warmes', 'warm'])],
      konzepte=[('wollen', ['要']), ('heiss', ['热'])]),

 dict(sz='essen_bezahlen', de='Zusammen, bitte.', zh='一起付。', py='yìqǐ fù.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zusammen', ['zusammen'])],
      konzepte=[('zusammen', ['一起']), ('zahlen', ['付'])]),
 dict(sz='essen_bezahlen', de='Kann ich mit dem Handy bezahlen?', zh='可以用手机付吗？',
      py='kěyǐ yòng shǒujī fù ma?',
      hinweis='Fast überall ja — und oft die einzige Möglichkeit. Bargeld nehmen kleine Lokale zwar an, haben aber selten Wechselgeld.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('handy', ['handy']), ('bezahlen', ['bezahlen', 'zahlen'])],
      konzepte=[('handy', ['手机']), ('zahlen', ['付'])]),
 dict(sz='essen_bezahlen', de='Stimmt so.', zh='不用找了。', py='bú yòng zhǎo le.',
      hinweis='Trinkgeld ist in China unüblich und wird oft zurückgegeben. Dieser Satz meint nur das Kleingeld.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('stimmt_so', ['stimmt so', 'passt'])],
      konzepte=[('nicht_noetig', ['不用']), ('wechselgeld', ['找'])]),
 dict(sz='essen_bezahlen', de='Wie viel macht das?', zh='一共多少？', py='yígòng duōshao?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('wieviel', ['wie viel', 'wieviel'])],
      konzepte=[('zusammen', ['一共']), ('wieviel', ['多少'])]),

 dict(sz='essen_geschmack', de='Das mag ich sehr.', zh='我很喜欢。', py='wǒ hěn xǐhuan.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('moegen', ['mag', 'gefällt'])],
      konzepte=[('moegen', ['喜欢'])]),
 dict(sz='essen_geschmack', de='Das mag ich nicht.', zh='我不喜欢。', py='wǒ bù xǐhuan.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('nicht_moegen', ['mag ich nicht', 'nicht'])],
      konzepte=[('nicht_moegen', ['不喜欢'])]),
 dict(sz='essen_geschmack', de='Was ist das für ein Fleisch?', zh='这是什么肉？',
      py='zhè shì shénme ròu?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('fleisch', ['fleisch'])],
      konzepte=[('was', ['什么']), ('fleisch', ['肉'])]),
 dict(sz='essen_geschmack', de='Das ist mir zu salzig.', zh='太咸了。', py='tài xián le.',
      hinweis=None, neu=['咸'], lookup=False, ansprache=None,
      de_konzepte=[('salzig', ['salzig'])],
      konzepte=[('zu_sehr', ['太']), ('salzig', ['咸'])]),
# ============================================================ Zweites Vorkommen
# Bewusst kurze Saetze, die die neu eingefuehrten Woerter ein zweites Mal
# benutzen. Das ist die Regel "rentabel": ein Wort, das nur einmal auftaucht,
# ist eine Vokabel zum Auswendiglernen statt ein Baustein. Alle hier sind
# echter Inhalt - was man an einem Tisch in China wirklich sagt.
 dict(sz='essen_platz', de='Zwei Personen.', zh='两位。', py='liǎng wèi.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zwei', ['zwei']), ('personen', ['personen'])],
      konzepte=[('zwei', ['两']), ('person', ['位'])]),
 dict(sz='essen_strassenessen', de='Zwei Portionen, bitte.', zh='要两份。',
      py='yào liǎng fèn.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zwei', ['zwei']), ('portionen', ['portionen', 'portion'])],
      konzepte=[('zwei', ['两']), ('portion', ['份'])]),
 dict(sz='essen_strassenessen', de='Das ist sehr frisch.', zh='很新鲜。', py='hěn xīnxiān.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('frisch', ['frisch'])],
      konzepte=[('frisch', ['新鲜'])]),
 dict(sz='essen_strassenessen', de='Ich möchte das Gleiche.', zh='我要一样的。',
      py='wǒ yào yíyàng de.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('gleiche', ['gleiche', 'dasselbe'])],
      konzepte=[('wollen', ['要']), ('gleich', ['一样'])]),
 dict(sz='essen_bezahlen', de='Können wir das einpacken?', zh='可以打包吗？',
      py='kěyǐ dǎbāo ma?',
      hinweis='Reste mitzunehmen ist normal und gilt nicht als knauserig — Essen wegzuwerfen dagegen schon.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('einpacken', ['einpacken', 'mitnehmen'])],
      konzepte=[('mitnehmen', ['打包'])]),
 dict(sz='essen_teilen', de='Bist du satt?', zh='你饱了吗？', py='nǐ bǎo le ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('satt', ['satt'])],
      konzepte=[('satt', ['饱'])]),
 dict(sz='essen_teilen', de='Noch eine Schüssel, bitte.', zh='再来一碗。',
      py='zài lái yì wǎn.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('schuessel', ['schüssel']), ('noch', ['noch'])],
      konzepte=[('nochmal', ['再']), ('schuessel', ['碗'])]),
 dict(sz='essen_teilen', de='Heute lade ich ein.', zh='今天我请客。', py='jīntiān wǒ qǐngkè.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('heute', ['heute']), ('einladen', ['lade ein', 'einladen'])],
      konzepte=[('heute', ['今天']), ('einladen', ['请客'])]),
 dict(sz='essen_teilen', de='Alle zusammen!', zh='大家一起！', py='dàjiā yìqǐ!',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('alle', ['alle']), ('zusammen', ['zusammen'])],
      konzepte=[('alle', ['大家']), ('zusammen', ['一起'])]),
 dict(sz='essen_getraenke', de='Zwei Flaschen, bitte.', zh='要两瓶。', py='yào liǎng píng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zwei', ['zwei']), ('flaschen', ['flaschen', 'flasche'])],
      konzepte=[('zwei', ['两']), ('flasche', ['瓶'])]),
 dict(sz='essen_getraenke', de='Mit Eis, bitte.', zh='要冰的。', py='yào bīng de.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('eis', ['eis', 'mit eis'])],
      konzepte=[('wollen', ['要']), ('eis', ['冰'])]),
 dict(sz='essen_getraenke', de='Ein bisschen Zucker, bitte.', zh='要一点糖。',
      py='yào yìdiǎn táng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zucker', ['zucker']), ('bisschen', ['bisschen'])],
      konzepte=[('ein_bisschen', ['一点']), ('zucker', ['糖'])]),
 dict(sz='essen_geschmack', de='Nicht zu salzig, bitte.', zh='不要太咸。',
      py='bú yào tài xián.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('salzig', ['salzig'])],
      konzepte=[('nicht_wollen', ['不要']), ('salzig', ['咸'])]),
 dict(sz='essen_bestellen', de='Zeigen Sie mir das mal.', zh='给我看一下。',
      py='gěi wǒ kàn yíxià.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('zeigen', ['zeigen', 'zeig'])],
      konzepte=[('geben', ['给']), ('schauen', ['看'])]),
 dict(sz='essen_bestellen', de='Diese hier, bitte.', zh='要这些。', py='yào zhèxiē.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('diese', ['diese', 'die hier'])],
      konzepte=[('wollen', ['要']), ('diese', ['这些'])]),
 dict(sz='essen_bestellen', de='Wie lange dauert es?', zh='要多久？', py='yào duōjiǔ?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('wie_lange', ['wie lange', 'dauert'])],
      konzepte=[('wie_lange', ['多久'])]),
 dict(sz='essen_teilen', de='Die anderen essen schon.', zh='别人在吃了。',
      py='biérén zài chī le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('andere', ['anderen', 'andere']), ('essen', ['essen'])],
      konzepte=[('andere_leute', ['别人']), ('essen', ['吃'])]),
 dict(sz='essen_schaerfe', de='Kannst du scharf essen?', zh='你能吃辣吗？',
      py='nǐ néng chī là ma?',
      hinweis='Die Frage, die man als Ausländer ständig gestellt bekommt — und mit der eine Tischrunde anfängt.',
      neu=[], lookup=False, ansprache=None,
      de_konzepte=[('koennen', ['kannst', 'können']), ('scharf', ['scharf'])],
      konzepte=[('koennen', ['能']), ('scharf', ['辣'])]),
 dict(sz='essen_bestellen', de='Gibt es davon ein Bild?', zh='有图片吗？', py='yǒu túpiàn ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      de_konzepte=[('bild', ['bild', 'foto'])],
      konzepte=[('haben', ['有']), ('bild', ['图片'])]),
]
