# -*- coding: utf-8 -*-
"""Health + Emergency: fuenf Situationen, Chinesisch.

Nutzer-Auswahl 2026-08-21: Notfall, Allergien, Versicherung + Bezahlen,
Krankenhaus und "Was mir fehlt" - **ohne Durchfall**. Apotheke, Zahnarzt und
Verhuetung bleiben bewusst draussen: "fuer den Rest gibt es ja immer noch
Uebersetzer oder Aerzte die Englisch sprechen".

Der Kurs deckt das Feld ungewoehnlich gut ab - 医院, 医生, 药, 疼, 发烧,
生病, 难受, 感冒 und alle Koerperteile stehen schon drin. Neu kommen vor
allem die Systembegriffe dazu (挂号, 保险, 发票) und die Notfallwoerter.

WAS IN CHINA ANDERS IST - der Grund, warum "Krankenhaus" eine eigene
Situation ist und nicht "Beim Arzt" heisst:

  Es gibt keinen Hausarzt. Fuer alles geht man ins Krankenhaus, auch fuer
  eine Erkaeltung. Dort meldet man sich zuerst an einem Schalter an (挂号)
  und bezahlt, BEVOR man behandelt wird. Wer das nicht weiss, steht im
  falschen Gang. Der Notruf ist 120, nicht 112. Und Apotheken fuehren
  chinesische und westliche Medizin nebeneinander - "ich moechte westliche
  Medizin" ist ein Satz, den man wirklich braucht.

Felder wie bei club_nightlife. `neu` deklariert die Vokabeln, die dieser
Satz einfuehrt - pruefe_saetze.py gleicht das gegen den Text ab.
"""

SAETZE = [
# ------------------------------------------------------------ Was mir fehlt
 dict(sz='health_symptome', de='Ich bin krank.', zh='我生病了。', py='wǒ shēngbìng le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('krank', ['生病'])]),
 dict(sz='health_symptome', de='Ich habe Fieber.', zh='我发烧了。', py='wǒ fāshāo le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('fieber', ['发烧'])]),
 dict(sz='health_symptome', de='Ich bin erkältet.', zh='我感冒了。', py='wǒ gǎnmào le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('erkaeltung', ['感冒'])]),
 dict(sz='health_symptome', de='Ich habe Kopfschmerzen.', zh='我头疼。', py='wǒ tóu téng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('kopf', ['头']), ('schmerz', ['疼'])]),
 dict(sz='health_symptome', de='Ich habe Bauchschmerzen.', zh='我肚子疼。', py='wǒ dùzi téng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('bauch', ['肚子']), ('schmerz', ['疼'])]),
 dict(sz='health_symptome', de='Mein Bein tut weh.', zh='我腿疼。', py='wǒ tuǐ téng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('bein', ['腿']), ('schmerz', ['疼'])]),
 dict(sz='health_symptome', de='Hier tut es weh.', zh='我这里疼。', py='wǒ zhèlǐ téng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('hier', ['这里']), ('schmerz', ['疼'])]),
 dict(sz='health_symptome', de='Mir geht es nicht gut.', zh='我不舒服。', py='wǒ bù shūfu.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('nicht', ['不']), ('wohl', ['舒服'])]),
 dict(sz='health_symptome', de='Mir geht es sehr schlecht.', zh='我很难受。', py='wǒ hěn nánshòu.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('unwohl', ['难受'])]),
 dict(sz='health_symptome', de='Ich bin sehr müde.', zh='我很累。', py='wǒ hěn lèi.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('muede', ['累'])]),
 dict(sz='health_symptome', de='Mir ist kalt.', zh='我很冷。', py='wǒ hěn lěng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('kalt', ['冷'])]),
 dict(sz='health_symptome', de='Seit gestern.', zh='从昨天开始。', py='cóng zuótiān kāishǐ.',
      hinweis=None, neu=['从'], lookup=False, ansprache=None,
      konzepte=[('gestern', ['昨天']), ('seit', ['从'])]),
 dict(sz='health_symptome', de='Seit heute Morgen.', zh='从今天早上开始。', py='cóng jīntiān zǎoshang kāishǐ.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('heute', ['今天']), ('seit', ['从'])]),

# ------------------------------------------------------------ Im Krankenhaus
 dict(sz='health_krankenhaus', de='Wo ist das Krankenhaus?', zh='医院在哪里？', py='yīyuàn zài nǎli?',
      hinweis='In China gibt es keinen Hausarzt — für alles geht man ins Krankenhaus, auch für eine Erkältung.',
      neu=[], lookup=False, ansprache=None,
      konzepte=[('krankenhaus', ['医院']), ('wo', ['哪里'])]),
 dict(sz='health_krankenhaus', de='Ich möchte zum Arzt.', zh='我想看医生。', py='wǒ xiǎng kàn yīshēng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('moechten', ['想']), ('arzt', ['医生'])]),
 dict(sz='health_krankenhaus', de='Wo melde ich mich an?', zh='在哪里挂号？', py='zài nǎli guàhào?',
      hinweis='挂号 heißt „sich anmelden". In chinesischen Krankenhäusern geht man zuerst an einen Schalter, bezahlt dort und bekommt erst dann einen Arzt zugewiesen.',
      neu=['挂号'], lookup=False, ansprache=None,
      konzepte=[('anmelden', ['挂号']), ('wo', ['哪里'])]),
 dict(sz='health_krankenhaus', de='Ich möchte mich anmelden.', zh='我要挂号。', py='wǒ yào guàhào.',
      hinweis=None, neu=['要'], lookup=False, ansprache=None,
      konzepte=[('anmelden', ['挂号'])]),
 dict(sz='health_krankenhaus', de='Ich habe keinen Termin.', zh='我没有预约。', py='wǒ méiyǒu yùyuē.',
      hinweis='Termine sind unüblich — man kommt und wartet. Ein Termin ist eher die Ausnahme.',
      neu=['预约'], lookup=False, ansprache=None,
      konzepte=[('kein', ['没有']), ('termin', ['预约'])]),
 dict(sz='health_krankenhaus', de='Kann ich einen Termin bekommen?', zh='我可以预约吗？', py='wǒ kěyǐ yùyuē ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('koennen', ['可以']), ('termin', ['预约'])]),
 dict(sz='health_krankenhaus', de='Wie lange muss ich warten?', zh='我要等多久？', py='wǒ yào děng duōjiǔ?',
      hinweis=None, neu=['多久'], lookup=False, ansprache=None,
      konzepte=[('warten', ['等']), ('wie_lange', ['多久'])]),
 dict(sz='health_krankenhaus', de='Wie lange dauert das?', zh='要多久？', py='yào duōjiǔ?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('wie_lange', ['多久'])]),
 dict(sz='health_krankenhaus', de='Bitte geben Sie mir ein Medikament.', zh='请给我药。', py='qǐng gěi wǒ yào.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('geben', ['给']), ('medizin', ['药'])]),
 dict(sz='health_krankenhaus', de='Ich möchte westliche Medizin.', zh='我要西药。', py='wǒ yào xīyào.',
      hinweis='Apotheken und Krankenhäuser führen traditionelle chinesische und westliche Medizin nebeneinander. Wer nichts sagt, bekommt womöglich Kräuter.',
      neu=['西药'], lookup=False, ansprache=None,
      konzepte=[('westliche_medizin', ['西药'])]),
 dict(sz='health_krankenhaus', de='Ist das westliche Medizin?', zh='这个是西药吗？', py='zhège shì xīyào ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('westliche_medizin', ['西药'])]),
 dict(sz='health_krankenhaus', de='Wie nehme ich das Medikament?', zh='这个药怎么吃？', py='zhège yào zěnme chī?',
      hinweis=None, neu=['怎么'], lookup=False, ansprache=None,
      konzepte=[('medizin', ['药']), ('wie', ['怎么'])]),
 dict(sz='health_krankenhaus', de='Wie komme ich dorthin?', zh='怎么去？', py='zěnme qù?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('wie', ['怎么']), ('gehen', ['去'])]),
 dict(sz='health_krankenhaus', de='Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
      zh='我不会说汉语，您可以写下来吗？', py='wǒ bú huì shuō Hànyǔ, nín kěyǐ xiě xiàlái ma?',
      hinweis=None, neu=[], lookup=True, ansprache=None,
      konzepte=[('sprechen', ['说']), ('schreiben', ['写'])]),

# ------------------------------------------------------------ Notfall
 dict(sz='health_notfall', de='Hilfe!', zh='救命！', py='jiùmìng!',
      hinweis='救命 ist der Notruf, wenn Leben in Gefahr ist. Für alltägliche Hilfe sagt man 帮帮我.',
      neu=['救命'], lookup=False, ansprache=None,
      konzepte=[('hilfe', ['救命'])]),
 dict(sz='health_notfall', de='Bitte helfen Sie mir!', zh='请帮帮我！', py='qǐng bāngbang wǒ!',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('helfen', ['帮'])]),
 dict(sz='health_notfall', de='Ich brauche einen Arzt.', zh='我要医生。', py='wǒ yào yīshēng.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('arzt', ['医生'])]),
 dict(sz='health_notfall', de='Bitte rufen Sie einen Krankenwagen!', zh='请叫救护车！', py='qǐng jiào jiùhùchē!',
      hinweis='Der Notruf in China ist 120, nicht 112.',
      neu=['救护车'], lookup=True, ansprache=None,
      konzepte=[('rufen', ['叫']), ('krankenwagen', ['救护车'])]),
 dict(sz='health_notfall', de='Ist der Krankenwagen schon unterwegs?', zh='救护车来了吗？', py='jiùhùchē lái le ma?',
      hinweis=None, neu=[], lookup=True, ansprache=None,
      konzepte=[('krankenwagen', ['救护车']), ('kommen', ['来'])]),
 dict(sz='health_notfall', de='Rufen Sie bitte 120 an.', zh='请打120。', py='qǐng dǎ yāo èr líng.',
      hinweis='120 ist der Rettungsdienst, 110 die Polizei, 119 die Feuerwehr. Die Ziffer 1 spricht man am Telefon „yāo" statt „yī", damit sie nicht mit 7 verwechselt wird.',
      neu=[], lookup=True, ansprache=None,
      konzepte=[('anrufen', ['打'])]),
 dict(sz='health_notfall', de='Jemand ist verletzt.', zh='有人受伤了。', py='yǒu rén shòushāng le.',
      hinweis=None, neu=['受伤'], lookup=True, ansprache=None,
      konzepte=[('person', ['人']), ('verletzt', ['受伤'])]),
 dict(sz='health_notfall', de='Ich bin verletzt.', zh='我受伤了。', py='wǒ shòushāng le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('verletzt', ['受伤'])]),
 dict(sz='health_notfall', de='Schnell, bitte!', zh='快一点！', py='kuài yìdiǎn!',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('schnell', ['快'])]),
 dict(sz='health_notfall', de='Wo ist das nächste Krankenhaus?', zh='最近的医院在哪里？', py='zuì jìn de yīyuàn zài nǎli?',
      hinweis=None, neu=['最近'], lookup=False, ansprache=None,
      konzepte=[('naechste', ['最近']), ('krankenhaus', ['医院'])]),
 dict(sz='health_notfall', de='Wo ist die nächste Apotheke?', zh='最近的药店在哪里？', py='zuì jìn de yàodiàn zài nǎli?',
      hinweis=None, neu=['药店'], lookup=False, ansprache=None,
      konzepte=[('naechste', ['最近']), ('apotheke', ['药店'])]),
 dict(sz='health_notfall', de='Ich brauche etwas aus der Apotheke.', zh='我要去药店。', py='wǒ yào qù yàodiàn.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('gehen', ['去']), ('apotheke', ['药店'])]),
 dict(sz='health_notfall', de='Ich bin allein hier.', zh='我一个人在这里。', py='wǒ yí ge rén zài zhèlǐ.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('allein', ['一个人'])]),
 dict(sz='health_notfall', de='Bitte rufen Sie meinen Freund an.', zh='请给我朋友打电话。', py='qǐng gěi wǒ péngyou dǎ diànhuà.',
      hinweis=None, neu=[], lookup=True, ansprache=None,
      konzepte=[('freund', ['朋友']), ('telefonieren', ['打电话'])]),

# ------------------------------------------------------------ Allergien
 dict(sz='health_allergie', de='Ich habe eine Allergie.', zh='我过敏。', py='wǒ guòmǐn.',
      hinweis=None, neu=['过敏'], lookup=False, ansprache=None,
      konzepte=[('allergie', ['过敏'])]),
 dict(sz='health_allergie', de='Ich bin allergisch gegen dieses Medikament.', zh='我对这个药过敏。', py='wǒ duì zhège yào guòmǐn.',
      hinweis=None, neu=['对'], lookup=False, ansprache=None,
      konzepte=[('medizin', ['药']), ('allergie', ['过敏'])]),
 dict(sz='health_allergie', de='Ich bin allergisch gegen Penizillin.', zh='我对青霉素过敏。', py='wǒ duì qīngméisù guòmǐn.',
      hinweis=None, neu=['青霉素'], lookup=True, ansprache=None,
      konzepte=[('penizillin', ['青霉素']), ('allergie', ['过敏'])]),
 dict(sz='health_allergie', de='Ich bin allergisch gegen Erdnüsse.', zh='我对花生过敏。', py='wǒ duì huāshēng guòmǐn.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('erdnuss', ['花生']), ('allergie', ['过敏'])]),
 dict(sz='health_allergie', de='Ich kann keine Erdnüsse essen.', zh='我不能吃花生。', py='wǒ bù néng chī huāshēng.',
      hinweis=None, neu=['花生'], lookup=False, ansprache=None,
      konzepte=[('nicht_koennen', ['不能']), ('erdnuss', ['花生'])]),
 dict(sz='health_allergie', de='Sind da Erdnüsse drin?', zh='这个有花生吗？', py='zhège yǒu huāshēng ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('haben', ['有']), ('erdnuss', ['花生'])]),
 dict(sz='health_allergie', de='Bitte ohne Erdnüsse.', zh='请不要放花生。', py='qǐng bú yào fàng huāshēng.',
      hinweis=None, neu=['放'], lookup=False, ansprache=None,
      konzepte=[('nicht', ['不要']), ('erdnuss', ['花生'])]),
 dict(sz='health_allergie', de='Bitte ohne Milch.', zh='请不要放牛奶。', py='qǐng bú yào fàng niúnǎi.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('nicht', ['不要']), ('milch', ['牛奶'])]),
 dict(sz='health_allergie', de='Ich vertrage keine Milch.', zh='我不能喝牛奶。', py='wǒ bù néng hē niúnǎi.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('nicht_koennen', ['不能']), ('milch', ['牛奶'])]),
 dict(sz='health_allergie', de='Was ist da drin?', zh='这个有什么？', py='zhège yǒu shénme?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('haben', ['有']), ('was', ['什么'])]),
 dict(sz='health_allergie', de='Ich habe mein Allergiemedikament dabei.', zh='我有过敏药。', py='wǒ yǒu guòmǐn yào.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('haben', ['有']), ('allergie', ['过敏'])]),
 dict(sz='health_allergie', de='Das ist für mich sehr gefährlich.', zh='这个对我很危险。', py='zhège duì wǒ hěn wēixiǎn.',
      hinweis=None, neu=['危险'], lookup=True, ansprache=None,
      konzepte=[('gefaehrlich', ['危险'])]),
 dict(sz='health_allergie', de='Ist das gefährlich?', zh='危险吗？', py='wēixiǎn ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('gefaehrlich', ['危险'])]),

# ------------------------------------------------- Versicherung und Bezahlen
 dict(sz='health_bezahlen', de='Wie viel kostet das?', zh='多少钱？', py='duōshao qián?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('wieviel', ['多少']), ('geld', ['钱'])]),
 dict(sz='health_bezahlen', de='Ich habe eine Versicherung.', zh='我有保险。', py='wǒ yǒu bǎoxiǎn.',
      hinweis=None, neu=['保险'], lookup=False, ansprache=None,
      konzepte=[('haben', ['有']), ('versicherung', ['保险'])]),
 dict(sz='health_bezahlen', de='Nehmen Sie meine Versicherung?', zh='你们收保险吗？', py='nǐmen shōu bǎoxiǎn ma?',
      hinweis='Ausländische Versicherungen werden fast nie direkt akzeptiert. Man zahlt selbst und reicht zu Hause ein — deshalb ist die Quittung wichtiger als die Frage.',
      neu=['收', '你们'], lookup=False, ansprache=None,
      konzepte=[('versicherung', ['保险'])]),
 dict(sz='health_bezahlen', de='Muss ich vorher bezahlen?', zh='要先给钱吗？', py='yào xiān gěi qián ma?',
      hinweis='Ja. In China wird vor der Behandlung bezahlt, oft schon bei der Anmeldung.',
      neu=['先'], lookup=False, ansprache=None,
      konzepte=[('zuerst', ['先']), ('geld_geben', ['给钱'])]),
 dict(sz='health_bezahlen', de='Bitte geben Sie mir eine Quittung.', zh='请给我发票。', py='qǐng gěi wǒ fāpiào.',
      hinweis='发票 ist die offizielle Quittung. Ohne sie erstattet die Versicherung zu Hause nichts — unbedingt verlangen, sie wird nicht von selbst gegeben.',
      neu=['发票'], lookup=False, ansprache=None,
      konzepte=[('geben', ['给']), ('quittung', ['发票'])]),
 dict(sz='health_bezahlen', de='Ich brauche die Quittung für meine Versicherung.', zh='我的保险要发票。', py='wǒ de bǎoxiǎn yào fāpiào.',
      hinweis=None, neu=[], lookup=True, ansprache=None,
      konzepte=[('versicherung', ['保险']), ('quittung', ['发票'])]),
 dict(sz='health_bezahlen', de='Kann ich mit dem Handy bezahlen?', zh='我可以用手机给钱吗？', py='wǒ kěyǐ yòng shǒujī gěi qián ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('handy', ['手机']), ('geld_geben', ['给钱'])]),
 dict(sz='health_bezahlen', de='Nehmen Sie auch Karte?', zh='你们收卡吗？', py='nǐmen shōu kǎ ma?',
      hinweis=None, neu=['卡'], lookup=False, ansprache=None,
      konzepte=[('nehmen', ['收']), ('karte', ['卡'])]),
 dict(sz='health_bezahlen', de='Hier ist meine Karte.', zh='这是我的卡。', py='zhè shì wǒ de kǎ.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('karte', ['卡'])]),
 dict(sz='health_bezahlen', de='Zuerst anmelden, dann bezahlen?', zh='先挂号，再给钱吗？', py='xiān guàhào, zài gěi qián ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('zuerst', ['先']), ('anmelden', ['挂号'])]),
 dict(sz='health_bezahlen', de='Wo bekomme ich die Quittung?', zh='在哪里拿发票？', py='zài nǎli ná fāpiào?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('wo', ['哪里']), ('quittung', ['发票'])]),
 dict(sz='health_bezahlen', de='Wo kann ich bezahlen?', zh='在哪里给钱？', py='zài nǎli gěi qián?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('wo', ['哪里']), ('geld_geben', ['给钱'])]),
 dict(sz='health_bezahlen', de='Das ist zu teuer.', zh='太贵了。', py='tài guì le.',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('teuer', ['贵'])]),
 dict(sz='health_bezahlen', de='Ich habe nicht genug Geld dabei.', zh='我的钱不够。', py='wǒ de qián bú gòu.',
      hinweis=None, neu=['够'], lookup=False, ansprache=None,
      konzepte=[('geld', ['钱']), ('nicht_genug', ['不够'])]),
 dict(sz='health_bezahlen', de='Reicht das?', zh='够吗？', py='gòu ma?',
      hinweis=None, neu=[], lookup=False, ansprache=None,
      konzepte=[('genug', ['够'])]),
]
