-- Italienisch, Norwegisch, Russisch (2026-09-03).
--
-- Drei neue Zielsprachen auf einen Schlag. Schema exakt wie
-- `franz_phrasebook`/`spanisch_phrasebook`, damit `loadExerciseSentences()`
-- ohne Sonderfall damit arbeitet - EINE Ausnahme, siehe Lautschrift unten.
--
-- NORWEGISCH ist Bokmaal. Nynorsk waere die zweite offizielle Schriftnorm,
-- aber Bokmaal ist das, was rund 85-90% schreiben, was jeder Sprachkurs
-- lehrt und was die Zielgruppe (Backpacker, Austauschstudenten) in Oslo
-- oder Bergen tatsaechlich liest. Nicht in den Daten vermerkt, weil es
-- keine Wahl gibt, die spaeter kippen koennte - hier steht es als
-- Begruendung.
--
-- RUSSISCH BEKOMMT EINE LAUTSCHRIFT-SPALTE (Simons Entscheidung
-- 2026-09-03). Dieselbe Rolle wie `pinyin` bei Chinesisch: kyrillisch ist
-- die Infrastruktur (TTS braucht es, STT gibt es zurueck), gelernt wird
-- ueber die Transliteration. Ohne sie stuende ein Anfaenger bei jedem Satz
-- vor "Извините, где туалет?" - genau die Huerde, die bei Chinesisch
-- bewusst umgangen wird (CLAUDE.md, "Gelernt wird ueber PINYIN, nicht ueber
-- Zeichen"; dort steht auch, warum Lesen/Schreiben gar nicht trainiert
-- werden sollen).
--
-- Die Spalte heisst `lautschrift`, NICHT `pinyin` - Pinyin ist ein
-- chinesisches Eigenwort und waere fuer Russisch schlicht falsch. Die App
-- waehlt die Spalte ab jetzt datengetrieben ueber `Language.lautschriftSpalte`
-- (data/languages.ts) statt ueber ein hartes `lang.id === 'zh'`; damit
-- kostet eine vierte Sprache mit eigener Schrift keine Code-Aenderung mehr.
--
-- ITALIENISCH braucht keine - lateinische Schrift, `target_text` traegt
-- alles. Gleiche Lage wie Franzoesisch und Spanisch.

create table if not exists public.italienisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

create table if not exists public.norwegisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

create table if not exists public.russisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  -- Transliteration - der eigentliche LERNTEXT, siehe Kopfkommentar.
  lautschrift       text,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

-- Die App filtert praktisch immer ueber `category`, teils zusaetzlich ueber
-- `scenario` (siehe loadExerciseSentences).
create index if not exists italienisch_phrasebook_category_idx on public.italienisch_phrasebook (category);
create index if not exists italienisch_phrasebook_scenario_idx on public.italienisch_phrasebook (scenario);
create index if not exists norwegisch_phrasebook_category_idx  on public.norwegisch_phrasebook  (category);
create index if not exists norwegisch_phrasebook_scenario_idx  on public.norwegisch_phrasebook  (scenario);
create index if not exists russisch_phrasebook_category_idx    on public.russisch_phrasebook    (category);
create index if not exists russisch_phrasebook_scenario_idx    on public.russisch_phrasebook    (scenario);

-- Der deutsche Satz ist der Abgleichschluessel der Import-Skripte
-- (Sprachlisten/uebersetzen/werkzeug.py). Eindeutig INNERHALB einer
-- Kategorie, nicht darueber hinaus: einige Saetze stehen bewusst in zwei
-- Kategorien ("Das ist zu teuer." in Bar und Shopping), genau wie im
-- deutschen Master. Ein globaler unique-Index waere hier also falsch.
create unique index if not exists italienisch_phrasebook_german_category_idx
  on public.italienisch_phrasebook (german, category);
create unique index if not exists norwegisch_phrasebook_german_category_idx
  on public.norwegisch_phrasebook (german, category);
create unique index if not exists russisch_phrasebook_german_category_idx
  on public.russisch_phrasebook (german, category);

-- Reiner Content, wie die uebrigen Phrasebook-Tabellen: jeder darf lesen,
-- niemand ueber die App schreiben. Gefuellt wird ausschliesslich mit dem
-- service_role-Schluessel aus den Skripten in Sprachlisten/.
alter table public.italienisch_phrasebook enable row level security;
alter table public.norwegisch_phrasebook  enable row level security;
alter table public.russisch_phrasebook    enable row level security;

drop policy if exists "italienisch_phrasebook lesbar fuer alle" on public.italienisch_phrasebook;
create policy "italienisch_phrasebook lesbar fuer alle"
  on public.italienisch_phrasebook for select using (true);

drop policy if exists "norwegisch_phrasebook lesbar fuer alle" on public.norwegisch_phrasebook;
create policy "norwegisch_phrasebook lesbar fuer alle"
  on public.norwegisch_phrasebook for select using (true);

drop policy if exists "russisch_phrasebook lesbar fuer alle" on public.russisch_phrasebook;
create policy "russisch_phrasebook lesbar fuer alle"
  on public.russisch_phrasebook for select using (true);
