-- Vietnamesisch, Polnisch, Englisch (2026-09-03, Simons Auftrag).
--
-- Dritte Welle nach Italienisch/Norwegisch/Russisch. Schema wie dort:
-- Phrasebook plus Vokabeltabelle je Sprache, RLS wie bei allem Content.
--
-- KEINE LAUTSCHRIFT-SPALTE FUER VIETNAMESISCH UND POLNISCH - und das ist
-- eine Entscheidung, keine Auslassung. Simon hat sie ausdruecklich
-- angeboten ("koennen auch wenn vorhanden Schriftzeichen bekommen wie
-- Chinesisch oder Russisch"). Die Antwort ist: es gibt dort nichts zu
-- verbergen.
--
--   Vietnamesisch schreibt seit ueber hundert Jahren `quoc ngu` - das
--   LATEINISCHE Alphabet mit Ton- und Vokalzeichen. Ein Vietnamese liest
--   und schreibt genau diese Buchstaben; eine zweite "einfachere" Zeile
--   daneben gaebe es in der Wirklichkeit nirgends, und sie wegzulassen
--   hiesse, die Toene wegzulassen - und die tragen die Bedeutung
--   (`ma` heisst je nach Zeichen Geist, Mutter, aber, Grab, Pferd, Reis-
--   saemling).
--
--   Polnisch schreibt ebenfalls lateinisch, mit neun Sonderzeichen
--   (a-ogonek, c-acute, e-ogonek, l-stroke, n-acute, o-acute, s-acute,
--   z-acute, z-dot). Auch hier ist die Schrift der Lerntext.
--
-- Der Unterschied zu Chinesisch und Russisch ist grundsaetzlich: dort ist
-- die Schrift eine EIGENE, die ein Anfaenger nicht lesen kann und laut
-- CLAUDE.md auch nicht lernen soll ("Lesen und Schreiben sollen NICHT
-- trainiert werden"). Hier ist sie dieselbe, die der Nutzer ohnehin kennt,
-- nur mit Zusatzzeichen. Wo die Aussprache trotzdem ueberrascht - und bei
-- Polnisch tut sie das oft (`szcz`, `w` wie deutsches w, `l-stroke` wie
-- englisches w) - steht das im `culture_note` am Satz, nicht in einer
-- eigenen Spalte.
--
-- ENGLISCH ist die erste Zielsprache, die viele Nutzer schon koennen. Sie
-- steht trotzdem im selben Schema - fuer die Zielgruppe (Backpacker,
-- Austauschstudenten) ist es die Sprache, in der sie unterwegs ohnehin am
-- meisten reden, und der Wortschatz rund um Hostel, Job und Nachtleben ist
-- auch fuer Fortgeschrittene nicht selbstverstaendlich.

create table if not exists public.vietnamesisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

create table if not exists public.polnisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

create table if not exists public.englisch_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text,
  word_tags         jsonb
);

create table if not exists public.vietnamesisch_vocab (
  id               bigint generated by default as identity primary key,
  vietnamese       text    not null,
  german           text    not null,
  category         text,
  genus            text,
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

create table if not exists public.polnisch_vocab (
  id               bigint generated by default as identity primary key,
  polish           text    not null,
  german           text    not null,
  category         text,
  genus            text,
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

create table if not exists public.englisch_vocab (
  id               bigint generated by default as identity primary key,
  english          text    not null,
  german           text    not null,
  category         text,
  genus            text,
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

create index if not exists vietnamesisch_phrasebook_category_idx on public.vietnamesisch_phrasebook (category);
create index if not exists vietnamesisch_phrasebook_scenario_idx on public.vietnamesisch_phrasebook (scenario);
create index if not exists polnisch_phrasebook_category_idx      on public.polnisch_phrasebook      (category);
create index if not exists polnisch_phrasebook_scenario_idx      on public.polnisch_phrasebook      (scenario);
create index if not exists englisch_phrasebook_category_idx      on public.englisch_phrasebook      (category);
create index if not exists englisch_phrasebook_scenario_idx      on public.englisch_phrasebook      (scenario);

create unique index if not exists vietnamesisch_phrasebook_german_category_idx
  on public.vietnamesisch_phrasebook (german, category);
create unique index if not exists polnisch_phrasebook_german_category_idx
  on public.polnisch_phrasebook (german, category);
create unique index if not exists englisch_phrasebook_german_category_idx
  on public.englisch_phrasebook (german, category);

create index if not exists vietnamesisch_vocab_category_idx on public.vietnamesisch_vocab (category);
create index if not exists polnisch_vocab_category_idx      on public.polnisch_vocab      (category);
create index if not exists englisch_vocab_category_idx      on public.englisch_vocab      (category);

create unique index if not exists vietnamesisch_vocab_wort_idx on public.vietnamesisch_vocab (vietnamese);
create unique index if not exists polnisch_vocab_wort_idx      on public.polnisch_vocab      (polish);
create unique index if not exists englisch_vocab_wort_idx      on public.englisch_vocab      (english);

alter table public.vietnamesisch_phrasebook enable row level security;
alter table public.polnisch_phrasebook      enable row level security;
alter table public.englisch_phrasebook      enable row level security;
alter table public.vietnamesisch_vocab      enable row level security;
alter table public.polnisch_vocab           enable row level security;
alter table public.englisch_vocab           enable row level security;

drop policy if exists "vietnamesisch_phrasebook lesbar fuer alle" on public.vietnamesisch_phrasebook;
create policy "vietnamesisch_phrasebook lesbar fuer alle"
  on public.vietnamesisch_phrasebook for select using (true);

drop policy if exists "polnisch_phrasebook lesbar fuer alle" on public.polnisch_phrasebook;
create policy "polnisch_phrasebook lesbar fuer alle"
  on public.polnisch_phrasebook for select using (true);

drop policy if exists "englisch_phrasebook lesbar fuer alle" on public.englisch_phrasebook;
create policy "englisch_phrasebook lesbar fuer alle"
  on public.englisch_phrasebook for select using (true);

drop policy if exists "vietnamesisch_vocab lesbar fuer alle" on public.vietnamesisch_vocab;
create policy "vietnamesisch_vocab lesbar fuer alle"
  on public.vietnamesisch_vocab for select using (true);

drop policy if exists "polnisch_vocab lesbar fuer alle" on public.polnisch_vocab;
create policy "polnisch_vocab lesbar fuer alle"
  on public.polnisch_vocab for select using (true);

drop policy if exists "englisch_vocab lesbar fuer alle" on public.englisch_vocab;
create policy "englisch_vocab lesbar fuer alle"
  on public.englisch_vocab for select using (true);
