-- Franzoesisches Phrasebook (2026-08-27).
--
-- Bis hierhin war Franzoesisch die einzige Sprache in languages.ts mit
-- `table: null` - es gab `franz_vocab` (515 Einzelwoerter), aber keinen
-- einzigen Satz. Damit war die Sprache im Onboarding ausgegraut ("bald"),
-- weil das Gate dort `hasContent && table !== null` prueft.
--
-- Schema exakt wie `spanisch_phrasebook`, damit `loadExerciseSentences()`
-- ohne Sonderfall damit arbeitet: die Nicht-Deutsch-Tabellen teilen sich
-- alle denselben Zuschnitt (target_text + german als Gloss, verb_cluster als
-- eigene Spalte statt in accepted_concepts verschachtelt - siehe
-- data/phrasebookContent.ts).
--
-- KEINE pinyin-Spalte: die gibt es nur bei Chinesisch, wo die Lautschrift
-- der eigentliche Lerntext ist. Franzoesisch wird in lateinischer Schrift
-- gelernt, `target_text` traegt alles.
--
-- `verb_cluster` bleibt vorerst ueberall NULL - `answer_clusters` enthaelt
-- 32 deutsche und 25 sv_-Cluster, aber keinen franzoesischen. Dieselbe Lage
-- wie im gesamten spanischen Bestand; die Spalte steht bereit, falls die
-- Cluster spaeter nachgezogen werden.

create table if not exists public.franz_phrasebook (
  id                bigint generated by default as identity primary key,
  target_text       text        not null,
  german            text        not null,
  scenario          text,
  tense             text        default 'present',
  difficulty        text        default 'A1',
  accepted_concepts jsonb       not null default '{"required": [], "optional": []}'::jsonb,
  audio_url         text,
  status            text        default 'Neu',
  category          text,
  verb_cluster      text,
  lookup_only       boolean     not null default false,
  addressing        text,
  culture_note      text
);

-- Die App filtert praktisch immer ueber `category` (siehe
-- loadExerciseSentences), teils zusaetzlich ueber `scenario`.
create index if not exists franz_phrasebook_category_idx
  on public.franz_phrasebook (category);
create index if not exists franz_phrasebook_scenario_idx
  on public.franz_phrasebook (scenario);

-- Der deutsche Satz ist der Abgleichschluessel der Import-Skripte
-- (Sprachlisten/uebersetzen/werkzeug.py). Eindeutig INNERHALB einer
-- Kategorie, nicht darueber hinaus: zehn Saetze stehen bewusst in zwei
-- Kategorien ("Das ist zu teuer." in Bar und Shopping), genau wie im
-- deutschen Master. Ein globaler unique-Index waere hier also falsch.
create unique index if not exists franz_phrasebook_german_category_idx
  on public.franz_phrasebook (german, category);

-- Reiner Content, wie die uebrigen Phrasebook-Tabellen: jeder darf lesen,
-- niemand ueber die App schreiben. Gefuellt wird ausschliesslich mit dem
-- service_role-Schluessel aus den Skripten in Sprachlisten/.
alter table public.franz_phrasebook enable row level security;

drop policy if exists "franz_phrasebook lesbar fuer alle" on public.franz_phrasebook;
create policy "franz_phrasebook lesbar fuer alle"
  on public.franz_phrasebook for select
  using (true);
