-- Vokabeltabellen fuer Italienisch, Norwegisch, Russisch (2026-09-03).
--
-- Ohne sie laeuft die Woerter-Wiederholung (`WordReviewScreen.tsx`) fuer
-- diese drei Sprachen komplett leer - `languages.ts` zeigte bis hierher
-- `vocabTable: null`. Genau die Luecke, die Spanisch bis zum 2026-08-30
-- hatte, obwohl das Phrasebook laengst vollstaendig war.
--
-- Schema wie `franz_vocab`/`spanisch_vocab` (der neuere, sauberere Zuschnitt
-- gegenueber `schwedisch_vocab`): `category` meint die WORTART, nicht die
-- Lernkategorie - das ist bei den Vokabeltabellen so gewachsen und wird hier
-- bewusst nicht abgeaendert, weil `vocabContent.ts` und der Wortart-Filter
-- der Woerter-Wiederholung genau darauf bauen.
--
-- RUSSISCH BEKOMMT WIEDER EINE LAUTSCHRIFT-SPALTE, aus demselben Grund wie
-- beim Phrasebook: gelernt wird ueber die Umschrift, Kyrillisch laeuft
-- passiv mit. Ein Wort ohne Lautschrift waere in der Woerter-Wiederholung
-- eine Kachel, die der Nutzer nicht lesen kann.
--
-- KEINE per-Sprache eigene Wortliste ist uebersetzbar: die 500 haeufigsten
-- Woerter des Italienischen sind nicht die Uebersetzungen der 500
-- haeufigsten deutschen. Genau deshalb ueberlappen die drei bestehenden
-- Tabellen im deutschen Feld auch nur zu rund 40% (gezaehlt: 185 von ~500
-- zwischen es und fr). Die Listen hier sind je Sprache eigenstaendig
-- zusammengestellt.

create table if not exists public.italienisch_vocab (
  id               bigint generated by default as identity primary key,
  italian          text    not null,
  german           text    not null,
  category         text,            -- WORTART (Nomen, Verb, Adjektiv, ...)
  genus            text,            -- m / f bei Nomen, sonst null
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

create table if not exists public.norwegisch_vocab (
  id               bigint generated by default as identity primary key,
  norwegian        text    not null,
  german           text    not null,
  category         text,
  genus            text,            -- m / f / n (Norwegisch hat drei Genera)
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

create table if not exists public.russisch_vocab (
  id               bigint generated by default as identity primary key,
  russian          text    not null,
  -- Transliteration - der eigentliche LERNTEXT, siehe Kopfkommentar.
  lautschrift      text,
  german           text    not null,
  category         text,
  genus            text,            -- m / f / n
  frequency_rank   integer,
  accepted_answers text[],
  audio_urls       jsonb,
  grammar_note     text,
  status           text default 'Neu'
);

-- Die Woerter-Wiederholung filtert ueber die Wortart und sortiert nach
-- Haeufigkeit; das Zielsprachen-Wort ist der Importschluessel.
create index if not exists italienisch_vocab_category_idx on public.italienisch_vocab (category);
create index if not exists norwegisch_vocab_category_idx  on public.norwegisch_vocab  (category);
create index if not exists russisch_vocab_category_idx    on public.russisch_vocab    (category);

create unique index if not exists italienisch_vocab_wort_idx on public.italienisch_vocab (italian);
create unique index if not exists norwegisch_vocab_wort_idx  on public.norwegisch_vocab  (norwegian);
create unique index if not exists russisch_vocab_wort_idx    on public.russisch_vocab    (russian);

-- Reiner Content wie alle Vokabeltabellen: lesbar fuer alle, beschrieben
-- ausschliesslich ueber den service_role-Schluessel aus Sprachlisten/.
alter table public.italienisch_vocab enable row level security;
alter table public.norwegisch_vocab  enable row level security;
alter table public.russisch_vocab    enable row level security;

drop policy if exists "italienisch_vocab lesbar fuer alle" on public.italienisch_vocab;
create policy "italienisch_vocab lesbar fuer alle"
  on public.italienisch_vocab for select using (true);

drop policy if exists "norwegisch_vocab lesbar fuer alle" on public.norwegisch_vocab;
create policy "norwegisch_vocab lesbar fuer alle"
  on public.norwegisch_vocab for select using (true);

drop policy if exists "russisch_vocab lesbar fuer alle" on public.russisch_vocab;
create policy "russisch_vocab lesbar fuer alle"
  on public.russisch_vocab for select using (true);
