# -*- coding: utf-8 -*-
"""
Schwedische Top-500-Wortliste fuer die Sprachlern-App.
Wird schrittweise erweitert - IMMER diese eine Datei verwenden/neu herunterladen.
Aktueller Stand: Funktionswoerter (Pronomen, Zahlen, Fragewoerter, Praepositionen,
Konjunktionen, Adverbien). Als naechstes folgen Verben, dann Nomen, dann Adjektive.
"""

WORDS = [
    # --- Personalpronomen ---
    {"swedish": "jag", "german": "ich", "category": "Pronomen"},
    {"swedish": "du", "german": "du", "category": "Pronomen"},
    {"swedish": "han", "german": "er", "category": "Pronomen"},
    {"swedish": "hon", "german": "sie (Sg.)", "category": "Pronomen"},
    {"swedish": "den", "german": "er/sie/es (Utrum)", "category": "Pronomen", "grammar_note": "für en-Wörter (Utrum)"},
    {"swedish": "det", "german": "er/sie/es (Neutrum)", "category": "Pronomen", "grammar_note": "für ett-Wörter (Neutrum)"},
    {"swedish": "vi", "german": "wir", "category": "Pronomen"},
    {"swedish": "ni", "german": "ihr", "category": "Pronomen"},
    {"swedish": "de", "german": "sie (Pl.)", "category": "Pronomen", "grammar_note": "gesprochen oft 'dom'"},
    {"swedish": "man", "german": "man", "category": "Pronomen"},
    {"swedish": "mig", "german": "mich, mir", "category": "Pronomen"},
    {"swedish": "dig", "german": "dich, dir", "category": "Pronomen"},
    {"swedish": "honom", "german": "ihn, ihm", "category": "Pronomen"},
    {"swedish": "henne", "german": "sie, ihr (Akk./Dat.)", "category": "Pronomen"},
    {"swedish": "oss", "german": "uns", "category": "Pronomen"},
    {"swedish": "er", "german": "euch", "category": "Pronomen"},
    {"swedish": "dem", "german": "sie, ihnen (Pl.)", "category": "Pronomen", "grammar_note": "gesprochen oft 'dom'"},
    {"swedish": "min", "german": "mein (Utrum)", "category": "Pronomen"},
    {"swedish": "mitt", "german": "mein (Neutrum)", "category": "Pronomen"},
    {"swedish": "mina", "german": "meine (Pl.)", "category": "Pronomen"},
    {"swedish": "din", "german": "dein (Utrum)", "category": "Pronomen"},
    {"swedish": "ditt", "german": "dein (Neutrum)", "category": "Pronomen"},
    {"swedish": "dina", "german": "deine (Pl.)", "category": "Pronomen"},
    {"swedish": "sin", "german": "sein/ihr eigenes (Utrum, reflexiv)", "category": "Pronomen"},
    {"swedish": "sitt", "german": "sein/ihr eigenes (Neutrum, reflexiv)", "category": "Pronomen"},
    {"swedish": "vår", "german": "unser (Utrum)", "category": "Pronomen"},
    {"swedish": "vårt", "german": "unser (Neutrum)", "category": "Pronomen"},
    {"swedish": "våra", "german": "unsere (Pl.)", "category": "Pronomen"},
    {"swedish": "denna", "german": "dieser/diese (Utrum)", "category": "Pronomen"},
    {"swedish": "detta", "german": "dieses (Neutrum)", "category": "Pronomen"},
    {"swedish": "dessa", "german": "diese (Pl.)", "category": "Pronomen"},
    {"swedish": "något", "german": "etwas", "category": "Pronomen"},
    {"swedish": "allt", "german": "alles", "category": "Pronomen"},
    {"swedish": "alla", "german": "alle", "category": "Pronomen"},
    {"swedish": "ingen", "german": "keiner/keine (Utrum)", "category": "Pronomen"},
    {"swedish": "inget", "german": "keines (Neutrum)", "category": "Pronomen"},

    # --- Zahlwörter ---
    {"swedish": "noll", "german": "null", "category": "Zahlwort"},
    {"swedish": "en/ett", "german": "eins", "category": "Zahlwort", "grammar_note": "en für Utrum-Wörter, ett für Neutrum-Wörter"},
    {"swedish": "två", "german": "zwei", "category": "Zahlwort"},
    {"swedish": "tre", "german": "drei", "category": "Zahlwort"},
    {"swedish": "fyra", "german": "vier", "category": "Zahlwort"},
    {"swedish": "fem", "german": "fünf", "category": "Zahlwort"},
    {"swedish": "sex", "german": "sechs", "category": "Zahlwort"},
    {"swedish": "sju", "german": "sieben", "category": "Zahlwort"},
    {"swedish": "åtta", "german": "acht", "category": "Zahlwort"},
    {"swedish": "nio", "german": "neun", "category": "Zahlwort"},
    {"swedish": "tio", "german": "zehn", "category": "Zahlwort"},
    {"swedish": "elva", "german": "elf", "category": "Zahlwort"},
    {"swedish": "tolv", "german": "zwölf", "category": "Zahlwort"},
    {"swedish": "tretton", "german": "dreizehn", "category": "Zahlwort"},
    {"swedish": "fjorton", "german": "vierzehn", "category": "Zahlwort"},
    {"swedish": "femton", "german": "fünfzehn", "category": "Zahlwort"},
    {"swedish": "sexton", "german": "sechzehn", "category": "Zahlwort"},
    {"swedish": "sjutton", "german": "siebzehn", "category": "Zahlwort"},
    {"swedish": "arton", "german": "achtzehn", "category": "Zahlwort"},
    {"swedish": "nitton", "german": "neunzehn", "category": "Zahlwort"},
    {"swedish": "tjugo", "german": "zwanzig", "category": "Zahlwort"},
    {"swedish": "trettio", "german": "dreißig", "category": "Zahlwort"},
    {"swedish": "fyrtio", "german": "vierzig", "category": "Zahlwort"},
    {"swedish": "femtio", "german": "fünfzig", "category": "Zahlwort"},
    {"swedish": "sextio", "german": "sechzig", "category": "Zahlwort"},
    {"swedish": "sjuttio", "german": "siebzig", "category": "Zahlwort"},
    {"swedish": "åttio", "german": "achtzig", "category": "Zahlwort"},
    {"swedish": "nittio", "german": "neunzig", "category": "Zahlwort"},
    {"swedish": "hundra", "german": "hundert", "category": "Zahlwort"},
    {"swedish": "tusen", "german": "tausend", "category": "Zahlwort"},
    {"swedish": "första", "german": "erste(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},
    {"swedish": "andra", "german": "zweite(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},
    {"swedish": "tredje", "german": "dritte(r)", "category": "Zahlwort", "grammar_note": "Ordinalzahl"},

    # --- Fragewörter ---
    {"swedish": "vad", "german": "was", "category": "Fragewort"},
    {"swedish": "vem", "german": "wer", "category": "Fragewort"},
    {"swedish": "vilken", "german": "welcher/welche (Utrum)", "category": "Fragewort"},
    {"swedish": "vilket", "german": "welches (Neutrum)", "category": "Fragewort"},
    {"swedish": "vilka", "german": "welche (Pl.)", "category": "Fragewort"},
    {"swedish": "var", "german": "wo", "category": "Fragewort"},
    {"swedish": "vart", "german": "wohin", "category": "Fragewort"},
    {"swedish": "när", "german": "wann", "category": "Fragewort"},
    {"swedish": "hur", "german": "wie", "category": "Fragewort"},
    {"swedish": "varför", "german": "warum", "category": "Fragewort"},
    {"swedish": "hur mycket", "german": "wie viel", "category": "Fragewort"},
    {"swedish": "hur många", "german": "wie viele", "category": "Fragewort"},

    # --- Präpositionen ---
    {"swedish": "i", "german": "in", "category": "Präposition"},
    {"swedish": "på", "german": "auf, an", "category": "Präposition"},
    {"swedish": "av", "german": "von", "category": "Präposition"},
    {"swedish": "till", "german": "zu, nach", "category": "Präposition"},
    {"swedish": "från", "german": "von, aus", "category": "Präposition"},
    {"swedish": "med", "german": "mit", "category": "Präposition"},
    {"swedish": "om", "german": "über, um, falls", "category": "Präposition"},
    {"swedish": "för", "german": "für", "category": "Präposition"},
    {"swedish": "utan", "german": "ohne", "category": "Präposition"},
    {"swedish": "under", "german": "unter, während", "category": "Präposition"},
    {"swedish": "över", "german": "über", "category": "Präposition"},
    {"swedish": "mellan", "german": "zwischen", "category": "Präposition"},
    {"swedish": "genom", "german": "durch", "category": "Präposition"},
    {"swedish": "efter", "german": "nach", "category": "Präposition"},
    {"swedish": "innan", "german": "vor (zeitlich)", "category": "Präposition"},
    {"swedish": "mot", "german": "gegen", "category": "Präposition"},
    {"swedish": "hos", "german": "bei", "category": "Präposition"},
    {"swedish": "vid", "german": "bei, an", "category": "Präposition"},
    {"swedish": "bakom", "german": "hinter", "category": "Präposition"},
    {"swedish": "framför", "german": "vor (räumlich)", "category": "Präposition"},
    {"swedish": "bredvid", "german": "neben", "category": "Präposition"},
    {"swedish": "runt", "german": "um, herum", "category": "Präposition"},

    # --- Konjunktionen ---
    {"swedish": "och", "german": "und", "category": "Konjunktion"},
    {"swedish": "men", "german": "aber", "category": "Konjunktion"},
    {"swedish": "eller", "german": "oder", "category": "Konjunktion"},
    {"swedish": "så", "german": "also, so", "category": "Konjunktion"},
    {"swedish": "att", "german": "dass", "category": "Konjunktion"},
    {"swedish": "om", "german": "wenn, falls", "category": "Konjunktion"},
    {"swedish": "när", "german": "wenn, als (zeitlich)", "category": "Konjunktion"},
    {"swedish": "eftersom", "german": "weil, da", "category": "Konjunktion"},
    {"swedish": "fastän", "german": "obwohl", "category": "Konjunktion"},
    {"swedish": "medan", "german": "während", "category": "Konjunktion"},
    {"swedish": "innan", "german": "bevor", "category": "Konjunktion"},
    {"swedish": "tills", "german": "bis", "category": "Konjunktion"},
    {"swedish": "för att", "german": "damit, um zu", "category": "Konjunktion"},

    # --- Häufige Adverbien ---
    {"swedish": "inte", "german": "nicht", "category": "Adverb"},
    {"swedish": "mycket", "german": "sehr, viel", "category": "Adverb"},
    {"swedish": "lite", "german": "wenig, ein bisschen", "category": "Adverb"},
    {"swedish": "alltid", "german": "immer", "category": "Adverb"},
    {"swedish": "aldrig", "german": "nie", "category": "Adverb"},
    {"swedish": "ofta", "german": "oft", "category": "Adverb"},
    {"swedish": "ibland", "german": "manchmal", "category": "Adverb"},
    {"swedish": "redan", "german": "schon", "category": "Adverb"},
    {"swedish": "snart", "german": "bald", "category": "Adverb"},
    {"swedish": "nu", "german": "jetzt", "category": "Adverb"},
    {"swedish": "då", "german": "dann, damals", "category": "Adverb"},
    {"swedish": "här", "german": "hier", "category": "Adverb"},
    {"swedish": "där", "german": "dort", "category": "Adverb"},
    {"swedish": "också", "german": "auch", "category": "Adverb"},
    {"swedish": "bara", "german": "nur", "category": "Adverb"},
    {"swedish": "kanske", "german": "vielleicht", "category": "Adverb"},
    {"swedish": "ganska", "german": "ziemlich", "category": "Adverb"},
    {"swedish": "väldigt", "german": "sehr", "category": "Adverb"},
    {"swedish": "idag", "german": "heute", "category": "Adverb"},
    {"swedish": "igår", "german": "gestern", "category": "Adverb"},
    {"swedish": "imorgon", "german": "morgen", "category": "Adverb"},
    {"swedish": "sedan", "german": "seitdem, danach", "category": "Adverb"},
    {"swedish": "fortfarande", "german": "immer noch", "category": "Adverb"},
    {"swedish": "genast", "german": "sofort", "category": "Adverb"},
    {"swedish": "tillsammans", "german": "zusammen", "category": "Adverb"},

    # --- Verben (Praesens/Preteritum/Supinum; Perfekt-Hilfsverb ist im Schwedischen
    #     praktisch immer "ha" -> har/hade + Supinum, deshalb keine eigene Spalte noetig.
    #     Futur wird mit "ska" + Infinitiv gebildet, ebenfalls ohne Zusatzdaten. ---
    {"swedish": "vara", "german": "sein", "category": "Verb", "forms": {"present": "är", "preteritum": "var", "supinum": "varit"}},
    {"swedish": "ha", "german": "haben", "category": "Verb", "forms": {"present": "har", "preteritum": "hade", "supinum": "haft"}},
    {"swedish": "göra", "german": "machen, tun", "category": "Verb", "forms": {"present": "gör", "preteritum": "gjorde", "supinum": "gjort"}},
    {"swedish": "säga", "german": "sagen", "category": "Verb", "forms": {"present": "säger", "preteritum": "sa", "supinum": "sagt"}},
    {"swedish": "kunna", "german": "können", "category": "Verb", "forms": {"present": "kan", "preteritum": "kunde", "supinum": "kunnat"}, "grammar_note": "Modalverb"},
    {"swedish": "vilja", "german": "wollen", "category": "Verb", "forms": {"present": "vill", "preteritum": "ville", "supinum": "velat"}, "grammar_note": "Modalverb"},
    {"swedish": "ska", "german": "werden, sollen", "category": "Verb", "forms": {"present": "ska", "preteritum": "skulle", "supinum": "skolat"}, "grammar_note": "Modalverb, bildet den Futur: ska + Infinitiv"},
    {"swedish": "måste", "german": "müssen", "category": "Verb", "forms": {"present": "måste", "preteritum": "var tvungen att", "supinum": "varit tvungen att"}, "grammar_note": "Modalverb ohne eigene Praesensform (immer 'måste')"},
    {"swedish": "komma", "german": "kommen", "category": "Verb", "forms": {"present": "kommer", "preteritum": "kom", "supinum": "kommit"}},
    {"swedish": "gå", "german": "gehen", "category": "Verb", "forms": {"present": "går", "preteritum": "gick", "supinum": "gått"}},
    {"swedish": "se", "german": "sehen", "category": "Verb", "forms": {"present": "ser", "preteritum": "såg", "supinum": "sett"}},
    {"swedish": "veta", "german": "wissen", "category": "Verb", "forms": {"present": "vet", "preteritum": "visste", "supinum": "vetat"}},
    {"swedish": "ta", "german": "nehmen", "category": "Verb", "forms": {"present": "tar", "preteritum": "tog", "supinum": "tagit"}},
    {"swedish": "få", "german": "bekommen, dürfen", "category": "Verb", "forms": {"present": "får", "preteritum": "fick", "supinum": "fått"}},
    {"swedish": "tro", "german": "glauben", "category": "Verb", "forms": {"present": "tror", "preteritum": "trodde", "supinum": "trott"}},
    {"swedish": "tycka", "german": "finden, meinen", "category": "Verb", "forms": {"present": "tycker", "preteritum": "tyckte", "supinum": "tyckt"}},
    {"swedish": "behöva", "german": "brauchen", "category": "Verb", "forms": {"present": "behöver", "preteritum": "behövde", "supinum": "behövt"}},
    {"swedish": "fråga", "german": "fragen", "category": "Verb", "forms": {"present": "frågar", "preteritum": "frågade", "supinum": "frågat"}},
    {"swedish": "tänka", "german": "denken", "category": "Verb", "forms": {"present": "tänker", "preteritum": "tänkte", "supinum": "tänkt"}},
    {"swedish": "arbeta", "german": "arbeiten", "category": "Verb", "forms": {"present": "arbetar", "preteritum": "arbetade", "supinum": "arbetat"}},
    {"swedish": "spela", "german": "spielen", "category": "Verb", "forms": {"present": "spelar", "preteritum": "spelade", "supinum": "spelat"}},
    {"swedish": "tala", "german": "sprechen", "category": "Verb", "forms": {"present": "talar", "preteritum": "talade", "supinum": "talat"}},
    {"swedish": "prata", "german": "reden, sprechen", "category": "Verb", "forms": {"present": "pratar", "preteritum": "pratade", "supinum": "pratat"}},
    {"swedish": "skriva", "german": "schreiben", "category": "Verb", "forms": {"present": "skriver", "preteritum": "skrev", "supinum": "skrivit"}},
    {"swedish": "läsa", "german": "lesen", "category": "Verb", "forms": {"present": "läser", "preteritum": "läste", "supinum": "läst"}},
    {"swedish": "äta", "german": "essen", "category": "Verb", "forms": {"present": "äter", "preteritum": "åt", "supinum": "ätit"}},
    {"swedish": "dricka", "german": "trinken", "category": "Verb", "forms": {"present": "dricker", "preteritum": "drack", "supinum": "druckit"}},
    {"swedish": "sova", "german": "schlafen", "category": "Verb", "forms": {"present": "sover", "preteritum": "sov", "supinum": "sovit"}},
    {"swedish": "bo", "german": "wohnen", "category": "Verb", "forms": {"present": "bor", "preteritum": "bodde", "supinum": "bott"}},
    {"swedish": "leva", "german": "leben", "category": "Verb", "forms": {"present": "lever", "preteritum": "levde", "supinum": "levt"}},
    {"swedish": "dö", "german": "sterben", "category": "Verb", "forms": {"present": "dör", "preteritum": "dog", "supinum": "dött"}},
    {"swedish": "köpa", "german": "kaufen", "category": "Verb", "forms": {"present": "köper", "preteritum": "köpte", "supinum": "köpt"}},
    {"swedish": "sälja", "german": "verkaufen", "category": "Verb", "forms": {"present": "säljer", "preteritum": "sålde", "supinum": "sålt"}},
    {"swedish": "ge", "german": "geben", "category": "Verb", "forms": {"present": "ger", "preteritum": "gav", "supinum": "gett"}},
    {"swedish": "hjälpa", "german": "helfen", "category": "Verb", "forms": {"present": "hjälper", "preteritum": "hjälpte", "supinum": "hjälpt"}},
    {"swedish": "förstå", "german": "verstehen", "category": "Verb", "forms": {"present": "förstår", "preteritum": "förstod", "supinum": "förstått"}},
    {"swedish": "lära", "german": "lehren, lernen", "category": "Verb", "forms": {"present": "lär", "preteritum": "lärde", "supinum": "lärt"}},
    {"swedish": "börja", "german": "beginnen", "category": "Verb", "forms": {"present": "börjar", "preteritum": "började", "supinum": "börjat"}},
    {"swedish": "sluta", "german": "aufhören", "category": "Verb", "forms": {"present": "slutar", "preteritum": "slutade", "supinum": "slutat"}},
    {"swedish": "fortsätta", "german": "fortsetzen", "category": "Verb", "forms": {"present": "fortsätter", "preteritum": "fortsatte", "supinum": "fortsatt"}},
    {"swedish": "stanna", "german": "bleiben, anhalten", "category": "Verb", "forms": {"present": "stannar", "preteritum": "stannade", "supinum": "stannat"}},
    {"swedish": "hitta", "german": "finden", "category": "Verb", "forms": {"present": "hittar", "preteritum": "hittade", "supinum": "hittat"}},
    {"swedish": "leta", "german": "suchen", "category": "Verb", "forms": {"present": "letar", "preteritum": "letade", "supinum": "letat"}},
    {"swedish": "titta", "german": "schauen", "category": "Verb", "forms": {"present": "tittar", "preteritum": "tittade", "supinum": "tittat"}},
    {"swedish": "lyssna", "german": "zuhören", "category": "Verb", "forms": {"present": "lyssnar", "preteritum": "lyssnade", "supinum": "lyssnat"}},
    {"swedish": "höra", "german": "hören", "category": "Verb", "forms": {"present": "hör", "preteritum": "hörde", "supinum": "hört"}},
    {"swedish": "känna", "german": "fühlen, kennen", "category": "Verb", "forms": {"present": "känner", "preteritum": "kände", "supinum": "känt"}},
    {"swedish": "bli", "german": "werden", "category": "Verb", "forms": {"present": "blir", "preteritum": "blev", "supinum": "blivit"}},
    {"swedish": "sitta", "german": "sitzen", "category": "Verb", "forms": {"present": "sitter", "preteritum": "satt", "supinum": "suttit"}},
    {"swedish": "stå", "german": "stehen", "category": "Verb", "forms": {"present": "står", "preteritum": "stod", "supinum": "stått"}},
    {"swedish": "ligga", "german": "liegen", "category": "Verb", "forms": {"present": "ligger", "preteritum": "låg", "supinum": "legat"}},
    {"swedish": "springa", "german": "laufen, rennen", "category": "Verb", "forms": {"present": "springer", "preteritum": "sprang", "supinum": "sprungit"}},
    {"swedish": "köra", "german": "fahren (Fahrzeug)", "category": "Verb", "forms": {"present": "kör", "preteritum": "körde", "supinum": "kört"}},
    {"swedish": "resa", "german": "reisen", "category": "Verb", "forms": {"present": "reser", "preteritum": "reste", "supinum": "rest"}},
    {"swedish": "flyga", "german": "fliegen", "category": "Verb", "forms": {"present": "flyger", "preteritum": "flög", "supinum": "flugit"}},
    {"swedish": "simma", "german": "schwimmen", "category": "Verb", "forms": {"present": "simmar", "preteritum": "simmade", "supinum": "simmat"}},
    {"swedish": "laga", "german": "reparieren, kochen", "category": "Verb", "forms": {"present": "lagar", "preteritum": "lagade", "supinum": "lagat"}},
    {"swedish": "öppna", "german": "öffnen", "category": "Verb", "forms": {"present": "öppnar", "preteritum": "öppnade", "supinum": "öppnat"}},
    {"swedish": "stänga", "german": "schließen", "category": "Verb", "forms": {"present": "stänger", "preteritum": "stängde", "supinum": "stängt"}},
    {"swedish": "lämna", "german": "verlassen, lassen", "category": "Verb", "forms": {"present": "lämnar", "preteritum": "lämnade", "supinum": "lämnat"}},
    {"swedish": "träffa", "german": "treffen", "category": "Verb", "forms": {"present": "träffar", "preteritum": "träffade", "supinum": "träffat"}},
    {"swedish": "ringa", "german": "anrufen, klingeln", "category": "Verb", "forms": {"present": "ringer", "preteritum": "ringde", "supinum": "ringt"}},
    {"swedish": "skicka", "german": "schicken", "category": "Verb", "forms": {"present": "skickar", "preteritum": "skickade", "supinum": "skickat"}},
    {"swedish": "betala", "german": "bezahlen", "category": "Verb", "forms": {"present": "betalar", "preteritum": "betalade", "supinum": "betalat"}},
    {"swedish": "glömma", "german": "vergessen", "category": "Verb", "forms": {"present": "glömmer", "preteritum": "glömde", "supinum": "glömt"}},
    {"swedish": "förlora", "german": "verlieren", "category": "Verb", "forms": {"present": "förlorar", "preteritum": "förlorade", "supinum": "förlorat"}},
    {"swedish": "vinna", "german": "gewinnen", "category": "Verb", "forms": {"present": "vinner", "preteritum": "vann", "supinum": "vunnit"}},
    {"swedish": "skratta", "german": "lachen", "category": "Verb", "forms": {"present": "skrattar", "preteritum": "skrattade", "supinum": "skrattat"}},
    {"swedish": "gråta", "german": "weinen", "category": "Verb", "forms": {"present": "gråter", "preteritum": "grät", "supinum": "gråtit"}},
    {"swedish": "le", "german": "lächeln", "category": "Verb", "forms": {"present": "ler", "preteritum": "log", "supinum": "lett"}},
    {"swedish": "vakna", "german": "aufwachen", "category": "Verb", "forms": {"present": "vaknar", "preteritum": "vaknade", "supinum": "vaknat"}},
    {"swedish": "duscha", "german": "duschen", "category": "Verb", "forms": {"present": "duschar", "preteritum": "duschade", "supinum": "duschat"}},
    {"swedish": "tvätta", "german": "waschen", "category": "Verb", "forms": {"present": "tvättar", "preteritum": "tvättade", "supinum": "tvättat"}},
    {"swedish": "städa", "german": "putzen", "category": "Verb", "forms": {"present": "städar", "preteritum": "städade", "supinum": "städat"}},
    {"swedish": "önska", "german": "wünschen", "category": "Verb", "forms": {"present": "önskar", "preteritum": "önskade", "supinum": "önskat"}},
    {"swedish": "hoppas", "german": "hoffen", "category": "Verb", "forms": {"present": "hoppas", "preteritum": "hoppades", "supinum": "hoppats"}, "grammar_note": "Deponens-Verb (endet immer auf -s)"},
    {"swedish": "bestämma", "german": "bestimmen, entscheiden", "category": "Verb", "forms": {"present": "bestämmer", "preteritum": "bestämde", "supinum": "bestämt"}},
    {"swedish": "välja", "german": "wählen", "category": "Verb", "forms": {"present": "väljer", "preteritum": "valde", "supinum": "valt"}},
    {"swedish": "förklara", "german": "erklären", "category": "Verb", "forms": {"present": "förklarar", "preteritum": "förklarade", "supinum": "förklarat"}},
    {"swedish": "visa", "german": "zeigen", "category": "Verb", "forms": {"present": "visar", "preteritum": "visade", "supinum": "visat"}},
    {"swedish": "byta", "german": "wechseln, tauschen", "category": "Verb", "forms": {"present": "byter", "preteritum": "bytte", "supinum": "bytt"}},
    {"swedish": "använda", "german": "benutzen", "category": "Verb", "forms": {"present": "använder", "preteritum": "använde", "supinum": "använt"}},
    {"swedish": "skapa", "german": "erschaffen", "category": "Verb", "forms": {"present": "skapar", "preteritum": "skapade", "supinum": "skapat"}},
    {"swedish": "bygga", "german": "bauen", "category": "Verb", "forms": {"present": "bygger", "preteritum": "byggde", "supinum": "byggt"}},
    {"swedish": "växa", "german": "wachsen", "category": "Verb", "forms": {"present": "växer", "preteritum": "växte", "supinum": "vuxit"}},
    {"swedish": "förändra", "german": "verändern", "category": "Verb", "forms": {"present": "förändrar", "preteritum": "förändrade", "supinum": "förändrat"}},
    {"swedish": "sätta", "german": "setzen, stellen", "category": "Verb", "forms": {"present": "sätter", "preteritum": "satte", "supinum": "satt"}},
    {"swedish": "flytta", "german": "umziehen", "category": "Verb", "forms": {"present": "flyttar", "preteritum": "flyttade", "supinum": "flyttat"}},
]