# -*- coding: utf-8 -*-
"""Gesundheit/Notfall und Job auf Russisch.

Zusammen 118 Master-Saetze - health_emergency (76), job_work (42).

**Lautschrift-Regeln** stehen im Kopf von `grundwortschatz_ru.py`.

**VIER SAETZE SIND CHINA-SPEZIFISCH und wandern NICHT woertlich mit** -
dieselben vier wie in den beiden Schwesterdateien, wieder mit eigener
Ersatzloesung:

  Rufen Sie bitte 120 an.     **120 ist der chinesische Rettungsdienst.**
                              In Russland ist der Krankenwagen die **103**
                              (vom Handy; 03 vom Festnetz), 112 ist die
                              uebergreifende Notrufnummer. Damit hat jede
                              der drei neuen Sprachen eine ANDERE Nummer:
                              112 (it), 113 (no), 103 (ru). Das ist der
                              Grund, warum dieser Satz nirgends einfach
                              uebersetzt wurde.
  Ich moechte westliche       Der Gegensatz westliche Medizin / TCM traegt
  Medizin.                    in Russland nicht. Beide ausgelassen.
  Ist das westliche Medizin?
  Ich spreche kein            Zielsprache im Satz - durch die russische
  Chinesisch. ...             Fassung ersetzt.

**116 Saetze uebersetzt, 4 ausgelassen, 2 neu.**

**Zwei russische Eigenheiten, die hier oefter auftauchen als sonstwo:**
die Vergangenheit richtet sich nach dem Geschlecht des SPRECHERS
(потерял/потеряла), und Befinden laeuft ueber den Dativ - "мне плохо"
heisst woertlich "mir ist schlecht", ein "ich bin" gibt es nicht.

**Nicht von Muttersprachlern geprueft** - bei Russisch faellt das staerker
ins Gewicht, weil die Lautschrift eine zusaetzliche Fehlerquelle ist. Bei
NOTFALL-Saetzen waere ein Muttersprachler-Check besonders wichtig.
"""

KATEGORIEN = ['health_emergency', 'job_work']

SAETZE = [

# ========================================================== health_emergency
 dict(kat='health_emergency', de='Ich bin allergisch gegen Penizillin.', ru='У меня аллергия на пенициллин.',
      py='U menjá allergíja na penizillín.',
      k=[('allergisch', ['аллергия']),
         ('penizillin', ['пенициллин'])],
      h='Wörtlich „bei mir ist Allergie auf ..." — Russisch sagt nicht „ich '
        'bin allergisch", sondern konstruiert es mit „у меня".'),
 dict(kat='health_emergency', de='Ich habe eine Allergie.', ru='У меня аллергия.',
      py='U menjá allergíja.',
      k=[('allergie', ['аллергия'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen dieses Medikament.', ru='У меня аллергия на это лекарство.',
      py='U menjá allergíja na éta lekárstwa.',
      k=[('allergisch', ['аллергия']),
         ('medikament', ['лекарство'])]),
 dict(kat='health_emergency', de='Ich bin allergisch gegen Erdnüsse.', ru='У меня аллергия на арахис.',
      py='U menjá allergíja na aráchis.',
      k=[('allergisch', ['аллергия']),
         ('erdnuesse', ['арахис'])]),
 dict(kat='health_emergency', de='Ich kann keine Erdnüsse essen.', ru='Мне нельзя арахис.',
      py='Mnje neljsjá aráchis.',
      k=[('nicht_essen', ['нельзя', 'мне нельзя']),
         ('erdnuesse', ['арахис'])],
      h='„Мне нельзя" (mir ist nicht erlaubt) ist die knappste und '
        'klarste Form, eine Unverträglichkeit zu nennen — kürzer als jede '
        'Konstruktion mit „ich kann nicht".'),
 dict(kat='health_emergency', de='Sind da Erdnüsse drin?', ru='Здесь есть арахис?',
      py='Sdjes jest aráchis?',
      k=[('erdnuesse', ['арахис'])]),
 dict(kat='health_emergency', de='Bitte ohne Erdnüsse.', ru='Без арахиса, пожалуйста.',
      py='Bes aráchissa, pashálusta.',
      k=[('ohne', ['без']),
         ('erdnuesse', ['арахиса', 'арахис'])]),
 dict(kat='health_emergency', de='Bitte ohne Milch.', ru='Без молока, пожалуйста.',
      py='Bes malaká, pashálusta.',
      k=[('ohne', ['без']),
         ('milch', ['молока', 'молоко'])]),
 dict(kat='health_emergency', de='Ich vertrage keine Milch.', ru='Я не переношу молоко.',
      py='Ja nje perenaschú malakó.',
      k=[('milch_vertragen', ['не переношу молоко', 'не переношу', 'молоко'])]),
 dict(kat='health_emergency', de='Was ist da drin?', ru='Что здесь внутри?',
      py='Schto sdjes wnutrí?',
      k=[('was_drin', ['что здесь', 'внутри', 'состав'])]),
 dict(kat='health_emergency', de='Ich habe mein Allergiemedikament dabei.', ru='У меня с собой лекарство от аллергии.',
      py='U menjá s sabój lekárstwa at allergíi.',
      k=[('allergiemedikament', ['лекарство от аллергии', 'от аллергии'])]),
 dict(kat='health_emergency', de='Das ist für mich sehr gefährlich.', ru='Для меня это очень опасно.',
      py='Dlja menjá éta ótschen apásna.',
      k=[('gefaehrlich', ['опасно', 'очень опасно'])]),
 dict(kat='health_emergency', de='Ist das gefährlich?', ru='Это опасно?',
      py='Éta apásna?',
      k=[('gefaehrlich', ['опасно'])]),
 dict(kat='health_emergency', de='Ich habe meine Versicherungskarte vergessen.', ru='Я забыл свою страховку.',
      py='Ja sabýl swajú strachówku.',
      k=[('versicherungskarte', ['страховку', 'страховка'])]),
 dict(kat='health_emergency', de='Wie viel kostet das?', ru='Сколько это стоит?',
      py='Skólka éta stóit?',
      k=[('kosten', ['сколько это стоит', 'сколько стоит'])]),
 dict(kat='health_emergency', de='Ich habe eine Versicherung.', ru='У меня есть страховка.',
      py='U menjá jest strachówka.',
      k=[('versicherung', ['страховка'])]),
 dict(kat='health_emergency', de='Nehmen Sie meine Versicherung?', ru='Вы принимаете мою страховку?',
      py='Wy prinimájetje majú strachówku?',
      k=[('versicherung_akzeptiert', ['принимаете', 'страховку'])]),
 dict(kat='health_emergency', de='Muss ich vorher bezahlen?', ru='Нужно платить заранее?',
      py='Núshna platít sarányeje?',
      k=[('vorher_bezahlen', ['платить заранее', 'заранее'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir eine Quittung.', ru='Дайте мне чек, пожалуйста.',
      py='Dájtje mnje tschek, pashálusta.',
      k=[('quittung', ['чек', 'квитанцию'])]),
 dict(kat='health_emergency', de='Ich brauche die Quittung für meine Versicherung.', ru='Мне нужен чек для страховки.',
      py='Mnje núshen tschek dlja strachówki.',
      k=[('quittung', ['чек', 'квитанция']),
         ('versicherung', ['страховки', 'страховка'])]),
 dict(kat='health_emergency', de='Kann ich mit dem Handy bezahlen?', ru='Можно оплатить телефоном?',
      py='Móshna aplatít teljefónam?',
      k=[('handy_bezahlen', ['телефоном', 'телефон'])]),
 dict(kat='health_emergency', de='Nehmen Sie auch Karte?', ru='Вы принимаете карту?',
      py='Wy prinimájetje kártu?',
      k=[('karte', ['карту', 'карта'])]),
 dict(kat='health_emergency', de='Hier ist meine Karte.', ru='Вот моя карта.',
      py='Wot majá kárta.',
      k=[('meine_karte', ['вот моя карта', 'моя карта', 'карта'])]),
 dict(kat='health_emergency', de='Zuerst anmelden, dann bezahlen?', ru='Сначала записаться, потом платить?',
      py='Snatschála sapissátsa, patóm platít?',
      k=[('anmelden', ['записаться', 'регистрация']),
         ('bezahlen', ['платить', 'оплата'])]),
 dict(kat='health_emergency', de='Wo bekomme ich die Quittung?', ru='Где получить чек?',
      py='Gdje palutschít tschek?',
      k=[('quittung', ['чек', 'квитанцию'])]),
 dict(kat='health_emergency', de='Wo kann ich bezahlen?', ru='Где можно оплатить?',
      py='Gdje móshna aplatít?',
      k=[('wo_bezahlen', ['где можно оплатить', 'оплатить', 'касса'])]),
 dict(kat='health_emergency', de='Das ist zu teuer.', ru='Это слишком дорого.',
      py='Éta slíschkam dóraga.',
      k=[('zu_teuer', ['слишком дорого', 'дорого'])]),
 dict(kat='health_emergency', de='Ich habe nicht genug Geld dabei.', ru='У меня с собой не хватит денег.',
      py='U menjá s sabój nje chwátit djénjeg.',
      k=[('nicht_genug_geld', ['не хватит денег', 'не хватает', 'денег'])]),
 dict(kat='health_emergency', de='Reicht das?', ru='Этого хватит?',
      py='Étawa chwátit?',
      k=[('reicht', ['хватит', 'достаточно'])]),
 dict(kat='health_emergency', de='Ich habe meine Tabletten vergessen.', ru='Я забыл свои таблетки.',
      py='Ja sabýl swaí tablétki.',
      k=[('tabletten_vergessen', ['забыл таблетки', 'таблетки', 'забыла'])]),
 dict(kat='health_emergency', de='Wie oft muss ich das Medikament nehmen?', ru='Как часто принимать лекарство?',
      py='Kak tschásta prinimát lekárstwa?',
      k=[('medikament_haeufigkeit', ['как часто', 'принимать лекарство', 'лекарство'])]),
 dict(kat='health_emergency', de='Wo ist das Krankenhaus?', ru='Где больница?',
      py='Gdje balníza?',
      k=[('krankenhaus', ['больница'])]),
 dict(kat='health_emergency', de='Ich möchte zum Arzt.', ru='Я хочу к врачу.',
      py='Ja chatschú k wratschú.',
      k=[('arzt', ['врачу', 'врач', 'доктор'])]),
 dict(kat='health_emergency', de='Wo melde ich mich an?', ru='Где регистратура?',
      py='Gdje registratúra?',
      k=[('anmelden', ['регистратура', 'записаться'])],
      h='Die „регистратура" ist der Anmeldeschalter — der erste Halt in '
        'jeder russischen Klinik, vor allem anderen.'),
 dict(kat='health_emergency', de='Ich möchte mich anmelden.', ru='Я хочу записаться.',
      py='Ja chatschú sapissátsa.',
      k=[('anmelden', ['записаться', 'запись'])]),
 dict(kat='health_emergency', de='Ich habe keinen Termin.', ru='У меня нет записи.',
      py='U menjá njet zápissi.',
      k=[('kein_termin', ['нет записи', 'записи'])]),
 dict(kat='health_emergency', de='Kann ich einen Termin bekommen?', ru='Можно записаться на приём?',
      py='Móshna sapissátsa na prijóm?',
      k=[('termin', ['записаться', 'приём', 'запись'])]),
 dict(kat='health_emergency', de='Wie lange muss ich warten?', ru='Сколько нужно ждать?',
      py='Skólka núshna shdat?',
      k=[('warten', ['сколько ждать', 'ждать'])]),
 dict(kat='health_emergency', de='Wie lange dauert das?', ru='Сколько это займёт?',
      py='Skólka éta sajmjót?',
      k=[('dauer', ['сколько займёт', 'займёт', 'сколько времени'])]),
 dict(kat='health_emergency', de='Bitte geben Sie mir ein Medikament.', ru='Дайте мне лекарство, пожалуйста.',
      py='Dájtje mnje lekárstwa, pashálusta.',
      k=[('medikament', ['лекарство'])]),
 dict(kat='health_emergency', de='Wie nehme ich das Medikament?', ru='Как принимать это лекарство?',
      py='Kak prinimát éta lekárstwa?',
      k=[('medikament_einnahme', ['как принимать', 'принимать', 'лекарство'])]),
 dict(kat='health_emergency', de='Wie komme ich dorthin?', ru='Как туда добраться?',
      py='Kak tudá dabrátsa?',
      k=[('wie_dorthin', ['как туда добраться', 'туда', 'добраться'])]),
 dict(kat='health_emergency', de='Ich brauche einen Arzt.', ru='Мне нужен врач.',
      py='Mnje núshen wratsch.',
      k=[('arzt', ['врач', 'доктор'])]),
 dict(kat='health_emergency', de='Wo ist die nächste Apotheke?', ru='Где ближайшая аптека?',
      py='Gdje blishájschaja aptjéka?',
      k=[('apotheke', ['аптека'])],
      h='Apotheken sind in russischen Städten dicht gesät und viele haben '
        'rund um die Uhr offen („круглосуточно"). Vieles, was bei uns '
        'verschreibungspflichtig ist, bekommt man dort direkt.'),
 dict(kat='health_emergency', de='Ich brauche dringend Hilfe.', ru='Мне срочно нужна помощь.',
      py='Mnje srótschna nushná pómasch.',
      k=[('dringend_hilfe', ['срочно нужна помощь', 'срочно', 'помощь'])]),
 dict(kat='health_emergency', de='Wo ist das nächste Krankenhaus?', ru='Где ближайшая больница?',
      py='Gdje blishájschaja balníza?',
      k=[('krankenhaus', ['больница'])]),
 dict(kat='health_emergency', de='Bitte helfen Sie mir!', ru='Помогите мне, пожалуйста!',
      py='Pamagítje mnje, pashálusta!',
      k=[('helfen', ['помогите', 'помощь'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie einen Krankenwagen!', ru='Вызовите скорую, пожалуйста!',
      py='Wýsawitje skóruju, pashálusta!',
      k=[('krankenwagen', ['скорую', 'скорая', 'скорую помощь'])],
      h='Der Krankenwagen heißt „скорая" (die Schnelle) — kurz für „скорая '
        'помощь". Niemand sagt das lange Wort aus.'),
 dict(kat='health_emergency', de='Ist der Krankenwagen schon unterwegs?', ru='Скорая уже едет?',
      py='Skóraja ushé jédjet?',
      k=[('krankenwagen', ['скорая']),
         ('unterwegs', ['уже едет', 'едет'])]),
 dict(kat='health_emergency', de='Jemand ist verletzt.', ru='Здесь есть пострадавший.',
      py='Sdjes jest pastradáwschij.',
      k=[('verletzt', ['пострадавший', 'ранен'])]),
 dict(kat='health_emergency', de='Ich bin verletzt.', ru='Я ранен.',
      py='Ja ránen.',
      k=[('verletzt', ['ранен', 'ранена'])]),
 dict(kat='health_emergency', de='Schnell, bitte!', ru='Быстрее, пожалуйста!',
      py='Bystrjéje, pashálusta!',
      k=[('schnell', ['быстрее', 'скорее'])]),
 dict(kat='health_emergency', de='Ich brauche etwas aus der Apotheke.', ru='Мне нужно кое-что из аптеки.',
      py='Mnje núshna kaje-schtó is aptjéki.',
      k=[('apotheke', ['аптеки', 'аптека'])]),
 dict(kat='health_emergency', de='Ich bin allein hier.', ru='Я здесь один.',
      py='Ja sdjes adín.',
      k=[('allein', ['один', 'одна'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie meinen Freund an.', ru='Позвоните моему другу, пожалуйста.',
      py='Pasvanítje majemú drúgu, pashálusta.',
      k=[('anrufen', ['позвоните', 'позвонить']),
         ('freund', ['другу', 'друг'])]),
 dict(kat='health_emergency', de='Bitte rufen Sie die Polizei!', ru='Вызовите полицию, пожалуйста!',
      py='Wýsawitje políziju, pashálusta!',
      k=[('polizei', ['полицию', 'полиция'])]),
 dict(kat='health_emergency', de='Ich möchte die Polizei rufen.', ru='Я хочу вызвать полицию.',
      py='Ja chatschú wýswat políziju.',
      k=[('polizei', ['полицию', 'полиция'])]),
 dict(kat='health_emergency', de='Mir geht es nicht gut.', ru='Мне нехорошо.',
      py='Mnje necharaschó.',
      k=[('nicht_gut', ['нехорошо', 'плохо'])]),
 dict(kat='health_emergency', de='Ich habe Kopfschmerzen.', ru='У меня болит голова.',
      py='U menjá balít galawá.',
      k=[('kopfschmerzen', ['болит голова', 'голова'])],
      h='Wörtlich „bei mir schmerzt der Kopf" — das Körperteil ist das '
        'Subjekt, nicht der Mensch. Nach demselben Muster: „болит живот" '
        '(Bauch), „болит горло" (Hals).'),
 dict(kat='health_emergency', de='Ich habe Fieber.', ru='У меня температура.',
      py='U menjá temperatúra.',
      k=[('fieber', ['температура', 'жар'])],
      h='„Температура" allein heißt schon Fieber — wer nur „Temperatur" '
        'meint, sagt es dazu.'),
 dict(kat='health_emergency', de='Ich habe mir den Fuß verletzt.', ru='Я повредил ногу.',
      py='Ja pawredíl nógu.',
      k=[('fuss_verletzt', ['повредил ногу', 'нога', 'ногу'])],
      h='„Нога" meint Bein UND Fuß — Russisch trennt die beiden nicht, '
        'genauso wenig wie „рука" Arm und Hand trennt.'),
 dict(kat='health_emergency', de='Ich fühle mich schwindelig.', ru='У меня кружится голова.',
      py='U menjá krúshitsa galawá.',
      k=[('schwindelig', ['кружится голова', 'кружится'])]),
 dict(kat='health_emergency', de='Ich bin krank.', ru='Я болею.',
      py='Ja baljéju.',
      k=[('krank', ['болею', 'болен', 'больна'])]),
 dict(kat='health_emergency', de='Ich bin erkältet.', ru='Я простудился.',
      py='Ja prastudílsja.',
      k=[('erkaeltet', ['простудился', 'простудилась', 'простуда'])]),
 dict(kat='health_emergency', de='Ich habe Bauchschmerzen.', ru='У меня болит живот.',
      py='U menjá balít shywót.',
      k=[('bauchschmerzen', ['болит живот', 'живот'])]),
 dict(kat='health_emergency', de='Mein Bein tut weh.', ru='У меня болит нога.',
      py='U menjá balít nagá.',
      k=[('bein_weh', ['болит нога', 'нога'])]),
 dict(kat='health_emergency', de='Hier tut es weh.', ru='Здесь болит.',
      py='Sdjes balít.',
      k=[('hier_weh', ['здесь болит', 'болит'])]),
 dict(kat='health_emergency', de='Mir geht es sehr schlecht.', ru='Мне очень плохо.',
      py='Mnje ótschen plócha.',
      k=[('sehr_schlecht', ['очень плохо', 'плохо'])]),
 dict(kat='health_emergency', de='Ich bin sehr müde.', ru='Я очень устал.',
      py='Ja ótschen ustál.',
      k=[('muede', ['устал', 'устала'])]),
 dict(kat='health_emergency', de='Mir ist kalt.', ru='Мне холодно.',
      py='Mnje chóladna.',
      k=[('kalt', ['мне холодно', 'холодно'])],
      h='Wieder der Dativ: „мне холодно" — mir ist kalt. „Я холодный" '
        'hieße, du seist ein kalter Mensch.'),
 dict(kat='health_emergency', de='Seit gestern.', ru='Со вчерашнего дня.',
      py='Sa wtscheráschnewa dnja.',
      k=[('seit_gestern', ['со вчерашнего дня', 'со вчера', 'вчера'])]),
 dict(kat='health_emergency', de='Seit heute Morgen.', ru='С сегодняшнего утра.',
      py='S sewódnjaschnewa utrá.',
      k=[('seit_heute_morgen', ['с сегодняшнего утра', 'с утра', 'утра'])]),
 dict(kat='health_emergency', de='Rufen Sie bitte 103 an.', ru='Позвоните 103, пожалуйста.',
      py='Pasvanítje sto tri, pashálusta.',
      neu=True, sz='health_notfall',
      k=[('notruf', ['103', 'сто три'])],
      h='Der Krankenwagen ist die 103 (vom Handy; 03 vom Festnetz), die '
        'übergreifende Notrufnummer die 112. Jede der drei neuen Sprachen '
        'hat eine andere Nummer — 112 in Italien, 113 in Norwegen, 103 '
        'hier.'),
 dict(kat='health_emergency', de='Ich spreche kein Russisch. Können Sie es aufschreiben?',
      ru='Я не говорю по-русски. Вы можете это записать?',
      py='Ja nje gawarjú pa-rússki. Wy móshetje éta sapissát?',
      neu=True, sz='health_krankenhaus',
      k=[('kein_russisch', ['не говорю по-русски', 'не говорю']),
         ('aufschreiben', ['записать', 'напишите'])]),

# ================================================================== job_work
 dict(kat='job_work', de='Ich kann heute nicht kommen.', ru='Я сегодня не смогу прийти.',
      py='Ja sewódnja nje smagú prijtí.',
      k=[('nicht_koennen', ['не смогу', 'не могу']),
         ('heute', ['сегодня']),
         ('kommen', ['прийти'])]),
 dict(kat='job_work', de='Ich bin krank und bleibe zu Hause.', ru='Я болею и останусь дома.',
      py='Ja baljéju i astánus dóma.',
      k=[('krank', ['болею', 'болен']),
         ('zu_hause', ['дома', 'останусь дома'])]),
 dict(kat='job_work', de='Ich komme später.', ru='Я приду позже.',
      py='Ja pridú pósche.',
      k=[('kommen', ['приду', 'прийти']),
         ('spaeter', ['позже'])]),
 dict(kat='job_work', de='Ich brauche einen Tag frei.', ru='Мне нужен выходной.',
      py='Mnje núshen wychadnój.',
      k=[('brauchen', ['мне нужен', 'нужен']),
         ('tag_frei', ['выходной'])]),
 dict(kat='job_work', de='Ich habe einen Arzttermin.', ru='У меня запись к врачу.',
      py='U menjá zápis k wratschú.',
      k=[('arzttermin', ['запись к врачу', 'к врачу', 'запись'])]),
 dict(kat='job_work', de='Ich habe schon in einem Restaurant gearbeitet.', ru='Я уже работал в ресторане.',
      py='Ja ushé rabótal w restaránje.',
      k=[('gearbeitet', ['работал', 'работала']),
         ('restaurant', ['ресторане', 'ресторан'])]),
 dict(kat='job_work', de='Ich habe keine Erfahrung.', ru='У меня нет опыта.',
      py='U menjá njet ópyta.',
      k=[('keine', ['нет']),
         ('erfahrung', ['опыта', 'опыт'])]),
 dict(kat='job_work', de='Ich lerne schnell.', ru='Я быстро учусь.',
      py='Ja býstra utschús.',
      k=[('lernen', ['учусь', 'научусь']),
         ('schnell', ['быстро'])]),
 dict(kat='job_work', de='Ich kann am Wochenende arbeiten.', ru='Я могу работать на выходных.',
      py='Ja magú rabótat na wychadných.',
      k=[('koennen', ['я могу', 'могу']),
         ('wochenende', ['на выходных', 'выходные']),
         ('arbeiten', ['работать'])]),
 dict(kat='job_work', de='Wann kann ich anfangen?', ru='Когда я могу начать?',
      py='Kagdá ja magú natschát?',
      k=[('wann', ['когда']),
         ('anfangen', ['начать', 'приступить'])]),
 dict(kat='job_work', de='Brauche ich eine Arbeitserlaubnis?', ru='Мне нужно разрешение на работу?',
      py='Mnje núshna raschrenije na rabótu?',
      k=[('brauchen', ['мне нужно', 'нужно']),
         ('arbeitserlaubnis', ['разрешение на работу', 'разрешение'])],
      h='Für Deutsche ist in Russland ein Arbeitsvisum nötig — anders als '
        'in Italien oder Norwegen, wo die EU-Freizügigkeit gilt. Ohne '
        'passendes Visum ist Arbeiten dort nicht legal möglich.'),
 dict(kat='job_work', de='Ich bin neu hier.', ru='Я здесь новенький.',
      py='Ja sdjes nówenkij.',
      k=[('neu', ['новенький', 'новенькая', 'новый']),
         ('hier', ['здесь'])]),
 dict(kat='job_work', de='Kannst du mir kurz helfen?', ru='Можешь мне помочь?',
      py='Móshesch mnje pamótsch?',
      k=[('koennen', ['можешь']),
         ('helfen', ['помочь', 'мне помочь'])]),
 dict(kat='job_work', de='Wie macht man das?', ru='Как это делается?',
      py='Kak éta djélajetsa?',
      k=[('wie', ['как']),
         ('machen', ['делается', 'делать'])]),
 dict(kat='job_work', de='Das habe ich noch nie gemacht.', ru='Я этого никогда не делал.',
      py='Ja étawa nikagdá nje djélal.',
      k=[('nie', ['никогда']),
         ('gemacht', ['не делал', 'делал', 'делала'])]),
 dict(kat='job_work', de='Wo finde ich das?', ru='Где мне это найти?',
      py='Gdje mnje éta najtí?',
      k=[('wo', ['где']),
         ('finden', ['найти'])]),
 dict(kat='job_work', de='Ich mache Pause.', ru='Я иду на перерыв.',
      py='Ja idú na pererýw.',
      k=[('pause', ['перерыв'])]),
 dict(kat='job_work', de='Danke für deine Hilfe.', ru='Спасибо за помощь.',
      py='Spassíba sa pómasch.',
      k=[('danke', ['спасибо']),
         ('hilfe', ['помощь', 'за помощь'])]),
 dict(kat='job_work', de='Kann ich Ihnen helfen?', ru='Я могу вам помочь?',
      py='Ja magú wam pamótsch?',
      k=[('koennen', ['я могу', 'могу']),
         ('helfen', ['вам помочь', 'помочь'])]),
 dict(kat='job_work', de='Der Nächste, bitte!', ru='Следующий, пожалуйста!',
      py='Slédujuschtschij, pashálusta!',
      k=[('naechste', ['следующий'])]),
 dict(kat='job_work', de='Möchten Sie noch etwas?', ru='Желаете что-нибудь ещё?',
      py='Shelájetje schto-nibúd jeschtschó?',
      k=[('moechten', ['желаете', 'хотите']),
         ('noch_etwas', ['что-нибудь ещё', 'ещё'])]),
 dict(kat='job_work', de='Zahlen Sie bar oder mit Karte?', ru='Наличными или картой?',
      py='Nalítschnymi íli kártaj?',
      k=[('bar', ['наличными', 'наличные']),
         ('karte', ['картой', 'карта'])]),
 dict(kat='job_work', de='Tut mir leid, das haben wir nicht.', ru='Извините, этого у нас нет.',
      py='Iswinítje, étawa u nas njet.',
      k=[('leid', ['извините', 'простите']),
         ('nicht_haben', ['у нас нет', 'нет'])]),
 dict(kat='job_work', de='Ich hole meinen Kollegen.', ru='Я позову коллегу.',
      py='Ja pasawú kalljégu.',
      k=[('holen', ['позову', 'позвать']),
         ('kollege', ['коллегу', 'коллега'])]),
 dict(kat='job_work', de='Kommen Sie gerne wieder!', ru='Приходите ещё!',
      py='Prichadítje jeschtschó!',
      k=[('wiederkommen', ['приходите ещё', 'приходите'])]),
 dict(kat='job_work', de='Wie viel verdiene ich pro Stunde?', ru='Сколько я получаю в час?',
      py='Skólka ja palutscháju w tschas?',
      k=[('verdienen', ['получаю', 'зарабатываю']),
         ('stunde', ['в час', 'час'])]),
 dict(kat='job_work', de='Wann bekomme ich mein Geld?', ru='Когда я получу зарплату?',
      py='Kagdá ja palutschú sarplátu?',
      k=[('wann', ['когда']),
         ('geld', ['зарплату', 'зарплата', 'деньги'])]),
 dict(kat='job_work', de='Werde ich bar bezahlt?', ru='Мне платят наличными?',
      py='Mnje plátjat nalítschnymi?',
      k=[('bar', ['наличными', 'наличные']),
         ('bezahlt', ['платят', 'мне платят'])]),
 dict(kat='job_work', de='Ich habe zehn Stunden gearbeitet.', ru='Я работал десять часов.',
      py='Ja rabótal djésjat tschassów.',
      k=[('zehn', ['десять']),
         ('stunden', ['часов', 'часа']),
         ('gearbeitet', ['работал', 'работала'])]),
 dict(kat='job_work', de='Wann fange ich an?', ru='Когда мне начинать?',
      py='Kagdá mnje natschinát?',
      k=[('wann', ['когда']),
         ('anfangen', ['начинать', 'начать'])]),
 dict(kat='job_work', de='Wann habe ich frei?', ru='Когда у меня выходной?',
      py='Kagdá u menjá wychadnój?',
      k=[('wann', ['когда']),
         ('frei', ['выходной'])]),
 dict(kat='job_work', de='Wie lange dauert die Schicht?', ru='Сколько длится смена?',
      py='Skólka dlítsa smjéna?',
      k=[('wie_lange', ['сколько длится', 'сколько']),
         ('schicht', ['смена'])]),
 dict(kat='job_work', de='Kann ich am Montag frei haben?', ru='Можно взять выходной в понедельник?',
      py='Móshna wsjat wychadnój w panedjélnik?',
      k=[('montag', ['понедельник']),
         ('frei', ['выходной'])]),
 dict(kat='job_work', de='Kann ich die Schicht tauschen?', ru='Можно поменяться сменами?',
      py='Móshna pamenjátsa smjénami?',
      k=[('schicht', ['сменами', 'смена']),
         ('tauschen', ['поменяться', 'поменять'])]),
 dict(kat='job_work', de='Ich komme morgen früher.', ru='Завтра я приду раньше.',
      py='Sáwtra ja pridú ránsche.',
      k=[('morgen', ['завтра']),
         ('frueher', ['раньше'])]),
 dict(kat='job_work', de='Wo ist der Dienstplan?', ru='Где график работы?',
      py='Gdje gráfik rabóty?',
      k=[('wo', ['где']),
         ('dienstplan', ['график работы', 'график', 'расписание'])]),
 dict(kat='job_work', de='Ich suche Arbeit.', ru='Я ищу работу.',
      py='Ja ischtschú rabótu.',
      k=[('suchen', ['ищу', 'искать']),
         ('arbeit', ['работу', 'работа'])]),
 dict(kat='job_work', de='Suchen Sie noch Leute?', ru='Вам ещё нужны люди?',
      py='Wam jeschtschó nushný ljúdi?',
      k=[('suchen', ['нужны', 'ищете']),
         ('leute', ['люди', 'сотрудники'])]),
 dict(kat='job_work', de='Haben Sie eine Stelle frei?', ru='У вас есть свободное место?',
      py='U was jest swabódnaje mjésta?',
      k=[('stelle', ['место', 'вакансия']),
         ('frei', ['свободное', 'есть'])]),
 dict(kat='job_work', de='Brauchen Sie Hilfe in der Küche?', ru='Вам нужна помощь на кухне?',
      py='Wam nushná pómasch na kúchnje?',
      k=[('brauchen', ['вам нужна', 'нужна']),
         ('hilfe', ['помощь']),
         ('kueche', ['на кухне', 'кухня'])]),
 dict(kat='job_work', de='Ich kann sofort anfangen.', ru='Я могу начать сразу.',
      py='Ja magú natschát srásu.',
      k=[('koennen', ['я могу', 'могу']),
         ('sofort', ['сразу', 'сейчас же']),
         ('anfangen', ['начать', 'приступить'])]),
 dict(kat='job_work', de='Ich bin für drei Monate hier.', ru='Я здесь на три месяца.',
      py='Ja sdjes na tri mjéssjaza.',
      k=[('drei_monate', ['три месяца', 'на три месяца']),
         ('hier', ['здесь'])]),
]

AUSGELASSEN = [
    # 120 ist der CHINESISCHE Rettungsdienst - in Russland ist es die 103
    # (bzw. 112 uebergreifend). Siehe Kopfkommentar: jede der drei neuen
    # Sprachen hat eine andere Nummer.
    'Rufen Sie bitte 120 an.',
    # Den Gegensatz westliche Medizin / TCM gibt es in Russland nicht.
    'Ich möchte westliche Medizin.',
    'Ist das westliche Medizin?',
    # Zielsprache steht im Satz - ersetzt durch die russische Fassung.
    'Ich spreche kein Chinesisch. Können Sie es aufschreiben?',
]
