# -*- coding: utf-8 -*-
"""Die uebrigen sieben Kategorien auf Franzoesisch: 133 Saetze.

Deckt travel_transportation, culture_immersion, moving_settling,
shopping_haggling, university_studying, hotel_accommodation und
smalltalk_socialising ab - eine Datei statt sieben, ueber `KATEGORIEN` plus
`kat=` je Satz (siehe werkzeug.py).

**Kein Ausschluss.** Alltagsthemen uebertragen sich vollstaendig.

**Neun eigene Kulturhinweise**, alle an Stellen, wo Frankreich anders
funktioniert als Deutschland und ein woertlich uebersetzter Satz ins Leere
liefe:

  Einwohnermeldeamt     Gibt es in Frankreich NICHT - man meldet seinen
                        Wohnsitz nirgends an. Der Satz bleibt trotzdem
                        nuetzlich, weil Behoerden staendig ein
                        "justificatif de domicile" verlangen; das ist der
                        Begriff, den man wirklich braucht.
  Semester              Franzoesische Unis zaehlen in JAHREN ("en quelle
                        année"), nicht in Semestern.
  Hoersaal / lernen     "Amphi" und "réviser" sind die Woerter, die
                        Studierende tatsaechlich benutzen - "amphithéâtre"
                        und "étudier" klingen im Alltag steif bzw. meinen
                        etwas anderes (étudier = ein Fach studieren,
                        réviser = fuer eine Pruefung lernen).
  Karte / Plan          Ein Stadtplan ist "un plan", "une carte" ist die
                        Landkarte. Wer "sur la carte" sagt, meint die falsche.
  Wetter                Franzoesisch bildet Wetter unpersoenlich mit "il fait"
                        - il fait froid, il fait beau. Kein Gegenstueck zu
                        "es ist kalt".

Dazu vier kleinere zu Miete/Kaution, WLAN-Aussprache, Auschecken und dem
Unterschied gare/arrêt.

**"Ich unterrichte Chinesisch." bleibt woertlich** ("J'enseigne le chinois"),
wie in rest_es.py entschieden: das ist ein Beruf, keine Aussage ueber die
Lernsituation - wer Franzoesisch lernt, kann sehr wohl Chinesisch
unterrichten.

**Staedtenamen bleiben, wie sie sind** (Muenchen, Berlin, Italien,
Frankreich). Anders als Waehrung oder Zielsprache fuehren sie niemanden in
die Irre - ein Deutscher faehrt durchaus nach Muenchen.

`verb_cluster` leer. **Nicht von Muttersprachlern geprueft.**
"""

KATEGORIEN = [
    "travel_transportation", "culture_immersion", "moving_settling",
    "shopping_haggling", "university_studying", "hotel_accommodation",
    "smalltalk_socialising",
]

SAETZE = [

# ================================================================ TRAVEL
# ---- Zug
 dict(kat='travel_transportation', de='Wo ist der Bahnhof?', fr='Où est la gare ?',
      k=[('wo', ['où']), ('bahnhof', ['gare', 'la gare'])],
      h='„La gare" ist der Bahnhof, „l\'arrêt" die Haltestelle von Bus oder '
        'Tram — nicht verwechseln, sonst wird man in die falsche Richtung '
        'geschickt.'),
 dict(kat='travel_transportation', de='Wann fährt der nächste Zug nach Berlin?',
      fr='Le prochain train pour Berlin part quand ?',
      k=[('naechster_zug', ['prochain train', 'train']), ('berlin', ['berlin'])]),
 dict(kat='travel_transportation', de='Von welchem Gleis fährt der Zug ab?',
      fr='Le train part de quelle voie ?',
      k=[('gleis', ['voie', 'quelle voie'])]),
 dict(kat='travel_transportation', de='Der Zug hat Verspätung.',
      fr='Le train a du retard.',
      k=[('verspaetung', ['du retard', 'retard'])]),
 dict(kat='travel_transportation', de='Muss ich umsteigen?', fr='Je dois changer ?',
      k=[('umsteigen', ['changer', 'je dois changer'])]),
 dict(kat='travel_transportation', de='Ist dieser Platz frei?',
      fr='Cette place est libre ?',
      k=[('platz', ['place', 'cette place']), ('frei', ['libre'])]),
# ---- Ticket
 dict(kat='travel_transportation', de='Ich möchte ein Ticket.',
      fr='Je voudrais un billet.',
      k=[('moechten', ['je voudrais', 'voudrais']), ('ticket', ['billet'])]),
 dict(kat='travel_transportation', de='Ich möchte eine Fahrkarte nach München, bitte.',
      fr='Je voudrais un billet pour Munich, s\'il vous plaît.',
      k=[('fahrkarte', ['billet']), ('muenchen', ['munich'])]),
 dict(kat='travel_transportation', de='Wie viel kostet die Fahrt zum Flughafen?',
      fr='Combien coûte le trajet jusqu\'à l\'aéroport ?',
      k=[('fahrt_kosten', ['combien coûte', 'trajet']), ('flughafen', ['aéroport'])]),
 dict(kat='travel_transportation', de='Ich möchte einen Mietwagen buchen.',
      fr='Je voudrais louer une voiture.',
      k=[('mietwagen', ['louer une voiture', 'voiture de location', 'louer'])]),
# ---- Bus
 dict(kat='travel_transportation', de='Wo ist die Bushaltestelle?',
      fr='Où est l\'arrêt de bus ?',
      k=[('wo', ['où']), ('bushaltestelle', ['arrêt de bus', 'arrêt'])]),
 dict(kat='travel_transportation', de='Welcher Bus fährt zum Flughafen?',
      fr='Quel bus va à l\'aéroport ?',
      k=[('bus', ['bus', 'quel bus']), ('flughafen', ['aéroport'])]),
 dict(kat='travel_transportation', de='Wir haben den Bus erwischt.',
      fr='On a eu le bus.',
      k=[('erwischen', ['on a eu', 'attrapé']), ('bus', ['bus', 'le bus'])]),
# ---- Flug
 dict(kat='travel_transportation', de='Ich habe meinen Flug verpasst.',
      fr='J\'ai raté mon vol.',
      k=[('flug_verpasst', ['j\'ai raté', 'raté']), ('flug', ['vol', 'mon vol'])]),
 dict(kat='travel_transportation', de='Mein Gepäck ist nicht angekommen.',
      fr='Mes bagages ne sont pas arrivés.',
      k=[('gepaeck', ['bagages']), ('nicht_angekommen', ['pas arrivés', 'arrivés'])]),
 dict(kat='travel_transportation', de='Wo ist der Check-in-Schalter?',
      fr='Où est le comptoir d\'enregistrement ?',
      k=[('checkin_schalter', ['comptoir d\'enregistrement', 'enregistrement'])]),
 dict(kat='travel_transportation', de='Wo kann ich mein Gepäck aufgeben?',
      fr='Où est-ce que je peux enregistrer mes bagages ?',
      k=[('gepaeck_aufgeben', ['enregistrer', 'enregistrer mes bagages']),
         ('gepaeck', ['bagages'])]),
# ---- Pläne
 dict(kat='travel_transportation', de='Wo wollt ihr hin?', fr='Vous allez où ?',
      k=[('wohin', ['où', 'vous allez où'])]),
 dict(kat='travel_transportation', de='Wie komme ich zum Hafen?',
      fr='Comment je vais au port ?',
      k=[('wie', ['comment']), ('hafen', ['port', 'au port'])]),
 dict(kat='travel_transportation', de='Ich war letztes Jahr in Frankreich.',
      fr='L\'année dernière, j\'étais en France.',
      k=[('letztes_jahr', ['l\'année dernière', 'année dernière']),
         ('frankreich', ['france', 'en france'])]),
 dict(kat='travel_transportation', de='Nächstes Jahr fahre ich nach Italien.',
      fr='L\'année prochaine, je vais en Italie.',
      k=[('naechstes_jahr', ['l\'année prochaine', 'année prochaine']),
         ('italien', ['italie', 'en italie'])]),
 dict(kat='travel_transportation', de='Warte an der Kreuzung auf mich.',
      fr='Attends-moi au carrefour.',
      k=[('warten', ['attends-moi', 'attendre']), ('kreuzung', ['carrefour'])]),
# ---- Weg fragen
 dict(kat='travel_transportation', de='Entschuldigung, wie komme ich zum Bahnhof?',
      fr='Pardon, comment je vais à la gare ?',
      k=[('entschuldigung', ['pardon', 'excusez-moi']), ('bahnhof', ['gare'])]),
 dict(kat='travel_transportation', de='Ist das weit von hier?', fr='C\'est loin d\'ici ?',
      k=[('weit', ['loin', 'loin d\'ici'])]),
 dict(kat='travel_transportation', de='Ist das in der Nähe?', fr='C\'est près d\'ici ?',
      k=[('in_der_naehe', ['près', 'près d\'ici', 'à côté'])]),
 dict(kat='travel_transportation', de='Wie weit ist es zu Fuß?',
      fr='C\'est à combien de temps à pied ?',
      k=[('zu_fuss', ['à pied']), ('wie_weit', ['combien de temps', 'combien'])]),
 dict(kat='travel_transportation', de='Können Sie mir den Weg zeigen?',
      fr='Vous pouvez m\'indiquer le chemin ?',
      k=[('weg_zeigen', ['indiquer le chemin', 'le chemin', 'montrer'])]),
 dict(kat='travel_transportation', de='Können Sie mir das auf der Karte zeigen?',
      fr='Vous pouvez me le montrer sur le plan ?',
      k=[('auf_karte', ['sur le plan', 'plan'])],
      h='Ein Stadtplan heißt „un plan". „Une carte" ist die Landkarte — wer '
        '„sur la carte" sagt, meint im Restaurant außerdem die Speisekarte.'),
 dict(kat='travel_transportation', de='Ich habe mich verlaufen.', fr='Je me suis perdu.',
      k=[('verlaufen', ['je me suis perdu', 'perdu'])]),
 dict(kat='travel_transportation', de='Wo ist der nächste Supermarkt?',
      fr='Où est le supermarché le plus proche ?',
      k=[('supermarkt', ['supermarché']), ('naechste', ['le plus proche', 'proche'])]),
# ---- Weg beschreiben
 dict(kat='travel_transportation', de='Gehen Sie geradeaus.', fr='Allez tout droit.',
      k=[('geradeaus', ['tout droit'])]),
 dict(kat='travel_transportation', de='Biegen Sie rechts ab.', fr='Tournez à droite.',
      k=[('rechts', ['à droite', 'droite'])]),
 dict(kat='travel_transportation', de='Biegen Sie links ab.', fr='Tournez à gauche.',
      k=[('links', ['à gauche', 'gauche'])]),
 dict(kat='travel_transportation', de='Nehmen Sie die zweite Straße rechts.',
      fr='Prenez la deuxième rue à droite.',
      k=[('zweite_strasse', ['deuxième rue', 'la deuxième'])]),
 dict(kat='travel_transportation', de='Es ist gleich um die Ecke.',
      fr='C\'est juste au coin.',
      k=[('um_die_ecke', ['au coin', 'juste au coin'])]),
 dict(kat='travel_transportation', de='Das Museum liegt gegenüber der Kirche.',
      fr='Le musée est en face de l\'église.',
      k=[('museum', ['musée']), ('kirche', ['église'])]),

# ================================================================ CULTURE
 dict(kat='culture_immersion', de='Wo findet das Konzert statt?',
      fr='Où a lieu le concert ?',
      k=[('konzert', ['concert']), ('wo', ['où', 'où a lieu'])]),
 dict(kat='culture_immersion', de='Wie viel kostet der Eintritt?',
      fr='Combien coûte l\'entrée ?',
      k=[('eintritt', ['entrée', 'l\'entrée']), ('kosten', ['combien coûte', 'coûte'])]),
 dict(kat='culture_immersion', de='Wann öffnet das Museum?',
      fr='À quelle heure ouvre le musée ?',
      k=[('museum', ['musée']), ('oeffnen', ['ouvre', 'à quelle heure ouvre'])]),
 dict(kat='culture_immersion', de='Das war ein tolles Konzert.',
      fr='C\'était un super concert.',
      k=[('konzert', ['concert']), ('toll', ['super', 'génial'])]),
 dict(kat='culture_immersion', de='Ich gehe gerne ins Kino.',
      fr='J\'aime aller au cinéma.',
      k=[('kino', ['cinéma', 'au cinéma']), ('gerne', ['j\'aime', 'aime'])]),
 dict(kat='culture_immersion', de='Ich interessiere mich für Geschichte.',
      fr='Je m\'intéresse à l\'histoire.',
      k=[('interessieren', ['je m\'intéresse', 'intéresse']),
         ('geschichte', ['histoire', 'l\'histoire'])]),
 dict(kat='culture_immersion', de='Treibst du Sport?', fr='Tu fais du sport ?',
      k=[('sport', ['sport', 'du sport'])]),
 dict(kat='culture_immersion', de='Ich spiele gerne Fußball.',
      fr='J\'aime jouer au foot.',
      k=[('fussball', ['foot', 'football']), ('gerne', ['j\'aime', 'aime'])]),
 dict(kat='culture_immersion', de='Wir spielen Fußball.', fr='On joue au foot.',
      k=[('spielen', ['on joue', 'jouer']), ('fussball', ['foot', 'football'])]),
 dict(kat='culture_immersion', de='Wo ist die Kirche?', fr='Où est l\'église ?',
      k=[('wo', ['où']), ('kirche', ['église', 'l\'église'])]),
 dict(kat='culture_immersion', de='Berlin ist sehr schön.', fr='Berlin est très belle.',
      k=[('berlin', ['berlin']), ('schoen', ['belle', 'très belle', 'jolie'])]),
 dict(kat='culture_immersion', de='Er ist gesprungen.', fr='Il a sauté.',
      k=[('springen', ['a sauté', 'sauté', 'sauter'])]),
 dict(kat='culture_immersion', de='Wie ist das Wetter heute?',
      fr='Quel temps fait-il aujourd\'hui ?',
      k=[('wetter_frage', ['quel temps', 'temps']), ('heute', ['aujourd\'hui'])],
      h='Wetter wird im Französischen unpersönlich mit „il fait" gebildet: '
        'il fait froid, il fait beau, il fait chaud. Ein wörtliches „es ist '
        'kalt" gibt es dafür nicht.'),
 dict(kat='culture_immersion', de='Es ist sehr kalt heute.',
      fr='Il fait très froid aujourd\'hui.',
      k=[('kalt', ['froid', 'il fait froid']), ('heute', ['aujourd\'hui'])]),
 dict(kat='culture_immersion', de='Es regnet.', fr='Il pleut.',
      k=[('regnet', ['il pleut', 'pleut'])]),
 dict(kat='culture_immersion', de='Die Sonne scheint.', fr='Il y a du soleil.',
      k=[('sonne_scheint', ['du soleil', 'soleil', 'il fait beau'])]),
 dict(kat='culture_immersion', de='Was machst du am Wochenende?',
      fr='Qu\'est-ce que tu fais ce week-end ?',
      k=[('wochenende', ['week-end', 'ce week-end'])]),
 dict(kat='culture_immersion', de='Möchtest du mitkommen?', fr='Tu veux venir ?',
      k=[('mitkommen', ['tu veux venir', 'venir'])]),
 dict(kat='culture_immersion', de='Nächstes Wochenende gehe ich wandern.',
      fr='Le week-end prochain, je vais faire une randonnée.',
      k=[('wandern', ['randonnée', 'faire une randonnée']),
         ('naechstes_wochenende', ['week-end prochain'])]),
 dict(kat='culture_immersion', de='Letztes Wochenende war ich am Strand.',
      fr='Le week-end dernier, j\'étais à la plage.',
      k=[('strand', ['plage', 'à la plage']),
         ('letztes_wochenende', ['week-end dernier'])]),

# ================================================================ MOVING
 dict(kat='moving_settling', de='Ich suche eine Wohnung.',
      fr='Je cherche un appartement.',
      k=[('wohnung_suchen', ['je cherche', 'cherche']),
         ('wohnung', ['appartement', 'un appartement'])]),
 dict(kat='moving_settling', de='Wie hoch ist die Miete?', fr='C\'est combien, le loyer ?',
      k=[('miete', ['loyer', 'le loyer'])]),
 dict(kat='moving_settling', de='Ist die Kaution im Preis enthalten?',
      fr='La caution est comprise ?',
      k=[('kaution', ['caution', 'la caution']), ('enthalten', ['comprise', 'compris'])],
      h='Die „caution" ist in Frankreich meist ein Monat Kaltmiete und wird '
        'getrennt vom Mietpreis genannt — sie ist nie „im Preis enthalten".'),
 dict(kat='moving_settling', de='Wann kann ich einziehen?',
      fr='Quand est-ce que je peux emménager ?',
      k=[('einziehen', ['emménager']), ('wann', ['quand'])]),
 dict(kat='moving_settling', de='Gibt es einen Aufzug im Haus?',
      fr='Il y a un ascenseur dans l\'immeuble ?',
      k=[('aufzug', ['ascenseur']), ('haus', ['immeuble', 'l\'immeuble'])]),
 dict(kat='moving_settling', de='Gibt es hier einen Waschraum?',
      fr='Il y a une buanderie ?',
      k=[('waschraum', ['buanderie', 'laverie'])]),
 dict(kat='moving_settling', de='Ich möchte den Mietvertrag unterschreiben.',
      fr='Je voudrais signer le bail.',
      k=[('mietvertrag', ['bail', 'le bail', 'contrat']),
         ('unterschreiben', ['signer'])]),
 dict(kat='moving_settling', de='Ich bin letzte Woche umgezogen.',
      fr='J\'ai déménagé la semaine dernière.',
      k=[('umgezogen', ['déménagé', 'j\'ai déménagé']),
         ('letzte_woche', ['la semaine dernière', 'semaine dernière'])]),
 dict(kat='moving_settling', de='Wie melde ich mich beim Einwohnermeldeamt an?',
      fr='Comment je m\'inscris à la mairie ?',
      k=[('anmelden', ['m\'inscris', 'inscrire']), ('amt', ['mairie', 'la mairie'])],
      h='Ein Einwohnermeldeamt gibt es in Frankreich nicht — man meldet seinen '
        'Wohnsitz nirgends an. Gebraucht wird stattdessen ständig ein '
        '„justificatif de domicile" (Adressnachweis, z. B. eine Stromrechnung).'),
 dict(kat='moving_settling', de='Ich brauche eine Bestätigung meiner Adresse.',
      fr='J\'ai besoin d\'un justificatif de domicile.',
      k=[('adressbestaetigung', ['justificatif de domicile', 'justificatif'])]),
 dict(kat='moving_settling', de='Ich muss den Strom anmelden.',
      fr='Je dois ouvrir un compte d\'électricité.',
      k=[('strom_anmelden', ['ouvrir un compte', 'électricité'])]),
 dict(kat='moving_settling', de='Das kann ich erledigen.', fr='Je peux m\'en occuper.',
      k=[('erledigen', ['m\'en occuper', 'occuper', 'je peux'])]),
 dict(kat='moving_settling', de='Ich bezahle mit dem Handy.',
      fr='Je paie avec le téléphone.',
      k=[('bezahlen', ['je paie', 'payer']),
         ('handy', ['téléphone', 'portable'])]),
 dict(kat='moving_settling', de='Die Heizung funktioniert nicht.',
      fr='Le chauffage ne marche pas.',
      k=[('heizung', ['chauffage']), ('kaputt', ['ne marche pas', 'marche pas'])]),
 dict(kat='moving_settling', de='Wo finde ich einen Handwerker?',
      fr='Où est-ce que je trouve un artisan ?',
      k=[('handwerker', ['artisan', 'un artisan']), ('wo', ['où'])]),
 dict(kat='moving_settling', de='Meine Nachbarn sind sehr nett.',
      fr='Mes voisins sont très sympas.',
      k=[('nachbarn', ['voisins', 'mes voisins']),
         ('nett', ['sympas', 'gentils', 'très sympas'])]),
 dict(kat='moving_settling', de='Das Buch liegt auf dem Tisch.',
      fr='Le livre est sur la table.',
      k=[('buch', ['livre', 'le livre']), ('tisch', ['table', 'la table'])]),
 dict(kat='moving_settling', de='Hier ist es sehr praktisch.',
      fr='C\'est très pratique ici.',
      k=[('praktisch', ['pratique', 'très pratique']), ('hier', ['ici'])]),

# ================================================================ SHOPPING
 dict(kat='shopping_haggling', de='Ich schaue mich nur um.', fr='Je regarde juste.',
      k=[('nur_umschauen', ['je regarde', 'juste regarder', 'regarde juste'])]),
 dict(kat='shopping_haggling', de='Können Sie mir helfen?', fr='Vous pouvez m\'aider ?',
      k=[('helfen', ['m\'aider', 'aider'])]),
 dict(kat='shopping_haggling', de='Ich suche ein Geschenk für meine Mutter.',
      fr='Je cherche un cadeau pour ma mère.',
      k=[('geschenk', ['cadeau', 'un cadeau']), ('mutter', ['mère', 'ma mère'])]),
 dict(kat='shopping_haggling', de='Kann ich das anprobieren?', fr='Je peux l\'essayer ?',
      k=[('anprobieren', ['essayer', 'l\'essayer'])]),
 dict(kat='shopping_haggling', de='Wo ist die Umkleidekabine?',
      fr='Où sont les cabines d\'essayage ?',
      k=[('umkleidekabine', ['cabines d\'essayage', 'cabine', 'essayage'])]),
 dict(kat='shopping_haggling', de='Haben Sie das auch in Größe M?',
      fr='Vous l\'avez en taille M ?',
      k=[('groesse', ['taille', 'taille m'])]),
 dict(kat='shopping_haggling', de='Haben Sie das in einer anderen Farbe?',
      fr='Vous l\'avez dans une autre couleur ?',
      k=[('andere_farbe', ['autre couleur', 'couleur'])]),
 dict(kat='shopping_haggling', de='Das ist zu teuer.', fr='C\'est trop cher.',
      k=[('teuer', ['cher', 'trop cher'])]),
 dict(kat='shopping_haggling', de='Das gilt nicht als teuer.', fr='Ce n\'est pas si cher.',
      k=[('nicht_teuer', ['pas si cher', 'pas cher'])]),
 dict(kat='shopping_haggling', de='Gibt es einen Rabatt?', fr='Il y a une réduction ?',
      k=[('rabatt', ['réduction', 'remise'])]),
 dict(kat='shopping_haggling', de='Kann ich mit Karte bezahlen?',
      fr='Je peux payer par carte ?',
      k=[('karte_zahlen', ['par carte', 'carte']), ('bezahlen', ['payer'])]),
 dict(kat='shopping_haggling', de='Nur Bargeld, bitte.',
      fr='Espèces seulement, s\'il vous plaît.',
      k=[('bargeld', ['espèces', 'liquide'])]),
 dict(kat='shopping_haggling', de='Haben Sie eine Tüte?', fr='Vous avez un sac ?',
      k=[('tuete', ['sac', 'un sac'])]),
 dict(kat='shopping_haggling', de='Ich möchte das zurückgeben.', fr='Je voudrais rendre ça.',
      k=[('zurueckgeben', ['rendre', 'rendre ça', 'échanger'])]),
 dict(kat='shopping_haggling', de='Wann schließt das Geschäft?',
      fr='Le magasin ferme à quelle heure ?',
      k=[('schliesst', ['ferme', 'à quelle heure ferme']), ('geschaeft', ['magasin'])]),
 dict(kat='shopping_haggling', de='Ich habe gestern ein neues Kleid gekauft.',
      fr='Hier, j\'ai acheté une nouvelle robe.',
      k=[('gekauft', ['j\'ai acheté', 'acheté']), ('kleid', ['robe'])]),

# ================================================================ UNIVERSITY
 dict(kat='university_studying', de='Wo ist der Hörsaal?', fr='Où est l\'amphi ?',
      k=[('hoersaal', ['amphi', 'amphithéâtre'])],
      h='„Amphi" (kurz für amphithéâtre) ist das Wort, das Studierende '
        'benutzen — „salle de cours" ist der normale Seminarraum.'),
 dict(kat='university_studying', de='Wo finde ich die Bibliothek?',
      fr='Où est la bibliothèque ?',
      k=[('bibliothek', ['bibliothèque', 'la bibliothèque'])]),
 dict(kat='university_studying', de='Wann beginnt die Vorlesung?',
      fr='Le cours commence à quelle heure ?',
      k=[('vorlesung_beginn', ['commence', 'à quelle heure']), ('kurs', ['cours'])]),
 dict(kat='university_studying', de='Wer ist der Dozent für diesen Kurs?',
      fr='Qui est le prof de ce cours ?',
      k=[('dozent', ['prof', 'professeur']), ('kurs', ['cours', 'ce cours'])]),
 dict(kat='university_studying', de='Ich studiere Informatik.', fr='J\'étudie l\'informatique.',
      k=[('studiere', ['j\'étudie', 'étudie']), ('informatik', ['informatique'])]),
 dict(kat='university_studying', de='In welchem Semester bist du?',
      fr='Tu es en quelle année ?',
      k=[('semester_frage', ['quelle année', 'année'])],
      h='Französische Unis zählen in JAHREN, nicht in Semestern: „je suis en '
        'deuxième année". Eine Frage nach dem Semester versteht man zwar, '
        'aber sie klingt fremd.'),
 dict(kat='university_studying', de='Wie viele Credits brauche ich?',
      fr='Il me faut combien de crédits ?',
      k=[('credits', ['crédits', 'combien de crédits'])]),
 dict(kat='university_studying', de='Wann ist die Anmeldefrist?',
      fr='C\'est quand la date limite d\'inscription ?',
      k=[('anmeldefrist', ['date limite', 'inscription'])]),
 dict(kat='university_studying', de='Ich habe morgen eine Prüfung.',
      fr='J\'ai un examen demain.',
      k=[('pruefung', ['examen']), ('morgen', ['demain'])]),
 dict(kat='university_studying', de='Ich habe die Prüfung bestanden.',
      fr='J\'ai réussi l\'examen.',
      k=[('pruefung_bestanden', ['j\'ai réussi', 'réussi']), ('pruefung', ['examen'])]),
 dict(kat='university_studying', de='Ich habe die Hausaufgabe vergessen.',
      fr='J\'ai oublié le devoir.',
      k=[('hausaufgabe_vergessen', ['j\'ai oublié', 'oublié']), ('hausaufgabe', ['devoir'])]),
 dict(kat='university_studying', de='Ich brauche mehr Zeit für die Hausarbeit.',
      fr='J\'ai besoin de plus de temps pour le dossier.',
      k=[('mehr_zeit', ['plus de temps']), ('hausarbeit', ['dossier', 'travail'])]),
 dict(kat='university_studying', de='Können wir zusammen lernen?',
      fr='On peut réviser ensemble ?',
      k=[('zusammen_lernen', ['réviser', 'réviser ensemble']), ('zusammen', ['ensemble'])],
      h='„Réviser" heißt für eine Prüfung lernen. „Étudier" meint ein Fach '
        'studieren — wer sagt „on peut étudier ensemble", klingt, als wolle '
        'er gemeinsam ein Studium aufnehmen.'),
 dict(kat='university_studying', de='Kann ich dieses Buch ausleihen?',
      fr='Je peux emprunter ce livre ?',
      k=[('ausleihen', ['emprunter']), ('buch', ['livre', 'ce livre'])]),
 dict(kat='university_studying', de='Ich habe drei Bücher.', fr='J\'ai trois livres.',
      k=[('drei', ['trois']), ('buch', ['livres', 'livre'])]),
 dict(kat='university_studying', de='Ich unterrichte Chinesisch.', fr='J\'enseigne le chinois.',
      k=[('unterrichten', ['j\'enseigne', 'enseigne']), ('chinesisch', ['chinois'])]),

# ================================================================ HOTEL
 dict(kat='hotel_accommodation', de='Ich habe eine Reservierung.', fr='J\'ai une réservation.',
      k=[('reservierung', ['réservation', 'une réservation'])]),
 dict(kat='hotel_accommodation', de='Haben Sie noch ein Zimmer frei?',
      fr='Vous avez encore une chambre libre ?',
      k=[('zimmer', ['chambre']), ('frei', ['libre'])]),
 dict(kat='hotel_accommodation', de='Ich möchte ein Einzelzimmer, bitte.',
      fr='Je voudrais une chambre simple, s\'il vous plaît.',
      k=[('einzelzimmer', ['chambre simple', 'simple'])]),
 dict(kat='hotel_accommodation', de='Wie viel kostet die Nacht?',
      fr='Combien coûte la nuit ?',
      k=[('preis_nacht', ['combien coûte', 'la nuit', 'par nuit'])]),
 dict(kat='hotel_accommodation', de='Wann ist der Check-in?',
      fr='À quelle heure est l\'arrivée ?',
      k=[('checkin', ['l\'arrivée', 'arrivée', 'check-in'])]),
 dict(kat='hotel_accommodation', de='Ist das Frühstück inklusive?',
      fr='Le petit-déjeuner est compris ?',
      k=[('fruehstueck', ['petit-déjeuner']), ('inklusive', ['compris', 'inclus'])]),
 dict(kat='hotel_accommodation', de='Gibt es hier WLAN?', fr='Il y a du wifi ici ?',
      k=[('wlan', ['wifi', 'du wifi'])],
      h='„Wifi" wird im Französischen „wi-fi" gesprochen, etwa „wiffi" — die '
        'englische Aussprache versteht man oft nicht. „WLAN" kennt hier '
        'niemand.'),
 dict(kat='hotel_accommodation', de='Wie ist das Passwort für das WLAN?',
      fr='C\'est quoi le mot de passe du wifi ?',
      k=[('wlan_passwort', ['mot de passe', 'le mot de passe']), ('wlan', ['wifi'])]),
 dict(kat='hotel_accommodation', de='Wo ist der Aufzug?', fr='Où est l\'ascenseur ?',
      k=[('aufzug', ['ascenseur', 'l\'ascenseur'])]),
 dict(kat='hotel_accommodation', de='Das Zimmer ist sehr sauber.',
      fr='La chambre est très propre.',
      k=[('zimmer', ['chambre']), ('sauber', ['propre', 'très propre'])]),
 dict(kat='hotel_accommodation', de='Mein Zimmer ist nicht sauber.',
      fr='Ma chambre n\'est pas propre.',
      k=[('zimmer', ['chambre', 'ma chambre']), ('nicht_sauber', ['pas propre', 'sale'])]),
 dict(kat='hotel_accommodation', de='Die Klimaanlage funktioniert nicht.',
      fr='La climatisation ne marche pas.',
      k=[('klimaanlage', ['climatisation', 'clim']),
         ('kaputt', ['ne marche pas', 'marche pas'])]),
 dict(kat='hotel_accommodation', de='Ich habe meinen Schlüssel verloren.',
      fr='J\'ai perdu ma clé.',
      k=[('schluessel_verloren', ['j\'ai perdu', 'perdu']), ('schluessel', ['clé', 'ma clé'])]),
 dict(kat='hotel_accommodation', de='Ich möchte auschecken.',
      fr='Je voudrais libérer la chambre.',
      k=[('checkout', ['libérer la chambre', 'libérer', 'partir'])],
      h='Für „auschecken" sagt man in Frankreich meist „libérer la chambre". '
        '„Faire le check-out" versteht man in großen Hotels, klingt aber '
        'nach Kette.'),
 dict(kat='hotel_accommodation', de='Können Sie mir ein Taxi rufen?',
      fr='Vous pouvez m\'appeler un taxi ?',
      k=[('taxi', ['taxi', 'un taxi']), ('rufen', ['appeler', 'm\'appeler'])]),

# ================================================================ SMALLTALK
 dict(kat='smalltalk_socialising', de='Was machst du beruflich?',
      fr='Qu\'est-ce que tu fais dans la vie ?',
      k=[('beruf_frage', ['qu\'est-ce que tu fais', 'dans la vie', 'métier'])]),
 dict(kat='smalltalk_socialising', de='Ich bin Student.', fr='Je suis étudiant.',
      k=[('student', ['étudiant', 'étudiante'])]),
 dict(kat='smalltalk_socialising', de='Ich arbeite als Lehrer.',
      fr='Je travaille comme professeur.',
      k=[('beruf', ['professeur', 'prof']), ('arbeiten', ['je travaille', 'travaille'])]),
 dict(kat='smalltalk_socialising', de='Wo wohnst du?', fr='Tu habites où ?',
      k=[('wo_wohnst', ['tu habites où', 'habites', 'où'])]),
 dict(kat='smalltalk_socialising', de='Ich wohne in Berlin.', fr='J\'habite à Berlin.',
      k=[('wohne_in', ['j\'habite', 'habite']), ('berlin', ['berlin'])]),
 dict(kat='smalltalk_socialising', de='Bist du verheiratet?', fr='Tu es marié ?',
      k=[('verheiratet', ['marié', 'mariée'])]),
 dict(kat='smalltalk_socialising', de='Noch nicht.', fr='Pas encore.',
      k=[('noch_nicht', ['pas encore'])]),
 dict(kat='smalltalk_socialising', de='Hast du Geschwister?',
      fr='Tu as des frères et sœurs ?',
      k=[('geschwister', ['frères et sœurs', 'frères', 'sœurs'])]),
 dict(kat='smalltalk_socialising', de='Ich habe eine Schwester.', fr='J\'ai une sœur.',
      k=[('schwester', ['sœur', 'une sœur'])]),
 dict(kat='smalltalk_socialising', de='Was sind deine Hobbys?',
      fr='Qu\'est-ce que tu aimes faire ?',
      k=[('hobbys_frage', ['qu\'est-ce que tu aimes faire', 'loisirs', 'aimes faire'])],
      h='„Hobby" ist im Französischen unüblich. Man fragt, was jemand gern '
        'macht („qu\'est-ce que tu aimes faire ?") oder nach „loisirs".'),
 dict(kat='smalltalk_socialising', de='Mein Hobby ist Sport.',
      fr='Mon passe-temps, c\'est le sport.',
      k=[('hobby', ['passe-temps', 'loisir']), ('sport', ['sport', 'le sport'])]),
 dict(kat='smalltalk_socialising', de='Ich lese gerne Bücher.', fr='J\'aime lire.',
      k=[('lesen', ['lire', 'j\'aime lire'])]),
]

AUSGELASSEN = []
