# -*- coding: utf-8 -*-
"""Die 500 haeufigsten englischen Woerter.

**Eigenstaendige Liste, KEINE Uebersetzung** - dieselbe Begruendung wie bei
`vokabeln_it.py`: Haeufigkeitslisten sind sprachgebunden.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen.

**KEIN GENUS.** Englische Nomen tragen kein grammatisches Geschlecht -
`the table` ist geschlechtslos. `vokabel_werkzeug.py` verlangt `g`
deshalb nur fuer it/no/ru/pl (siehe MIT_GENUS dort) und meldet ein Genus
hier umgekehrt als Fehler.

**Nur DREI Artikel** (a, an, the) statt acht wie im Italienischen - der
englische Artikel beugt sich nicht.

**Britisch, wo es auseinandergeht** (`flat`, `lift`, `shop`, `autumn`);
die amerikanische Form steht in `ok` als zusaetzlich akzeptierte deutsche
Antwort oder im Hinweis.

**Unregelmaessige Verben stehen im Infinitiv**, mit den beiden anderen
Stammformen im Hinweis, wo sie nicht zu erraten sind (go/went/gone).
Das ist die Stelle, an der Englisch fuer Deutsche wirklich Arbeit macht -
nicht die Grammatik.
"""

WOERTER = [

# ---------------------------------------------------------------- Artikel
 dict(w='the', de='der, die, das', k='Artikel', rang=1),
 dict(w='a', de='ein, eine', k='Artikel', rang=2),
 dict(w='an', de='ein (vor Vokal)', k='Artikel', rang=3,
      hin='Vor Vokal-LAUT, nicht vor Vokal-Buchstabe: an hour, aber a university.'),

# --------------------------------------------------------------- Pronomen
 dict(w='I', de='ich', k='Pronomen', rang=4,
      hin='Wird IMMER grossgeschrieben, egal wo im Satz.'),
 dict(w='you', de='du, ihr, Sie', k='Pronomen', rang=5,
      hin='Ein Wort fuer alles - Englisch kennt kein Du/Sie.'),
 dict(w='he', de='er', k='Pronomen', rang=6),
 dict(w='she', de='sie', k='Pronomen', rang=7),
 dict(w='it', de='es', k='Pronomen', rang=8),
 dict(w='we', de='wir', k='Pronomen', rang=9),
 dict(w='they', de='sie (Mehrzahl)', k='Pronomen', rang=10),
 dict(w='me', de='mir, mich', k='Pronomen', rang=11),
 dict(w='him', de='ihm, ihn', k='Pronomen', rang=12),
 dict(w='her', de='ihr, sie', k='Pronomen', rang=13),
 dict(w='us', de='uns', k='Pronomen', rang=14),
 dict(w='them', de='ihnen, sie', k='Pronomen', rang=15),
 dict(w='my', de='mein', k='Pronomen', rang=16),
 dict(w='your', de='dein, euer', k='Pronomen', rang=17),
 dict(w='his', de='sein', k='Pronomen', rang=18),
 dict(w='its', de='sein (saechlich)', k='Pronomen', rang=19,
      hin='Ohne Apostroph. "It’s" mit Apostroph heisst "it is".'),
 dict(w='our', de='unser', k='Pronomen', rang=20),
 dict(w='their', de='ihr (Mehrzahl)', k='Pronomen', rang=21),
 dict(w='mine', de='meiner', k='Pronomen', rang=22),
 dict(w='yours', de='deiner', k='Pronomen', rang=23),
 dict(w='myself', de='mich selbst', k='Pronomen', rang=24),
 dict(w='yourself', de='dich selbst', k='Pronomen', rang=25),
 dict(w='himself', de='sich selbst', k='Pronomen', rang=26),
 dict(w='each other', de='einander', k='Pronomen', rang=27),
 dict(w='this', de='dieser', k='Pronomen', rang=28),
 dict(w='these', de='diese (Mehrzahl)', k='Pronomen', rang=29),
 dict(w='those', de='jene', k='Pronomen', rang=30),
 dict(w='who', de='wer, der', k='Pronomen', rang=31),
 dict(w='which', de='welcher', k='Pronomen', rang=32),
 dict(w='someone', de='jemand', k='Pronomen', rang=33),
 dict(w='something', de='etwas', k='Pronomen', rang=34),
 dict(w='anything', de='irgendetwas', k='Pronomen', rang=35),
 dict(w='nothing', de='nichts', k='Pronomen', rang=36),
 dict(w='nobody', de='niemand', k='Pronomen', rang=37),
 dict(w='everyone', de='jeder', k='Pronomen', rang=38),
 dict(w='everything', de='alles', k='Pronomen', rang=39),
 dict(w='another', de='ein anderer', k='Pronomen', rang=40),
 dict(w='both', de='beide', k='Pronomen', rang=41),
 dict(w='each', de='jeder einzelne', k='Pronomen', rang=42),
 dict(w='few', de='wenige', k='Pronomen', rang=43),

# -------------------------------------------------------------- Fragewort
 dict(w='what', de='was', k='Fragewort', rang=44),
 dict(w='where', de='wo', k='Fragewort', rang=45),
 dict(w='when', de='wann', k='Fragewort', rang=46),
 dict(w='how', de='wie', k='Fragewort', rang=47),
 dict(w='why', de='warum', k='Fragewort', rang=48),
 dict(w='whose', de='wessen', k='Fragewort', rang=49),
 dict(w='how much', de='wie viel', k='Fragewort', rang=50),
 dict(w='how many', de='wie viele', k='Fragewort', rang=51,
      hin='"How many" bei zaehlbaren Dingen, "how much" bei nicht zaehlbaren.'),
 dict(w='how long', de='wie lange', k='Fragewort', rang=52),
 dict(w='whether', de='ob', k='Fragewort', rang=53),

# ------------------------------------------------------------ Konjunktion
 dict(w='and', de='und', k='Konjunktion', rang=54),
 dict(w='or', de='oder', k='Konjunktion', rang=55),
 dict(w='but', de='aber', k='Konjunktion', rang=56),
 dict(w='if', de='wenn, falls', k='Konjunktion', rang=57),
 dict(w='because', de='weil', k='Konjunktion', rang=58),
 dict(w='so', de='also', k='Konjunktion', rang=59),
 dict(w='that', de='dass', k='Konjunktion', rang=60),
 dict(w='while', de='waehrend', k='Konjunktion', rang=61),
 dict(w='although', de='obwohl', k='Konjunktion', rang=62),
 dict(w='than', de='als (Vergleich)', k='Konjunktion', rang=63),
 dict(w='as', de='als, wie', k='Konjunktion', rang=64),
 dict(w='unless', de='es sei denn', k='Konjunktion', rang=65),
 dict(w='however', de='jedoch', k='Konjunktion', rang=66),
 dict(w='therefore', de='deshalb', k='Konjunktion', rang=67),
 dict(w='since', de='seit, da', k='Konjunktion', rang=68),

# ----------------------------------------------------------- Praeposition
 dict(w='in', de='in', k='Praeposition', rang=69),
 dict(w='on', de='auf', k='Praeposition', rang=70),
 dict(w='at', de='an, bei', k='Praeposition', rang=71),
 dict(w='to', de='zu, nach', k='Praeposition', rang=72),
 dict(w='of', de='von', k='Praeposition', rang=73),
 dict(w='for', de='fuer', k='Praeposition', rang=74),
 dict(w='with', de='mit', k='Praeposition', rang=75),
 dict(w='from', de='von, aus', k='Praeposition', rang=76),
 dict(w='by', de='von, per', k='Praeposition', rang=77),
 dict(w='about', de='ueber', k='Praeposition', rang=78),
 dict(w='after', de='nach', k='Praeposition', rang=79),
 dict(w='before', de='vor', k='Praeposition', rang=80),
 dict(w='under', de='unter', k='Praeposition', rang=81),
 dict(w='over', de='ueber, mehr als', k='Praeposition', rang=82),
 dict(w='between', de='zwischen', k='Praeposition', rang=83),
 dict(w='without', de='ohne', k='Praeposition', rang=84),
 dict(w='against', de='gegen', k='Praeposition', rang=85),
 dict(w='through', de='durch', k='Praeposition', rang=86),
 dict(w='into', de='hinein', k='Praeposition', rang=87),
 dict(w='during', de='waehrend', k='Praeposition', rang=88),
 dict(w='behind', de='hinter', k='Praeposition', rang=89),
 dict(w='next to', de='neben', k='Praeposition', rang=90),
 dict(w='until', de='bis', k='Praeposition', rang=91),
 dict(w='around', de='um herum', k='Praeposition', rang=92),
 dict(w='near', de='nahe', k='Praeposition', rang=93),

# ----------------------------------------------------------------- Adverb
 dict(w='not', de='nicht', k='Adverb', rang=94),
 dict(w='yes', de='ja', k='Adverb', rang=95),
 dict(w='no', de='nein', k='Adverb', rang=96),
 dict(w='very', de='sehr', k='Adverb', rang=97),
 dict(w='more', de='mehr', k='Adverb', rang=98),
 dict(w='less', de='weniger', k='Adverb', rang=99),
 dict(w='much', de='viel', k='Adverb', rang=100),
 dict(w='little', de='wenig', k='Adverb', rang=101),
 dict(w='too', de='zu, auch', k='Adverb', rang=102),
 dict(w='well', de='gut', k='Adverb', rang=103),
 dict(w='badly', de='schlecht', k='Adverb', rang=104),
 dict(w='here', de='hier', k='Adverb', rang=105),
 dict(w='there', de='dort', k='Adverb', rang=106),
 dict(w='now', de='jetzt', k='Adverb', rang=107),
 dict(w='today', de='heute', k='Adverb', rang=108),
 dict(w='yesterday', de='gestern', k='Adverb', rang=109),
 dict(w='tomorrow', de='morgen', k='Adverb', rang=110),
 dict(w='always', de='immer', k='Adverb', rang=111),
 dict(w='never', de='nie', k='Adverb', rang=112),
 dict(w='often', de='oft', k='Adverb', rang=113),
 dict(w='sometimes', de='manchmal', k='Adverb', rang=114),
 dict(w='rarely', de='selten', k='Adverb', rang=115),
 dict(w='soon', de='bald', k='Adverb', rang=116),
 dict(w='still', de='noch', k='Adverb', rang=117),
 dict(w='already', de='schon', k='Adverb', rang=118),
 dict(w='yet', de='noch nicht, schon', k='Adverb', rang=119),
 dict(w='early', de='frueh', k='Adverb', rang=120),
 dict(w='late', de='spaet', k='Adverb', rang=121),
 dict(w='together', de='zusammen', k='Adverb', rang=122),
 dict(w='only', de='nur', k='Adverb', rang=123),
 dict(w='just', de='gerade, nur', k='Adverb', rang=124),
 dict(w='maybe', de='vielleicht', k='Adverb', rang=125),
 dict(w='really', de='wirklich', k='Adverb', rang=126),
 dict(w='enough', de='genug', k='Adverb', rang=127),
 dict(w='almost', de='fast', k='Adverb', rang=128),
 dict(w='exactly', de='genau', k='Adverb', rang=129),
 dict(w='sure', de='sicher', k='Adverb', rang=130),
 dict(w='slowly', de='langsam', k='Adverb', rang=131),
 dict(w='quickly', de='schnell', k='Adverb', rang=132),
 dict(w='again', de='wieder', k='Adverb', rang=133),
 dict(w='outside', de='draussen', k='Adverb', rang=134),
 dict(w='inside', de='drinnen', k='Adverb', rang=135),
 dict(w='home', de='nach Hause', k='Adverb', rang=136),
 dict(w='also', de='auch', k='Adverb', rang=137),
 dict(w='even', de='sogar', k='Adverb', rang=138),
 dict(w='finally', de='endlich', k='Adverb', rang=139),
 dict(w='probably', de='wahrscheinlich', k='Adverb', rang=140),
 dict(w='hopefully', de='hoffentlich', k='Adverb', rang=141),
 dict(w='unfortunately', de='leider', k='Adverb', rang=142),
 dict(w='straight', de='geradeaus', k='Adverb', rang=143),

# --------------------------------------------------------------- Zahlwort
 dict(w='zero', de='null', k='Zahlwort', rang=144),
 dict(w='one', de='eins', k='Zahlwort', rang=145),
 dict(w='two', de='zwei', k='Zahlwort', rang=146),
 dict(w='three', de='drei', k='Zahlwort', rang=147),
 dict(w='four', de='vier', k='Zahlwort', rang=148),
 dict(w='five', de='fuenf', k='Zahlwort', rang=149),
 dict(w='six', de='sechs', k='Zahlwort', rang=150),
 dict(w='seven', de='sieben', k='Zahlwort', rang=151),
 dict(w='eight', de='acht', k='Zahlwort', rang=152),
 dict(w='nine', de='neun', k='Zahlwort', rang=153),
 dict(w='ten', de='zehn', k='Zahlwort', rang=154),
 dict(w='eleven', de='elf', k='Zahlwort', rang=155),
 dict(w='twelve', de='zwoelf', k='Zahlwort', rang=156),
 dict(w='thirteen', de='dreizehn', k='Zahlwort', rang=157),
 dict(w='fourteen', de='vierzehn', k='Zahlwort', rang=158),
 dict(w='fifteen', de='fuenfzehn', k='Zahlwort', rang=159),
 dict(w='sixteen', de='sechzehn', k='Zahlwort', rang=160),
 dict(w='seventeen', de='siebzehn', k='Zahlwort', rang=161),
 dict(w='eighteen', de='achtzehn', k='Zahlwort', rang=162),
 dict(w='nineteen', de='neunzehn', k='Zahlwort', rang=163),
 dict(w='twenty', de='zwanzig', k='Zahlwort', rang=164),
 dict(w='thirty', de='dreissig', k='Zahlwort', rang=165),
 dict(w='forty', de='vierzig', k='Zahlwort', rang=166),
 dict(w='fifty', de='fuenfzig', k='Zahlwort', rang=167),
 dict(w='sixty', de='sechzig', k='Zahlwort', rang=168),
 dict(w='seventy', de='siebzig', k='Zahlwort', rang=169),
 dict(w='eighty', de='achtzig', k='Zahlwort', rang=170),
 dict(w='ninety', de='neunzig', k='Zahlwort', rang=171),
 dict(w='hundred', de='hundert', k='Zahlwort', rang=172),
 dict(w='thousand', de='tausend', k='Zahlwort', rang=173),
 dict(w='million', de='Million', k='Zahlwort', rang=174),
 dict(w='first', de='erster', k='Zahlwort', rang=175),
 dict(w='second', de='zweiter', k='Zahlwort', rang=176),
 dict(w='third', de='dritter', k='Zahlwort', rang=177),
 dict(w='last', de='letzter', k='Zahlwort', rang=178),
 dict(w='half', de='halb', k='Zahlwort', rang=179),
 dict(w='double', de='doppelt', k='Zahlwort', rang=180),
 dict(w='pair', de='Paar', k='Zahlwort', rang=181),

# -------------------------------------------------------------------- Verb
 dict(w='be', de='sein', k='Verb', rang=182,
      hin='Unregelmaessig: be / was, were / been.'),
 dict(w='have', de='haben', k='Verb', rang=183,
      hin='have / had / had.'),
 dict(w='do', de='tun, machen', k='Verb', rang=184,
      hin='do / did / done. Bildet ausserdem Fragen und Verneinungen.'),
 dict(w='say', de='sagen', k='Verb', rang=185, hin='say / said / said.'),
 dict(w='go', de='gehen', k='Verb', rang=186, hin='go / went / gone.'),
 dict(w='get', de='bekommen, werden', k='Verb', rang=187,
      hin='get / got / got. Das vielseitigste Verb des Englischen.'),
 dict(w='make', de='machen, herstellen', k='Verb', rang=188,
      hin='make / made / made. "Make" erschafft, "do" fuehrt aus.'),
 dict(w='know', de='wissen, kennen', k='Verb', rang=189, hin='know / knew / known.'),
 dict(w='think', de='denken', k='Verb', rang=190, hin='think / thought / thought.'),
 dict(w='take', de='nehmen', k='Verb', rang=191, hin='take / took / taken.'),
 dict(w='see', de='sehen', k='Verb', rang=192, hin='see / saw / seen.'),
 dict(w='come', de='kommen', k='Verb', rang=193, hin='come / came / come.'),
 dict(w='want', de='wollen', k='Verb', rang=194),
 dict(w='look', de='schauen', k='Verb', rang=195),
 dict(w='use', de='benutzen', k='Verb', rang=196),
 dict(w='find', de='finden', k='Verb', rang=197, hin='find / found / found.'),
 dict(w='give', de='geben', k='Verb', rang=198, hin='give / gave / given.'),
 dict(w='tell', de='erzaehlen', k='Verb', rang=199, hin='tell / told / told.'),
 dict(w='work', de='arbeiten, funktionieren', k='Verb', rang=200),
 dict(w='call', de='rufen, anrufen', k='Verb', rang=201),
 dict(w='try', de='versuchen', k='Verb', rang=202),
 dict(w='ask', de='fragen', k='Verb', rang=203),
 dict(w='need', de='brauchen', k='Verb', rang=204),
 dict(w='feel', de='fuehlen', k='Verb', rang=205, hin='feel / felt / felt.'),
 dict(w='become', de='werden', k='Verb', rang=206, hin='become / became / become.'),
 dict(w='leave', de='verlassen, abfahren', k='Verb', rang=207, hin='leave / left / left.'),
 dict(w='put', de='legen, stellen', k='Verb', rang=208, hin='put / put / put.'),
 dict(w='mean', de='bedeuten, meinen', k='Verb', rang=209, hin='mean / meant / meant.'),
 dict(w='keep', de='behalten', k='Verb', rang=210, hin='keep / kept / kept.'),
 dict(w='let', de='lassen', k='Verb', rang=211, hin='let / let / let.'),
 dict(w='begin', de='anfangen', k='Verb', rang=212, hin='begin / began / begun.'),
 dict(w='help', de='helfen', k='Verb', rang=213,
      hin='Auch das Nomen Hilfe: "I need help."'),
 dict(w='talk', de='reden', k='Verb', rang=214),
 dict(w='speak', de='sprechen', k='Verb', rang=215, hin='speak / spoke / spoken.'),
 dict(w='turn', de='drehen, abbiegen', k='Verb', rang=216),
 dict(w='start', de='starten', k='Verb', rang=217),
 dict(w='show', de='zeigen', k='Verb', rang=218),
 dict(w='hear', de='hoeren', k='Verb', rang=219, hin='hear / heard / heard.'),
 dict(w='play', de='spielen', k='Verb', rang=220),
 dict(w='run', de='rennen', k='Verb', rang=221, hin='run / ran / run.'),
 dict(w='move', de='bewegen, umziehen', k='Verb', rang=222),
 dict(w='live', de='leben, wohnen', k='Verb', rang=223),
 dict(w='believe', de='glauben', k='Verb', rang=224),
 dict(w='bring', de='bringen', k='Verb', rang=225, hin='bring / brought / brought.'),
 dict(w='happen', de='geschehen', k='Verb', rang=226),
 dict(w='write', de='schreiben', k='Verb', rang=227, hin='write / wrote / written.'),
 dict(w='sit', de='sitzen', k='Verb', rang=228, hin='sit / sat / sat.'),
 dict(w='stand', de='stehen', k='Verb', rang=229, hin='stand / stood / stood.'),
 dict(w='lose', de='verlieren', k='Verb', rang=230, hin='lose / lost / lost.'),
 dict(w='pay', de='bezahlen', k='Verb', rang=231, hin='pay / paid / paid.'),
 dict(w='meet', de='treffen', k='Verb', rang=232, hin='meet / met / met.'),
 dict(w='learn', de='lernen', k='Verb', rang=233),
 dict(w='change', de='aendern', k='Verb', rang=234),
 dict(w='understand', de='verstehen', k='Verb', rang=235,
      hin='understand / understood / understood.'),
 dict(w='eat', de='essen', k='Verb', rang=236, hin='eat / ate / eaten.'),
 dict(w='drink', de='trinken', k='Verb', rang=237, hin='drink / drank / drunk.'),
 dict(w='sleep', de='schlafen', k='Verb', rang=238, hin='sleep / slept / slept.'),
 dict(w='buy', de='kaufen', k='Verb', rang=239, hin='buy / bought / bought.'),
 dict(w='sell', de='verkaufen', k='Verb', rang=240, hin='sell / sold / sold.'),
 dict(w='cost', de='kosten', k='Verb', rang=241, hin='cost / cost / cost.'),
 dict(w='open', de='oeffnen', k='Verb', rang=242),
 dict(w='close', de='schliessen', k='Verb', rang=243),
 dict(w='wait', de='warten', k='Verb', rang=244),
 dict(w='stay', de='bleiben', k='Verb', rang=245),
 dict(w='arrive', de='ankommen', k='Verb', rang=246),
 dict(w='travel', de='reisen', k='Verb', rang=247),
 dict(w='drive', de='fahren', k='Verb', rang=248, hin='drive / drove / driven.'),
 dict(w='walk', de='gehen, laufen', k='Verb', rang=249),
 dict(w='visit', de='besuchen', k='Verb', rang=250),
 dict(w='like', de='moegen', k='Verb', rang=251),
 dict(w='enjoy', de='geniessen', k='Verb', rang=252),
 dict(w='remember', de='sich erinnern', k='Verb', rang=253),
 dict(w='forget', de='vergessen', k='Verb', rang=254, hin='forget / forgot / forgotten.'),
 dict(w='read', de='lesen', k='Verb', rang=255,
      hin='read / read / read - gleich geschrieben, aber anders gesprochen (riid / red).'),
 dict(w='study', de='studieren, lernen', k='Verb', rang=256),
 dict(w='teach', de='unterrichten', k='Verb', rang=257, hin='teach / taught / taught.'),
 dict(w='send', de='senden', k='Verb', rang=258, hin='send / sent / sent.'),
 dict(w='wear', de='tragen (Kleidung)', k='Verb', rang=259, hin='wear / wore / worn.'),
 dict(w='cook', de='kochen', k='Verb', rang=260),
 dict(w='wash', de='waschen', k='Verb', rang=261),
 dict(w='tidy', de='aufraeumen', k='Verb', rang=262),
 dict(w='laugh', de='lachen', k='Verb', rang=263),
 dict(w='cry', de='weinen', k='Verb', rang=264),
 dict(w='smile', de='laecheln', k='Verb', rang=265),
 dict(w='dance', de='tanzen', k='Verb', rang=266),
 dict(w='sing', de='singen', k='Verb', rang=267, hin='sing / sang / sung.'),
 dict(w='listen', de='zuhoeren', k='Verb', rang=268),
 dict(w='watch', de='ansehen', k='Verb', rang=269),
 dict(w='order', de='bestellen', k='Verb', rang=270),
 dict(w='reserve', de='reservieren', k='Verb', rang=271),
 dict(w='rent', de='mieten', k='Verb', rang=272),
 dict(w='sign', de='unterschreiben', k='Verb', rang=273),
 dict(w='borrow', de='sich leihen', k='Verb', rang=274,
      hin='"Borrow" nimmt, "lend" gibt - Deutsche verwechseln das staendig, '
          'weil "leihen" fuer beides steht.'),
 dict(w='hope', de='hoffen', k='Verb', rang=275),
 dict(w='thank', de='danken', k='Verb', rang=276),
 dict(w='marry', de='heiraten', k='Verb', rang=277),
 dict(w='win', de='gewinnen', k='Verb', rang=278, hin='win / won / won.'),
 dict(w='finish', de='beenden', k='Verb', rang=279),
 dict(w='continue', de='fortsetzen', k='Verb', rang=280),
 dict(w='choose', de='waehlen', k='Verb', rang=281, hin='choose / chose / chosen.'),

# ---------------------------------------------------------------- Adjektiv
 dict(w='good', de='gut', k='Adjektiv', rang=282,
      hin='Steigerung unregelmaessig: good / better / best.'),
 dict(w='bad', de='schlecht', k='Adjektiv', rang=283, hin='bad / worse / worst.'),
 dict(w='big', de='gross', k='Adjektiv', rang=284),
 dict(w='small', de='klein', k='Adjektiv', rang=285),
 dict(w='new', de='neu', k='Adjektiv', rang=286),
 dict(w='old', de='alt', k='Adjektiv', rang=287),
 dict(w='young', de='jung', k='Adjektiv', rang=288),
 dict(w='beautiful', de='schoen', k='Adjektiv', rang=289),
 dict(w='pretty', de='huebsch', k='Adjektiv', rang=290),
 dict(w='ugly', de='haesslich', k='Adjektiv', rang=291),
 dict(w='long', de='lang', k='Adjektiv', rang=292),
 dict(w='short', de='kurz', k='Adjektiv', rang=293),
 dict(w='tall', de='gross (Person)', k='Adjektiv', rang=294,
      hin='"Tall" bei Personen, "high" bei Dingen - "a tall man", "a high wall".'),
 dict(w='high', de='hoch', k='Adjektiv', rang=295),
 dict(w='low', de='niedrig', k='Adjektiv', rang=296),
 dict(w='hot', de='heiss, scharf', k='Adjektiv', rang=297),
 dict(w='warm', de='warm', k='Adjektiv', rang=298),
 dict(w='cold', de='kalt', k='Adjektiv', rang=299),
 dict(w='easy', de='einfach', k='Adjektiv', rang=300),
 dict(w='difficult', de='schwierig', k='Adjektiv', rang=301),
 dict(w='important', de='wichtig', k='Adjektiv', rang=302),
 dict(w='possible', de='moeglich', k='Adjektiv', rang=303),
 dict(w='true', de='wahr', k='Adjektiv', rang=304),
 dict(w='wrong', de='falsch', k='Adjektiv', rang=305),
 dict(w='right', de='richtig, rechts', k='Adjektiv', rang=306),
 dict(w='left', de='links', k='Adjektiv', rang=307),
 dict(w='expensive', de='teuer', k='Adjektiv', rang=308),
 dict(w='cheap', de='billig', k='Adjektiv', rang=309),
 dict(w='free', de='frei, kostenlos', k='Adjektiv', rang=310),
 dict(w='full', de='voll, satt', k='Adjektiv', rang=311),
 dict(w='empty', de='leer', k='Adjektiv', rang=312),
 dict(w='busy', de='beschaeftigt, besetzt', k='Adjektiv', rang=313),
 dict(w='ready', de='bereit', k='Adjektiv', rang=314),
 dict(w='tired', de='muede', k='Adjektiv', rang=315),
 dict(w='ill', de='krank', k='Adjektiv', rang=316,
      hin='"Ill" ist britisch, "sick" amerikanisch - in Grossbritannien heisst '
          '"sick" eher, dass einem uebel ist.'),
 dict(w='healthy', de='gesund', k='Adjektiv', rang=317),
 dict(w='happy', de='gluecklich', k='Adjektiv', rang=318),
 dict(w='sad', de='traurig', k='Adjektiv', rang=319),
 dict(w='angry', de='wuetend', k='Adjektiv', rang=320),
 dict(w='nice', de='nett', k='Adjektiv', rang=321),
 dict(w='kind', de='freundlich', k='Adjektiv', rang=322),
 dict(w='lovely', de='reizend', k='Adjektiv', rang=323,
      hin='In Grossbritannien das Allzweck-Lob fuer alles - Wetter, Essen, '
          'Menschen.'),
 dict(w='strong', de='stark', k='Adjektiv', rang=324),
 dict(w='weak', de='schwach', k='Adjektiv', rang=325),
 dict(w='fast', de='schnell', k='Adjektiv', rang=326),
 dict(w='slow', de='langsam', k='Adjektiv', rang=327),
 dict(w='heavy', de='schwer', k='Adjektiv', rang=328),
 dict(w='light', de='leicht, hell', k='Adjektiv', rang=329),
 dict(w='clean', de='sauber', k='Adjektiv', rang=330,
      hin='Auch das Verb putzen: "to clean the room".'),
 dict(w='dirty', de='schmutzig', k='Adjektiv', rang=331),
 dict(w='fresh', de='frisch', k='Adjektiv', rang=332),
 dict(w='sweet', de='suess', k='Adjektiv', rang=333),
 dict(w='salty', de='salzig', k='Adjektiv', rang=334),
 dict(w='spicy', de='scharf', k='Adjektiv', rang=335),
 dict(w='delicious', de='lecker', k='Adjektiv', rang=336),
 dict(w='white', de='weiss', k='Adjektiv', rang=337),
 dict(w='black', de='schwarz', k='Adjektiv', rang=338),
 dict(w='red', de='rot', k='Adjektiv', rang=339),
 dict(w='blue', de='blau', k='Adjektiv', rang=340),
 dict(w='green', de='gruen', k='Adjektiv', rang=341),
 dict(w='yellow', de='gelb', k='Adjektiv', rang=342),
 dict(w='grey', de='grau', k='Adjektiv', rang=343,
      hin='Britisch "grey", amerikanisch "gray".'),
 dict(w='brown', de='braun', k='Adjektiv', rang=344),
 dict(w='English', de='englisch', k='Adjektiv', rang=345),
 dict(w='German', de='deutsch', k='Adjektiv', rang=346),
 dict(w='foreign', de='auslaendisch', k='Adjektiv', rang=347),
 dict(w='next', de='naechster', k='Adjektiv', rang=348),
 dict(w='same', de='gleich', k='Adjektiv', rang=349),
 dict(w='different', de='verschieden', k='Adjektiv', rang=350),
 dict(w='usual', de='ueblich', k='Adjektiv', rang=351),
 dict(w='funny', de='lustig', k='Adjektiv', rang=352),
 dict(w='boring', de='langweilig', k='Adjektiv', rang=353),
 dict(w='interesting', de='interessant', k='Adjektiv', rang=354),
 dict(w='safe', de='sicher', k='Adjektiv', rang=355),
 dict(w='dangerous', de='gefaehrlich', k='Adjektiv', rang=356),

# ------------------------------------------------------------------- Nomen
 dict(w='man', de='Mann', k='Nomen', rang=357, hin='Mehrzahl: men.'),
 dict(w='woman', de='Frau', k='Nomen', rang=358, hin='Mehrzahl: women.'),
 dict(w='boy', de='Junge', k='Nomen', rang=359),
 dict(w='girl', de='Maedchen', k='Nomen', rang=360),
 dict(w='child', de='Kind', k='Nomen', rang=361, hin='Mehrzahl: children.'),
 dict(w='person', de='Person', k='Nomen', rang=362, hin='Mehrzahl: people.'),
 dict(w='people', de='Leute', k='Nomen', rang=363),
 dict(w='friend', de='Freund', k='Nomen', rang=364),
 dict(w='family', de='Familie', k='Nomen', rang=365),
 dict(w='father', de='Vater', k='Nomen', rang=366),
 dict(w='mother', de='Mutter', k='Nomen', rang=367),
 dict(w='son', de='Sohn', k='Nomen', rang=368),
 dict(w='daughter', de='Tochter', k='Nomen', rang=369),
 dict(w='brother', de='Bruder', k='Nomen', rang=370),
 dict(w='sister', de='Schwester', k='Nomen', rang=371),
 dict(w='husband', de='Ehemann', k='Nomen', rang=372),
 dict(w='wife', de='Ehefrau', k='Nomen', rang=373, hin='Mehrzahl: wives.'),
 dict(w='name', de='Name', k='Nomen', rang=374),
 dict(w='year', de='Jahr', k='Nomen', rang=375),
 dict(w='month', de='Monat', k='Nomen', rang=376),
 dict(w='week', de='Woche', k='Nomen', rang=377),
 dict(w='day', de='Tag', k='Nomen', rang=378),
 dict(w='hour', de='Stunde', k='Nomen', rang=379),
 dict(w='minute', de='Minute', k='Nomen', rang=380),
 dict(w='time', de='Zeit', k='Nomen', rang=381),
 dict(w='morning', de='Morgen', k='Nomen', rang=382),
 dict(w='afternoon', de='Nachmittag', k='Nomen', rang=383),
 dict(w='evening', de='Abend', k='Nomen', rang=384),
 dict(w='night', de='Nacht', k='Nomen', rang=385),
 dict(w='weekend', de='Wochenende', k='Nomen', rang=386),
 dict(w='house', de='Haus', k='Nomen', rang=387),
 dict(w='flat', de='Wohnung', k='Nomen', rang=388,
      hin='Britisch "flat", amerikanisch "apartment".'),
 dict(w='room', de='Zimmer', k='Nomen', rang=389),
 dict(w='door', de='Tuer', k='Nomen', rang=390),
 dict(w='window', de='Fenster', k='Nomen', rang=391),
 dict(w='table', de='Tisch', k='Nomen', rang=392),
 dict(w='bed', de='Bett', k='Nomen', rang=393),
 dict(w='kitchen', de='Kueche', k='Nomen', rang=394),
 dict(w='toilet', de='Toilette', k='Nomen', rang=395,
      hin='Britisch "toilet", amerikanisch "restroom" oder "bathroom".'),
 dict(w='city', de='Stadt', k='Nomen', rang=396),
 dict(w='country', de='Land', k='Nomen', rang=397),
 dict(w='street', de='Strasse', k='Nomen', rang=398),
 dict(w='way', de='Weg', k='Nomen', rang=399),
 dict(w='place', de='Ort, Platz', k='Nomen', rang=400),
 dict(w='shop', de='Laden', k='Nomen', rang=401,
      hin='Britisch "shop", amerikanisch "store".'),
 dict(w='market', de='Markt', k='Nomen', rang=402),
 dict(w='restaurant', de='Restaurant', k='Nomen', rang=403),
 dict(w='pub', de='Kneipe', k='Nomen', rang=404,
      hin='Die britische Institution schlechthin - bestellt und bezahlt wird '
          'an der Theke.'),
 dict(w='hotel', de='Hotel', k='Nomen', rang=405),
 dict(w='hospital', de='Krankenhaus', k='Nomen', rang=406),
 dict(w='pharmacy', de='Apotheke', k='Nomen', rang=407,
      hin='Im Alltag britisch "chemist".'),
 dict(w='station', de='Bahnhof', k='Nomen', rang=408),
 dict(w='airport', de='Flughafen', k='Nomen', rang=409),
 dict(w='train', de='Zug', k='Nomen', rang=410),
 dict(w='bus', de='Bus', k='Nomen', rang=411),
 dict(w='car', de='Auto', k='Nomen', rang=412),
 dict(w='ticket', de='Fahrkarte', k='Nomen', rang=413),
 dict(w='luggage', de='Gepaeck', k='Nomen', rang=414,
      hin='Nicht zaehlbar: "a luggage" gibt es nicht, man sagt "a piece of '
          'luggage" oder "a bag".'),
 dict(w='passport', de='Pass', k='Nomen', rang=415),
 dict(w='money', de='Geld', k='Nomen', rang=416),
 dict(w='price', de='Preis', k='Nomen', rang=417),
 dict(w='bill', de='Rechnung', k='Nomen', rang=418,
      hin='Britisch "bill", amerikanisch "check".'),
 dict(w='card', de='Karte', k='Nomen', rang=419),
 dict(w='job', de='Arbeit, Stelle', k='Nomen', rang=420),
 dict(w='school', de='Schule', k='Nomen', rang=421),
 dict(w='university', de='Universitaet', k='Nomen', rang=422),
 dict(w='student', de='Student', k='Nomen', rang=423),
 dict(w='lecture', de='Vorlesung', k='Nomen', rang=424),
 dict(w='exam', de='Pruefung', k='Nomen', rang=425),
 dict(w='book', de='Buch', k='Nomen', rang=426,
      hin='Auch das Verb buchen: "to book a table".'),
 dict(w='word', de='Wort', k='Nomen', rang=427),
 dict(w='language', de='Sprache', k='Nomen', rang=428),
 dict(w='question', de='Frage', k='Nomen', rang=429),
 dict(w='answer', de='Antwort', k='Nomen', rang=430),
 dict(w='problem', de='Problem', k='Nomen', rang=431),
 dict(w='thing', de='Ding, Sache', k='Nomen', rang=432),
 dict(w='water', de='Wasser', k='Nomen', rang=433),
 dict(w='wine', de='Wein', k='Nomen', rang=434),
 dict(w='beer', de='Bier', k='Nomen', rang=435),
 dict(w='tea', de='Tee', k='Nomen', rang=436),
 dict(w='coffee', de='Kaffee', k='Nomen', rang=437),
 dict(w='milk', de='Milch', k='Nomen', rang=438),
 dict(w='bread', de='Brot', k='Nomen', rang=439),
 dict(w='cheese', de='Kaese', k='Nomen', rang=440),
 dict(w='meat', de='Fleisch', k='Nomen', rang=441),
 dict(w='fish', de='Fisch', k='Nomen', rang=442, hin='Mehrzahl meist auch "fish".'),
 dict(w='fruit', de='Obst', k='Nomen', rang=443),
 dict(w='vegetables', de='Gemuese', k='Nomen', rang=444),
 dict(w='sugar', de='Zucker', k='Nomen', rang=445),
 dict(w='salt', de='Salz', k='Nomen', rang=446),
 dict(w='food', de='Essen', k='Nomen', rang=447),
 dict(w='breakfast', de='Fruehstueck', k='Nomen', rang=448),
 dict(w='lunch', de='Mittagessen', k='Nomen', rang=449),
 dict(w='dinner', de='Abendessen', k='Nomen', rang=450),
 dict(w='menu', de='Speisekarte', k='Nomen', rang=451),
 dict(w='plate', de='Teller', k='Nomen', rang=452),
 dict(w='glass', de='Glas', k='Nomen', rang=453),
 dict(w='bottle', de='Flasche', k='Nomen', rang=454),
 dict(w='head', de='Kopf', k='Nomen', rang=455),
 dict(w='hand', de='Hand', k='Nomen', rang=456),
 dict(w='foot', de='Fuss', k='Nomen', rang=457, hin='Mehrzahl: feet.'),
 dict(w='eye', de='Auge', k='Nomen', rang=458),
 dict(w='mouth', de='Mund', k='Nomen', rang=459),
 dict(w='arm', de='Arm', k='Nomen', rang=460),
 dict(w='leg', de='Bein', k='Nomen', rang=461),
 dict(w='hair', de='Haare', k='Nomen', rang=462,
      hin='Nicht zaehlbar: "her hair is lovely", nie "hairs".'),
 dict(w='body', de='Koerper', k='Nomen', rang=463),
 dict(w='doctor', de='Arzt', k='Nomen', rang=464),
 dict(w='medicine', de='Medizin', k='Nomen', rang=465),
 dict(w='pain', de='Schmerz', k='Nomen', rang=466),
 dict(w='phone', de='Handy', k='Nomen', rang=467),
 dict(w='number', de='Nummer', k='Nomen', rang=468),
 dict(w='music', de='Musik', k='Nomen', rang=469),
 dict(w='film', de='Film', k='Nomen', rang=470,
      hin='Britisch "film", amerikanisch "movie".'),
 dict(w='party', de='Party', k='Nomen', rang=471),
 dict(w='life', de='Leben', k='Nomen', rang=472, hin='Mehrzahl: lives.'),
 dict(w='world', de='Welt', k='Nomen', rang=473),
 dict(w='sun', de='Sonne', k='Nomen', rang=474),
 dict(w='rain', de='Regen', k='Nomen', rang=475),
 dict(w='snow', de='Schnee', k='Nomen', rang=476),
 dict(w='weather', de='Wetter', k='Nomen', rang=477),
 dict(w='sea', de='Meer', k='Nomen', rang=478),
 dict(w='mountain', de='Berg', k='Nomen', rang=479),
 dict(w='air', de='Luft', k='Nomen', rang=480),
 dict(w='dog', de='Hund', k='Nomen', rang=481),
 dict(w='cat', de='Katze', k='Nomen', rang=482),
 dict(w='clothes', de='Kleidung', k='Nomen', rang=483,
      hin='Nur Mehrzahl: "a clothes" gibt es nicht.'),
 dict(w='shoe', de='Schuh', k='Nomen', rang=484),
 dict(w='bag', de='Tasche', k='Nomen', rang=485),
 dict(w='key', de='Schluessel', k='Nomen', rang=486),
 dict(w='present', de='Geschenk', k='Nomen', rang=487),
 dict(w='love', de='Liebe', k='Nomen', rang=488,
      hin='Auch das Verb lieben: "I love you."'),
 dict(w='part', de='Teil', k='Nomen', rang=489),
 dict(w='end', de='Ende', k='Nomen', rang=490),
 dict(w='beginning', de='Anfang', k='Nomen', rang=491),
 dict(w='reason', de='Grund', k='Nomen', rang=492),
 dict(w='example', de='Beispiel', k='Nomen', rang=493),
 dict(w='idea', de='Idee', k='Nomen', rang=494),
 dict(w='story', de='Geschichte', k='Nomen', rang=495),
 dict(w='moment', de='Moment', k='Nomen', rang=496),
 dict(w='police', de='Polizei', k='Nomen', rang=497,
      hin='Immer Mehrzahl: "the police are coming".'),
 dict(w='shift', de='Schicht', k='Nomen', rang=498),
 dict(w='colleague', de='Kollege', k='Nomen', rang=499),
 dict(w='customer', de='Kunde', k='Nomen', rang=500),
]
