# -*- coding: utf-8 -*-
"""Die 500 haeufigsten vietnamesischen Woerter.

**Eigenstaendige Liste, KEINE Uebersetzung** - dieselbe Begruendung wie bei
`vokabeln_it.py`.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen.

**KEIN GENUS, KEINE ARTIKEL, KEINE KONJUGATION, KEINE MEHRZAHLFORM.**
Vietnamesisch ist isolierend: jedes Wort bleibt, wie es ist. Was im
Deutschen die Endung leistet, leisten hier eigene Woerter -
`đã` (Vergangenheit), `sẽ` (Zukunft), `đang` (gerade dabei), `các` und
`những` (Mehrzahl). Genau deshalb ist die automatische Wortart-Erkennung
(`wortarten_auto.py`) fuer Vietnamesisch besonders treffsicher: die Form
im Satz IST die Woerterbuchform.

**Die Toene sind Teil des Wortes.** `ma` (Geist), `má` (Mutter), `mà`
(aber), `mạ` (Reissaemling), `mã` (Pferd), `mả` (Grab) sind sechs
verschiedene Woerter. Ein weggelassenes Tonzeichen ist kein Tippfehler,
sondern ein anderes Wort - deshalb stehen sie hier alle.

**ANREDEWOERTER STATT PRONOMEN.** Es gibt kein neutrales "du" und kein
neutrales "ich" - angeredet wird mit Verwandtschaftswoertern nach Alter
und Geschlecht, und dasselbe Wort heisst je nach Sprecher ich ODER du.
Sie stehen hier unter Pronomen, weil sie im Satz diese Rolle spielen; die
lange Erklaerung steht im Kopf von `grundwortschatz_vi.py`.

**Zaehlwoerter sind Pflicht.** Zwischen Zahl und Nomen muss eines stehen:
`hai cái bàn` (zwei Stueck Tisch), nie `hai bàn`. Die gebraeuchlichsten
(`cái`, `con`, `người`, `quyển`, `chiếc`) stehen als eigene Eintraege.
"""

WOERTER = [

# --------------------------------------------------------------- Pronomen
 dict(w='tôi', de='ich (neutral)', k='Pronomen', rang=1,
      hin='Die sichere Wahl fuer Auslaender - hoeflich, etwas distanziert, '
          'immer richtig.'),
 dict(w='mình', de='ich, wir (vertraut)', k='Pronomen', rang=2),
 dict(w='bạn', de='du (Gleichaltrige), Freund', k='Pronomen', rang=3),
 dict(w='anh', de='du/ich (aelterer Mann)', k='Pronomen', rang=4,
      hin='Heisst zugleich "aelterer Bruder". Wer selbst der aeltere Mann '
          'ist, benutzt es fuer SICH.'),
 dict(w='chị', de='du/ich (aeltere Frau)', k='Pronomen', rang=5),
 dict(w='em', de='du/ich (juengere Person)', k='Pronomen', rang=6,
      hin='Zwischen Paaren die uebliche Anrede fuer die Frau - unabhaengig '
          'vom echten Alter.'),
 dict(w='ông', de='du (alter Mann), Herr', k='Pronomen', rang=7),
 dict(w='bà', de='du (alte Frau), Frau', k='Pronomen', rang=8),
 dict(w='cô', de='du (Frau mittleren Alters), Lehrerin', k='Pronomen', rang=9),
 dict(w='chú', de='du (Mann mittleren Alters)', k='Pronomen', rang=10),
 dict(w='cháu', de='ich (zu viel Aelteren), Enkel', k='Pronomen', rang=11),
 dict(w='con', de='ich (zu den Eltern), Kind', k='Pronomen', rang=12,
      hin='Zugleich das Zaehlwort fuer Tiere: "hai con cho" - zwei Hunde.'),
 dict(w='nó', de='er, sie, es (vertraut)', k='Pronomen', rang=13),
 dict(w='họ', de='sie (Mehrzahl)', k='Pronomen', rang=14),
 dict(w='chúng tôi', de='wir (ohne dich)', k='Pronomen', rang=15,
      hin='Vietnamesisch trennt das WIR: "chúng tôi" schliesst den '
          'Angesprochenen aus, "chúng ta" ein.'),
 dict(w='chúng ta', de='wir (mit dir)', k='Pronomen', rang=16),
 dict(w='các bạn', de='ihr', k='Pronomen', rang=17),
 dict(w='ai', de='wer, jemand', k='Pronomen', rang=18),
 dict(w='này', de='dieser', k='Pronomen', rang=19),
 dict(w='kia', de='jener', k='Pronomen', rang=20),
 dict(w='đó', de='das, jenes', k='Pronomen', rang=21),
 dict(w='tất cả', de='alles, alle', k='Pronomen', rang=22),
 dict(w='mọi người', de='alle Leute', k='Pronomen', rang=23),
 dict(w='ai đó', de='irgendjemand', k='Pronomen', rang=24),
 dict(w='cái gì', de='etwas, was', k='Pronomen', rang=25),
 dict(w='không ai', de='niemand', k='Pronomen', rang=26),
 dict(w='khác', de='anderer', k='Pronomen', rang=27),
 dict(w='mỗi', de='jeder', k='Pronomen', rang=28),
 dict(w='cả hai', de='beide', k='Pronomen', rang=29),
 dict(w='nhau', de='einander', k='Pronomen', rang=30),
 dict(w='của', de='von (Besitz)', k='Pronomen', rang=31,
      hin='Bildet den Besitz: "sách của tôi" - mein Buch, woertlich "Buch '
          'von mir".'),
 dict(w='chính mình', de='selbst', k='Pronomen', rang=32),

# -------------------------------------------------------------- Fragewort
 dict(w='gì', de='was', k='Fragewort', rang=33,
      hin='Steht am SATZENDE, nicht am Anfang: "bạn làm gì?" - was machst '
          'du?'),
 dict(w='đâu', de='wo', k='Fragewort', rang=34),
 dict(w='khi nào', de='wann', k='Fragewort', rang=35),
 dict(w='thế nào', de='wie', k='Fragewort', rang=36),
 dict(w='tại sao', de='warum', k='Fragewort', rang=37),
 dict(w='bao nhiêu', de='wie viel', k='Fragewort', rang=38),
 dict(w='mấy', de='wie viele (kleine Zahl)', k='Fragewort', rang=39),
 dict(w='nào', de='welcher', k='Fragewort', rang=40),
 dict(w='không', de='nicht (Fragepartikel)', k='Fragewort', rang=41,
      hin='Am Satzende macht es aus jeder Aussage eine Ja/Nein-Frage: "bạn '
          'khỏe không?" - geht es dir gut?'),
 dict(w='chưa', de='schon?, noch nicht', k='Fragewort', rang=42,
      hin='Dieselbe Silbe fragt und antwortet: "an chua?" - schon gegessen? '
          '"Chua." - noch nicht.'),

# ------------------------------------------------------------ Konjunktion
 dict(w='và', de='und', k='Konjunktion', rang=43),
 dict(w='hoặc', de='oder', k='Konjunktion', rang=44),
 dict(w='hay', de='oder (in Fragen), gut', k='Konjunktion', rang=45),
 dict(w='nhưng', de='aber', k='Konjunktion', rang=46),
 dict(w='nếu', de='wenn, falls', k='Konjunktion', rang=47),
 dict(w='vì', de='weil', k='Konjunktion', rang=48),
 dict(w='nên', de='also, sollte', k='Konjunktion', rang=49),
 dict(w='mà', de='aber, welcher', k='Konjunktion', rang=50),
 dict(w='khi', de='als, wenn', k='Konjunktion', rang=51),
 dict(w='trong khi', de='waehrend', k='Konjunktion', rang=52),
 dict(w='mặc dù', de='obwohl', k='Konjunktion', rang=53),
 dict(w='hơn', de='als (Vergleich), mehr', k='Konjunktion', rang=54),
 dict(w='cũng', de='auch', k='Konjunktion', rang=55),
 dict(w='thì', de='dann (Satzverbinder)', k='Konjunktion', rang=56),
 dict(w='rồi', de='dann, schon', k='Konjunktion', rang=57,
      hin='Am Satzende zeigt es an, dass etwas GESCHEHEN ist: "an rồi" - ich '
          'habe gegessen.'),

# ----------------------------------------------------------- Praeposition
 dict(w='ở', de='in, an, bei', k='Praeposition', rang=58),
 dict(w='trong', de='in, innerhalb', k='Praeposition', rang=59),
 dict(w='trên', de='auf, ueber', k='Praeposition', rang=60),
 dict(w='dưới', de='unter', k='Praeposition', rang=61),
 dict(w='với', de='mit', k='Praeposition', rang=62),
 dict(w='cho', de='fuer, geben', k='Praeposition', rang=63),
 dict(w='từ', de='von, aus', k='Praeposition', rang=64,
      hin='Als Nomen heisst es auch Wort - "tu dien" ist das Woerterbuch.'),
 dict(w='đến', de='bis, ankommen', k='Praeposition', rang=65),
 dict(w='về', de='ueber, zurueck', k='Praeposition', rang=66),
 dict(w='sau', de='nach, hinter', k='Praeposition', rang=67),
 dict(w='trước', de='vor', k='Praeposition', rang=68),
 dict(w='giữa', de='zwischen', k='Praeposition', rang=69),
 dict(w='ngoài', de='ausserhalb, draussen', k='Praeposition', rang=70),
 dict(w='bên cạnh', de='neben', k='Praeposition', rang=71),
 dict(w='qua', de='durch, vorbei', k='Praeposition', rang=72),
 dict(w='theo', de='gemaess, folgen', k='Praeposition', rang=73),
 dict(w='bằng', de='mit (Mittel), gleich', k='Praeposition', rang=74,
      hin='Fuer das Mittel: "đi bằng xe" - mit dem Auto fahren.'),
 dict(w='đối với', de='fuer, gegenueber', k='Praeposition', rang=75),
 dict(w='quanh', de='um herum', k='Praeposition', rang=76),
 dict(w='gần', de='nahe', k='Praeposition', rang=77),
 dict(w='xa', de='weit', k='Praeposition', rang=78),
 dict(w='cùng', de='zusammen mit', k='Praeposition', rang=79),
 dict(w='thay vì', de='anstatt', k='Praeposition', rang=80),

# ----------------------------------------------------------------- Adverb
 dict(w='có', de='ja, haben, es gibt', k='Adverb', rang=81,
      hin='Das Allzweckwort: bejaht eine Frage, heisst haben und "es gibt".'),
 dict(w='vâng', de='ja (hoeflich, Norden)', k='Adverb', rang=82),
 dict(w='dạ', de='ja (hoeflich, Sueden)', k='Adverb', rang=83),
 dict(w='rất', de='sehr', k='Adverb', rang=84),
 dict(w='quá', de='zu, sehr', k='Adverb', rang=85,
      hin='Nach dem Adjektiv verstaerkt es: "dep qua!" - so schoen!'),
 dict(w='nhiều', de='viel', k='Adverb', rang=86),
 dict(w='ít', de='wenig', k='Adverb', rang=87),
 dict(w='một chút', de='ein bisschen', k='Adverb', rang=88),
 dict(w='tốt', de='gut', k='Adverb', rang=89),
 dict(w='dở', de='schlecht', k='Adverb', rang=90),
 dict(w='đây', de='hier', k='Adverb', rang=91),
 dict(w='kìa', de='dort', k='Adverb', rang=92),
 dict(w='bây giờ', de='jetzt', k='Adverb', rang=93),
 dict(w='hôm nay', de='heute', k='Adverb', rang=94),
 dict(w='hôm qua', de='gestern', k='Adverb', rang=95),
 dict(w='ngày mai', de='morgen', k='Adverb', rang=96),
 dict(w='luôn luôn', de='immer', k='Adverb', rang=97),
 dict(w='không bao giờ', de='nie', k='Adverb', rang=98),
 dict(w='thường', de='oft', k='Adverb', rang=99),
 dict(w='đôi khi', de='manchmal', k='Adverb', rang=100),
 dict(w='hiếm khi', de='selten', k='Adverb', rang=101),
 dict(w='sớm', de='frueh, bald', k='Adverb', rang=102),
 dict(w='muộn', de='spaet', k='Adverb', rang=103),
 dict(w='còn', de='noch', k='Adverb', rang=104),
 dict(w='đã', de='schon (Vergangenheit)', k='Adverb', rang=105,
      hin='Steht VOR dem Verb und macht daraus die Vergangenheit - das Verb '
          'selbst bleibt unveraendert.'),
 dict(w='sẽ', de='wird (Zukunft)', k='Adverb', rang=106),
 dict(w='đang', de='gerade (Verlaufsform)', k='Adverb', rang=107),
 dict(w='chung', de='zusammen', k='Adverb', rang=108),
 dict(w='chỉ', de='nur', k='Adverb', rang=109),
 dict(w='có lẽ', de='vielleicht', k='Adverb', rang=110),
 dict(w='thật', de='wirklich', k='Adverb', rang=111),
 dict(w='vậy', de='so', k='Adverb', rang=112),
 dict(w='đủ', de='genug', k='Adverb', rang=113),
 dict(w='gần như', de='fast', k='Adverb', rang=114),
 dict(w='đúng', de='genau, richtig', k='Adverb', rang=115),
 dict(w='chắc chắn', de='sicher', k='Adverb', rang=116),
 dict(w='chậm', de='langsam', k='Adverb', rang=117),
 dict(w='nhanh', de='schnell', k='Adverb', rang=118),
 dict(w='lại', de='wieder', k='Adverb', rang=119),
 dict(w='nữa', de='noch mehr', k='Adverb', rang=120),
 dict(w='cuối cùng', de='endlich', k='Adverb', rang=121),
 dict(w='tiếc là', de='leider', k='Adverb', rang=122),
 dict(w='ngay', de='sofort', k='Adverb', rang=123),
 dict(w='thẳng', de='geradeaus', k='Adverb', rang=124),
 dict(w='hết', de='aufgebraucht, ganz', k='Adverb', rang=125),
 dict(w='cứ', de='ruhig, einfach', k='Adverb', rang=126),
 dict(w='mới', de='gerade erst, neu', k='Adverb', rang=127),
 dict(w='từ từ', de='langsam, gemaechlich', k='Adverb', rang=128),
 dict(w='thôi', de='nur, genug', k='Adverb', rang=129),
 dict(w='nhé', de='ja? (freundliche Partikel)', k='Adverb', rang=130,
      hin='Am Satzende macht es Bitten und Vorschlaege weich - fast '
          'unverzichtbar, um nicht schroff zu klingen.'),

# --------------------------------------------------------------- Zahlwort
 dict(w='không (số)', de='null', k='Zahlwort', rang=131,
      hin='Dasselbe Wort wie "nicht" - hier als Zahl.'),
 dict(w='một', de='eins', k='Zahlwort', rang=132),
 dict(w='hai', de='zwei', k='Zahlwort', rang=133),
 dict(w='ba', de='drei', k='Zahlwort', rang=134),
 dict(w='bốn', de='vier', k='Zahlwort', rang=135),
 dict(w='năm', de='fuenf, Jahr', k='Zahlwort', rang=136),
 dict(w='sáu', de='sechs', k='Zahlwort', rang=137),
 dict(w='bảy', de='sieben', k='Zahlwort', rang=138),
 dict(w='tám', de='acht', k='Zahlwort', rang=139),
 dict(w='chín', de='neun', k='Zahlwort', rang=140),
 dict(w='mười', de='zehn', k='Zahlwort', rang=141),
 dict(w='mười một', de='elf', k='Zahlwort', rang=142),
 dict(w='mười hai', de='zwoelf', k='Zahlwort', rang=143),
 dict(w='mười ba', de='dreizehn', k='Zahlwort', rang=144),
 dict(w='mười bốn', de='vierzehn', k='Zahlwort', rang=145),
 dict(w='mười lăm', de='fuenfzehn', k='Zahlwort', rang=146,
      hin='Nicht "mười năm" - die Fuenf wird nach Zehnern zu "lăm".'),
 dict(w='mười sáu', de='sechzehn', k='Zahlwort', rang=147),
 dict(w='mười bảy', de='siebzehn', k='Zahlwort', rang=148),
 dict(w='mười tám', de='achtzehn', k='Zahlwort', rang=149),
 dict(w='mười chín', de='neunzehn', k='Zahlwort', rang=150),
 dict(w='hai mươi', de='zwanzig', k='Zahlwort', rang=151),
 dict(w='ba mươi', de='dreissig', k='Zahlwort', rang=152),
 dict(w='bốn mươi', de='vierzig', k='Zahlwort', rang=153),
 dict(w='năm mươi', de='fuenfzig', k='Zahlwort', rang=154),
 dict(w='sáu mươi', de='sechzig', k='Zahlwort', rang=155),
 dict(w='bảy mươi', de='siebzig', k='Zahlwort', rang=156),
 dict(w='tám mươi', de='achtzig', k='Zahlwort', rang=157),
 dict(w='chín mươi', de='neunzig', k='Zahlwort', rang=158),
 dict(w='một trăm', de='hundert', k='Zahlwort', rang=159),
 dict(w='một nghìn', de='tausend', k='Zahlwort', rang=160),
 dict(w='triệu', de='Million', k='Zahlwort', rang=161),
 dict(w='thứ nhất', de='erster', k='Zahlwort', rang=162),
 dict(w='thứ hai', de='zweiter, Montag', k='Zahlwort', rang=163,
      hin='Auch der Wochentag: die Tage sind durchnummeriert, Montag ist der '
          'zweite.'),
 dict(w='thứ ba', de='dritter, Dienstag', k='Zahlwort', rang=164),
 dict(w='cuối', de='letzter', k='Zahlwort', rang=165),
 dict(w='nửa', de='halb', k='Zahlwort', rang=166),
 dict(w='đôi', de='Paar', k='Zahlwort', rang=167),
 dict(w='cái', de='Stueck (Zaehlwort)', k='Zahlwort', rang=168,
      hin='Das haeufigste Zaehlwort - fuer Dinge. Zwischen Zahl und Nomen ist '
          'eines PFLICHT: "hai cái bàn", nie "hai bàn".'),
 dict(w='tờ', de='Stueck (Blaetter, Papiere)', k='Zahlwort', rang=169),
 dict(w='người', de='Person (Zaehlwort), Mensch', k='Zahlwort', rang=170),
 dict(w='quyển', de='Stueck (Buecher)', k='Zahlwort', rang=171),
 dict(w='chiếc', de='Stueck (Fahrzeuge, Einzelstuecke)', k='Zahlwort', rang=172),

# -------------------------------------------------------------------- Verb
 dict(w='là', de='sein', k='Verb', rang=173,
      hin='Nur zwischen zwei NOMEN: "tôi là sinh viên". Vor Adjektiven faellt '
          'es weg - "tôi mệt", nicht "tôi là mệt".'),
 dict(w='ở lại', de='bleiben', k='Verb', rang=174),
 dict(w='làm', de='machen, arbeiten', k='Verb', rang=175),
 dict(w='nói', de='sprechen, sagen', k='Verb', rang=176),
 dict(w='đi', de='gehen, fahren', k='Verb', rang=177),
 dict(w='thấy', de='sehen', k='Verb', rang=178),
 dict(w='nhìn', de='schauen', k='Verb', rang=179),
 dict(w='nghe', de='hoeren', k='Verb', rang=180),
 dict(w='biết', de='wissen, kennen', k='Verb', rang=181),
 dict(w='hiểu', de='verstehen', k='Verb', rang=182),
 dict(w='nghĩ', de='denken', k='Verb', rang=183),
 dict(w='tin', de='glauben', k='Verb', rang=184),
 dict(w='muốn', de='wollen', k='Verb', rang=185),
 dict(w='cần', de='brauchen', k='Verb', rang=186),
 dict(w='phải', de='muessen', k='Verb', rang=187),
 dict(w='được', de='koennen, duerfen, bekommen', k='Verb', rang=188,
      hin='Nach dem Verb heisst es "koennen": "an duoc" - essen koennen. Am '
          'Satzende mit "khong" wird es zur Bitte.'),
 dict(w='hỏi', de='fragen', k='Verb', rang=189),
 dict(w='trả lời', de='antworten', k='Verb', rang=190),
 dict(w='gọi', de='rufen, bestellen', k='Verb', rang=191),
 dict(w='ăn', de='essen', k='Verb', rang=192),
 dict(w='uống', de='trinken', k='Verb', rang=193),
 dict(w='ngủ', de='schlafen', k='Verb', rang=194),
 dict(w='sống', de='leben', k='Verb', rang=195),
 dict(w='mua', de='kaufen', k='Verb', rang=196),
 dict(w='bán', de='verkaufen', k='Verb', rang=197),
 dict(w='trả', de='bezahlen, zurueckgeben', k='Verb', rang=198),
 dict(w='mở', de='oeffnen', k='Verb', rang=199),
 dict(w='đóng', de='schliessen', k='Verb', rang=200),
 dict(w='đợi', de='warten', k='Verb', rang=201),
 dict(w='tìm', de='suchen', k='Verb', rang=202),
 dict(w='mang', de='bringen, tragen', k='Verb', rang=203),
 dict(w='dùng', de='benutzen', k='Verb', rang=204),
 dict(w='giúp', de='helfen', k='Verb', rang=205),
 dict(w='thích', de='moegen', k='Verb', rang=206),
 dict(w='yêu', de='lieben', k='Verb', rang=207),
 dict(w='học', de='lernen, studieren', k='Verb', rang=208),
 dict(w='dạy', de='unterrichten', k='Verb', rang=209),
 dict(w='đọc', de='lesen', k='Verb', rang=210),
 dict(w='viết', de='schreiben', k='Verb', rang=211),
 dict(w='nhớ', de='sich erinnern, vermissen', k='Verb', rang=212),
 dict(w='quên', de='vergessen', k='Verb', rang=213),
 dict(w='bắt đầu', de='anfangen', k='Verb', rang=214),
 dict(w='kết thúc', de='beenden', k='Verb', rang=215),
 dict(w='tiếp tục', de='fortsetzen', k='Verb', rang=216),
 dict(w='thử', de='versuchen, probieren', k='Verb', rang=217),
 dict(w='mất', de='verlieren, dauern', k='Verb', rang=218),
 dict(w='thắng', de='gewinnen', k='Verb', rang=219),
 dict(w='chơi', de='spielen', k='Verb', rang=220),
 dict(w='hát', de='singen', k='Verb', rang=221),
 dict(w='nhảy', de='tanzen, springen', k='Verb', rang=222),
 dict(w='chạy', de='rennen', k='Verb', rang=223),
 dict(w='lái', de='fahren (lenken)', k='Verb', rang=224),
 dict(w='du lịch', de='reisen', k='Verb', rang=225),
 dict(w='thăm', de='besuchen', k='Verb', rang=226),
 dict(w='gặp', de='treffen', k='Verb', rang=227),
 dict(w='quen', de='kennenlernen, gewohnt sein', k='Verb', rang=228),
 dict(w='cưới', de='heiraten', k='Verb', rang=229),
 dict(w='sinh', de='geboren werden, gebaeren', k='Verb', rang=230),
 dict(w='chết', de='sterben', k='Verb', rang=231),
 dict(w='đổi', de='wechseln, tauschen', k='Verb', rang=232),
 dict(w='trở thành', de='werden', k='Verb', rang=233),
 dict(w='xảy ra', de='geschehen', k='Verb', rang=234),
 dict(w='hy vọng', de='hoffen', k='Verb', rang=235),
 dict(w='đặt', de='bestellen, reservieren', k='Verb', rang=236),
 dict(w='thuê', de='mieten', k='Verb', rang=237),
 dict(w='ký', de='unterschreiben', k='Verb', rang=238),
 dict(w='rửa', de='waschen', k='Verb', rang=239),
 dict(w='nấu', de='kochen', k='Verb', rang=240),
 dict(w='dọn', de='aufraeumen', k='Verb', rang=241),
 dict(w='cười', de='lachen, laecheln', k='Verb', rang=242),
 dict(w='khóc', de='weinen', k='Verb', rang=243),
 dict(w='cảm ơn', de='danken', k='Verb', rang=244),
 dict(w='xin lỗi', de='sich entschuldigen', k='Verb', rang=245),
 dict(w='chào', de='gruessen', k='Verb', rang=246),
 dict(w='chỉ đường', de='den Weg zeigen', k='Verb', rang=247),
 dict(w='kể', de='erzaehlen', k='Verb', rang=248),
 dict(w='nhận', de='bekommen, annehmen', k='Verb', rang=249),
 dict(w='giữ', de='halten, behalten', k='Verb', rang=250),
 dict(w='dừng', de='anhalten', k='Verb', rang=251),
 dict(w='chuyển', de='umziehen, uebertragen', k='Verb', rang=252),
 dict(w='ngồi', de='sitzen', k='Verb', rang=253),
 dict(w='đứng', de='stehen', k='Verb', rang=254),
 dict(w='nằm', de='liegen', k='Verb', rang=255),
 dict(w='mặc', de='anziehen (Kleidung)', k='Verb', rang=256),
 dict(w='mời', de='einladen, bitten', k='Verb', rang=257,
      hin='Vor dem Essen laedt man die Aelteren ausdruecklich ein - "mời" '
          'plus Anredewort. Das gilt als Pflicht, nicht als Geste.'),
 dict(w='lấy', de='nehmen, holen', k='Verb', rang=258),
 dict(w='đưa', de='geben, bringen', k='Verb', rang=259),
 dict(w='về nhà', de='nach Hause gehen', k='Verb', rang=260),
 dict(w='ra', de='hinausgehen', k='Verb', rang=261),
 dict(w='vào', de='hineingehen', k='Verb', rang=262),
 dict(w='lên', de='hinaufgehen, einsteigen', k='Verb', rang=263),
 dict(w='xuống', de='hinuntergehen, aussteigen', k='Verb', rang=264),
 dict(w='bị', de='erleiden (Passiv, negativ)', k='Verb', rang=265,
      hin='Markiert etwas Unangenehmes: "bi om" - krank sein, "bi mat" - '
          'verlieren. Fuer Gutes nimmt man "duoc".'),
 dict(w='sạc', de='aufladen', k='Verb', rang=266),
 dict(w='tính tiền', de='abrechnen', k='Verb', rang=267),
 dict(w='đăng ký', de='sich anmelden', k='Verb', rang=268),
 dict(w='khám', de='untersuchen (Arzt)', k='Verb', rang=269),
 dict(w='nghỉ', de='ausruhen, freihaben', k='Verb', rang=270),
 dict(w='gửi', de='schicken, abgeben', k='Verb', rang=271),

# ---------------------------------------------------------------- Adjektiv
 dict(w='đẹp', de='schoen', k='Adjektiv', rang=272),
 dict(w='xinh', de='huebsch', k='Adjektiv', rang=273),
 dict(w='xấu', de='haesslich, schlecht', k='Adjektiv', rang=274),
 dict(w='to', de='gross', k='Adjektiv', rang=275),
 dict(w='lớn', de='gross, erwachsen', k='Adjektiv', rang=276),
 dict(w='nhỏ', de='klein', k='Adjektiv', rang=277),
 dict(w='cũ', de='alt (Sache)', k='Adjektiv', rang=278),
 dict(w='già', de='alt (Person)', k='Adjektiv', rang=279,
      hin='Vietnamesisch trennt: "cu" fuer Dinge, "gia" fuer Menschen.'),
 dict(w='trẻ', de='jung', k='Adjektiv', rang=280),
 dict(w='dài', de='lang', k='Adjektiv', rang=281),
 dict(w='ngắn', de='kurz', k='Adjektiv', rang=282),
 dict(w='cao', de='hoch, gross', k='Adjektiv', rang=283),
 dict(w='thấp', de='niedrig, klein', k='Adjektiv', rang=284),
 dict(w='nóng', de='heiss', k='Adjektiv', rang=285),
 dict(w='ấm', de='warm', k='Adjektiv', rang=286),
 dict(w='lạnh', de='kalt', k='Adjektiv', rang=287),
 dict(w='dễ', de='einfach', k='Adjektiv', rang=288),
 dict(w='khó', de='schwierig', k='Adjektiv', rang=289),
 dict(w='quan trọng', de='wichtig', k='Adjektiv', rang=290),
 dict(w='sai', de='falsch', k='Adjektiv', rang=291),
 dict(w='đắt', de='teuer', k='Adjektiv', rang=292),
 dict(w='rẻ', de='billig', k='Adjektiv', rang=293),
 dict(w='miễn phí', de='kostenlos', k='Adjektiv', rang=294),
 dict(w='đầy', de='voll', k='Adjektiv', rang=295),
 dict(w='trống', de='leer, frei', k='Adjektiv', rang=296),
 dict(w='bận', de='beschaeftigt', k='Adjektiv', rang=297),
 dict(w='sẵn sàng', de='bereit', k='Adjektiv', rang=298),
 dict(w='mệt', de='muede', k='Adjektiv', rang=299),
 dict(w='ốm', de='krank', k='Adjektiv', rang=300),
 dict(w='khỏe', de='gesund, stark', k='Adjektiv', rang=301),
 dict(w='vui', de='froehlich', k='Adjektiv', rang=302),
 dict(w='buồn', de='traurig', k='Adjektiv', rang=303),
 dict(w='giận', de='wuetend', k='Adjektiv', rang=304),
 dict(w='dễ thương', de='suess, niedlich', k='Adjektiv', rang=305,
      hin='Das meistgebrauchte Kompliment unter jungen Vietnamesen - '
          'woertlich "leicht zu moegen".'),
 dict(w='tử tế', de='freundlich', k='Adjektiv', rang=306),
 dict(w='mạnh', de='stark', k='Adjektiv', rang=307),
 dict(w='yếu', de='schwach', k='Adjektiv', rang=308),
 dict(w='nặng', de='schwer', k='Adjektiv', rang=309),
 dict(w='nhẹ', de='leicht', k='Adjektiv', rang=310),
 dict(w='sạch', de='sauber', k='Adjektiv', rang=311),
 dict(w='bẩn', de='schmutzig', k='Adjektiv', rang=312),
 dict(w='tươi', de='frisch', k='Adjektiv', rang=313),
 dict(w='ngọt', de='suess (Geschmack)', k='Adjektiv', rang=314),
 dict(w='mặn', de='salzig', k='Adjektiv', rang=315),
 dict(w='cay', de='scharf', k='Adjektiv', rang=316),
 dict(w='chua', de='sauer', k='Adjektiv', rang=317),
 dict(w='ngon', de='lecker', k='Adjektiv', rang=318,
      hin='Eines der ersten Woerter, die man braucht - Essen ist in Vietnam '
          'Gespraechsthema Nummer eins.'),
 dict(w='trắng', de='weiss', k='Adjektiv', rang=319),
 dict(w='đen', de='schwarz', k='Adjektiv', rang=320),
 dict(w='đỏ', de='rot', k='Adjektiv', rang=321),
 dict(w='xanh', de='blau, gruen', k='Adjektiv', rang=322,
      hin='EIN Wort fuer blau und gruen. Wo es zaehlt, sagt man "xanh da '
          'trời" (himmelblau) oder "xanh lá cây" (blattgruen).'),
 dict(w='vàng', de='gelb, golden', k='Adjektiv', rang=323),
 dict(w='xám', de='grau', k='Adjektiv', rang=324),
 dict(w='nâu', de='braun', k='Adjektiv', rang=325),
 dict(w='mới mẻ', de='neu, frisch', k='Adjektiv', rang=326),
 dict(w='tiếp theo', de='naechster', k='Adjektiv', rang=327),
 dict(w='giống', de='gleich, aehnlich', k='Adjektiv', rang=328),
 dict(w='bình thường', de='normal, ueblich', k='Adjektiv', rang=329),
 dict(w='buồn cười', de='lustig', k='Adjektiv', rang=330),
 dict(w='chán', de='langweilig', k='Adjektiv', rang=331),
 dict(w='thú vị', de='interessant', k='Adjektiv', rang=332),
 dict(w='an toàn', de='sicher', k='Adjektiv', rang=333),
 dict(w='nguy hiểm', de='gefaehrlich', k='Adjektiv', rang=334),
 dict(w='ồn', de='laut', k='Adjektiv', rang=335),
 dict(w='yên tĩnh', de='ruhig', k='Adjektiv', rang=336),
 dict(w='đông', de='voll, ueberfuellt', k='Adjektiv', rang=337),
 dict(w='rảnh', de='frei (Zeit)', k='Adjektiv', rang=338),
 dict(w='no', de='satt', k='Adjektiv', rang=339),
 dict(w='đói', de='hungrig', k='Adjektiv', rang=340),
 dict(w='khát', de='durstig', k='Adjektiv', rang=341),
 dict(w='ngầu', de='cool', k='Adjektiv', rang=342),
 dict(w='giỏi', de='tuechtig, gut in', k='Adjektiv', rang=343),
 dict(w='thật thà', de='ehrlich', k='Adjektiv', rang=344),
 dict(w='trắng trẻo', de='hellhaeutig', k='Adjektiv', rang=345,
      hin='Helle Haut gilt in Vietnam als Schoenheitsideal - das Wort ist ein '
          'Kompliment, anders als es in Europa ankaeme.'),

# ------------------------------------------------------------------- Nomen
 dict(w='người Việt', de='Vietnamese', k='Nomen', rang=346),
 dict(w='đàn ông', de='Mann', k='Nomen', rang=347),
 dict(w='phụ nữ', de='Frau', k='Nomen', rang=348),
 dict(w='con trai', de='Junge, Sohn', k='Nomen', rang=349),
 dict(w='con gái', de='Maedchen, Tochter', k='Nomen', rang=350),
 dict(w='trẻ con', de='Kind', k='Nomen', rang=351),
 dict(w='bạn bè', de='Freunde', k='Nomen', rang=352),
 dict(w='người yêu', de='fester Freund, feste Freundin', k='Nomen', rang=353,
      hin='Geschlechtsneutral - woertlich "geliebte Person".'),
 dict(w='gia đình', de='Familie', k='Nomen', rang=354),
 dict(w='bố', de='Vater', k='Nomen', rang=355, hin='"Ba" im Sueden.'),
 dict(w='mẹ', de='Mutter', k='Nomen', rang=356, hin='"Má" im Sueden.'),
 dict(w='anh trai', de='aelterer Bruder', k='Nomen', rang=357),
 dict(w='em trai', de='juengerer Bruder', k='Nomen', rang=358),
 dict(w='chị gái', de='aeltere Schwester', k='Nomen', rang=359),
 dict(w='em gái', de='juengere Schwester', k='Nomen', rang=360,
      hin='Ein neutrales Wort fuer "Schwester" gibt es nicht - das Alter '
          'steckt im Wort.'),
 dict(w='chồng', de='Ehemann', k='Nomen', rang=361),
 dict(w='vợ', de='Ehefrau', k='Nomen', rang=362),
 dict(w='tên', de='Name', k='Nomen', rang=363),
 dict(w='tuổi', de='Alter, Jahre alt', k='Nomen', rang=364),
 dict(w='tháng', de='Monat', k='Nomen', rang=365,
      hin='Die Monate sind durchnummeriert: "tháng ba" ist der dritte Monat, '
          'also Maerz.'),
 dict(w='tuần', de='Woche', k='Nomen', rang=366),
 dict(w='ngày', de='Tag', k='Nomen', rang=367),
 dict(w='giờ', de='Stunde, Uhr', k='Nomen', rang=368),
 dict(w='tiếng', de='Stunde (Dauer), Sprache', k='Nomen', rang=369,
      hin='"Tieng" ist die Stunde als DAUER und zugleich das Wort fuer '
          'Sprache: "tieng Viet", "tieng Duc".'),
 dict(w='phút', de='Minute', k='Nomen', rang=370),
 dict(w='thời gian', de='Zeit', k='Nomen', rang=371),
 dict(w='sáng', de='Morgen', k='Nomen', rang=372),
 dict(w='trưa', de='Mittag', k='Nomen', rang=373),
 dict(w='chiều', de='Nachmittag', k='Nomen', rang=374),
 dict(w='tối', de='Abend', k='Nomen', rang=375),
 dict(w='đêm', de='Nacht', k='Nomen', rang=376),
 dict(w='cuối tuần', de='Wochenende', k='Nomen', rang=377),
 dict(w='nhà', de='Haus, Zuhause', k='Nomen', rang=378),
 dict(w='phòng', de='Zimmer', k='Nomen', rang=379),
 dict(w='cửa', de='Tuer', k='Nomen', rang=380),
 dict(w='cửa sổ', de='Fenster', k='Nomen', rang=381),
 dict(w='bàn', de='Tisch', k='Nomen', rang=382),
 dict(w='ghế', de='Stuhl', k='Nomen', rang=383),
 dict(w='giường', de='Bett', k='Nomen', rang=384),
 dict(w='bếp', de='Kueche', k='Nomen', rang=385),
 dict(w='nhà vệ sinh', de='Toilette', k='Nomen', rang=386),
 dict(w='thành phố', de='Stadt', k='Nomen', rang=387),
 dict(w='nước', de='Wasser, Land', k='Nomen', rang=388,
      hin='EIN Wort fuer beides: "nuoc Duc" ist Deutschland, "nuoc uong" '
          'Trinkwasser.'),
 dict(w='đường', de='Strasse, Zucker', k='Nomen', rang=389),
 dict(w='chỗ', de='Platz, Ort', k='Nomen', rang=390),
 dict(w='cửa hàng', de='Laden', k='Nomen', rang=391),
 dict(w='chợ', de='Markt', k='Nomen', rang=392),
 dict(w='quán', de='Garkueche, Lokal', k='Nomen', rang=393,
      hin='Der kleine Strassenstand - dort isst man am besten und '
          'billigsten.'),
 dict(w='nhà hàng', de='Restaurant', k='Nomen', rang=394),
 dict(w='khách sạn', de='Hotel', k='Nomen', rang=395),
 dict(w='bệnh viện', de='Krankenhaus', k='Nomen', rang=396),
 dict(w='nhà thuốc', de='Apotheke', k='Nomen', rang=397),
 dict(w='ga tàu', de='Bahnhof', k='Nomen', rang=398),
 dict(w='sân bay', de='Flughafen', k='Nomen', rang=399),
 dict(w='tàu', de='Zug, Schiff', k='Nomen', rang=400),
 dict(w='xe buýt', de='Bus', k='Nomen', rang=401),
 dict(w='xe máy', de='Motorroller', k='Nomen', rang=402,
      hin='Das eigentliche Verkehrsmittel Vietnams - Autos sind die '
          'Ausnahme.'),
 dict(w='ô tô', de='Auto', k='Nomen', rang=403),
 dict(w='vé', de='Fahrkarte, Ticket', k='Nomen', rang=404),
 dict(w='hành lý', de='Gepaeck', k='Nomen', rang=405),
 dict(w='hộ chiếu', de='Pass', k='Nomen', rang=406),
 dict(w='tiền', de='Geld', k='Nomen', rang=407),
 dict(w='giá', de='Preis', k='Nomen', rang=408),
 dict(w='hóa đơn', de='Rechnung', k='Nomen', rang=409),
 dict(w='thẻ', de='Karte', k='Nomen', rang=410),
 dict(w='việc', de='Arbeit, Sache', k='Nomen', rang=411),
 dict(w='trường', de='Schule', k='Nomen', rang=412),
 dict(w='đại học', de='Universitaet', k='Nomen', rang=413),
 dict(w='sinh viên', de='Student', k='Nomen', rang=414),
 dict(w='giáo viên', de='Lehrer', k='Nomen', rang=415),
 dict(w='bài', de='Lektion, Aufgabe', k='Nomen', rang=416),
 dict(w='kỳ thi', de='Pruefung', k='Nomen', rang=417),
 dict(w='sách', de='Buch', k='Nomen', rang=418),
 dict(w='chữ', de='Wort, Schriftzeichen', k='Nomen', rang=419),
 dict(w='câu', de='Satz', k='Nomen', rang=420),
 dict(w='câu hỏi', de='Frage', k='Nomen', rang=421),
 dict(w='vấn đề', de='Problem', k='Nomen', rang=422),
 dict(w='thứ', de='Ding, Sache', k='Nomen', rang=423),
 dict(w='rượu', de='Alkohol, Schnaps', k='Nomen', rang=424),
 dict(w='bia', de='Bier', k='Nomen', rang=425),
 dict(w='trà', de='Tee', k='Nomen', rang=426),
 dict(w='cà phê', de='Kaffee', k='Nomen', rang=427,
      hin='"Cà phê sữa đá" - mit gesuesster Kondensmilch und Eis - ist das '
          'Nationalgetraenk.'),
 dict(w='sữa', de='Milch', k='Nomen', rang=428),
 dict(w='bánh mì', de='Brot, Baguette-Sandwich', k='Nomen', rang=429),
 dict(w='cơm', de='Reis (gekocht), Mahlzeit', k='Nomen', rang=430),
 dict(w='phở', de='Nudelsuppe', k='Nomen', rang=431),
 dict(w='thịt', de='Fleisch', k='Nomen', rang=432),
 dict(w='cá', de='Fisch', k='Nomen', rang=433),
 dict(w='rau', de='Gemuese, Kraeuter', k='Nomen', rang=434),
 dict(w='trái cây', de='Obst', k='Nomen', rang=435),
 dict(w='muối', de='Salz', k='Nomen', rang=436),
 dict(w='nước mắm', de='Fischsauce', k='Nomen', rang=437,
      hin='Steckt in fast jedem Gericht - wichtig zu wissen, wer sich '
          'vegetarisch ernaehrt.'),
 dict(w='đồ ăn', de='Essen', k='Nomen', rang=438),
 dict(w='bữa sáng', de='Fruehstueck', k='Nomen', rang=439),
 dict(w='bữa trưa', de='Mittagessen', k='Nomen', rang=440),
 dict(w='bữa tối', de='Abendessen', k='Nomen', rang=441),
 dict(w='thực đơn', de='Speisekarte', k='Nomen', rang=442),
 dict(w='bát', de='Schuessel', k='Nomen', rang=443, hin='"Chén" im Sueden.'),
 dict(w='ly', de='Glas', k='Nomen', rang=444),
 dict(w='chai', de='Flasche', k='Nomen', rang=445),
 dict(w='đũa', de='Essstaebchen', k='Nomen', rang=446),
 dict(w='đầu', de='Kopf', k='Nomen', rang=447),
 dict(w='tay', de='Hand, Arm', k='Nomen', rang=448),
 dict(w='chân', de='Bein, Fuss', k='Nomen', rang=449),
 dict(w='mắt', de='Auge', k='Nomen', rang=450),
 dict(w='miệng', de='Mund', k='Nomen', rang=451),
 dict(w='tóc', de='Haare', k='Nomen', rang=452),
 dict(w='da', de='Haut', k='Nomen', rang=453),
 dict(w='người bệnh', de='Patient', k='Nomen', rang=454),
 dict(w='bác sĩ', de='Arzt', k='Nomen', rang=455),
 dict(w='thuốc', de='Medikament', k='Nomen', rang=456),
 dict(w='điện thoại', de='Telefon, Handy', k='Nomen', rang=457),
 dict(w='số', de='Nummer, Zahl', k='Nomen', rang=458),
 dict(w='nhạc', de='Musik', k='Nomen', rang=459),
 dict(w='phim', de='Film', k='Nomen', rang=460),
 dict(w='tiệc', de='Party, Fest', k='Nomen', rang=461),
 dict(w='cuộc sống', de='Leben', k='Nomen', rang=462),
 dict(w='thế giới', de='Welt', k='Nomen', rang=463),
 dict(w='mặt trời', de='Sonne', k='Nomen', rang=464),
 dict(w='mưa', de='Regen', k='Nomen', rang=465),
 dict(w='thời tiết', de='Wetter', k='Nomen', rang=466),
 dict(w='biển', de='Meer', k='Nomen', rang=467),
 dict(w='núi', de='Berg', k='Nomen', rang=468),
 dict(w='rừng', de='Wald', k='Nomen', rang=469),
 dict(w='chó', de='Hund', k='Nomen', rang=470),
 dict(w='mèo', de='Katze', k='Nomen', rang=471),
 dict(w='quần áo', de='Kleidung', k='Nomen', rang=472),
 dict(w='áo', de='Oberteil, Hemd', k='Nomen', rang=473),
 dict(w='giày', de='Schuh', k='Nomen', rang=474),
 dict(w='túi', de='Tasche, Tuete', k='Nomen', rang=475),
 dict(w='chìa khóa', de='Schluessel', k='Nomen', rang=476),
 dict(w='quà', de='Geschenk', k='Nomen', rang=477),
 dict(w='tình yêu', de='Liebe', k='Nomen', rang=478),
 dict(w='phần', de='Teil, Portion', k='Nomen', rang=479),
 dict(w='lý do', de='Grund', k='Nomen', rang=480),
 dict(w='ví dụ', de='Beispiel', k='Nomen', rang=481),
 dict(w='ý tưởng', de='Idee', k='Nomen', rang=482),
 dict(w='chuyện', de='Geschichte, Angelegenheit', k='Nomen', rang=483),
 dict(w='công an', de='Polizei', k='Nomen', rang=484),
 dict(w='ca', de='Schicht', k='Nomen', rang=485),
 dict(w='đồng nghiệp', de='Kollege', k='Nomen', rang=486),
 dict(w='khách', de='Kunde, Gast', k='Nomen', rang=487),
 dict(w='lương', de='Lohn', k='Nomen', rang=488),
 dict(w='hợp đồng', de='Vertrag', k='Nomen', rang=489),
 dict(w='giấy', de='Papier, Dokument', k='Nomen', rang=490),
 dict(w='đá', de='Eis, Stein', k='Nomen', rang=491),
 dict(w='lửa', de='Feuer', k='Nomen', rang=492),
 dict(w='gió', de='Wind', k='Nomen', rang=493),
 dict(w='xe ôm', de='Motorradtaxi', k='Nomen', rang=494),
 dict(w='cầu', de='Bruecke', k='Nomen', rang=495),
 dict(w='ngã tư', de='Kreuzung', k='Nomen', rang=496,
      hin='Woertlich "Vier-Wege" - die Zahl steckt im Wort, "ngã ba" ist die '
          'Dreier-Gabelung.'),
 dict(w='bản đồ', de='Landkarte', k='Nomen', rang=497),
 dict(w='chuyến bay', de='Flug', k='Nomen', rang=498),
 dict(w='hàng xóm', de='Nachbar', k='Nomen', rang=499),
 dict(w='sở thích', de='Hobby', k='Nomen', rang=500),
]
