# -*- coding: utf-8 -*-
"""Die 500 haeufigsten norwegischen Woerter (Bokmaal).

**Eigenstaendige Liste, KEINE Uebersetzung** - dieselbe Begruendung wie bei
`vokabeln_it.py`: Haeufigkeitslisten sind sprachgebunden, die 500
haeufigsten norwegischen Woerter sind nicht die Uebersetzungen der 500
haeufigsten deutschen.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen. Welche Woerter dazugehoeren, ist
belastbar; die genaue Rangfolge innerhalb eines Zehnerblocks nicht.

**BOKMAAL, nicht Nynorsk** - siehe Migration 20260903120000.

**Drei Genera, aber das weibliche ist optional.** Bokmaal laesst fuer fast
jedes weibliche Nomen auch die maennliche Form zu: `ei bok` und `en bok`
sind beide richtig, und viele Norweger (besonders in Oslo) nehmen
durchgehend `en`. Wo `g='f'` steht, ist die weibliche Form die
gebraeuchlichere; wer sie nicht benutzt, macht trotzdem nichts falsch. Das
ist der Grund, warum Genus hier weniger schwer wiegt als im Italienischen.

**Verben stehen im blossen Infinitiv, ohne `aa`** - `snakke`, nicht
`aa snakke`. Das entspricht der Nennform im Woerterbuch.

**Der bestimmte Artikel haengt hinten an** (`bok` -> `boka`, `hus` ->
`huset`). Deshalb stehen unter Artikel nur die unbestimmten und die
hinweisenden Formen; die angehaengten sind keine eigenen Woerter.
"""

WOERTER = [

# ---------------------------------------------------------------- Artikel
 dict(w='en', de='ein (maennlich)', k='Artikel', rang=1),
 dict(w='ei', de='eine (weiblich)', k='Artikel', rang=2),
 dict(w='et', de='ein (saechlich)', k='Artikel', rang=3),
 dict(w='den', de='der, die', k='Artikel', rang=4),
 dict(w='det', de='das', k='Artikel', rang=5),
 dict(w='de', de='die (Mehrzahl)', k='Artikel', rang=6),
 dict(w='denne', de='dieser', k='Artikel', rang=7),
 dict(w='dette', de='dieses', k='Artikel', rang=8),

# --------------------------------------------------------------- Pronomen
 dict(w='jeg', de='ich', k='Pronomen', rang=9),
 dict(w='du', de='du', k='Pronomen', rang=10),
 dict(w='han', de='er', k='Pronomen', rang=11),
 dict(w='hun', de='sie', k='Pronomen', rang=12),
 dict(w='vi', de='wir', k='Pronomen', rang=13),
 dict(w='dere', de='ihr', k='Pronomen', rang=14),
 dict(w='meg', de='mir, mich', k='Pronomen', rang=15),
 dict(w='deg', de='dir, dich', k='Pronomen', rang=16),
 dict(w='ham', de='ihm, ihn', k='Pronomen', rang=17),
 dict(w='henne', de='ihr, sie', k='Pronomen', rang=18),
 dict(w='oss', de='uns', k='Pronomen', rang=19),
 dict(w='seg', de='sich', k='Pronomen', rang=20),
 dict(w='min', de='mein', k='Pronomen', rang=21),
 dict(w='din', de='dein', k='Pronomen', rang=22),
 dict(w='hans', de='sein', k='Pronomen', rang=23),
 dict(w='hennes', de='ihr', k='Pronomen', rang=24),
 dict(w='vår', de='unser', k='Pronomen', rang=25),
 dict(w='deres', de='euer, ihr', k='Pronomen', rang=26),
 dict(w='som', de='der, die, das', k='Pronomen', rang=27),
 dict(w='alle', de='alle', k='Pronomen', rang=28),
 dict(w='alt', de='alles', k='Pronomen', rang=29),
 dict(w='noe', de='etwas', k='Pronomen', rang=30),
 dict(w='noen', de='jemand, einige', k='Pronomen', rang=31),
 dict(w='ingen', de='niemand', k='Pronomen', rang=32),
 dict(w='ingenting', de='nichts', k='Pronomen', rang=33),
 dict(w='man', de='man', k='Pronomen', rang=34),
 dict(w='andre', de='andere', k='Pronomen', rang=35),
 dict(w='samme', de='selbe', k='Pronomen', rang=36),
 dict(w='hverandre', de='einander', k='Pronomen', rang=37),
 dict(w='begge', de='beide', k='Pronomen', rang=38),
 dict(w='hver', de='jeder', k='Pronomen', rang=39),
 dict(w='selv', de='selbst', k='Pronomen', rang=40),

# -------------------------------------------------------------- Fragewort
 dict(w='hva', de='was', k='Fragewort', rang=41),
 dict(w='hvor', de='wo', k='Fragewort', rang=42),
 dict(w='når', de='wann', k='Fragewort', rang=43),
 dict(w='hvordan', de='wie', k='Fragewort', rang=44),
 dict(w='hvorfor', de='warum', k='Fragewort', rang=45),
 dict(w='hvem', de='wer', k='Fragewort', rang=46),
 dict(w='hvilken', de='welcher', k='Fragewort', rang=47),
 dict(w='hvor mye', de='wie viel', k='Fragewort', rang=48),
 dict(w='hvor mange', de='wie viele', k='Fragewort', rang=49),

# ------------------------------------------------------------ Konjunktion
 dict(w='og', de='und', k='Konjunktion', rang=50),
 dict(w='eller', de='oder', k='Konjunktion', rang=51),
 dict(w='men', de='aber', k='Konjunktion', rang=52),
 dict(w='hvis', de='wenn, falls', k='Konjunktion', rang=53),
 dict(w='at', de='dass', k='Konjunktion', rang=54),
 dict(w='fordi', de='weil', k='Konjunktion', rang=55),
 dict(w='så', de='so, also', k='Konjunktion', rang=56),
 dict(w='da', de='als, da', k='Konjunktion', rang=57),
 dict(w='mens', de='waehrend', k='Konjunktion', rang=58),
 dict(w='enn', de='als (Vergleich)', k='Konjunktion', rang=59),
 dict(w='selv om', de='obwohl', k='Konjunktion', rang=60),
 dict(w='derfor', de='deshalb', k='Konjunktion', rang=61),
 dict(w='likevel', de='trotzdem', k='Konjunktion', rang=62),
 dict(w='samt', de='sowie', k='Konjunktion', rang=63),

# ----------------------------------------------------------- Praeposition
 dict(w='i', de='in', k='Praeposition', rang=64),
 dict(w='på', de='auf', k='Praeposition', rang=65),
 dict(w='til', de='zu, nach', k='Praeposition', rang=66),
 dict(w='av', de='von', k='Praeposition', rang=67),
 dict(w='med', de='mit', k='Praeposition', rang=68),
 dict(w='for', de='fuer', k='Praeposition', rang=69),
 dict(w='fra', de='von, aus', k='Praeposition', rang=70),
 dict(w='om', de='ueber, um', k='Praeposition', rang=71),
 dict(w='ved', de='bei, an', k='Praeposition', rang=72),
 dict(w='etter', de='nach', k='Praeposition', rang=73),
 dict(w='under', de='unter', k='Praeposition', rang=74),
 dict(w='over', de='ueber', k='Praeposition', rang=75),
 dict(w='mellom', de='zwischen', k='Praeposition', rang=76),
 dict(w='uten', de='ohne', k='Praeposition', rang=77),
 dict(w='mot', de='gegen, Richtung', k='Praeposition', rang=78),
 dict(w='foran', de='vor', k='Praeposition', rang=79),
 dict(w='bak', de='hinter', k='Praeposition', rang=80),
 dict(w='hos', de='bei (jemandem)', k='Praeposition', rang=81),
 dict(w='rundt', de='um herum', k='Praeposition', rang=82),
 dict(w='gjennom', de='durch', k='Praeposition', rang=83),
 dict(w='langs', de='entlang', k='Praeposition', rang=84),
 dict(w='siden', de='seit', k='Praeposition', rang=85),
 dict(w='inntil', de='bis', k='Praeposition', rang=86),

# ----------------------------------------------------------------- Adverb
 dict(w='ikke', de='nicht', k='Adverb', rang=87),
 dict(w='ja', de='ja', k='Adverb', rang=88),
 dict(w='nei', de='nein', k='Adverb', rang=89),
 dict(w='jo', de='doch', k='Adverb', rang=90,
      hin='Antwort auf eine verneinte Frage - wie das deutsche doch.'),
 dict(w='mer', de='mehr', k='Adverb', rang=91),
 dict(w='mindre', de='weniger', k='Adverb', rang=92),
 dict(w='veldig', de='sehr', k='Adverb', rang=93),
 dict(w='mye', de='viel', k='Adverb', rang=94),
 dict(w='litt', de='ein bisschen', k='Adverb', rang=95),
 dict(w='bra', de='gut', k='Adverb', rang=96),
 dict(w='her', de='hier', k='Adverb', rang=97),
 dict(w='der', de='dort', k='Adverb', rang=98),
 dict(w='nå', de='jetzt', k='Adverb', rang=99),
 dict(w='i dag', de='heute', k='Adverb', rang=100),
 dict(w='i går', de='gestern', k='Adverb', rang=101),
 dict(w='i morgen', de='morgen', k='Adverb', rang=102),
 dict(w='alltid', de='immer', k='Adverb', rang=103),
 dict(w='aldri', de='nie', k='Adverb', rang=104),
 dict(w='ofte', de='oft', k='Adverb', rang=105),
 dict(w='sjelden', de='selten', k='Adverb', rang=106),
 dict(w='snart', de='bald', k='Adverb', rang=107),
 dict(w='ennå', de='noch', k='Adverb', rang=108),
 dict(w='allerede', de='schon', k='Adverb', rang=109),
 dict(w='tidlig', de='frueh', k='Adverb', rang=110),
 dict(w='sent', de='spaet', k='Adverb', rang=111),
 dict(w='sammen', de='zusammen', k='Adverb', rang=112),
 dict(w='bare', de='nur', k='Adverb', rang=113),
 dict(w='kanskje', de='vielleicht', k='Adverb', rang=114),
 dict(w='virkelig', de='wirklich', k='Adverb', rang=115),
 dict(w='slik', de='so', k='Adverb', rang=116),
 dict(w='nok', de='genug', k='Adverb', rang=117),
 dict(w='nesten', de='fast', k='Adverb', rang=118),
 dict(w='akkurat', de='genau', k='Adverb', rang=119),
 dict(w='sikkert', de='sicher', k='Adverb', rang=120),
 dict(w='gjerne', de='gerne', k='Adverb', rang=121),
 dict(w='dessverre', de='leider', k='Adverb', rang=122),
 dict(w='sakte', de='langsam', k='Adverb', rang=123),
 dict(w='fort', de='schnell', k='Adverb', rang=124),
 dict(w='igjen', de='wieder', k='Adverb', rang=125),
 dict(w='ute', de='draussen', k='Adverb', rang=126),
 dict(w='inne', de='drinnen', k='Adverb', rang=127),
 dict(w='hjemme', de='zu Hause', k='Adverb', rang=128),
 dict(w='hjem', de='nach Hause', k='Adverb', rang=129),
 dict(w='også', de='auch', k='Adverb', rang=130),
 dict(w='kun', de='bloss', k='Adverb', rang=131),
 dict(w='straks', de='sofort', k='Adverb', rang=132),
 dict(w='endelig', de='endlich', k='Adverb', rang=133),

# --------------------------------------------------------------- Zahlwort
 dict(w='null', de='null', k='Zahlwort', rang=134),
 dict(w='en gang', de='einmal', k='Zahlwort', rang=135),
 dict(w='to', de='zwei', k='Zahlwort', rang=136),
 dict(w='tre', de='drei', k='Zahlwort', rang=137),
 dict(w='fire', de='vier', k='Zahlwort', rang=138),
 dict(w='fem', de='fuenf', k='Zahlwort', rang=139),
 dict(w='seks', de='sechs', k='Zahlwort', rang=140),
 dict(w='sju', de='sieben', k='Zahlwort', rang=141),
 dict(w='åtte', de='acht', k='Zahlwort', rang=142),
 dict(w='ni', de='neun', k='Zahlwort', rang=143),
 dict(w='ti', de='zehn', k='Zahlwort', rang=144),
 dict(w='elleve', de='elf', k='Zahlwort', rang=145),
 dict(w='tolv', de='zwoelf', k='Zahlwort', rang=146),
 dict(w='tretten', de='dreizehn', k='Zahlwort', rang=147),
 dict(w='fjorten', de='vierzehn', k='Zahlwort', rang=148),
 dict(w='femten', de='fuenfzehn', k='Zahlwort', rang=149),
 dict(w='seksten', de='sechzehn', k='Zahlwort', rang=150),
 dict(w='sytten', de='siebzehn', k='Zahlwort', rang=151),
 dict(w='atten', de='achtzehn', k='Zahlwort', rang=152),
 dict(w='nitten', de='neunzehn', k='Zahlwort', rang=153),
 dict(w='tjue', de='zwanzig', k='Zahlwort', rang=154),
 dict(w='tretti', de='dreissig', k='Zahlwort', rang=155),
 dict(w='førti', de='vierzig', k='Zahlwort', rang=156),
 dict(w='femti', de='fuenfzig', k='Zahlwort', rang=157),
 dict(w='seksti', de='sechzig', k='Zahlwort', rang=158),
 dict(w='sytti', de='siebzig', k='Zahlwort', rang=159),
 dict(w='åtti', de='achtzig', k='Zahlwort', rang=160),
 dict(w='nitti', de='neunzig', k='Zahlwort', rang=161),
 dict(w='hundre', de='hundert', k='Zahlwort', rang=162),
 dict(w='tusen', de='tausend', k='Zahlwort', rang=163),
 dict(w='første', de='erster', k='Zahlwort', rang=164),
 dict(w='annen', de='zweiter', k='Zahlwort', rang=165),
 dict(w='tredje', de='dritter', k='Zahlwort', rang=166),
 dict(w='siste', de='letzter', k='Zahlwort', rang=167),
 dict(w='halv', de='halb', k='Zahlwort', rang=168),
 dict(w='dobbel', de='doppelt', k='Zahlwort', rang=169),
 dict(w='par', de='Paar', k='Zahlwort', rang=170),
 dict(w='million', de='Million', k='Zahlwort', rang=171),

# -------------------------------------------------------------------- Verb
 dict(w='være', de='sein', k='Verb', rang=172),
 dict(w='ha', de='haben', k='Verb', rang=173),
 dict(w='bli', de='werden, bleiben', k='Verb', rang=174),
 dict(w='gjøre', de='machen, tun', k='Verb', rang=175),
 dict(w='si', de='sagen', k='Verb', rang=176),
 dict(w='kunne', de='koennen', k='Verb', rang=177),
 dict(w='ville', de='wollen', k='Verb', rang=178),
 dict(w='måtte', de='muessen', k='Verb', rang=179),
 dict(w='skulle', de='sollen, werden', k='Verb', rang=180),
 dict(w='vite', de='wissen', k='Verb', rang=181),
 dict(w='gå', de='gehen', k='Verb', rang=182),
 dict(w='komme', de='kommen', k='Verb', rang=183),
 dict(w='se', de='sehen', k='Verb', rang=184),
 dict(w='gi', de='geben', k='Verb', rang=185),
 dict(w='ta', de='nehmen', k='Verb', rang=186),
 dict(w='snakke', de='sprechen', k='Verb', rang=187),
 dict(w='finne', de='finden', k='Verb', rang=188),
 dict(w='høre', de='hoeren', k='Verb', rang=189),
 dict(w='legge', de='legen', k='Verb', rang=190),
 dict(w='sette', de='setzen', k='Verb', rang=191),
 dict(w='tenke', de='denken', k='Verb', rang=192),
 dict(w='tro', de='glauben', k='Verb', rang=193),
 dict(w='forstå', de='verstehen', k='Verb', rang=194),
 dict(w='spørre', de='fragen', k='Verb', rang=195),
 dict(w='svare', de='antworten', k='Verb', rang=196),
 dict(w='hete', de='heissen', k='Verb', rang=197),
 dict(w='jobbe', de='arbeiten', k='Verb', rang=198),
 dict(w='spise', de='essen', k='Verb', rang=199),
 dict(w='drikke', de='trinken', k='Verb', rang=200),
 dict(w='sove', de='schlafen', k='Verb', rang=201),
 dict(w='leve', de='leben', k='Verb', rang=202),
 dict(w='bo', de='wohnen', k='Verb', rang=203),
 dict(w='kjøpe', de='kaufen', k='Verb', rang=204),
 dict(w='betale', de='bezahlen', k='Verb', rang=205),
 dict(w='koste', de='kosten', k='Verb', rang=206),
 dict(w='åpne', de='oeffnen', k='Verb', rang=207),
 dict(w='stenge', de='schliessen', k='Verb', rang=208),
 dict(w='reise', de='reisen, abfahren', k='Verb', rang=209),
 dict(w='ankomme', de='ankommen', k='Verb', rang=210),
 dict(w='dra', de='fahren, ziehen', k='Verb', rang=211),
 dict(w='vente', de='warten', k='Verb', rang=212),
 dict(w='lete', de='suchen', k='Verb', rang=213),
 dict(w='bringe', de='bringen', k='Verb', rang=214),
 dict(w='bruke', de='benutzen', k='Verb', rang=215),
 dict(w='hjelpe', de='helfen', k='Verb', rang=216),
 dict(w='like', de='moegen', k='Verb', rang=217),
 dict(w='elske', de='lieben', k='Verb', rang=218),
 dict(w='kjenne', de='kennen', k='Verb', rang=219),
 dict(w='studere', de='studieren', k='Verb', rang=220),
 dict(w='lære', de='lernen', k='Verb', rang=221),
 dict(w='undervise', de='unterrichten', k='Verb', rang=222),
 dict(w='lese', de='lesen, lernen', k='Verb', rang=223,
      hin='Heisst auch pauken: aa lese til eksamen ist fuer die Pruefung lernen.'),
 dict(w='skrive', de='schreiben', k='Verb', rang=224),
 dict(w='huske', de='sich erinnern', k='Verb', rang=225),
 dict(w='glemme', de='vergessen', k='Verb', rang=226),
 dict(w='begynne', de='anfangen', k='Verb', rang=227),
 dict(w='slutte', de='aufhoeren', k='Verb', rang=228),
 dict(w='fortsette', de='fortsetzen', k='Verb', rang=229),
 dict(w='prøve', de='versuchen', k='Verb', rang=230),
 dict(w='klare', de='schaffen', k='Verb', rang=231),
 dict(w='miste', de='verlieren', k='Verb', rang=232),
 dict(w='vinne', de='gewinnen', k='Verb', rang=233),
 dict(w='spille', de='spielen', k='Verb', rang=234),
 dict(w='synge', de='singen', k='Verb', rang=235),
 dict(w='danse', de='tanzen', k='Verb', rang=236),
 dict(w='løpe', de='rennen', k='Verb', rang=237),
 dict(w='kjøre', de='fahren', k='Verb', rang=238),
 dict(w='besøke', de='besuchen', k='Verb', rang=239),
 dict(w='møte', de='treffen', k='Verb', rang=240),
 dict(w='gifte', de='heiraten', k='Verb', rang=241),
 dict(w='fødes', de='geboren werden', k='Verb', rang=242),
 dict(w='dø', de='sterben', k='Verb', rang=243),
 dict(w='endre', de='aendern', k='Verb', rang=244),
 dict(w='bytte', de='tauschen, wechseln', k='Verb', rang=245),
 dict(w='virke', de='wirken, funktionieren', k='Verb', rang=246),
 dict(w='skje', de='geschehen', k='Verb', rang=247),
 dict(w='trenge', de='brauchen', k='Verb', rang=248),
 dict(w='håpe', de='hoffen', k='Verb', rang=249),
 dict(w='bestille', de='bestellen, reservieren', k='Verb', rang=250),
 dict(w='leie', de='mieten', k='Verb', rang=251),
 dict(w='signere', de='unterschreiben', k='Verb', rang=252),
 dict(w='vaske', de='waschen', k='Verb', rang=253),
 dict(w='lage', de='machen, kochen', k='Verb', rang=254),
 dict(w='rydde', de='aufraeumen', k='Verb', rang=255),
 dict(w='le', de='lachen', k='Verb', rang=256),
 dict(w='gråte', de='weinen', k='Verb', rang=257),
 dict(w='beklage', de='bedauern', k='Verb', rang=258),
 dict(w='takke', de='danken', k='Verb', rang=259),
 dict(w='hilse', de='gruessen', k='Verb', rang=260),
 dict(w='ringe', de='anrufen', k='Verb', rang=261),
 dict(w='vise', de='zeigen', k='Verb', rang=262),
 dict(w='fortelle', de='erzaehlen', k='Verb', rang=263),
 dict(w='få', de='bekommen', k='Verb', rang=264),
 dict(w='holde', de='halten', k='Verb', rang=265),
 dict(w='stoppe', de='anhalten', k='Verb', rang=266),
 dict(w='følge', de='folgen, begleiten', k='Verb', rang=267),
 dict(w='flytte', de='umziehen', k='Verb', rang=268),
 dict(w='sitte', de='sitzen', k='Verb', rang=269),
 dict(w='stå', de='stehen', k='Verb', rang=270),

# ---------------------------------------------------------------- Adjektiv
 dict(w='god', de='gut', k='Adjektiv', rang=271),
 dict(w='dårlig', de='schlecht', k='Adjektiv', rang=272),
 dict(w='stor', de='gross', k='Adjektiv', rang=273),
 dict(w='liten', de='klein', k='Adjektiv', rang=274),
 dict(w='ny', de='neu', k='Adjektiv', rang=275),
 dict(w='gammel', de='alt', k='Adjektiv', rang=276),
 dict(w='ung', de='jung', k='Adjektiv', rang=277),
 dict(w='pen', de='schoen, huebsch', k='Adjektiv', rang=278),
 dict(w='stygg', de='haesslich', k='Adjektiv', rang=279),
 dict(w='lang', de='lang', k='Adjektiv', rang=280),
 dict(w='kort', de='kurz', k='Adjektiv', rang=281,
      hin='Als Nomen (et kort) heisst es Karte - betale med kort.'),
 dict(w='høy', de='hoch, laut', k='Adjektiv', rang=282),
 dict(w='lav', de='niedrig', k='Adjektiv', rang=283),
 dict(w='varm', de='warm', k='Adjektiv', rang=284),
 dict(w='kald', de='kalt', k='Adjektiv', rang=285),
 dict(w='lett', de='leicht, einfach', k='Adjektiv', rang=286),
 dict(w='vanskelig', de='schwierig', k='Adjektiv', rang=287),
 dict(w='viktig', de='wichtig', k='Adjektiv', rang=288),
 dict(w='mulig', de='moeglich', k='Adjektiv', rang=289),
 dict(w='sann', de='wahr', k='Adjektiv', rang=290),
 dict(w='feil', de='falsch', k='Adjektiv', rang=291),
 dict(w='riktig', de='richtig', k='Adjektiv', rang=292),
 dict(w='dyr', de='teuer', k='Adjektiv', rang=293),
 dict(w='billig', de='billig', k='Adjektiv', rang=294),
 dict(w='gratis', de='kostenlos', k='Adjektiv', rang=295),
 dict(w='full', de='voll', k='Adjektiv', rang=296),
 dict(w='tom', de='leer', k='Adjektiv', rang=297),
 dict(w='åpen', de='offen', k='Adjektiv', rang=298),
 dict(w='stengt', de='geschlossen', k='Adjektiv', rang=299),
 dict(w='ledig', de='frei', k='Adjektiv', rang=300),
 dict(w='opptatt', de='besetzt, beschaeftigt', k='Adjektiv', rang=301),
 dict(w='klar', de='bereit, klar', k='Adjektiv', rang=302),
 dict(w='trøtt', de='muede', k='Adjektiv', rang=303),
 dict(w='syk', de='krank', k='Adjektiv', rang=304),
 dict(w='frisk', de='gesund', k='Adjektiv', rang=305),
 dict(w='glad', de='froh', k='Adjektiv', rang=306),
 dict(w='lei', de='traurig, ueberdruessig', k='Adjektiv', rang=307),
 dict(w='fornøyd', de='zufrieden', k='Adjektiv', rang=308),
 dict(w='sint', de='wuetend', k='Adjektiv', rang=309),
 dict(w='hyggelig', de='nett, angenehm', k='Adjektiv', rang=310,
      hin='Das norwegische Allzweckwort fuer nett - Person, Abend, Gespraech.'),
 dict(w='snill', de='lieb, freundlich', k='Adjektiv', rang=311),
 dict(w='flink', de='tuechtig', k='Adjektiv', rang=312),
 dict(w='sterk', de='stark, scharf', k='Adjektiv', rang=313,
      hin='Beim Essen heisst sterk immer scharf, nicht stark.'),
 dict(w='svak', de='schwach', k='Adjektiv', rang=314),
 dict(w='rask', de='schnell', k='Adjektiv', rang=315),
 dict(w='treg', de='langsam, traege', k='Adjektiv', rang=316),
 dict(w='tung', de='schwer', k='Adjektiv', rang=317),
 dict(w='ren', de='sauber', k='Adjektiv', rang=318),
 dict(w='skitten', de='schmutzig', k='Adjektiv', rang=319),
 dict(w='fersk', de='frisch', k='Adjektiv', rang=320),
 dict(w='søt', de='suess', k='Adjektiv', rang=321),
 dict(w='salt', de='salzig', k='Adjektiv', rang=322),
 dict(w='hvit', de='weiss', k='Adjektiv', rang=323),
 dict(w='svart', de='schwarz', k='Adjektiv', rang=324),
 dict(w='rød', de='rot', k='Adjektiv', rang=325),
 dict(w='blå', de='blau', k='Adjektiv', rang=326),
 dict(w='grønn', de='gruen', k='Adjektiv', rang=327),
 dict(w='gul', de='gelb', k='Adjektiv', rang=328),
 dict(w='grå', de='grau', k='Adjektiv', rang=329),
 dict(w='brun', de='braun', k='Adjektiv', rang=330),
 dict(w='norsk', de='norwegisch', k='Adjektiv', rang=331),
 dict(w='tysk', de='deutsch', k='Adjektiv', rang=332),
 dict(w='engelsk', de='englisch', k='Adjektiv', rang=333),
 dict(w='utenlandsk', de='auslaendisch', k='Adjektiv', rang=334),
 dict(w='neste', de='naechster', k='Adjektiv', rang=335),
 dict(w='forrige', de='letzter, voriger', k='Adjektiv', rang=336),
 dict(w='vanlig', de='ueblich, normal', k='Adjektiv', rang=337),
 dict(w='morsom', de='lustig', k='Adjektiv', rang=338),
 dict(w='kjedelig', de='langweilig', k='Adjektiv', rang=339),
 dict(w='interessant', de='interessant', k='Adjektiv', rang=340),
 dict(w='sikker', de='sicher', k='Adjektiv', rang=341),
 dict(w='farlig', de='gefaehrlich', k='Adjektiv', rang=342),
 dict(w='nødvendig', de='noetig', k='Adjektiv', rang=343),

# ------------------------------------------------------------------- Nomen
 dict(w='mann', de='Mann', k='Nomen', g='m', rang=344),
 dict(w='kvinne', de='Frau', k='Nomen', g='f', rang=345),
 dict(w='gutt', de='Junge', k='Nomen', g='m', rang=346),
 dict(w='jente', de='Maedchen', k='Nomen', g='f', rang=347),
 dict(w='barn', de='Kind', k='Nomen', g='n', rang=348),
 dict(w='menneske', de='Mensch', k='Nomen', g='n', rang=349),
 dict(w='folk', de='Leute, Volk', k='Nomen', g='n', rang=350),
 dict(w='venn', de='Freund', k='Nomen', g='m', rang=351),
 dict(w='kjæreste', de='fester Freund, feste Freundin', k='Nomen', g='m', rang=352,
      hin='Geschlechtsneutral - ein Wort fuer beides, anders als im Deutschen.'),
 dict(w='familie', de='Familie', k='Nomen', g='m', rang=353),
 dict(w='far', de='Vater', k='Nomen', g='m', rang=354),
 dict(w='mor', de='Mutter', k='Nomen', g='f', rang=355),
 dict(w='sønn', de='Sohn', k='Nomen', g='m', rang=356),
 dict(w='datter', de='Tochter', k='Nomen', g='f', rang=357),
 dict(w='bror', de='Bruder', k='Nomen', g='m', rang=358),
 dict(w='søster', de='Schwester', k='Nomen', g='f', rang=359),
 dict(w='søsken', de='Geschwister', k='Nomen', g='n', rang=360),
 dict(w='navn', de='Name', k='Nomen', g='n', rang=361),
 dict(w='år', de='Jahr', k='Nomen', g='n', rang=362),
 dict(w='måned', de='Monat', k='Nomen', g='m', rang=363),
 dict(w='uke', de='Woche', k='Nomen', g='f', rang=364),
 dict(w='dag', de='Tag', k='Nomen', g='m', rang=365),
 dict(w='time', de='Stunde, Termin', k='Nomen', g='m', rang=366,
      hin='Auch der Arzttermin: aa bestille time heisst einen Termin machen.'),
 dict(w='minutt', de='Minute', k='Nomen', g='n', rang=367),
 dict(w='tid', de='Zeit', k='Nomen', g='f', rang=368),
 dict(w='morgen', de='Morgen', k='Nomen', g='m', rang=369),
 dict(w='ettermiddag', de='Nachmittag', k='Nomen', g='m', rang=370),
 dict(w='kveld', de='Abend', k='Nomen', g='m', rang=371),
 dict(w='natt', de='Nacht', k='Nomen', g='f', rang=372),
 dict(w='helg', de='Wochenende', k='Nomen', g='f', rang=373),
 dict(w='hus', de='Haus', k='Nomen', g='n', rang=374),
 dict(w='leilighet', de='Wohnung', k='Nomen', g='f', rang=375),
 dict(w='rom', de='Zimmer', k='Nomen', g='n', rang=376),
 dict(w='dør', de='Tuer', k='Nomen', g='f', rang=377),
 dict(w='vindu', de='Fenster', k='Nomen', g='n', rang=378),
 dict(w='bord', de='Tisch', k='Nomen', g='n', rang=379),
 dict(w='seng', de='Bett', k='Nomen', g='f', rang=380),
 dict(w='kjøkken', de='Kueche', k='Nomen', g='n', rang=381),
 dict(w='toalett', de='Toilette', k='Nomen', g='n', rang=382),
 dict(w='by', de='Stadt', k='Nomen', g='m', rang=383),
 dict(w='land', de='Land', k='Nomen', g='n', rang=384),
 dict(w='gate', de='Strasse', k='Nomen', g='f', rang=385),
 dict(w='vei', de='Weg', k='Nomen', g='m', rang=386),
 dict(w='plass', de='Platz', k='Nomen', g='m', rang=387),
 dict(w='sted', de='Ort', k='Nomen', g='n', rang=388),
 dict(w='butikk', de='Laden, Geschaeft', k='Nomen', g='m', rang=389),
 dict(w='restaurant', de='Restaurant', k='Nomen', g='m', rang=390),
 dict(w='hotell', de='Hotel', k='Nomen', g='n', rang=391),
 dict(w='sykehus', de='Krankenhaus', k='Nomen', g='n', rang=392),
 dict(w='apotek', de='Apotheke', k='Nomen', g='n', rang=393),
 dict(w='stasjon', de='Bahnhof', k='Nomen', g='m', rang=394),
 dict(w='flyplass', de='Flughafen', k='Nomen', g='m', rang=395),
 dict(w='tog', de='Zug', k='Nomen', g='n', rang=396),
 dict(w='buss', de='Bus', k='Nomen', g='m', rang=397),
 dict(w='bil', de='Auto', k='Nomen', g='m', rang=398),
 dict(w='billett', de='Fahrkarte', k='Nomen', g='m', rang=399),
 dict(w='bagasje', de='Gepaeck', k='Nomen', g='m', rang=400),
 dict(w='pass', de='Pass', k='Nomen', g='n', rang=401),
 dict(w='penger', de='Geld', k='Nomen', g='m', rang=402),
 dict(w='pris', de='Preis', k='Nomen', g='m', rang=403),
 dict(w='regning', de='Rechnung', k='Nomen', g='f', rang=404),
 dict(w='bankkort', de='Bankkarte', k='Nomen', g='n', rang=405),
 dict(w='jobb', de='Arbeit, Job', k='Nomen', g='m', rang=406),
 dict(w='skole', de='Schule', k='Nomen', g='m', rang=407),
 dict(w='universitet', de='Universitaet', k='Nomen', g='n', rang=408),
 dict(w='student', de='Student', k='Nomen', g='m', rang=409),
 dict(w='forelesning', de='Vorlesung', k='Nomen', g='f', rang=410),
 dict(w='eksamen', de='Pruefung', k='Nomen', g='m', rang=411),
 dict(w='bok', de='Buch', k='Nomen', g='f', rang=412),
 dict(w='ord', de='Wort', k='Nomen', g='n', rang=413),
 dict(w='språk', de='Sprache', k='Nomen', g='n', rang=414),
 dict(w='spørsmål', de='Frage', k='Nomen', g='n', rang=415),
 dict(w='svar', de='Antwort', k='Nomen', g='n', rang=416),
 dict(w='problem', de='Problem', k='Nomen', g='n', rang=417),
 dict(w='ting', de='Ding, Sache', k='Nomen', g='m', rang=418),
 dict(w='vann', de='Wasser', k='Nomen', g='n', rang=419),
 dict(w='vin', de='Wein', k='Nomen', g='m', rang=420),
 dict(w='øl', de='Bier', k='Nomen', g='n', rang=421),
 dict(w='kaffe', de='Kaffee', k='Nomen', g='m', rang=422),
 dict(w='melk', de='Milch', k='Nomen', g='f', rang=423),
 dict(w='brød', de='Brot', k='Nomen', g='n', rang=424),
 dict(w='ost', de='Kaese', k='Nomen', g='m', rang=425),
 dict(w='kjøtt', de='Fleisch', k='Nomen', g='n', rang=426),
 dict(w='fisk', de='Fisch', k='Nomen', g='m', rang=427),
 dict(w='frukt', de='Obst', k='Nomen', g='f', rang=428),
 dict(w='grønnsak', de='Gemuese', k='Nomen', g='f', rang=429),
 dict(w='sukker', de='Zucker', k='Nomen', g='n', rang=430),
 dict(w='mat', de='Essen', k='Nomen', g='m', rang=431),
 dict(w='frokost', de='Fruehstueck', k='Nomen', g='m', rang=432),
 dict(w='lunsj', de='Mittagessen', k='Nomen', g='m', rang=433),
 dict(w='middag', de='Abendessen', k='Nomen', g='m', rang=434,
      hin='Heisst woertlich Mittag, meint aber die warme Hauptmahlzeit am Abend.'),
 dict(w='meny', de='Speisekarte', k='Nomen', g='m', rang=435),
 dict(w='glass', de='Glas', k='Nomen', g='n', rang=436),
 dict(w='flaske', de='Flasche', k='Nomen', g='f', rang=437),
 dict(w='hode', de='Kopf', k='Nomen', g='n', rang=438),
 dict(w='hånd', de='Hand', k='Nomen', g='f', rang=439),
 dict(w='fot', de='Fuss', k='Nomen', g='m', rang=440),
 dict(w='øye', de='Auge', k='Nomen', g='n', rang=441),
 dict(w='munn', de='Mund', k='Nomen', g='m', rang=442),
 dict(w='arm', de='Arm', k='Nomen', g='m', rang=443),
 dict(w='bein', de='Bein', k='Nomen', g='n', rang=444),
 dict(w='hår', de='Haar', k='Nomen', g='n', rang=445),
 dict(w='kropp', de='Koerper', k='Nomen', g='m', rang=446),
 dict(w='lege', de='Arzt', k='Nomen', g='m', rang=447),
 dict(w='medisin', de='Medizin', k='Nomen', g='m', rang=448),
 dict(w='smerte', de='Schmerz', k='Nomen', g='m', rang=449),
 dict(w='feber', de='Fieber', k='Nomen', g='m', rang=450),
 dict(w='mobil', de='Handy', k='Nomen', g='m', rang=451),
 dict(w='nummer', de='Nummer', k='Nomen', g='n', rang=452),
 dict(w='musikk', de='Musik', k='Nomen', g='m', rang=453),
 dict(w='film', de='Film', k='Nomen', g='m', rang=454),
 dict(w='fest', de='Fest, Party', k='Nomen', g='m', rang=455),
 dict(w='liv', de='Leben', k='Nomen', g='n', rang=456),
 dict(w='verden', de='Welt', k='Nomen', g='m', rang=457),
 dict(w='sol', de='Sonne', k='Nomen', g='f', rang=458),
 dict(w='regn', de='Regen', k='Nomen', g='n', rang=459),
 dict(w='snø', de='Schnee', k='Nomen', g='m', rang=460),
 dict(w='vær', de='Wetter', k='Nomen', g='n', rang=461),
 dict(w='hav', de='Meer', k='Nomen', g='n', rang=462),
 dict(w='fjell', de='Berg', k='Nomen', g='n', rang=463),
 dict(w='skog', de='Wald', k='Nomen', g='m', rang=464),
 dict(w='tur', de='Wanderung, Ausflug', k='Nomen', g='m', rang=465,
      hin='Vom Sonntagsspaziergang bis zur Bergtour - das norwegische Allzweckwort fuer Rausgehen.'),
 dict(w='luft', de='Luft', k='Nomen', g='f', rang=466),
 dict(w='hund', de='Hund', k='Nomen', g='m', rang=467),
 dict(w='katt', de='Katze', k='Nomen', g='m', rang=468),
 dict(w='klær', de='Kleidung', k='Nomen', g='m', rang=469),
 dict(w='sko', de='Schuh', k='Nomen', g='m', rang=470),
 dict(w='veske', de='Tasche', k='Nomen', g='f', rang=471),
 dict(w='nøkkel', de='Schluessel', k='Nomen', g='m', rang=472),
 dict(w='gave', de='Geschenk', k='Nomen', g='f', rang=473),
 dict(w='kjærlighet', de='Liebe', k='Nomen', g='f', rang=474),
 dict(w='del', de='Teil', k='Nomen', g='m', rang=475),
 dict(w='slutt', de='Ende', k='Nomen', g='m', rang=476),
 dict(w='begynnelse', de='Anfang', k='Nomen', g='m', rang=477),
 dict(w='måte', de='Art, Weise', k='Nomen', g='m', rang=478),
 dict(w='grunn', de='Grund', k='Nomen', g='m', rang=479),
 dict(w='eksempel', de='Beispiel', k='Nomen', g='n', rang=480),
 dict(w='idé', de='Idee', k='Nomen', g='m', rang=481),
 dict(w='historie', de='Geschichte', k='Nomen', g='f', rang=482),
 dict(w='angst', de='Angst', k='Nomen', g='m', rang=483),
 dict(w='sult', de='Hunger', k='Nomen', g='m', rang=484),
 dict(w='tørst', de='Durst', k='Nomen', g='m', rang=485),
 dict(w='søvn', de='Schlaf', k='Nomen', g='m', rang=486),
 dict(w='rabatt', de='Rabatt', k='Nomen', g='m', rang=487),
 dict(w='størrelse', de='Groesse', k='Nomen', g='m', rang=488),
 dict(w='inngang', de='Eingang', k='Nomen', g='m', rang=489),
 dict(w='utgang', de='Ausgang', k='Nomen', g='m', rang=490),
 dict(w='hjelp', de='Hilfe', k='Nomen', g='f', rang=491),
 dict(w='politi', de='Polizei', k='Nomen', g='n', rang=492),
 dict(w='vakt', de='Wache, Schicht', k='Nomen', g='f', rang=493),
 dict(w='kollega', de='Kollege', k='Nomen', g='m', rang=494),
 dict(w='kunde', de='Kunde', k='Nomen', g='m', rang=495),
 dict(w='lønn', de='Lohn', k='Nomen', g='f', rang=496),
 dict(w='ferie', de='Urlaub', k='Nomen', g='m', rang=497),
 dict(w='pause', de='Pause', k='Nomen', g='m', rang=498),
 dict(w='avtale', de='Verabredung, Vertrag', k='Nomen', g='m', rang=499),
 dict(w='kontrakt', de='Vertrag', k='Nomen', g='m', rang=500),
]
