# -*- coding: utf-8 -*-
"""Die 500 haeufigsten polnischen Woerter.

**Eigenstaendige Liste, KEINE Uebersetzung** - dieselbe Begruendung wie bei
`vokabeln_it.py`.

**Herkunft und Vorbehalt:** nach bestem Wissen zusammengestellt, NICHT
gegen ein Referenzkorpus abgeglichen.

**KEINE ARTIKEL** - wie Russisch hat Polnisch weder einen bestimmten noch
einen unbestimmten. `stół` heisst Tisch, der Tisch und ein Tisch. Die
Plaetze gehen an Pronomen.

**Genus ist Pflicht** (m/f/n) und laesst sich zum Glueck meist an der
Endung ablesen: Konsonant = maennlich, -a = weiblich, -o/-e = saechlich.
Die Ausnahmen stehen im Hinweis am Wort.

**SIEBEN FAELLE, und die Woerterbuchform ist nur einer davon.** Die Liste
zeigt den Nominativ; im Satz steht selten dieser. `kawa` (Kaffee) wird zu
`kawę` beim Bestellen, `piwo` zu `piwa` bei "zwei Bier". Das ist der
Grund, warum die automatische Wortart-Erkennung
(`wortarten_auto.py`) fuer Polnisch weniger Treffer landet als fuer
Englisch - sie erkennt nur die Grundform.

**Verben stehen im Infinitiv**, und zwar meist im UNVOLLENDETEN Aspekt
(`robić`, nicht `zrobić`). Der Aspekt ist bewusst nicht abgebildet: die
Liste wuerde sich verdoppeln, und fuer den Einstieg reicht die Form, die
auch die Gegenwart bildet - dieselbe Entscheidung wie bei Russisch.
"""

WOERTER = [

# --------------------------------------------------------------- Pronomen
 dict(w='ja', de='ich', k='Pronomen', rang=1),
 dict(w='ty', de='du', k='Pronomen', rang=2),
 dict(w='on', de='er', k='Pronomen', rang=3),
 dict(w='ona', de='sie', k='Pronomen', rang=4),
 dict(w='ono', de='es', k='Pronomen', rang=5),
 dict(w='my', de='wir', k='Pronomen', rang=6),
 dict(w='wy', de='ihr', k='Pronomen', rang=7),
 dict(w='oni', de='sie (Mehrzahl, maennlich)', k='Pronomen', rang=8),
 dict(w='one', de='sie (Mehrzahl, nicht maennlich)', k='Pronomen', rang=9,
      hin='Polnisch trennt in der Mehrzahl: "oni" nur wenn mindestens ein '
          'Mann dabei ist, sonst "one".'),
 dict(w='mnie', de='mich, mir', k='Pronomen', rang=10),
 dict(w='ciebie', de='dich', k='Pronomen', rang=11),
 dict(w='ci', de='dir', k='Pronomen', rang=12),
 dict(w='go', de='ihn', k='Pronomen', rang=13),
 dict(w='jej', de='ihr', k='Pronomen', rang=14),
 dict(w='nas', de='uns', k='Pronomen', rang=15),
 dict(w='wam', de='euch', k='Pronomen', rang=16),
 dict(w='ich', de='ihnen, ihr', k='Pronomen', rang=17,
      hin='Sieht aus wie das deutsche "ich", heisst aber "ihnen" - einer der '
          'gemeinsten falschen Freunde.'),
 dict(w='się', de='sich', k='Pronomen', rang=18),
 dict(w='siebie', de='sich selbst', k='Pronomen', rang=19),
 dict(w='mój', de='mein', k='Pronomen', rang=20),
 dict(w='twój', de='dein', k='Pronomen', rang=21),
 dict(w='jego', de='sein', k='Pronomen', rang=22),
 dict(w='nasz', de='unser', k='Pronomen', rang=23),
 dict(w='wasz', de='euer', k='Pronomen', rang=24),
 dict(w='swój', de='sein eigener', k='Pronomen', rang=25),
 dict(w='ten', de='dieser', k='Pronomen', rang=26),
 dict(w='ta', de='diese', k='Pronomen', rang=27),
 dict(w='tamten', de='jener', k='Pronomen', rang=28),
 dict(w='który', de='welcher', k='Pronomen', rang=29),
 dict(w='wszystko', de='alles', k='Pronomen', rang=30),
 dict(w='wszyscy', de='alle', k='Pronomen', rang=31),
 dict(w='ktoś', de='jemand', k='Pronomen', rang=32),
 dict(w='coś', de='etwas', k='Pronomen', rang=33),
 dict(w='nikt', de='niemand', k='Pronomen', rang=34),
 dict(w='nic', de='nichts', k='Pronomen', rang=35),
 dict(w='inny', de='anderer', k='Pronomen', rang=36),
 dict(w='taki', de='solcher', k='Pronomen', rang=37),
 dict(w='każdy', de='jeder', k='Pronomen', rang=38),
 dict(w='sam', de='selbst, allein', k='Pronomen', rang=39),
 dict(w='obaj', de='beide', k='Pronomen', rang=40),
 dict(w='siebie nawzajem', de='einander', k='Pronomen', rang=41),

# -------------------------------------------------------------- Fragewort
 dict(w='co', de='was', k='Fragewort', rang=42),
 dict(w='gdzie', de='wo', k='Fragewort', rang=43),
 dict(w='kiedy', de='wann', k='Fragewort', rang=44,
      hin='Heisst als Konjunktion auch "als": "kiedy bylem maly" - als ich klein war.'),
 dict(w='jak', de='wie', k='Fragewort', rang=45),
 dict(w='dlaczego', de='warum', k='Fragewort', rang=46),
 dict(w='kto', de='wer', k='Fragewort', rang=47),
 dict(w='ile', de='wie viel, wie viele', k='Fragewort', rang=48),
 dict(w='jaki', de='was fuer ein', k='Fragewort', rang=49),
 dict(w='dokąd', de='wohin', k='Fragewort', rang=50),
 dict(w='czy', de='ob (Fragepartikel)', k='Fragewort', rang=51,
      hin='Steht am Anfang jeder Ja/Nein-Frage und hat kein deutsches '
          'Gegenstueck: "Czy masz czas?" - hast du Zeit?'),

# ------------------------------------------------------------ Konjunktion
 dict(w='i', de='und', k='Konjunktion', rang=52),
 dict(w='albo', de='oder', k='Konjunktion', rang=53),
 dict(w='ale', de='aber', k='Konjunktion', rang=54),
 dict(w='jeśli', de='wenn, falls', k='Konjunktion', rang=55),
 dict(w='bo', de='weil', k='Konjunktion', rang=56),
 dict(w='ponieważ', de='weil (foermlich)', k='Konjunktion', rang=57),
 dict(w='że', de='dass', k='Konjunktion', rang=58),
 dict(w='więc', de='also', k='Konjunktion', rang=59),
 dict(w='gdy', de='als, wenn', k='Konjunktion', rang=60,
      hin='"Gdy" ist die reine Konjunktion; "kiedy" kann beides - Fragewort '
          'und Konjunktion. Deshalb steht "kiedy" hier nur als Fragewort.'),
 dict(w='niż', de='als (Vergleich)', k='Konjunktion', rang=61),
 dict(w='chociaż', de='obwohl', k='Konjunktion', rang=62),
 dict(w='dlatego', de='deshalb', k='Konjunktion', rang=63),
 dict(w='jednak', de='jedoch', k='Konjunktion', rang=64),
 dict(w='oraz', de='sowie', k='Konjunktion', rang=65),
 dict(w='czyli', de='das heisst', k='Konjunktion', rang=66),

# ----------------------------------------------------------- Praeposition
 dict(w='w', de='in', k='Praeposition', rang=67),
 dict(w='na', de='auf', k='Praeposition', rang=68),
 dict(w='z', de='mit, aus', k='Praeposition', rang=69),
 dict(w='do', de='zu, nach', k='Praeposition', rang=70),
 dict(w='od', de='von, seit', k='Praeposition', rang=71),
 dict(w='dla', de='fuer', k='Praeposition', rang=72),
 dict(w='o', de='ueber, um', k='Praeposition', rang=73),
 dict(w='przez', de='durch', k='Praeposition', rang=74),
 dict(w='po', de='nach', k='Praeposition', rang=75),
 dict(w='przed', de='vor', k='Praeposition', rang=76),
 dict(w='pod', de='unter', k='Praeposition', rang=77),
 dict(w='nad', de='ueber', k='Praeposition', rang=78),
 dict(w='między', de='zwischen', k='Praeposition', rang=79),
 dict(w='bez', de='ohne', k='Praeposition', rang=80),
 dict(w='przy', de='bei, an', k='Praeposition', rang=81),
 dict(w='obok', de='neben', k='Praeposition', rang=82),
 dict(w='wokół', de='um herum', k='Praeposition', rang=83),
 dict(w='wzdłuż', de='entlang', k='Praeposition', rang=84),
 dict(w='zamiast', de='anstatt', k='Praeposition', rang=85),
 dict(w='oprócz', de='ausser', k='Praeposition', rang=86),
 dict(w='podczas', de='waehrend', k='Praeposition', rang=87),
 dict(w='przeciwko', de='gegen', k='Praeposition', rang=88),
 dict(w='blisko', de='nahe', k='Praeposition', rang=89),

# ----------------------------------------------------------------- Adverb
 dict(w='nie', de='nicht, nein', k='Adverb', rang=90),
 dict(w='tak', de='ja, so', k='Adverb', rang=91),
 dict(w='bardzo', de='sehr', k='Adverb', rang=92),
 dict(w='dużo', de='viel', k='Adverb', rang=93),
 dict(w='mało', de='wenig', k='Adverb', rang=94),
 dict(w='trochę', de='ein bisschen', k='Adverb', rang=95),
 dict(w='więcej', de='mehr', k='Adverb', rang=96),
 dict(w='mniej', de='weniger', k='Adverb', rang=97),
 dict(w='dobrze', de='gut', k='Adverb', rang=98),
 dict(w='źle', de='schlecht', k='Adverb', rang=99),
 dict(w='tutaj', de='hier', k='Adverb', rang=100),
 dict(w='tam', de='dort', k='Adverb', rang=101),
 dict(w='teraz', de='jetzt', k='Adverb', rang=102),
 dict(w='dzisiaj', de='heute', k='Adverb', rang=103),
 dict(w='wczoraj', de='gestern', k='Adverb', rang=104),
 dict(w='jutro', de='morgen', k='Adverb', rang=105),
 dict(w='zawsze', de='immer', k='Adverb', rang=106),
 dict(w='nigdy', de='nie', k='Adverb', rang=107),
 dict(w='często', de='oft', k='Adverb', rang=108),
 dict(w='czasami', de='manchmal', k='Adverb', rang=109),
 dict(w='rzadko', de='selten', k='Adverb', rang=110),
 dict(w='wkrótce', de='bald', k='Adverb', rang=111),
 dict(w='jeszcze', de='noch', k='Adverb', rang=112),
 dict(w='już', de='schon', k='Adverb', rang=113),
 dict(w='wcześnie', de='frueh', k='Adverb', rang=114),
 dict(w='późno', de='spaet', k='Adverb', rang=115),
 dict(w='razem', de='zusammen', k='Adverb', rang=116),
 dict(w='tylko', de='nur', k='Adverb', rang=117),
 dict(w='może', de='vielleicht', k='Adverb', rang=118),
 dict(w='naprawdę', de='wirklich', k='Adverb', rang=119),
 dict(w='wystarczy', de='genug', k='Adverb', rang=120),
 dict(w='prawie', de='fast', k='Adverb', rang=121),
 dict(w='dokładnie', de='genau', k='Adverb', rang=122),
 dict(w='pewnie', de='sicher', k='Adverb', rang=123),
 dict(w='powoli', de='langsam', k='Adverb', rang=124),
 dict(w='szybko', de='schnell', k='Adverb', rang=125),
 dict(w='znowu', de='wieder', k='Adverb', rang=126),
 dict(w='na zewnątrz', de='draussen', k='Adverb', rang=127),
 dict(w='w środku', de='drinnen', k='Adverb', rang=128),
 dict(w='w domu', de='zu Hause', k='Adverb', rang=129),
 dict(w='też', de='auch', k='Adverb', rang=130),
 dict(w='nawet', de='sogar', k='Adverb', rang=131),
 dict(w='wreszcie', de='endlich', k='Adverb', rang=132),
 dict(w='niestety', de='leider', k='Adverb', rang=133),
 dict(w='chętnie', de='gerne', k='Adverb', rang=134),
 dict(w='zaraz', de='sofort', k='Adverb', rang=135),
 dict(w='wszędzie', de='ueberall', k='Adverb', rang=136),
 dict(w='prosto', de='geradeaus', k='Adverb', rang=137),
 dict(w='daleko', de='weit', k='Adverb', rang=138),
 dict(w='spokojnie', de='ruhig', k='Adverb', rang=139),

# --------------------------------------------------------------- Zahlwort
 dict(w='zero', de='null', k='Zahlwort', rang=140),
 dict(w='jeden', de='eins', k='Zahlwort', rang=141),
 dict(w='dwa', de='zwei', k='Zahlwort', rang=142),
 dict(w='trzy', de='drei', k='Zahlwort', rang=143),
 dict(w='cztery', de='vier', k='Zahlwort', rang=144),
 dict(w='pięć', de='fuenf', k='Zahlwort', rang=145),
 dict(w='sześć', de='sechs', k='Zahlwort', rang=146),
 dict(w='siedem', de='sieben', k='Zahlwort', rang=147),
 dict(w='osiem', de='acht', k='Zahlwort', rang=148),
 dict(w='dziewięć', de='neun', k='Zahlwort', rang=149),
 dict(w='dziesięć', de='zehn', k='Zahlwort', rang=150),
 dict(w='jedenaście', de='elf', k='Zahlwort', rang=151),
 dict(w='dwanaście', de='zwoelf', k='Zahlwort', rang=152),
 dict(w='trzynaście', de='dreizehn', k='Zahlwort', rang=153),
 dict(w='czternaście', de='vierzehn', k='Zahlwort', rang=154),
 dict(w='piętnaście', de='fuenfzehn', k='Zahlwort', rang=155),
 dict(w='szesnaście', de='sechzehn', k='Zahlwort', rang=156),
 dict(w='siedemnaście', de='siebzehn', k='Zahlwort', rang=157),
 dict(w='osiemnaście', de='achtzehn', k='Zahlwort', rang=158),
 dict(w='dziewiętnaście', de='neunzehn', k='Zahlwort', rang=159),
 dict(w='dwadzieścia', de='zwanzig', k='Zahlwort', rang=160),
 dict(w='trzydzieści', de='dreissig', k='Zahlwort', rang=161),
 dict(w='czterdzieści', de='vierzig', k='Zahlwort', rang=162),
 dict(w='pięćdziesiąt', de='fuenfzig', k='Zahlwort', rang=163),
 dict(w='sześćdziesiąt', de='sechzig', k='Zahlwort', rang=164),
 dict(w='siedemdziesiąt', de='siebzig', k='Zahlwort', rang=165),
 dict(w='osiemdziesiąt', de='achtzig', k='Zahlwort', rang=166),
 dict(w='dziewięćdziesiąt', de='neunzig', k='Zahlwort', rang=167),
 dict(w='sto', de='hundert', k='Zahlwort', rang=168),
 dict(w='tysiąc', de='tausend', k='Zahlwort', rang=169),
 dict(w='milion', de='Million', k='Zahlwort', rang=170),
 dict(w='pierwszy', de='erster', k='Zahlwort', rang=171),
 dict(w='drugi', de='zweiter', k='Zahlwort', rang=172),
 dict(w='trzeci', de='dritter', k='Zahlwort', rang=173),
 dict(w='ostatni', de='letzter', k='Zahlwort', rang=174),
 dict(w='pół', de='halb', k='Zahlwort', rang=175),
 dict(w='podwójny', de='doppelt', k='Zahlwort', rang=176),
 dict(w='para', de='Paar', k='Zahlwort', rang=177),

# -------------------------------------------------------------------- Verb
 dict(w='być', de='sein', k='Verb', rang=178),
 dict(w='mieć', de='haben', k='Verb', rang=179),
 dict(w='móc', de='koennen', k='Verb', rang=180),
 dict(w='chcieć', de='wollen', k='Verb', rang=181),
 dict(w='musieć', de='muessen', k='Verb', rang=182),
 dict(w='wiedzieć', de='wissen', k='Verb', rang=183),
 dict(w='znać', de='kennen', k='Verb', rang=184,
      hin='"Wiedzieć" weiss Fakten, "znać" kennt Personen und Orte - wie im '
          'Franzoesischen savoir/connaître.'),
 dict(w='robić', de='machen', k='Verb', rang=185),
 dict(w='mówić', de='sprechen, sagen', k='Verb', rang=186),
 dict(w='powiedzieć', de='sagen', k='Verb', rang=187),
 dict(w='iść', de='gehen', k='Verb', rang=188),
 dict(w='jechać', de='fahren', k='Verb', rang=189,
      hin='Polnisch trennt gehen und fahren streng - "iść" zu Fuss, "jechać" '
          'mit Fahrzeug.'),
 dict(w='przyjść', de='kommen', k='Verb', rang=190),
 dict(w='widzieć', de='sehen', k='Verb', rang=191),
 dict(w='patrzeć', de='schauen', k='Verb', rang=192),
 dict(w='dać', de='geben', k='Verb', rang=193),
 dict(w='brać', de='nehmen', k='Verb', rang=194),
 dict(w='znaleźć', de='finden', k='Verb', rang=195),
 dict(w='słyszeć', de='hoeren', k='Verb', rang=196),
 dict(w='słuchać', de='zuhoeren', k='Verb', rang=197),
 dict(w='kłaść', de='legen', k='Verb', rang=198),
 dict(w='myśleć', de='denken', k='Verb', rang=199),
 dict(w='wierzyć', de='glauben', k='Verb', rang=200),
 dict(w='rozumieć', de='verstehen', k='Verb', rang=201),
 dict(w='pytać', de='fragen', k='Verb', rang=202),
 dict(w='odpowiadać', de='antworten', k='Verb', rang=203),
 dict(w='nazywać', de='nennen', k='Verb', rang=204),
 dict(w='pracować', de='arbeiten', k='Verb', rang=205),
 dict(w='jeść', de='essen', k='Verb', rang=206),
 dict(w='pić', de='trinken', k='Verb', rang=207),
 dict(w='spać', de='schlafen', k='Verb', rang=208),
 dict(w='żyć', de='leben', k='Verb', rang=209),
 dict(w='mieszkać', de='wohnen', k='Verb', rang=210),
 dict(w='kupować', de='kaufen', k='Verb', rang=211),
 dict(w='płacić', de='bezahlen', k='Verb', rang=212),
 dict(w='kosztować', de='kosten', k='Verb', rang=213),
 dict(w='otwierać', de='oeffnen', k='Verb', rang=214),
 dict(w='zamykać', de='schliessen', k='Verb', rang=215),
 dict(w='wyjeżdżać', de='abfahren', k='Verb', rang=216),
 dict(w='przyjeżdżać', de='ankommen', k='Verb', rang=217),
 dict(w='wracać', de='zurueckkehren', k='Verb', rang=218),
 dict(w='wychodzić', de='hinausgehen', k='Verb', rang=219),
 dict(w='wchodzić', de='hineingehen', k='Verb', rang=220),
 dict(w='zostawać', de='bleiben', k='Verb', rang=221),
 dict(w='czekać', de='warten', k='Verb', rang=222),
 dict(w='szukać', de='suchen', k='Verb', rang=223),
 dict(w='nosić', de='tragen', k='Verb', rang=224),
 dict(w='używać', de='benutzen', k='Verb', rang=225),
 dict(w='pomagać', de='helfen', k='Verb', rang=226),
 dict(w='lubić', de='moegen', k='Verb', rang=227),
 dict(w='kochać', de='lieben', k='Verb', rang=228),
 dict(w='uczyć się', de='lernen', k='Verb', rang=229),
 dict(w='studiować', de='studieren', k='Verb', rang=230),
 dict(w='czytać', de='lesen', k='Verb', rang=231),
 dict(w='pisać', de='schreiben', k='Verb', rang=232),
 dict(w='pamiętać', de='sich erinnern', k='Verb', rang=233),
 dict(w='zapominać', de='vergessen', k='Verb', rang=234),
 dict(w='zaczynać', de='anfangen', k='Verb', rang=235),
 dict(w='kończyć', de='beenden', k='Verb', rang=236),
 dict(w='próbować', de='versuchen', k='Verb', rang=237),
 dict(w='tracić', de='verlieren', k='Verb', rang=238),
 dict(w='wygrywać', de='gewinnen', k='Verb', rang=239),
 dict(w='grać', de='spielen', k='Verb', rang=240),
 dict(w='śpiewać', de='singen', k='Verb', rang=241),
 dict(w='tańczyć', de='tanzen', k='Verb', rang=242),
 dict(w='biegać', de='rennen', k='Verb', rang=243),
 dict(w='prowadzić', de='fahren, fuehren', k='Verb', rang=244),
 dict(w='podróżować', de='reisen', k='Verb', rang=245),
 dict(w='odwiedzać', de='besuchen', k='Verb', rang=246),
 dict(w='spotykać', de='treffen', k='Verb', rang=247),
 dict(w='poznawać', de='kennenlernen', k='Verb', rang=248),
 dict(w='żenić się', de='heiraten', k='Verb', rang=249),
 dict(w='rodzić się', de='geboren werden', k='Verb', rang=250),
 dict(w='umierać', de='sterben', k='Verb', rang=251),
 dict(w='zmieniać', de='aendern', k='Verb', rang=252),
 dict(w='stawać się', de='werden', k='Verb', rang=253),
 dict(w='wydawać się', de='scheinen', k='Verb', rang=254),
 dict(w='zdarzać się', de='geschehen', k='Verb', rang=255),
 dict(w='potrzebować', de='brauchen', k='Verb', rang=256),
 dict(w='mieć nadzieję', de='hoffen', k='Verb', rang=257),
 dict(w='zamawiać', de='bestellen', k='Verb', rang=258),
 dict(w='rezerwować', de='reservieren', k='Verb', rang=259),
 dict(w='wynajmować', de='mieten', k='Verb', rang=260),
 dict(w='podpisywać', de='unterschreiben', k='Verb', rang=261),
 dict(w='myć', de='waschen', k='Verb', rang=262),
 dict(w='gotować', de='kochen', k='Verb', rang=263),
 dict(w='sprzątać', de='aufraeumen', k='Verb', rang=264),
 dict(w='śmiać się', de='lachen', k='Verb', rang=265),
 dict(w='płakać', de='weinen', k='Verb', rang=266),
 dict(w='przepraszać', de='sich entschuldigen', k='Verb', rang=267),
 dict(w='dziękować', de='danken', k='Verb', rang=268),
 dict(w='witać', de='begruessen', k='Verb', rang=269),
 dict(w='dzwonić', de='anrufen', k='Verb', rang=270),
 dict(w='pokazywać', de='zeigen', k='Verb', rang=271),
 dict(w='opowiadać', de='erzaehlen', k='Verb', rang=272),
 dict(w='dostawać', de='bekommen', k='Verb', rang=273),
 dict(w='trzymać', de='halten', k='Verb', rang=274),
 dict(w='siedzieć', de='sitzen', k='Verb', rang=275),
 dict(w='stać', de='stehen', k='Verb', rang=276),
 dict(w='załatwiać', de='erledigen', k='Verb', rang=277,
      hin='Eines der meistgebrauchten polnischen Verben - deckt erledigen, '
          'organisieren und regeln ab.'),

# ---------------------------------------------------------------- Adjektiv
 dict(w='dobry', de='gut', k='Adjektiv', rang=278),
 dict(w='zły', de='schlecht, boese', k='Adjektiv', rang=279),
 dict(w='duży', de='gross', k='Adjektiv', rang=280),
 dict(w='mały', de='klein', k='Adjektiv', rang=281),
 dict(w='nowy', de='neu', k='Adjektiv', rang=282),
 dict(w='stary', de='alt', k='Adjektiv', rang=283),
 dict(w='młody', de='jung', k='Adjektiv', rang=284),
 dict(w='ładny', de='huebsch', k='Adjektiv', rang=285),
 dict(w='piękny', de='schoen', k='Adjektiv', rang=286),
 dict(w='brzydki', de='haesslich', k='Adjektiv', rang=287),
 dict(w='długi', de='lang', k='Adjektiv', rang=288),
 dict(w='krótki', de='kurz', k='Adjektiv', rang=289),
 dict(w='wysoki', de='hoch, gross', k='Adjektiv', rang=290),
 dict(w='niski', de='niedrig, klein', k='Adjektiv', rang=291),
 dict(w='ciepły', de='warm', k='Adjektiv', rang=292),
 dict(w='zimny', de='kalt', k='Adjektiv', rang=293),
 dict(w='gorący', de='heiss', k='Adjektiv', rang=294),
 dict(w='łatwy', de='einfach', k='Adjektiv', rang=295),
 dict(w='trudny', de='schwierig', k='Adjektiv', rang=296),
 dict(w='ważny', de='wichtig', k='Adjektiv', rang=297),
 dict(w='możliwy', de='moeglich', k='Adjektiv', rang=298),
 dict(w='prawdziwy', de='wahr, echt', k='Adjektiv', rang=299),
 dict(w='fałszywy', de='falsch', k='Adjektiv', rang=300),
 dict(w='drogi', de='teuer, lieb', k='Adjektiv', rang=301),
 dict(w='tani', de='billig', k='Adjektiv', rang=302),
 dict(w='darmowy', de='kostenlos', k='Adjektiv', rang=303),
 dict(w='pełny', de='voll', k='Adjektiv', rang=304),
 dict(w='pusty', de='leer', k='Adjektiv', rang=305),
 dict(w='otwarty', de='offen', k='Adjektiv', rang=306),
 dict(w='zamknięty', de='geschlossen', k='Adjektiv', rang=307),
 dict(w='wolny', de='frei, langsam', k='Adjektiv', rang=308),
 dict(w='zajęty', de='besetzt', k='Adjektiv', rang=309),
 dict(w='gotowy', de='bereit', k='Adjektiv', rang=310),
 dict(w='zmęczony', de='muede', k='Adjektiv', rang=311),
 dict(w='chory', de='krank', k='Adjektiv', rang=312),
 dict(w='zdrowy', de='gesund', k='Adjektiv', rang=313),
 dict(w='szczęśliwy', de='gluecklich', k='Adjektiv', rang=314),
 dict(w='smutny', de='traurig', k='Adjektiv', rang=315),
 dict(w='zadowolony', de='zufrieden', k='Adjektiv', rang=316),
 dict(w='wściekły', de='wuetend', k='Adjektiv', rang=317),
 dict(w='miły', de='nett', k='Adjektiv', rang=318),
 dict(w='sympatyczny', de='sympathisch', k='Adjektiv', rang=319),
 dict(w='fajny', de='cool, nett', k='Adjektiv', rang=320,
      hin='Das polnische Allzweckwort fuer gut und angenehm - man hoert es '
          'staendig.'),
 dict(w='silny', de='stark', k='Adjektiv', rang=321),
 dict(w='słaby', de='schwach', k='Adjektiv', rang=322),
 dict(w='szybki', de='schnell', k='Adjektiv', rang=323),
 dict(w='ciężki', de='schwer', k='Adjektiv', rang=324),
 dict(w='lekki', de='leicht', k='Adjektiv', rang=325),
 dict(w='czysty', de='sauber', k='Adjektiv', rang=326),
 dict(w='brudny', de='schmutzig', k='Adjektiv', rang=327),
 dict(w='świeży', de='frisch', k='Adjektiv', rang=328),
 dict(w='słodki', de='suess', k='Adjektiv', rang=329),
 dict(w='słony', de='salzig', k='Adjektiv', rang=330),
 dict(w='ostry', de='scharf', k='Adjektiv', rang=331),
 dict(w='smaczny', de='lecker', k='Adjektiv', rang=332),
 dict(w='biały', de='weiss', k='Adjektiv', rang=333),
 dict(w='czarny', de='schwarz', k='Adjektiv', rang=334),
 dict(w='czerwony', de='rot', k='Adjektiv', rang=335),
 dict(w='niebieski', de='blau', k='Adjektiv', rang=336),
 dict(w='zielony', de='gruen', k='Adjektiv', rang=337),
 dict(w='żółty', de='gelb', k='Adjektiv', rang=338),
 dict(w='szary', de='grau', k='Adjektiv', rang=339),
 dict(w='brązowy', de='braun', k='Adjektiv', rang=340),
 dict(w='polski', de='polnisch', k='Adjektiv', rang=341),
 dict(w='niemiecki', de='deutsch', k='Adjektiv', rang=342),
 dict(w='angielski', de='englisch', k='Adjektiv', rang=343),
 dict(w='zagraniczny', de='auslaendisch', k='Adjektiv', rang=344),
 dict(w='następny', de='naechster', k='Adjektiv', rang=345),
 dict(w='poprzedni', de='voriger', k='Adjektiv', rang=346),
 dict(w='zwykły', de='gewoehnlich', k='Adjektiv', rang=347),
 dict(w='śmieszny', de='lustig', k='Adjektiv', rang=348),
 dict(w='nudny', de='langweilig', k='Adjektiv', rang=349),
 dict(w='ciekawy', de='interessant', k='Adjektiv', rang=350),
 dict(w='bezpieczny', de='sicher', k='Adjektiv', rang=351),
 dict(w='niebezpieczny', de='gefaehrlich', k='Adjektiv', rang=352),

# ------------------------------------------------------------------- Nomen
 dict(w='człowiek', de='Mensch', k='Nomen', g='m', rang=353,
      hin='Mehrzahl unregelmaessig: "ludzie".'),
 dict(w='mężczyzna', de='Mann', k='Nomen', g='m', rang=354,
      hin='Endet auf -a, ist aber MAENNLICH - eine der wenigen Ausnahmen.'),
 dict(w='kobieta', de='Frau', k='Nomen', g='f', rang=355),
 dict(w='chłopak', de='Junge, fester Freund', k='Nomen', g='m', rang=356),
 dict(w='dziewczyna', de='Maedchen, feste Freundin', k='Nomen', g='f', rang=357),
 dict(w='dziecko', de='Kind', k='Nomen', g='n', rang=358),
 dict(w='ludzie', de='Leute', k='Nomen', g='m', rang=359),
 dict(w='kolega', de='Kumpel', k='Nomen', g='m', rang=360),
 dict(w='przyjaciel', de='Freund (enger)', k='Nomen', g='m', rang=361),
 dict(w='rodzina', de='Familie', k='Nomen', g='f', rang=362),
 dict(w='ojciec', de='Vater', k='Nomen', g='m', rang=363),
 dict(w='matka', de='Mutter', k='Nomen', g='f', rang=364),
 dict(w='syn', de='Sohn', k='Nomen', g='m', rang=365),
 dict(w='córka', de='Tochter', k='Nomen', g='f', rang=366),
 dict(w='brat', de='Bruder', k='Nomen', g='m', rang=367),
 dict(w='siostra', de='Schwester', k='Nomen', g='f', rang=368),
 dict(w='rodzeństwo', de='Geschwister', k='Nomen', g='n', rang=369),
 dict(w='mąż', de='Ehemann', k='Nomen', g='m', rang=370),
 dict(w='żona', de='Ehefrau', k='Nomen', g='f', rang=371),
 dict(w='imię', de='Vorname', k='Nomen', g='n', rang=372),
 dict(w='rok', de='Jahr', k='Nomen', g='m', rang=373),
 dict(w='miesiąc', de='Monat', k='Nomen', g='m', rang=374),
 dict(w='tydzień', de='Woche', k='Nomen', g='m', rang=375),
 dict(w='dzień', de='Tag', k='Nomen', g='m', rang=376),
 dict(w='godzina', de='Stunde', k='Nomen', g='f', rang=377),
 dict(w='minuta', de='Minute', k='Nomen', g='f', rang=378),
 dict(w='czas', de='Zeit', k='Nomen', g='m', rang=379),
 dict(w='rano', de='Morgen', k='Nomen', g='n', rang=380),
 dict(w='wieczór', de='Abend', k='Nomen', g='m', rang=381),
 dict(w='noc', de='Nacht', k='Nomen', g='f', rang=382),
 dict(w='weekend', de='Wochenende', k='Nomen', g='m', rang=383),
 dict(w='dom', de='Haus', k='Nomen', g='m', rang=384),
 dict(w='mieszkanie', de='Wohnung', k='Nomen', g='n', rang=385),
 dict(w='pokój', de='Zimmer', k='Nomen', g='m', rang=386,
      hin='Heisst auch Frieden - "pokój" ist beides.'),
 dict(w='drzwi', de='Tuer', k='Nomen', g='n', rang=387,
      hin='Nur Mehrzahl: "eine Tuer" gibt es grammatisch nicht.'),
 dict(w='okno', de='Fenster', k='Nomen', g='n', rang=388),
 dict(w='stół', de='Tisch', k='Nomen', g='m', rang=389),
 dict(w='łóżko', de='Bett', k='Nomen', g='n', rang=390),
 dict(w='kuchnia', de='Kueche', k='Nomen', g='f', rang=391),
 dict(w='toaleta', de='Toilette', k='Nomen', g='f', rang=392),
 dict(w='miasto', de='Stadt', k='Nomen', g='n', rang=393),
 dict(w='kraj', de='Land', k='Nomen', g='m', rang=394),
 dict(w='ulica', de='Strasse', k='Nomen', g='f', rang=395),
 dict(w='droga', de='Weg', k='Nomen', g='f', rang=396),
 dict(w='miejsce', de='Platz, Ort', k='Nomen', g='n', rang=397),
 dict(w='sklep', de='Laden', k='Nomen', g='m', rang=398),
 dict(w='rynek', de='Markt, Marktplatz', k='Nomen', g='m', rang=399),
 dict(w='restauracja', de='Restaurant', k='Nomen', g='f', rang=400),
 dict(w='hotel', de='Hotel', k='Nomen', g='m', rang=401),
 dict(w='szpital', de='Krankenhaus', k='Nomen', g='m', rang=402),
 dict(w='apteka', de='Apotheke', k='Nomen', g='f', rang=403),
 dict(w='dworzec', de='Bahnhof', k='Nomen', g='m', rang=404),
 dict(w='lotnisko', de='Flughafen', k='Nomen', g='n', rang=405),
 dict(w='pociąg', de='Zug', k='Nomen', g='m', rang=406),
 dict(w='autobus', de='Bus', k='Nomen', g='m', rang=407),
 dict(w='samochód', de='Auto', k='Nomen', g='m', rang=408),
 dict(w='bilet', de='Fahrkarte', k='Nomen', g='m', rang=409),
 dict(w='bagaż', de='Gepaeck', k='Nomen', g='m', rang=410),
 dict(w='paszport', de='Pass', k='Nomen', g='m', rang=411),
 dict(w='pieniądze', de='Geld', k='Nomen', g='m', rang=412),
 dict(w='cena', de='Preis', k='Nomen', g='f', rang=413),
 dict(w='rachunek', de='Rechnung', k='Nomen', g='m', rang=414),
 dict(w='karta', de='Karte', k='Nomen', g='f', rang=415),
 dict(w='praca', de='Arbeit', k='Nomen', g='f', rang=416),
 dict(w='szkoła', de='Schule', k='Nomen', g='f', rang=417),
 dict(w='uniwersytet', de='Universitaet', k='Nomen', g='m', rang=418),
 dict(w='student', de='Student', k='Nomen', g='m', rang=419),
 dict(w='wykład', de='Vorlesung', k='Nomen', g='m', rang=420),
 dict(w='egzamin', de='Pruefung', k='Nomen', g='m', rang=421),
 dict(w='książka', de='Buch', k='Nomen', g='f', rang=422),
 dict(w='słowo', de='Wort', k='Nomen', g='n', rang=423),
 dict(w='język', de='Sprache, Zunge', k='Nomen', g='m', rang=424),
 dict(w='pytanie', de='Frage', k='Nomen', g='n', rang=425),
 dict(w='odpowiedź', de='Antwort', k='Nomen', g='f', rang=426),
 dict(w='problem', de='Problem', k='Nomen', g='m', rang=427),
 dict(w='rzecz', de='Sache, Ding', k='Nomen', g='f', rang=428),
 dict(w='woda', de='Wasser', k='Nomen', g='f', rang=429),
 dict(w='wino', de='Wein', k='Nomen', g='n', rang=430),
 dict(w='piwo', de='Bier', k='Nomen', g='n', rang=431),
 dict(w='herbata', de='Tee', k='Nomen', g='f', rang=432),
 dict(w='kawa', de='Kaffee', k='Nomen', g='f', rang=433),
 dict(w='mleko', de='Milch', k='Nomen', g='n', rang=434),
 dict(w='chleb', de='Brot', k='Nomen', g='m', rang=435),
 dict(w='ser', de='Kaese', k='Nomen', g='m', rang=436),
 dict(w='mięso', de='Fleisch', k='Nomen', g='n', rang=437),
 dict(w='ryba', de='Fisch', k='Nomen', g='f', rang=438),
 dict(w='owoce', de='Obst', k='Nomen', g='m', rang=439),
 dict(w='warzywa', de='Gemuese', k='Nomen', g='n', rang=440),
 dict(w='cukier', de='Zucker', k='Nomen', g='m', rang=441),
 dict(w='sól', de='Salz', k='Nomen', g='f', rang=442),
 dict(w='jedzenie', de='Essen', k='Nomen', g='n', rang=443),
 dict(w='śniadanie', de='Fruehstueck', k='Nomen', g='n', rang=444),
 dict(w='obiad', de='Mittagessen', k='Nomen', g='m', rang=445),
 dict(w='kolacja', de='Abendessen', k='Nomen', g='f', rang=446),
 dict(w='menu', de='Speisekarte', k='Nomen', g='n', rang=447),
 dict(w='talerz', de='Teller', k='Nomen', g='m', rang=448),
 dict(w='szklanka', de='Glas', k='Nomen', g='f', rang=449),
 dict(w='butelka', de='Flasche', k='Nomen', g='f', rang=450),
 dict(w='głowa', de='Kopf', k='Nomen', g='f', rang=451),
 dict(w='ręka', de='Hand, Arm', k='Nomen', g='f', rang=452,
      hin='Wie im Russischen ein Wort fuer Hand UND Arm.'),
 dict(w='noga', de='Bein, Fuss', k='Nomen', g='f', rang=453),
 dict(w='oko', de='Auge', k='Nomen', g='n', rang=454, hin='Mehrzahl: "oczy".'),
 dict(w='usta', de='Mund', k='Nomen', g='n', rang=455, hin='Nur Mehrzahl.'),
 dict(w='włosy', de='Haare', k='Nomen', g='m', rang=456),
 dict(w='ciało', de='Koerper', k='Nomen', g='n', rang=457),
 dict(w='lekarz', de='Arzt', k='Nomen', g='m', rang=458),
 dict(w='lek', de='Medikament', k='Nomen', g='m', rang=459),
 dict(w='ból', de='Schmerz', k='Nomen', g='m', rang=460),
 dict(w='gorączka', de='Fieber', k='Nomen', g='f', rang=461),
 dict(w='telefon', de='Telefon, Handy', k='Nomen', g='m', rang=462),
 dict(w='numer', de='Nummer', k='Nomen', g='m', rang=463),
 dict(w='muzyka', de='Musik', k='Nomen', g='f', rang=464),
 dict(w='film', de='Film', k='Nomen', g='m', rang=465),
 dict(w='impreza', de='Party', k='Nomen', g='f', rang=466),
 dict(w='życie', de='Leben', k='Nomen', g='n', rang=467),
 dict(w='świat', de='Welt', k='Nomen', g='m', rang=468),
 dict(w='słońce', de='Sonne', k='Nomen', g='n', rang=469),
 dict(w='deszcz', de='Regen', k='Nomen', g='m', rang=470),
 dict(w='śnieg', de='Schnee', k='Nomen', g='m', rang=471),
 dict(w='pogoda', de='Wetter', k='Nomen', g='f', rang=472),
 dict(w='morze', de='Meer', k='Nomen', g='n', rang=473),
 dict(w='góra', de='Berg', k='Nomen', g='f', rang=474),
 dict(w='las', de='Wald', k='Nomen', g='m', rang=475),
 dict(w='powietrze', de='Luft', k='Nomen', g='n', rang=476),
 dict(w='pies', de='Hund', k='Nomen', g='m', rang=477),
 dict(w='kot', de='Katze', k='Nomen', g='m', rang=478),
 dict(w='ubranie', de='Kleidung', k='Nomen', g='n', rang=479),
 dict(w='sukienka', de='Kleid', k='Nomen', g='f', rang=480),
 dict(w='but', de='Schuh', k='Nomen', g='m', rang=481),
 dict(w='torba', de='Tasche', k='Nomen', g='f', rang=482),
 dict(w='klucz', de='Schluessel', k='Nomen', g='m', rang=483),
 dict(w='prezent', de='Geschenk', k='Nomen', g='m', rang=484),
 dict(w='miłość', de='Liebe', k='Nomen', g='f', rang=485),
 dict(w='część', de='Teil', k='Nomen', g='f', rang=486),
 dict(w='koniec', de='Ende', k='Nomen', g='m', rang=487),
 dict(w='początek', de='Anfang', k='Nomen', g='m', rang=488),
 dict(w='powód', de='Grund', k='Nomen', g='m', rang=489),
 dict(w='przykład', de='Beispiel', k='Nomen', g='m', rang=490),
 dict(w='pomysł', de='Idee', k='Nomen', g='m', rang=491),
 dict(w='historia', de='Geschichte', k='Nomen', g='f', rang=492),
 dict(w='strach', de='Angst', k='Nomen', g='m', rang=493),
 dict(w='pomoc', de='Hilfe', k='Nomen', g='f', rang=494),
 dict(w='policja', de='Polizei', k='Nomen', g='f', rang=495),
 dict(w='zmiana', de='Schicht, Aenderung', k='Nomen', g='f', rang=496),
 dict(w='klient', de='Kunde', k='Nomen', g='m', rang=497),
 dict(w='wypłata', de='Lohn', k='Nomen', g='f', rang=498),
 dict(w='urlop', de='Urlaub', k='Nomen', g='m', rang=499),
 dict(w='przerwa', de='Pause', k='Nomen', g='f', rang=500),
]
