# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/travel_transportation (Deutsch).

36 Saetze, keine Konjunktion.
"""

TAGS = [
    {"id": 61, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                         {"w": "Bahnhof?", "c": "n"}]},
    {"id": 62, "tags": [{"w": "Wann", "c": None}, {"w": "fährt", "c": "v"}, {"w": "der", "c": None},
                         {"w": "nächste", "c": "a"}, {"w": "Zug", "c": "n"}, {"w": "nach", "c": None},
                         {"w": "Berlin?", "c": "n"}]},
    {"id": 63, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "eine", "c": None},
                         {"w": "Fahrkarte", "c": "n"}, {"w": "nach", "c": None}, {"w": "München,", "c": "n"},
                         {"w": "bitte.", "c": None}]},
    {"id": 64, "tags": [{"w": "Ist", "c": "v"}, {"w": "dieser", "c": None}, {"w": "Platz", "c": "n"},
                         {"w": "frei?", "c": "a"}]},
    {"id": 65, "tags": [{"w": "Muss", "c": "v"}, {"w": "ich", "c": None}, {"w": "umsteigen?", "c": "v"}]},
    {"id": 66, "tags": [{"w": "Von", "c": None}, {"w": "welchem", "c": None}, {"w": "Gleis", "c": "n"},
                         {"w": "fährt", "c": "v"}, {"w": "der", "c": None}, {"w": "Zug", "c": "n"},
                         {"w": "ab?", "c": None}]},
    {"id": 67, "tags": [{"w": "Der", "c": None}, {"w": "Zug", "c": "n"}, {"w": "hat", "c": "v"},
                         {"w": "Verspätung.", "c": "n"}]},
    {"id": 68, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "die", "c": None},
                         {"w": "Bushaltestelle?", "c": "n"}]},
    {"id": 69, "tags": [{"w": "Welcher", "c": None}, {"w": "Bus", "c": "n"}, {"w": "fährt", "c": "v"},
                         {"w": "zum", "c": None}, {"w": "Flughafen?", "c": "n"}]},
    {"id": 70, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "meinen", "c": None},
                         {"w": "Flug", "c": "n"}, {"w": "verpasst.", "c": "v"}]},
    {"id": 71, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                         {"w": "Check-in-Schalter?", "c": "n"}]},
    {"id": 72, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "einen", "c": None},
                         {"w": "Mietwagen", "c": "n"}, {"w": "buchen.", "c": "v"}]},
    {"id": 73, "tags": [{"w": "Wie", "c": None}, {"w": "komme", "c": "v"}, {"w": "ich", "c": None},
                         {"w": "zum", "c": None}, {"w": "Hafen?", "c": "n"}]},
    {"id": 74, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "kostet", "c": "v"},
                         {"w": "die", "c": None}, {"w": "Fahrt", "c": "n"}, {"w": "zum", "c": None},
                         {"w": "Flughafen?", "c": "n"}]},
    {"id": 75, "tags": [{"w": "Ich", "c": None}, {"w": "war", "c": "v"}, {"w": "letztes", "c": "a"},
                         {"w": "Jahr", "c": "n"}, {"w": "in", "c": None}, {"w": "Frankreich.", "c": "n"}]},
    {"id": 76, "tags": [{"w": "Nächstes", "c": "a"}, {"w": "Jahr", "c": "n"}, {"w": "fahre", "c": "v"},
                         {"w": "ich", "c": None}, {"w": "nach", "c": None}, {"w": "Italien.", "c": "n"}]},
    {"id": 77, "tags": [{"w": "Wo", "c": None}, {"w": "kann", "c": "v"}, {"w": "ich", "c": None},
                         {"w": "mein", "c": None}, {"w": "Gepäck", "c": "n"}, {"w": "aufgeben?", "c": "v"}]},
    {"id": 78, "tags": [{"w": "Mein", "c": None}, {"w": "Gepäck", "c": "n"}, {"w": "ist", "c": "v"},
                         {"w": "nicht", "c": None}, {"w": "angekommen.", "c": "v"}]},
    {"id": 114, "tags": [{"w": "Entschuldigung,", "c": "n"}, {"w": "wie", "c": None}, {"w": "komme", "c": "v"},
                          {"w": "ich", "c": None}, {"w": "zum", "c": None}, {"w": "Bahnhof?", "c": "n"}]},
    {"id": 115, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "weit", "c": "a"},
                          {"w": "von", "c": None}, {"w": "hier?", "c": None}]},
    {"id": 116, "tags": [{"w": "Gehen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "geradeaus.", "c": None}]},
    {"id": 117, "tags": [{"w": "Biegen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "links", "c": None},
                          {"w": "ab.", "c": None}]},
    {"id": 118, "tags": [{"w": "Biegen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "rechts", "c": None},
                          {"w": "ab.", "c": None}]},
    {"id": 119, "tags": [{"w": "Es", "c": None}, {"w": "ist", "c": "v"}, {"w": "gleich", "c": None},
                          {"w": "um", "c": None}, {"w": "die", "c": None}, {"w": "Ecke.", "c": "n"}]},
    {"id": 120, "tags": [{"w": "Können", "c": "v"}, {"w": "Sie", "c": None}, {"w": "mir", "c": None},
                          {"w": "das", "c": None}, {"w": "auf", "c": None}, {"w": "der", "c": None},
                          {"w": "Karte", "c": "n"}, {"w": "zeigen?", "c": "v"}]},
    {"id": 121, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "mich", "c": None},
                          {"w": "verlaufen.", "c": "v"}]},
    {"id": 122, "tags": [{"w": "Wie", "c": None}, {"w": "weit", "c": "a"}, {"w": "ist", "c": "v"},
                          {"w": "es", "c": None}, {"w": "zu", "c": None}, {"w": "Fuß?", "c": "n"}]},
    {"id": 123, "tags": [{"w": "Nehmen", "c": "v"}, {"w": "Sie", "c": None}, {"w": "die", "c": None},
                          {"w": "zweite", "c": None}, {"w": "Straße", "c": "n"}, {"w": "rechts.", "c": None}]},
    {"id": 124, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                          {"w": "nächste", "c": "a"}, {"w": "Supermarkt?", "c": "n"}]},
    {"id": 125, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "in", "c": None},
                          {"w": "der", "c": None}, {"w": "Nähe?", "c": "n"}]},
    {"id": 126, "tags": [{"w": "Können", "c": "v"}, {"w": "Sie", "c": None}, {"w": "mir", "c": None},
                          {"w": "den", "c": None}, {"w": "Weg", "c": "n"}, {"w": "zeigen?", "c": "v"}]},
    {"id": 127, "tags": [{"w": "Das", "c": None}, {"w": "Museum", "c": "n"}, {"w": "liegt", "c": "v"},
                          {"w": "gegenüber", "c": None}, {"w": "der", "c": None}, {"w": "Kirche.", "c": "n"}]},
    {"id": 500, "tags": [{"w": "Wir", "c": None}, {"w": "haben", "c": "v"}, {"w": "den", "c": None},
                          {"w": "Bus", "c": "n"}, {"w": "erwischt.", "c": "v"}]},
    {"id": 501, "tags": [{"w": "Wo", "c": None}, {"w": "wollt", "c": "v"}, {"w": "ihr", "c": None},
                          {"w": "hin?", "c": None}]},
    {"id": 502, "tags": [{"w": "Warte", "c": "v"}, {"w": "an", "c": None}, {"w": "der", "c": None},
                          {"w": "Kreuzung", "c": "n"}, {"w": "auf", "c": None}, {"w": "mich.", "c": None}]},
    {"id": 503, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "ein", "c": None},
                          {"w": "Ticket.", "c": "n"}]},
]
