# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/club_nightlife (Deutsch).

138 Saetze, groesste Kategorie. Drei Konjunktionen: "dass" (227),
"oder" (267, 268, 482), "und" (297).
"""

TAGS = [
    {"id": 190, "tags": [{"w": "Prost!", "c": None}]},
    {"id": 191, "tags": [{"w": "Immer", "c": None}, {"w": "mit", "c": None}, {"w": "der", "c": None},
                          {"w": "Ruhe", "c": "n"}, {"w": "-", "c": None}, {"w": "trink", "c": "v"},
                          {"w": "so", "c": None}, {"w": "viel", "c": None}, {"w": "du", "c": None},
                          {"w": "magst.", "c": "v"}]},
    {"id": 192, "tags": [{"w": "Ich", "c": None}, {"w": "trinke", "c": "v"}, {"w": "langsam.", "c": "a"}]},
    {"id": 193, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "nicht", "c": None},
                          {"w": "mehr", "c": None}, {"w": "trinken.", "c": "v"}]},
    {"id": 194, "tags": [{"w": "Ich", "c": None}, {"w": "muss", "c": "v"}, {"w": "morgen", "c": None},
                          {"w": "arbeiten.", "c": "v"}]},
    {"id": 195, "tags": [{"w": "Ich", "c": None}, {"w": "trinke", "c": "v"}, {"w": "nur", "c": None},
                          {"w": "ein", "c": None}, {"w": "bisschen.", "c": None}]},
    {"id": 196, "tags": [{"w": "Was", "c": None}, {"w": "trinkst", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 197, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "noch", "c": None},
                          {"w": "ein", "c": None}, {"w": "Bier.", "c": "n"}]},
    {"id": 199, "tags": [{"w": "Trinken", "c": "v"}, {"w": "wir", "c": None}, {"w": "zusammen!", "c": None}]},
    {"id": 200, "tags": [{"w": "Ich", "c": None}, {"w": "trinke", "c": "v"}, {"w": "keinen", "c": None},
                          {"w": "Alkohol.", "c": "n"}]},
    {"id": 201, "tags": [{"w": "Was", "c": None}, {"w": "kostet", "c": "v"}, {"w": "das?", "c": None}]},
    {"id": 202, "tags": [{"w": "Wie", "c": None}, {"w": "heißt", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 203, "tags": [{"w": "Bist", "c": "v"}, {"w": "du", "c": None}, {"w": "aus", "c": None},
                          {"w": "China?", "c": "n"}]},
    {"id": 204, "tags": [{"w": "Gefällt", "c": "v"}, {"w": "es", "c": None}, {"w": "dir", "c": None},
                          {"w": "hier", "c": None}, {"w": "auch?", "c": None}]},
    {"id": 205, "tags": [{"w": "Ich", "c": None}, {"w": "sehe", "c": "v"}, {"w": "dir", "c": None},
                          {"w": "gern", "c": None}, {"w": "beim", "c": None}, {"w": "Tanzen", "c": "n"},
                          {"w": "zu.", "c": None}]},
    {"id": 206, "tags": [{"w": "Du", "c": None}, {"w": "bist", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "hübsch.", "c": "a"}]},
    {"id": 207, "tags": [{"w": "Du", "c": None}, {"w": "siehst", "c": "v"}, {"w": "gut", "c": "a"},
                          {"w": "aus.", "c": None}]},
    {"id": 208, "tags": [{"w": "Bist", "c": "v"}, {"w": "du", "c": None}, {"w": "Single?", "c": "n"}]},
    {"id": 209, "tags": [{"w": "Ist", "c": "v"}, {"w": "dein", "c": None}, {"w": "Freund", "c": "n"},
                          {"w": "auch", "c": None}, {"w": "hier?", "c": None}]},
    {"id": 210, "tags": [{"w": "Ist", "c": "v"}, {"w": "deine", "c": None}, {"w": "Freundin", "c": "n"},
                          {"w": "auch", "c": None}, {"w": "hier?", "c": None}]},
    {"id": 211, "tags": [{"w": "Wollen", "c": "v"}, {"w": "wir", "c": None}, {"w": "zusammen", "c": None},
                          {"w": "tanzen?", "c": "v"}]},
    {"id": 212, "tags": [{"w": "Hier", "c": None}, {"w": "ist", "c": "v"}, {"w": "es", "c": None},
                          {"w": "zu", "c": None}, {"w": "laut.", "c": "a"}, {"w": "Gehen", "c": "v"},
                          {"w": "wir", "c": None}, {"w": "nach", "c": None}, {"w": "draußen?", "c": None}]},
    {"id": 213, "tags": [{"w": "Lass", "c": "v"}, {"w": "uns", "c": None}, {"w": "WeChat", "c": "n"},
                          {"w": "austauschen.", "c": "v"}]},
    {"id": 214, "tags": [{"w": "Mein", "c": None}, {"w": "Chinesisch", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "nicht", "c": None}, {"w": "so", "c": None}, {"w": "gut.", "c": "a"}]},
    {"id": 215, "tags": [{"w": "Ich", "c": None}, {"w": "gehe", "c": "v"}, {"w": "jetzt.", "c": None}]},
    {"id": 216, "tags": [{"w": "Mir", "c": None}, {"w": "geht", "c": "v"}, {"w": "es", "c": None},
                          {"w": "nicht", "c": None}, {"w": "gut.", "c": "a"}]},
    {"id": 217, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "nach", "c": None},
                          {"w": "Hause.", "c": "n"}]},
    {"id": 218, "tags": [{"w": "Kannst", "c": "v"}, {"w": "du", "c": None}, {"w": "mir", "c": None},
                          {"w": "helfen?", "c": "v"}]},
    {"id": 219, "tags": [{"w": "Mein", "c": None}, {"w": "Freund", "c": "n"}, {"w": "wartet", "c": "v"},
                          {"w": "draußen", "c": None}, {"w": "auf", "c": None}, {"w": "mich.", "c": None}]},
    {"id": 220, "tags": [{"w": "Meine", "c": None}, {"w": "Freundin", "c": "n"}, {"w": "wartet", "c": "v"},
                          {"w": "draußen", "c": None}, {"w": "auf", "c": None}, {"w": "mich.", "c": None}]},
    {"id": 221, "tags": [{"w": "Lass", "c": "v"}, {"w": "mich", "c": None}, {"w": "in", "c": None},
                          {"w": "Ruhe.", "c": "n"}]},
    {"id": 222, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "kein", "c": None},
                          {"w": "Interesse.", "c": "n"}, {"w": "Geh", "c": "v"}, {"w": "bitte", "c": None},
                          {"w": "weg.", "c": None}]},
    {"id": 223, "tags": [{"w": "Die", "c": None}, {"w": "Person", "c": "n"}, {"w": "dort", "c": None},
                          {"w": "lässt", "c": "v"}, {"w": "mich", "c": None}, {"w": "nicht", "c": None},
                          {"w": "in", "c": None}, {"w": "Ruhe.", "c": "n"}]},
    {"id": 224, "tags": [{"w": "Bitte", "c": None}, {"w": "tu", "c": "v"}, {"w": "so,", "c": None},
                          {"w": "als", "c": None}, {"w": "würden", "c": "v"}, {"w": "wir", "c": None},
                          {"w": "uns", "c": None}, {"w": "kennen.", "c": "v"}]},
    {"id": 225, "tags": [{"w": "Bitte", "c": None}, {"w": "pass", "c": "v"}, {"w": "kurz", "c": "a"},
                          {"w": "auf", "c": None}, {"w": "mein", "c": None}, {"w": "Glas", "c": "n"},
                          {"w": "auf.", "c": None}]},
    {"id": 226, "tags": [{"w": "Bitte", "c": None}, {"w": "rufen", "c": "v"}, {"w": "Sie", "c": None},
                          {"w": "die", "c": None}, {"w": "Polizei.", "c": "n"}]},
    {"id": 227, "tags": [{"w": "Entschuldigung,", "c": "n"}, {"w": "ich", "c": None}, {"w": "wusste", "c": "v"},
                          {"w": "nicht,", "c": None}, {"w": "dass", "c": "k"}, {"w": "ihr", "c": None},
                          {"w": "zusammen", "c": None}, {"w": "seid.", "c": "v"}]},
    {"id": 228, "tags": [{"w": "Was", "c": None}, {"w": "kostet", "c": "v"}, {"w": "der", "c": None},
                          {"w": "Eintritt?", "c": "n"}]},
    {"id": 229, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "ein", "c": None},
                          {"w": "Ticket", "c": "n"}, {"w": "kaufen.", "c": "v"}]},
    {"id": 230, "tags": [{"w": "Wir", "c": None}, {"w": "sind", "c": "v"}, {"w": "zu", "c": None},
                          {"w": "zweit.", "c": None}]},
    {"id": 231, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "mein", "c": None},
                          {"w": "Pass.", "c": "n"}]},
    {"id": 232, "tags": [{"w": "Habt", "c": "v"}, {"w": "ihr", "c": None}, {"w": "heute", "c": None},
                          {"w": "offen?", "c": "a"}]},
    {"id": 233, "tags": [{"w": "Bis", "c": None}, {"w": "wann", "c": None}, {"w": "habt", "c": "v"},
                          {"w": "ihr", "c": None}, {"w": "heute", "c": None}, {"w": "offen?", "c": "a"}]},
    {"id": 234, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "mit", "c": None},
                          {"w": "Freunden", "c": "n"}, {"w": "hier.", "c": None}]},
    {"id": 235, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "hier", "c": None},
                          {"w": "bezahlen?", "c": "v"}]},
    {"id": 236, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "die", "c": None},
                          {"w": "Toilette?", "c": "n"}]},
    {"id": 237, "tags": [{"w": "Meine", "c": None}, {"w": "Freunde", "c": "n"}, {"w": "kommen", "c": "v"},
                          {"w": "später.", "c": "a"}]},
    {"id": 238, "tags": [{"w": "Ich", "c": None}, {"w": "bin", "c": "v"}, {"w": "nicht", "c": None},
                          {"w": "von", "c": None}, {"w": "hier.", "c": None}]},
    {"id": 239, "tags": [{"w": "Zwei", "c": None}, {"w": "Bier,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 240, "tags": [{"w": "Hier", "c": None}, {"w": "ist", "c": "v"}, {"w": "es", "c": None},
                          {"w": "zu", "c": None}, {"w": "laut.", "c": "a"}]},
    {"id": 241, "tags": [{"w": "Es", "c": None}, {"w": "ist", "c": "v"}, {"w": "laut,", "c": "a"},
                          {"w": "sag", "c": "v"}, {"w": "es", "c": None}, {"w": "bitte", "c": None},
                          {"w": "nochmal.", "c": None}]},
    {"id": 242, "tags": [{"w": "Was", "c": None}, {"w": "möchtest", "c": "v"}, {"w": "du", "c": None},
                          {"w": "trinken?", "c": "v"}]},
    {"id": 243, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "Wasser?", "c": "n"}]},
    {"id": 244, "tags": [{"w": "Das", "c": None}, {"w": "ist", "c": "v"}, {"w": "zu", "c": None},
                          {"w": "teuer.", "c": "a"}]},
    {"id": 245, "tags": [{"w": "Noch", "c": None}, {"w": "eins,", "c": None}, {"w": "bitte.", "c": None}]},
    {"id": 246, "tags": [{"w": "Ich", "c": None}, {"w": "zahle", "c": "v"}, {"w": "mit", "c": None},
                          {"w": "WeChat.", "c": "n"}]},
    {"id": 247, "tags": [{"w": "Das", "c": None}, {"w": "bezahle", "c": "v"}, {"w": "ich.", "c": None}]},
    {"id": 248, "tags": [{"w": "Wo", "c": None}, {"w": "kann", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "bezahlen?", "c": "v"}]},
    {"id": 249, "tags": [{"w": "Ich", "c": None}, {"w": "nehme", "c": "v"}, {"w": "das", "c": None},
                          {"w": "Gleiche.", "c": "n"}]},
    {"id": 250, "tags": [{"w": "Was", "c": None}, {"w": "möchten", "c": "v"}, {"w": "Sie?", "c": None}]},
    {"id": 251, "tags": [{"w": "Wollen", "c": "v"}, {"w": "wir", "c": None}, {"w": "Karaoke", "c": "n"},
                          {"w": "singen?", "c": "v"}]},
    {"id": 252, "tags": [{"w": "Ich", "c": None}, {"w": "kann", "c": "v"}, {"w": "nicht", "c": None},
                          {"w": "singen.", "c": "v"}]},
    {"id": 253, "tags": [{"w": "Sing", "c": "v"}, {"w": "du", "c": None}, {"w": "zuerst.", "c": None}]},
    {"id": 254, "tags": [{"w": "Welches", "c": None}, {"w": "Lied", "c": "n"}, {"w": "singst", "c": "v"},
                          {"w": "du?", "c": None}]},
    {"id": 255, "tags": [{"w": "Dieses", "c": None}, {"w": "Lied", "c": "n"}, {"w": "kenne", "c": "v"},
                          {"w": "ich!", "c": None}]},
    {"id": 256, "tags": [{"w": "Ein", "c": None}, {"w": "Zimmer", "c": "n"}, {"w": "für", "c": None},
                          {"w": "vier", "c": None}, {"w": "Personen.", "c": "n"}]},
    {"id": 257, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "kostet", "c": "v"},
                          {"w": "das", "c": None}, {"w": "Zimmer?", "c": "n"}]},
    {"id": 258, "tags": [{"w": "Wir", "c": None}, {"w": "bleiben", "c": "v"}, {"w": "zwei", "c": None},
                          {"w": "Stunden.", "c": "n"}]},
    {"id": 259, "tags": [{"w": "Du", "c": None}, {"w": "singst", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "gut!", "c": "a"}]},
    {"id": 260, "tags": [{"w": "Wir", "c": None}, {"w": "singen", "c": "v"}, {"w": "zusammen.", "c": None}]},
    {"id": 261, "tags": [{"w": "Sing", "c": "v"}, {"w": "noch", "c": None}, {"w": "eins!", "c": None}]},
    {"id": 262, "tags": [{"w": "Ich", "c": None}, {"w": "finde", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "sehr", "c": None}, {"w": "nett.", "c": "a"}]},
    {"id": 263, "tags": [{"w": "Ich", "c": None}, {"w": "mag", "c": "v"}, {"w": "dich.", "c": None}]},
    {"id": 264, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "okay", "c": "a"},
                          {"w": "für", "c": None}, {"w": "dich?", "c": None}]},
    {"id": 265, "tags": [{"w": "Gehen", "c": "v"}, {"w": "wir", "c": None}, {"w": "woanders", "c": None},
                          {"w": "hin?", "c": None}]},
    {"id": 266, "tags": [{"w": "Ich", "c": None}, {"w": "kenne", "c": "v"}, {"w": "einen", "c": None},
                          {"w": "guten", "c": "a"}, {"w": "Ort.", "c": "n"}]},
    {"id": 267, "tags": [{"w": "Zu", "c": None}, {"w": "dir", "c": None}, {"w": "oder", "c": "k"},
                          {"w": "zu", "c": None}, {"w": "mir?", "c": None}]},
    {"id": 268, "tags": [{"w": "Bier", "c": "n"}, {"w": "oder", "c": "k"}, {"w": "Wasser?", "c": "n"}]},
    {"id": 269, "tags": [{"w": "Ich", "c": None}, {"w": "reise", "c": "v"}, {"w": "morgen", "c": None},
                          {"w": "weiter.", "c": None}]},
    {"id": 270, "tags": [{"w": "Gehen", "c": "v"}, {"w": "wir", "c": None}, {"w": "kurz", "c": "a"},
                          {"w": "nach", "c": None}, {"w": "draußen.", "c": None}]},
    {"id": 271, "tags": [{"w": "Du", "c": None}, {"w": "gefällst", "c": "v"}, {"w": "mir", "c": None},
                          {"w": "sehr.", "c": None}]},
    {"id": 272, "tags": [{"w": "Du", "c": None}, {"w": "bist", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "cool.", "c": "a"}]},
    {"id": 273, "tags": [{"w": "Ich", "c": None}, {"w": "suche", "c": "v"}, {"w": "gerade", "c": None},
                          {"w": "nichts", "c": None}, {"w": "Festes", "c": "a"}, {"w": "—", "c": None},
                          {"w": "ich", "c": None}, {"w": "reise", "c": "v"}, {"w": "bald", "c": None},
                          {"w": "weiter.", "c": None}]},
    {"id": 274, "tags": [{"w": "Können", "c": "v"}, {"w": "wir", "c": None}, {"w": "zu", "c": None},
                          {"w": "dir?", "c": None}]},
    {"id": 275, "tags": [{"w": "In", "c": None}, {"w": "meinem", "c": None}, {"w": "Hotel", "c": "n"},
                          {"w": "geht", "c": "v"}, {"w": "das", "c": None}, {"w": "nicht.", "c": None}]},
    {"id": 276, "tags": [{"w": "Nehmen", "c": "v"}, {"w": "wir", "c": None}, {"w": "ein", "c": None},
                          {"w": "Zimmer.", "c": "n"}]},
    {"id": 277, "tags": [{"w": "Das", "c": None}, {"w": "Zimmer", "c": "n"}, {"w": "bezahle", "c": "v"},
                          {"w": "ich.", "c": None}]},
    {"id": 278, "tags": [{"w": "Das", "c": None}, {"w": "Hotel", "c": "n"}, {"w": "will", "c": "v"},
                          {"w": "meinen", "c": None}, {"w": "Pass", "c": "n"}, {"w": "sehen.", "c": "v"}]},
    {"id": 279, "tags": [{"w": "Ich", "c": None}, {"w": "rufe", "c": "v"}, {"w": "ein", "c": None},
                          {"w": "Taxi.", "c": "n"}]},
    {"id": 280, "tags": [{"w": "Zuerst", "c": None}, {"w": "zu", "c": None}, {"w": "dir,", "c": None},
                          {"w": "dann", "c": None}, {"w": "zu", "c": None}, {"w": "mir.", "c": None}]},
    {"id": 281, "tags": [{"w": "Wo", "c": None}, {"w": "wohnst", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 282, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "weit?", "c": "a"}]},
    {"id": 283, "tags": [{"w": "Mein", "c": None}, {"w": "Hotel", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "nicht", "c": None}, {"w": "weit.", "c": "a"}]},
    {"id": 284, "tags": [{"w": "Ich", "c": None}, {"w": "fahre", "c": "v"}, {"w": "nach", "c": None},
                          {"w": "Hause.", "c": "n"}]},
    {"id": 285, "tags": [{"w": "Ich", "c": None}, {"w": "finde", "c": "v"}, {"w": "meine", "c": None},
                          {"w": "Freunde", "c": "n"}, {"w": "nicht.", "c": None}]},
    {"id": 286, "tags": [{"w": "Hast", "c": "v"}, {"w": "du", "c": None}, {"w": "meinen", "c": None},
                          {"w": "Freund", "c": "n"}, {"w": "gesehen?", "c": "v"}]},
    {"id": 287, "tags": [{"w": "Wo", "c": None}, {"w": "bist", "c": "v"}, {"w": "du?", "c": None}]},
    {"id": 288, "tags": [{"w": "Ich", "c": None}, {"w": "warte", "c": "v"}, {"w": "hier", "c": None},
                          {"w": "auf", "c": None}, {"w": "dich.", "c": None}]},
    {"id": 289, "tags": [{"w": "Mein", "c": None}, {"w": "Handy", "c": "n"}, {"w": "hat", "c": "v"},
                          {"w": "keinen", "c": None}, {"w": "Strom", "c": "n"}, {"w": "mehr.", "c": None}]},
    {"id": 290, "tags": [{"w": "Wo", "c": None}, {"w": "kann", "c": "v"}, {"w": "ich", "c": None},
                          {"w": "mein", "c": None}, {"w": "Handy", "c": "n"}, {"w": "laden?", "c": "v"}]},
    {"id": 291, "tags": [{"w": "Ich", "c": None}, {"w": "muss", "c": "v"}, {"w": "mein", "c": None},
                          {"w": "Handy", "c": "n"}, {"w": "laden.", "c": "v"}]},
    {"id": 292, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "dein", "c": None},
                          {"w": "Handy", "c": "n"}, {"w": "benutzen?", "c": "v"}]},
    {"id": 293, "tags": [{"w": "Ich", "c": None}, {"w": "rufe", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "an.", "c": None}]},
    {"id": 294, "tags": [{"w": "Wir", "c": None}, {"w": "treffen", "c": "v"}, {"w": "uns", "c": None},
                          {"w": "draußen.", "c": None}]},
    {"id": 295, "tags": [{"w": "Bis", "c": None}, {"w": "morgen!", "c": None}]},
    {"id": 296, "tags": [{"w": "Ich", "c": None}, {"w": "nehme", "c": "v"}, {"w": "ein", "c": None},
                          {"w": "Taxi", "c": "n"}, {"w": "nach", "c": None}, {"w": "Hause.", "c": "n"}]},
    {"id": 297, "tags": [{"w": "Entschuldigung,", "c": "n"}, {"w": "ich", "c": None}, {"w": "habe", "c": "v"},
                          {"w": "meine", "c": None}, {"w": "Freunde", "c": "n"}, {"w": "verloren", "c": "v"},
                          {"w": "und", "c": "k"}, {"w": "mein", "c": None}, {"w": "Handy", "c": "n"},
                          {"w": "ist", "c": "v"}, {"w": "leer.", "c": "a"}, {"w": "Können", "c": "v"},
                          {"w": "Sie", "c": None}, {"w": "mir", "c": None}, {"w": "helfen?", "c": "v"}]},
    {"id": 298, "tags": [{"w": "Du", "c": None}, {"w": "siehst", "c": "v"}, {"w": "heute", "c": None},
                          {"w": "toll", "c": "a"}, {"w": "aus.", "c": None}]},
    {"id": 299, "tags": [{"w": "Dein", "c": None}, {"w": "Outfit", "c": "n"}, {"w": "gefällt", "c": "v"},
                          {"w": "mir.", "c": None}]},
    {"id": 300, "tags": [{"w": "Deine", "c": None}, {"w": "Haare", "c": "n"}, {"w": "sind", "c": "v"},
                          {"w": "schön.", "c": "a"}]},
    {"id": 301, "tags": [{"w": "Sind", "c": "v"}, {"w": "deine", "c": None}, {"w": "Haare", "c": "n"},
                          {"w": "neu?", "c": "a"}]},
    {"id": 302, "tags": [{"w": "Du", "c": None}, {"w": "bist", "c": "v"}, {"w": "sehr", "c": None},
                          {"w": "süß.", "c": "a"}]},
    {"id": 303, "tags": [{"w": "Du", "c": None}, {"w": "bist", "c": "v"}, {"w": "groß.", "c": "a"}]},
    {"id": 304, "tags": [{"w": "Du", "c": None}, {"w": "bist", "c": "v"}, {"w": "schlank.", "c": "a"}]},
    {"id": 305, "tags": [{"w": "Deine", "c": None}, {"w": "Augen", "c": "n"}, {"w": "sind", "c": "v"},
                          {"w": "schön.", "c": "a"}]},
    {"id": 306, "tags": [{"w": "Du", "c": None}, {"w": "hast", "c": "v"}, {"w": "Klasse.", "c": "n"}]},
    {"id": 307, "tags": [{"w": "Deine", "c": None}, {"w": "Freundin", "c": "n"}, {"w": "hat", "c": "v"},
                          {"w": "Klasse.", "c": "n"}]},
    {"id": 308, "tags": [{"w": "Ich", "c": None}, {"w": "mag", "c": "v"}, {"w": "deine", "c": None},
                          {"w": "Stimme.", "c": "n"}]},
    {"id": 309, "tags": [{"w": "Deine", "c": None}, {"w": "Stimme", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "sehr", "c": None}, {"w": "schön.", "c": "a"}]},
    {"id": 310, "tags": [{"w": "Du", "c": None}, {"w": "tanzt", "c": "v"}, {"w": "wirklich", "c": None},
                          {"w": "gut.", "c": "a"}]},
    {"id": 311, "tags": [{"w": "Ach", "c": None}, {"w": "wo!", "c": None}, {"w": "(bescheidene", "c": "a"},
                          {"w": "Antwort", "c": "n"}, {"w": "auf", "c": None}, {"w": "ein", "c": None},
                          {"w": "Lob)", "c": "n"}]},
    {"id": 312, "tags": [{"w": "Nein,", "c": None}, {"w": "nein.", "c": None}, {"w": "(auf", "c": None},
                          {"w": "ein", "c": None}, {"w": "Lob)", "c": "n"}]},
    {"id": 313, "tags": [{"w": "Danke,", "c": "v"}, {"w": "du", "c": None}, {"w": "aber", "c": None},
                          {"w": "auch.", "c": None}]},
    {"id": 314, "tags": [{"w": "Darf", "c": "v"}, {"w": "ich", "c": None}, {"w": "mich", "c": None},
                          {"w": "hierhin", "c": None}, {"w": "setzen?", "c": "v"}]},
    {"id": 315, "tags": [{"w": "Deine", "c": None}, {"w": "Hände", "c": "n"}, {"w": "sind", "c": "v"},
                          {"w": "ganz", "c": None}, {"w": "kalt.", "c": "a"}]},
    {"id": 316, "tags": [{"w": "Ich", "c": None}, {"w": "bringe", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "nach", "c": None}, {"w": "Hause.", "c": "n"}]},
    {"id": 317, "tags": [{"w": "Soll", "c": "v"}, {"w": "ich", "c": None}, {"w": "dich", "c": None},
                          {"w": "nach", "c": None}, {"w": "Hause", "c": "n"}, {"w": "bringen?", "c": "v"}]},
    {"id": 318, "tags": [{"w": "Wir", "c": None}, {"w": "lassen", "c": "v"}, {"w": "es", "c": None},
                          {"w": "langsam", "c": "a"}, {"w": "angehen.", "c": "v"}]},
    {"id": 319, "tags": [{"w": "Ich", "c": None}, {"w": "finde", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "sehr", "c": None}, {"w": "attraktiv.", "c": "a"}]},
    {"id": 320, "tags": [{"w": "Du", "c": None}, {"w": "hast", "c": "v"}, {"w": "eine", "c": None},
                          {"w": "sehr", "c": None}, {"w": "helle", "c": "a"}, {"w": "Haut.", "c": "n"}]},
    {"id": 321, "tags": [{"w": "Ich", "c": None}, {"w": "lade", "c": "v"}, {"w": "dich", "c": None},
                          {"w": "ein.", "c": None}]},
    {"id": 482, "tags": [{"w": "Die", "c": None}, {"w": "Musik", "c": "n"}, {"w": "hier", "c": None},
                          {"w": "ist", "c": "v"}, {"w": "gut,", "c": "a"}, {"w": "oder?", "c": "k"}]},
    {"id": 483, "tags": [{"w": "Kommst", "c": "v"}, {"w": "du", "c": None}, {"w": "oft", "c": None},
                          {"w": "hierher?", "c": None}]},
    {"id": 484, "tags": [{"w": "Bist", "c": "v"}, {"w": "du", "c": None}, {"w": "von", "c": None},
                          {"w": "hier?", "c": None}]},
    {"id": 485, "tags": [{"w": "Soll", "c": "v"}, {"w": "ich", "c": None}, {"w": "dich", "c": None},
                          {"w": "scannen?", "c": "v"}]},
    {"id": 486, "tags": [{"w": "Du", "c": None}, {"w": "hast", "c": "v"}, {"w": "ein", "c": None},
                          {"w": "süßes", "c": "a"}, {"w": "Lächeln.", "c": "n"}]},
    {"id": 487, "tags": [{"w": "Deine", "c": None}, {"w": "Frisur", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "sehr", "c": None}, {"w": "schön.", "c": "a"}]},
    {"id": 488, "tags": [{"w": "Mit", "c": None}, {"w": "dir", "c": None}, {"w": "zu", "c": None},
                          {"w": "reden", "c": "v"}, {"w": "macht", "c": "v"}, {"w": "Spaß.", "c": "n"}]},
]
