# -*- coding: utf-8 -*-
"""Wort-fuer-Wort-Tagging fuer phrasebook_master/hotel_accommodation (Deutsch).

25 Saetze, keine Konjunktion.
"""

TAGS = [
    {"id": 47, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "eine", "c": None},
                         {"w": "Reservierung.", "c": "n"}]},
    {"id": 48, "tags": [{"w": "Haben", "c": "v"}, {"w": "Sie", "c": None}, {"w": "noch", "c": None},
                         {"w": "ein", "c": None}, {"w": "Zimmer", "c": "n"}, {"w": "frei?", "c": "a"}]},
    {"id": 49, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "ein", "c": None},
                         {"w": "Einzelzimmer,", "c": "n"}, {"w": "bitte.", "c": None}]},
    {"id": 50, "tags": [{"w": "Wie", "c": None}, {"w": "viel", "c": None}, {"w": "kostet", "c": "v"},
                         {"w": "die", "c": None}, {"w": "Nacht?", "c": "n"}]},
    {"id": 51, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "Frühstück", "c": "n"},
                         {"w": "inklusive?", "c": "a"}]},
    {"id": 52, "tags": [{"w": "Wann", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                         {"w": "Check-in?", "c": "n"}]},
    {"id": 53, "tags": [{"w": "Ich", "c": None}, {"w": "möchte", "c": "v"}, {"w": "auschecken.", "c": "v"}]},
    {"id": 54, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "hier", "c": None},
                         {"w": "WLAN?", "c": "n"}]},
    {"id": 55, "tags": [{"w": "Wie", "c": None}, {"w": "ist", "c": "v"}, {"w": "das", "c": None},
                         {"w": "Passwort", "c": "n"}, {"w": "für", "c": None}, {"w": "das", "c": None},
                         {"w": "WLAN?", "c": "n"}]},
    {"id": 56, "tags": [{"w": "Mein", "c": None}, {"w": "Zimmer", "c": "n"}, {"w": "ist", "c": "v"},
                         {"w": "nicht", "c": None}, {"w": "sauber.", "c": "a"}]},
    {"id": 57, "tags": [{"w": "Die", "c": None}, {"w": "Klimaanlage", "c": "n"}, {"w": "funktioniert", "c": "v"},
                         {"w": "nicht.", "c": None}]},
    {"id": 58, "tags": [{"w": "Können", "c": "v"}, {"w": "Sie", "c": None}, {"w": "mir", "c": None},
                         {"w": "ein", "c": None}, {"w": "Taxi", "c": "n"}, {"w": "rufen?", "c": "v"}]},
    {"id": 59, "tags": [{"w": "Wo", "c": None}, {"w": "ist", "c": "v"}, {"w": "der", "c": None},
                         {"w": "Aufzug?", "c": "n"}]},
    {"id": 60, "tags": [{"w": "Ich", "c": None}, {"w": "habe", "c": "v"}, {"w": "meinen", "c": None},
                         {"w": "Schlüssel", "c": "n"}, {"w": "verloren.", "c": "v"}]},
    {"id": 504, "tags": [{"w": "Das", "c": None}, {"w": "Zimmer", "c": "n"}, {"w": "ist", "c": "v"},
                          {"w": "sehr", "c": None}, {"w": "sauber.", "c": "a"}]},
    {"id": 556, "tags": [{"w": "Ist", "c": "v"}, {"w": "das", "c": None}, {"w": "ein", "c": None},
                          {"w": "Mehrbettzimmer?", "c": "n"}]},
    {"id": 557, "tags": [{"w": "Wie", "c": None}, {"w": "viele", "c": None}, {"w": "Betten", "c": "n"},
                          {"w": "hat", "c": "v"}, {"w": "der", "c": None}, {"w": "Schlafsaal?", "c": "n"}]},
    {"id": 558, "tags": [{"w": "Ich", "c": None}, {"w": "hätte", "c": "v"}, {"w": "gern", "c": None},
                          {"w": "das", "c": None}, {"w": "untere", "c": "a"}, {"w": "Bett.", "c": "n"}]},
    {"id": 559, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "Schließfächer", "c": "n"},
                          {"w": "für", "c": None}, {"w": "das", "c": None}, {"w": "Gepäck?", "c": "n"}]},
    {"id": 560, "tags": [{"w": "Ist", "c": "v"}, {"w": "Bettwäsche", "c": "n"}, {"w": "im", "c": None},
                          {"w": "Preis", "c": "n"}, {"w": "inbegriffen?", "c": "a"}]},
    {"id": 561, "tags": [{"w": "Kann", "c": "v"}, {"w": "ich", "c": None}, {"w": "ein", "c": None},
                          {"w": "Handtuch", "c": "n"}, {"w": "leihen?", "c": "v"}]},
    {"id": 562, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "eine", "c": None},
                          {"w": "Gemeinschaftsküche?", "c": "n"}]},
    {"id": 563, "tags": [{"w": "Gibt", "c": "v"}, {"w": "es", "c": None}, {"w": "eine", "c": None},
                          {"w": "Nachtruhe?", "c": "n"}]},
    {"id": 564, "tags": [{"w": "Habt", "c": "v"}, {"w": "ihr", "c": None}, {"w": "einen", "c": None},
                          {"w": "Frauenschlafsaal?", "c": "n"}]},
    {"id": 565, "tags": [{"w": "Muss", "c": "v"}, {"w": "ich", "c": None}, {"w": "eine", "c": None},
                          {"w": "Kaution", "c": "n"}, {"w": "hinterlegen?", "c": "v"}]},
]
